### ISSUE TITLE
Add option on .env to change ending of vitualhost

### ISSUE THREAD

**Issue by cagartner** [cytopia/devilbox#10]
It would be very nice to be able to change the end of the virtual host on .env file.

Cheers.

**Comment by cytopia** [comment]
If I understand correctly, you want to have domain names from `*.loc` to by dynamic to make it for example `*.test` or `*.example`?

This is tricky and will require some re-organisation.
Currently domain endings are hard-coded in e.g.: `.devilbox/etc/nginx-stable/02-vhost-mass.conf` (and other webserver configs).

Sounds however reasonable.

I will schedule it to 1.1 for now, as I don't know how fast i can come up with a good solution.

Solutions welcome :-)

**Comment by cagartner** [comment]
Exactly,

I changed this config on my local development and worked, for me ok.

Maybe this config can be changed on a online editor in http://localhost on any future update.

Thank you for the awesome work :) and sorry for my bad english.

**Comment by cytopia** [comment]
It is not yet fully dynamic, but if you want to change the TLD suffix, you will do have to to that in two places at the moment:

`.devilbox/www/config.php` at `$TLD_SUFFIX` as well as in your webservers mass vhost config file `.devilbox/etc/<webserver>/02-vhost-mass.conf`

Might be soon a single option inside `.env`

**Comment by leobudima** [comment]
FWIF, editing 02-vhost-mass.conf as:

```
ServerAlias *
VirtualDocumentRoot /shared/httpd/%0/htdocs/
```

solved the problem for me and projects / vhosts can now be called whatever.

**Comment by cytopia** [comment]
@cagartner @leobudima Now fixed in new release.
