### ISSUE TITLE
[Howto]: multitenancy

### ISSUE THREAD

**Issue by morsergen** [cytopia/devilbox#1008]
### Have you already checked elsewhere?

- [X] I have read the [Devilbox documentation](https://devilbox.readthedocs.io/en/latest/)
- [X] I have checked the [Devilbox Troubleshooting Guide](https://devilbox.readthedocs.io/en/latest/)
- [X] I have checked the [Devilbox FAQ](https://devilbox.readthedocs.io/en/latest/support/faq.html)
- [X] I have checked the [Devilbox Howto](https://devilbox.readthedocs.io/en/latest/support/howto.html)
- [X] I have checked the [Devilbox Forum](https://devilbox.discourse.group/)
- [X] I have checked [existing issues](https://github.com/cytopia/devilbox/issues)
- [X] I have googled already with no luck
- [ ] I have not done any of the above

### What are you struggling with?

Good afternoon
Can you help me?
I'm trying to use Laravel 10 with the tenancyforlaravel package(https://tenancyforlaravel.com/docs/v3/quickstart/) and subdomains are not working for me.
Is it possible to somehow solve this issue?
Thank you.

### What have you tried already?

-

### What is your goal?

-

**Comment by vikas5914** [comment]
@morsergen, You need to use the wildcard subdomain for this. Check this out (For Apache, just scroll up the page and you will see the details): https://devilbox.readthedocs.io/en/latest/vhost-gen/example-add-subdomains.html?highlight=subdomain#adding-catch-all-sub-domain-1

**Comment by morsergen** [comment]
@vikas5914 Thank you very much! Everything worked!
