### ISSUE TITLE
Not able to change directory for the Virtual Machine on Windows.

### ISSUE THREAD

**Issue by HappyCampers** [cytopia/devilbox#103]
I'm currently having an issue with installing Laravel and running DevilBox at the same time.

The machine I'm using is a Windows 10 machine that has a fresh installation of Devilbox. I have successfully created the VirtualMachine for my laravel applications but seem to be having an issue making the directory point to the "/public" folder. 

I have checked the docs, but the ones related to Laravel also seem to be UNIX based docs.

Any help would be appreciated!

**Comment by pro6ka** [comment]
hello HappyCampers. I think you can use FAR manager in windows to create simbolic link, or use other windows tools for it.

**Comment by cytopia** [comment]
Hi @HappyCampers 

Did you follow the provided instructions:
https://github.com/cytopia/devilbox/blob/master/docs/Examples.md#4-setup-laravel

Did you enter the PHP container and created the symlink from inside the PHP container?

**Comment by cytopia** [comment]
@HappyCampers I will close this ticket due to missing feedback.

As far as I have understood your problem, it should be **resolvable with the above stated documentation**.
If you still encounter problems with laravel, please re-open and provide more information.
