### ISSUE TITLE
Custom Virtual Host (vhost)

### ISSUE THREAD

**Issue by iadj** [cytopia/devilbox#106]
I'm looking to use a `yii2-app-advanced` project with Devilbox. I need to be able to set a custom vhost configuration for this, instead of the one being auto-generated. Is this possible? If so, how?

**Comment by cytopia** [comment]
@iadj I am afraid, this is currently not yet possible.

Can you let me know what vhost settings you require. I will try to find a temporary solution for you until this feature has been fully integrated.

**Comment by cytopia** [comment]
@iadj I will close this issue, as it duplicates https://github.com/cytopia/devilbox/issues/75.

Please let me know in #75 what custom vhost settings you require
