### ISSUE TITLE
Add feature to add custom .so modules

### ISSUE THREAD

**Issue by fe3dback** [cytopia/devilbox#107]
Some my project require ioncube-loader extension. So now i copy it to docker by hands and rebuild image with this extension. 

So will be good if in devilbox users can just copy our extension in folder, and add custom ini config with loader.

devilbox/modules/ioncube_loader_lin_7.0.so
devilbox/config/php-fpm-7.0/00-ioncube-loader.ini:
```
zend_extension = /usr/lib64/php/modules/ioncube_loader_lin_7.0.so
```

**Comment by cytopia** [comment]
Good idea, I will add that feature

**Comment by eortega** [comment]
This feature will be really helpful !

**Comment by cytopia** [comment]
I made a few quick changes to allow custom modules.

* PR: https://github.com/cytopia/devilbox/pull/108
* Branch: DVL-012-custom-php-modules

**How to (Example for `PHP 7.0` and module `ioncube_loader_lin_7.0.so`)**

1. Copy your custom `*.so` modules to: `./cfg/php-fpm-7.0/ioncube_loader_lin_7.0.so`
2. Create your config to load this module
```shell
cat cat cfg/php-fpm-7.0/01-ioncube.ini
zend_extension = /usr/lib64/php/custom-modules/ioncube_loader_lin_7.0.so
```

**Note:** The config file name needs to begin with `01-*` or similar low number as ioncube needs to be loaded before any other PHP Zend extensions. Configuration files are loaded in alphabetical order.


I just gave it a try and it works.


Please check out the above listed branch and give it a try.

Before merging I will also have to update the documentation

**Comment by cytopia** [comment]
Its been documented, tested and merged.

https://github.com/cytopia/devilbox/blob/master/docs/Configure.md#425-custom-php-modules

**Comment by Stepa4man** [comment]
Does it work only for nginx? ./cfg/php-fpm-7.0/
Or apache also can use fpm?

**Comment by cytopia** [comment]
@Stepa4man Apache or Nginx are only the webservers, they don't care what backend technology is used (e.g. PHP-FPM). Use whatever webserver in whatever version, they all make their calls to PHP-FPM

**Comment by franzose** [comment]
Hello, @cytopia!

> Its been documented, tested and merged.
> 
> https://github.com/cytopia/devilbox/blob/master/docs/Configure.md#425-custom-php-modules

The link is outdated. Could you, please, provide the current one?
