### ISSUE TITLE
Webpack (new tool request)

### ISSUE THREAD

**Issue by mrpsiho** [cytopia/devilbox#117]
Any chances that webpack could be included in the next release? I think it is a great tool by itself and it would be handy to have it by default.

**Comment by cytopia** [comment]
@mrpsiho 
Will be available in a few hours. I will comment again with instructions.

* [X] https://github.com/cytopia/docker-php-fpm-5.4/pull/29
* [X] https://github.com/cytopia/docker-php-fpm-5.5/pull/26
* [X] https://github.com/cytopia/docker-php-fpm-5.6/pull/28
* [X] https://github.com/cytopia/docker-php-fpm-7.0/pull/26
* [X] https://github.com/cytopia/docker-php-fpm-7.1/pull/26
* [X] https://github.com/cytopia/docker-php-fpm-7.2/pull/6
* [X] https://github.com/cytopia/docker-hhvm-latest/pull/13

**Comment by cytopia** [comment]
Everything is merged and will be built by Docker Hub now. Should be available in less than one hour.
Simply run `./update-docker.sh` to fetch latest Docker containers then.
