### ISSUE TITLE
Features request for devilbox: Password protect the devilbox control panel page

### ISSUE THREAD

**Issue by kanglinyao** [cytopia/devilbox#121]
I love devilbox so much and thank you for putting this project together. I used to be a XAMPP user, but now I am using devilbox only for testing and development purposes. I think the following features might improve the project.
Features that might improve usability:
1. Password protect the devilbox control panel page. 
----
> edited by @cytopia
>
> @kanglinyao I have split each of your feature requests into a separate ticket for better tractability.
> Your other feature requests have gone here:
> * #125
> * #126

**Comment by cytopia** [comment]
@kanglinyao can you check out branch `DVL-012-password-protection` and see if this is sufficient.

Note, you must edit `.env` (check `env-example` for new changes) and enable password protection.

**Comment by kanglinyao** [comment]
Ok. Thank you.

**Comment by cytopia** [comment]
Code is merged.
