### ISSUE TITLE
Can not install npm grunt

### ISSUE THREAD

**Issue by normance** [cytopia/devilbox#122]
Hi,

I have just update following https://github.com/cytopia/devilbox/blob/master/docs/Update.md 
(because I was expecting more locale but localedef -i fr_FR -f UTF-8 fr_FR.UTF-8 and localedef -i es_ES -f UTF-8 es_ES.UTF-8 are still missing ... anyway that is another topic).

I notice that ./shell.sh has replaced ./bash.sh  and ./root_bash.sh (on master)

But while before (master in early July) I could do 
./root_bash.sh
npm install -g grunt

and in another ./bash.sh session do
grunt --help

Now I always get "grunt: command not found" (either in devilbox or root user)
How to reproduce:
sudo su - 
npm install -g grunt
npm install -g grunt-cli
(seems installing fine into /usr/local/src/node-v6.11.2-linux-x64/lib/node_modules/grunt/bin/grunt)

[ EDIT ] the problem is related to the path that is not updated (or updatable) by npm/node
since doing this intuitive command works fine:
/usr/local/src/node-v6.11.2-linux-x64/lib/node_modules/grunt/bin/grunt --help

**Comment by cytopia** [comment]
Hi @normance  good catch. I can reproduce the problem. Expected behavior should be as simple as this:

```shell
sudo npm install -g grunt
grunt
```

I will fix this.

Please also open up a separate ticket for all the locales you are missing.
See here for currently added locales: https://github.com/cytopia/docker-php-fpm-5.4/blob/master/Dockerfile#L341

**Comment by cytopia** [comment]
@normance 

I have updated the Docker containers:

* [X] https://github.com/cytopia/docker-php-fpm-5.4/pull/30
* [X] https://github.com/cytopia/docker-php-fpm-5.5/pull/27
* [X] https://github.com/cytopia/docker-php-fpm-5.6/pull/29
* [X] https://github.com/cytopia/docker-php-fpm-7.0/pull/27
* [X] https://github.com/cytopia/docker-php-fpm-7.1/pull/27
* [X] https://github.com/cytopia/docker-php-fpm-7.2/pull/7
* [X] https://github.com/cytopia/docker-hhvm-latest/pull/14

There is no more `root_bash.sh`, as `sudo` can be issued passwordless.

So you will be able to simply do:

```shell
$ sudo npm install -g grunt
$ grunt
```

The Docker container will be built by dockerhub and should be available around one hour after merging the above pull requests.

To get all the new containers at once, simply run:
```shell
$ ./update-docker.sh
```
