### ISSUE TITLE
Add locale fr_FR  and es_ES

### ISSUE THREAD

**Issue by normance** [cytopia/devilbox#123]
In order to allow php producing date in other languages than english, could you please add the following ones :
localedef -i fr_FR -f UTF-8 fr_FR.UTF-8
localedef -i es_ES -f UTF-8 es_ES.UTF-8

**Comment by cytopia** [comment]
@normance 

I have updated the Docker containers:

* [X] https://github.com/cytopia/docker-php-fpm-5.4/pull/30
* [X] https://github.com/cytopia/docker-php-fpm-5.5/pull/27
* [X] https://github.com/cytopia/docker-php-fpm-5.6/pull/29
* [X] https://github.com/cytopia/docker-php-fpm-7.0/pull/27
* [X] https://github.com/cytopia/docker-php-fpm-7.1/pull/27
* [X] https://github.com/cytopia/docker-php-fpm-7.2/pull/7
* [X] https://github.com/cytopia/docker-hhvm-latest/pull/14

All of them now include `fr_FR.UTF-8` and `es_ES.UTF-8`

The Docker container will be built by dockerhub and should be available around one hour after merging the above pull requests.

To get all the new containers at once, simply run:
```shell
$ ./update-docker.sh
``` 

If you need more locales, just let me know.
