### ISSUE TITLE
Features request for devilbox: Add port number for localhost

### ISSUE THREAD

**Issue by cytopia** [cytopia/devilbox#125]
Originally from @kanglinyao. (Multiple feature requests moved into separate stand-alone tickets)

> I love devilbox so much and thank you for putting this project together. I used to be a XAMPP user, but now I am using devilbox only for testing and development purposes. I think the following features might improve the project.
> Features that might improve usability:
> 1.  devilbox uses something like localhost:8888 rather than just localhost as default control panel address.
>
> Original ticket #121

**Comment by cytopia** [comment]
@kanglinyao Do you mean to only change the port of the devilbox intranet or to change the ports for all vhosts (including the devilbox intranet)?

**Comment by kanglinyao** [comment]
Hi Cytopia:

Change the port of the intranet and all vhosts still use port 80.

**Comment by cytopia** [comment]
@kanglinyao I am afraid, separating Intranet port and project ports is not going to be easily included and won't fix atm.

You can however now disable the Intranet completely. See here: https://github.com/cytopia/devilbox/issues/126

I will have to close this as: WON'T FIX
