### ISSUE TITLE
Features request for devilbox: Allowing users assign the default vhost when the listening IP is accessed

### ISSUE THREAD

**Issue by cytopia** [cytopia/devilbox#126]
Originally from @kanglinyao. (Multiple feature requests moved into separate stand-alone tickets)

> I love devilbox so much and thank you for putting this project together. I used to be a XAMPP user, but now I am using devilbox only for testing and development purposes. I think the following features might improve the project.
> Features that might improve usability:
> 1. Allowing users assign the default vhost when the listening IP is accessed. That way people can work on the same project at the same time on remote devilbox projects.
>
> Original ticket #121

**Comment by cytopia** [comment]
@kanglinyao In the upcoming pull request: https://github.com/cytopia/devilbox/pull/130

You can completely disable the intranet. When disabled, any request will be served by the first found vhost. So when you access it by its ip address, the first found vhost (of your projects) will server it.

Is this sufficient?

**Comment by kanglinyao** [comment]
This is good enough. Thank you so much.
