### ISSUE TITLE
doc : suggest shell env var mechanism 

### ISSUE THREAD

**Issue by normance** [cytopia/devilbox#128]
It is not clear where and how user-defined environment var should be handled. 
I would expect using a dedicated (using prefix MY_ ?) sections in the .env file, so I would find my vars when running 'set' after ./shell.sh

Currently it is not the case (you only export what you know and expect from .env), and I am not in apache/php shell to manually perform export env vars. So I am doing an hugly hack : 
in .env I am defining my var like MY_APPLICATION_ENV=development
and in docker-compose.yml I had this under php/environment : 
-MY_APPLICATION_ENV  
I would like not having to modifiy your docker-compose.yml but at least i see my vars when i run     set | grep MY_  (after ./shell.sh)     

Those env vars are expected by my application, for instance, in my index.php I have:
defined('APPLICATION_ENV') || define('APPLICATION_ENV', getenv('MY_APPLICATION_ENV') );

cfg/*.ini are related to third parties applications with specific version
while those vars are related to the application itself and do not change between php versions

As a workaround, .htaccess can be used to declare such var like 
SetEnv MY_APPLICATION_ENV development
but I would have to manage different .htaccess for development and production in my github and this file is  #ignored in CLI context :(

Note that my PAAS provider is using environment variables injection, so my bootstrap use more and more getenv()

**Comment by cytopia** [comment]
@normance I made a few tests and it seems pretty simple to accomplish that.
Do the following in `docker-compose.yml` under the php section:

Just add `env_file:` pointing to the local `.env` file:
```yml
  php:
    ...
    env_file:
      - ./.env
    ...
```

Now you will be able to have any value specified in `.env` to be avilable in each php container.

Can you give this a try and let me know if it works as expected for you,

**Comment by normance** [comment]
It works fine, thanks for the support 👍 

because of the priority of  `environment:` over `env-file:` you could even make this mechanism as default behaviour in docker-compose.yml ?

The reference you provide deserve to be added in your doc, it is very usefull.

**Comment by cytopia** [comment]
@normance glad it works. I will add this to master as well as to the documentation. Let's keep this issue open until its been merged.

**Comment by cytopia** [comment]
It's up for the next release: https://github.com/cytopia/devilbox/pull/130

**Comment by cytopia** [comment]
@normance could you please confirm that it works for you in the upcoming relase: #130 (Detailed Instructions for how to check it out in the comment)

**Comment by normance** [comment]
tested with success on REL-012 branch :)

**Comment by cytopia** [comment]
Merged and ready in v0.12
