### ISSUE TITLE
Volume mount in mariadb-10.1

### ISSUE THREAD

**Issue by Novitsh** [cytopia/devilbox#129]
Not sure if it's an actual issue but I noticed on https://hub.docker.com/r/cytopia/mariadb-10.1/~/dockerfile/ following volumes block:

```
VOLUME /var/lib/mysql
VOLUME /var/log/mysql
VOLUME /var/sock/mysqld
VOLUME /etc/mysql/conf.d
VOLUME etc/mysql/docker-default.d
```

Should the last volume not be prefixed with a slash?

**Comment by cytopia** [comment]
@Novitsh good catch. As I have this also affects other mariadb dockers.

**Comment by cytopia** [comment]
@Novitsh looks like it has affected every MySQL, MariaDB and PerconaDB server. PR's are open and ready to be merged once they passed travis checks.

* https://github.com/cytopia/docker-mysql-5.5/pull/9
* https://github.com/cytopia/docker-mysql-5.6/pull/9
* https://github.com/cytopia/docker-mysql-5.7/pull/13
* https://github.com/cytopia/docker-mysql-8.0/pull/8
* https://github.com/cytopia/docker-mariadb-5.5/pull/9
* https://github.com/cytopia/docker-mariadb-10.0/pull/10
* https://github.com/cytopia/docker-mariadb-10.1/pull/9
* https://github.com/cytopia/docker-mariadb-10.2/pull/9
* https://github.com/cytopia/docker-mariadb-10.3/pull/5
* https://github.com/cytopia/docker-percona-5.5/pull/2
* https://github.com/cytopia/docker-percona-5.6/pull/2
* https://github.com/cytopia/docker-percona-5.7/pull/2

**Comment by cytopia** [comment]
Looks like MySQL 8.0 is currently working. I have to wait until its fixed before I will merge them and close this issue.

**Comment by laminr** [comment]
does the MySql are fixed? it's Feb 2018 and I have the same issue while trying to use MySql 5.7

**Comment by cytopia** [comment]
@laminr merged on Feb 25th. Forgot to close this issue here.

**Comment by cytopia** [comment]
Devilbox v1.0.0 will use official MySQL images: https://github.com/cytopia/devilbox/pull/416
