### ISSUE TITLE
Devilbox not booting / Error message included in report

### ISSUE THREAD

**Issue by fly-man-** [cytopia/devilbox#133]
- [X] Pull latest dockers (e.g.: `docker pull cytopia/<used_docker>`) before running `docker-compose up`
- [X] Specify used docker versions (php, web and database)
- [X] Attach logs for php, mysql and webserver (found in `log/` directory)
No logs created
- [X] Start with debug mode and attach docker-compose output (`.env` setting `DEBUG_COMPOSE_ENTRYPOINT=1`)
- [X] Never use different mysql|mariadb versions on the same `HOST_PATH_TO_MYSQL_DATADIR` on existing database files. Different mysql|mariadb versions might upgrade/corrupt existing database files. If you have done that already, start with a different path of `HOST_PATH_TO_MYSQL_DATADIR` (to an empty directory) and try again.

Please also specify the following info:

- [X] Which operating system are you at (Linux, OSX or Windows)

Linux ubuntu 4.4.0-96-generic #119-Ubuntu SMP Tue Sep 12 14:59:54 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

- [X] `docker version`

Client:
 Version:      17.09.0-ce
 API version:  1.32
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:42:18 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.09.0-ce
 API version:  1.32 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:40:56 2017
 OS/Arch:      linux/amd64
 Experimental: false

- [X] `docker-compose version`

docker-compose version 1.8.0, build unknown
docker-py version: 1.9.0
CPython version: 2.7.12
OpenSSL version: OpenSSL 1.0.2g  1 Mar 2016

---
When trying to start the devilbox for the first time the following message appears in the console:

**ERROR:** Version in "./docker-compose.yml" is unsupported. You might be seeing this error because you're using the wrong Compose file version. Either specify a version of "2" (or "2.0") and place your service definitions under the `services` key, or omit the `version` key and place your service definitions at the root of the file to use version 1.
For more on the Compose file format versions, see https://docs.docker.com/compose/compose-file/

**Comment by cytopia** [comment]
@fly-man- 
Can you try this again with a different docker-compose version set in `docker-compose.yml`

Please change `version: '2.1'` to `version: '2.0'` and give it a shot.

**Comment by fly-man-** [comment]
Changed it to 2.0, next error came up after running docker-compose up

**ERROR:** Invalid interpolation format for "image" option in service "httpd": "cytopia/${HTTPD_SERVER:-nginx-stable}:latest"

**Comment by cytopia** [comment]
Try to change `"cytopia/${HTTPD_SERVER:-nginx-stable}:latest"` to `"cytopia/${HTTPD_SERVER}:latest"` Looks like variable interpolation is supported from v2.1 onwards.

**Comment by cytopia** [comment]
Btw just saw it now, your docker-compose version is simply outdated. You have `docker-compose version 1.8.0, build unknown`

When you update it to `Compose 1.9.0+.` everything should work fine without any changes

**Comment by fly-man-** [comment]
That's the version that the installation script for Docker installed, will have a look how to get it to update to 1.9+

**Comment by cytopia** [comment]
Good, let me know how it works out for you. Also while you're at it try out git branch `REL-0.12` this has all the latest changes and is going to be merged within the next few days.

**Comment by fly-man-** [comment]
I just issued these 2 commands from this page to get docker-compose to update:

* https://github.com/docker/compose/releases

And currently it's downloading and updating the images so it's doing something more now.

**Comment by fly-man-** [comment]
Devilbox is running now, it was indeed the "older" version of docker-compose that made the issue.
