### ISSUE TITLE
403 Errors on additional projects 

### ISSUE THREAD

**Issue by clindelof** [cytopia/devilbox#136]
If you encounter a bug and something does not work, make sure you have done the following and check those boxes before submitting an issue - thank you!

- [x] Pull latest dockers (e.g.: `docker pull cytopia/<used_docker>`) before running `docker-compose up`
- [x] Specify used docker versions (php, web and database)
- [x] Attach logs for php, mysql and webserver (found in `log/` directory)
- [x] Start with debug mode and attach docker-compose output (`.env` setting `DEBUG_COMPOSE_ENTRYPOINT=1`)
- [x] Never use different mysql|mariadb versions on the same `HOST_PATH_TO_MYSQL_DATADIR` on existing database files. Different mysql|mariadb versions might upgrade/corrupt existing database files. If you have done that already, start with a different path of `HOST_PATH_TO_MYSQL_DATADIR` (to an empty directory) and try again.

Please also specify the following info:

- [x] Which operating system are you at (Linux, OSX or Windows)
- [x] `docker version`
- [x] `docker-compose version`

Getting 403 Forbidden Errors when adding new projects. 

Permissions are the same for working projects in attached image 911computersolutions is a working project and testing is not working.

Running: 
    - macOS High Sierra
    - docker community edition 17.09.0-ce-mac35 (19611)
    - docker-compose version 1.16.1, build 6d1ac21

[log.zip](https://github.com/cytopia/devilbox/files/1384858/log.zip)

<img width="578" alt="screen shot 2017-10-14 at 1 55 17 pm" src="https://user-images.githubusercontent.com/7719355/31578134-fe6fabb8-b0e8-11e7-8726-efa0827816d2.png">

[env-configuration.txt](https://github.com/cytopia/devilbox/files/1384859/env-configuration.txt)

[docker-compose-output.txt](https://github.com/cytopia/devilbox/files/1384863/docker-compose-output.txt)

**Comment by cytopia** [comment]
@clindelof `403` just looks like you cannot reach the requested resource. Is there an `index.php` file inside `htdocs/` directory?

Could you also please attach the webserver logfiles from the `log/` directory.

**Comment by clindelof** [comment]
index.php was there but when I checked the file permissions on that file in specific it didn't have access to it. 

closing this issue.

**Comment by cytopia** [comment]
Good to know.
