### ISSUE TITLE
Add support multiple TLD_SUFFIX

### ISSUE THREAD

**Issue by lbngoc** [cytopia/devilbox#139]
Can devilbox support nultiple TLD_SUFFFIX ?
eg `TLD_SUFFIX=loc,dev,test `

**Comment by cytopia** [comment]
@lbngoc could you explain the use-case for multiple `TLD_SUFFIX`'s?

**Comment by lbngoc** [comment]
I think it may be a new ENV,  bind service should be listened to all TLD_SUPPORTED_SUFFIX in the list instead one at current. For example:
- File `.env`
```
TLD_SUFFIX= # leave empty because I want to put TLD_SUFFIX by myself when creating vhost folder
TLD_SUPPORTED_SUFFIX=dev,com,net
```
- In `data/www`:
```
├── example.dev
│   └── htdocs
├── example.com
│   ├── htdocs
├── example.net
│   ├── htdocs
```

**Comment by cytopia** [comment]
By looking at your directory structure, I now better understand why this should be added. Looks valid to me.

**Comment by cytopia** [comment]
I further looked into this feature. It requires changes in

* Intranet
* Apache 2.2, Apache 2.4, Nginx stable, Nginx mainline
* DNS server

Its quite extensive, but possible

**Comment by cytopia** [comment]
@lbngoc I had another look. I missunderstood you.

When having multiple tld suffices, it is not going to give you want you want. Lets check your example:

`TLD_SUFFIX=dev,com,net`
```
├── example.dev
│   └── htdocs
├── example.com
│   ├── htdocs
├── example.net
│   ├── htdocs
```
This would make each of your projects available under three suffices:

For directory `example.dev/`:
* `http://example.dev.dev`
* `http://example.dev.com`
* `http://example.dev.net`

For directory `example.com/`:
* `http://example.com.dev`
* `http://example.com.com`
* `http://example.com.net`

For directory `example.net/`:
* `http://example.net.dev`
* `http://example.net.com`
* `http://example.net.net`

This is probably not what you wanted or?

**Comment by cytopia** [comment]
You could however use a custom virtual host config for your webserver and set the `server_name` (nginx) or `ServerName` (apache) yourself. Have a look at the following comment to see how to customize a single vhost configuration:

https://github.com/cytopia/devilbox/issues/142#issuecomment-343670549

Let me know if this helps

**Comment by lbngoc** [comment]
Hi @cytopia,

I have already config vhost before open issue here, I think that a core issue here came from bind_service. I could not disable TLD_SUFFIX (because the default is .loc), then maybe all my vhost was not working.

I will reconfigure this again and let you know my results later. Thanks.

**Comment by cytopia** [comment]
@lbngoc are there any updates on this?

**Comment by cytopia** [comment]
I will close this issue due to inactivity. Feel free to open this up again in case you still experience issues.

**Comment by cytopia** [comment]
@alzen8work even with multiple domains you can still use the directory structure I've shown above: https://github.com/cytopia/devilbox/issues/139#issuecomment-345947795

Also using official domain TLD's for the Devilbox should be avoided, as the DNS server will catch-all all sub-domains and redirect everything to the bundled webserver (apache or nginx). You won't be able to make any http(s)? requests anymore from inside the PHP container.

**Comment by alzen8work** [comment]
what u mean by "Also using official domain TLD's for the Devilbox should be avoided?"

for instance i have purchase 2 domain with different tld, 
1 is http://example.com, 
another is http://example.space

will it be possible to setup like this
TLD_SUFFIX=space,com

because i had tried in my digitalocean droplet, does not work.

**Comment by cytopia** [comment]
> what u mean by "Also using official domain TLD's for the Devilbox should be avoided?"

https://devilbox.readthedocs.io/en/latest/configuration-files/env-file.html#tld-suffix

The reason if you are using e.g. `com` as your TLD_SUFFIX, the DNS server will intercept all requests from the PHP-FPM container going to `*.com` and redirect them to the Devilbox webserver.

So the container won't have any internet for the `*.com` part of the web.

> will it be possible to setup like this
> TLD_SUFFIX=space,com

The bind container does already support multiple DNS names: https://github.com/cytopia/docker-bind#wildcard_dns

Its just not yet reflected in the docker-compose.yml file.

---

However what is the benefit over using the following:

* example.com.loc
* example.space.loc

**Comment by alzen8work** [comment]
> However what is the benefit over using the following:
> 
> * example.com.loc
> * example.space.loc

well @cytopia my objective is not to have
example.com.loc
example.space.loc

but  to have

example.com
example.space

working... so..

**Comment by science695** [comment]
@alzen8work Is this setup to be a production environment?

Because Cytopia's answers are assuming a development environment with autodns.

If this was to be a production environment, you would want to use your public DNS, and not autodns.

**Comment by cytopia** [comment]
@alzen8work let me know if you're trying to setup a production environment as @science695 was assuming.

Then reverse-proxying one might be a good starting point to dig into. Have a look here for the idea: https://github.com/cytopia/devilbox/issues/405#issuecomment-434908527

**Comment by alzen8work** [comment]
well... it is for staging but the domain is public

**Comment by alzen8work** [comment]
@science695 
can elaborate the how to configure in devilbox of using public DNS , and not autodns?

**Comment by cytopia** [comment]
@alzen8work if you need that publically available, why don't you just take one of your valid domains as the TLD_SUFIX. e.g.: `TLD_SUFFIX=example.space`

This way all of your projects advertise as:

* project1.example.space
* project2.example.space
* ...

You will only need to take care about creating DNS records for `project1` and `project2` separately.

Alternatively you can also create a staging sub-domain with a catch-all to your staging server: `TLD_SUFFIX=staging.example.space` (where `*.staging.example.space` is a catch-all to the staging server)

This way all of your projects **automatically** advertise as:

* project1.staging.example.space
* project2.staging.example.space
* ...

**Comment by alzen8work** [comment]
@cytopia well... 
proj1.example.space 
proj2.example.space

might be staging for 1 domain... 

how about adding staging to another domain eg .com:
proj3.example.com
proj4.example.com

well thats my usecase.... any solution on going about that?

**Comment by cytopia** [comment]
So basically there are two choices:

#### 1. Do not care about the domain, but separate your projects by different subdomains to emulate different domains:

**Domain 1**:

* project1.staging-**subdomain**.example.com
* project2.staging-**subdomain**.example.com

**Domain 2**:

* project3.staging-**just-another-subdomain**.example.com
* project4.staging-**just-another-subdomain**.example.com

#### 2. Add vhost-gen templates to your project to overwrite the default nginx/apache behaviour:

You are free to choose any domain you want. Read up more here: https://devilbox.readthedocs.io/en/latest/vhost-gen/example-add-subdomains.html

2.1 Keep at least one entry for the original domain which uses the TLD_SUFFIX, otherwise you won't be able to access the project from within the PHP container

2.2 Or you use FQDN and can just rely on vhost-gen changes

---

Hope that helps. I would however still be interested why there is a need for different domains.

**Comment by alzen8work** [comment]
> So basically there are two choices:
> 
> #### 1. Do not care about the domain, but separate your projects by different subdomains to emulate different domains:
> **Domain 1**:
> 
> * project1.staging-**subdomain**.example.com
> * project2.staging-**subdomain**.example.com
> 
> **Domain 2**:
> 
> * project3.staging-**just-another-subdomain**.example.com
> * project4.staging-**just-another-subdomain**.example.com
> 
> #### 2. Add vhost-gen templates to your project to overwrite the default nginx/apache behaviour:
> You are free to choose any domain you want. Read up more here: https://devilbox.readthedocs.io/en/latest/vhost-gen/example-add-subdomains.html
> 
> 2.1 Keep at least one entry for the original domain which uses the TLD_SUFFIX, otherwise you won't be able to access the project from within the PHP container
> 
> 2.2 Or you use FQDN and can just rely on vhost-gen changes
> 
> Hope that helps. I would however still be interested why there is a need for different domains.

![image](https://user-images.githubusercontent.com/20431509/47962694-78e94780-e05b-11e8-929c-be9df8c4bea3.png)

**Comment by cytopia** [comment]
I already got the *what* and was actually interested in the *why*.

Anyway, the answer to *how* is still the same:

> #### 2. Add vhost-gen templates to your project to overwrite the default nginx/apache behaviour:
> You are free to choose any domain you want. Read up more here: https://devilbox.readthedocs.io/en/latest/vhost-gen/example-add-subdomains.html

Are more in-depth explanation about how `vhost-gen` integration works is explained here: https://devilbox.readthedocs.io/en/latest/vhost-gen/customize-specific-virtual-host.html
