### ISSUE TITLE
Linuxbrew support?

### ISSUE THREAD

**Issue by tracyfloyd** [cytopia/devilbox#143]
Any chance you could pre-install http://linuxbrew.sh/ in the PHP containers?

**Comment by cytopia** [comment]
@tracyfloyd can be added.
Can you please direct the request here:

https://github.com/devilbox/docker-php-fpm-7.3

This is going to be the base for all PHP container. Once this one has been finalized, I will copy it to the other versions.

**Comment by tracyfloyd** [comment]
Done - thanks!
https://github.com/devilbox/docker-php-fpm-7.3/issues/6
