### ISSUE TITLE
Indexing Vhosts

### ISSUE THREAD

**Issue by mavimedia** [cytopia/devilbox#145]
Current behaviour is that vhost-gen is indexing all folders under ./data/www.

```
./www/data
/project1
/project2
/project3
/project4
/project5
```
this will result in URLs like
```
project1.loc
project2.loc
project3.loc
project4.loc
project5.loc
```
What i want to do is to structure my projects a little bit, like customers or project types or other criteria.
E.g.
```
./www/data
/customer1/project1
/customer1/project2
/customer2/project3
/customer2/project4
/customer2/project5
/own-projects/project6
/own-projects/project7
```
The domains could still get the projects folder name, but indexing should be a level deeper.

Is this possible?

**Comment by cytopia** [comment]
@mavimedia this is currently not possible. Implementing this would also raise other problems, such as:

You could have the same folder name in `customer1/` and `own-projects/` which would result in creating only one vhost for either one of them.

This might be solveable, but will rather be time consuming. I currently have some other features to work on. It is a very valid request, so I leave it open, but it will take some time to get this sorted.

**Comment by mavimedia** [comment]
That's right, this could be, but in normal, one domain will show only on one folder, so generating of one vhost wouldn't be the problem. 

Problems could be in the following case:
```
/data/www...
/customer1/laravel/ => laravel.loc
/customer2/laravel/ => error generating laravel.loc
```
In those cases, the user maybe renames his folders:
```
/customer2/laravel.customer2/ => laravel.customer2.loc
```
or something else.

**Those problems could also be solved with a static host entry in a local vhost-gen template.** 

That's something, the user has to rule for himself.

It's not urgent, but it would be nice for organizing my projects.

**Comment by cytopia** [comment]
There could also be a trade-off solution. You could name your projects as follows:

```
customer1.project1/
customer1.project2/
customer1.other-project/
differentcustomer.project1/
differentcustomer.whatever/
differentcustomer.other-stuff/
```

Then I could add grouping the the vhost intranet page based on the sub-domain:

```
CUSTOMER1

PROJECT                    DocumentRoot            Valid                 URL
customer1.project1       ./www/data/...              OK                   customer1.project1
customer1.project2       ./www/data/...              OK                   customer1.project2

DIFFERENTCUSTOMER

PROJECT                               DocumentRoot            Valid                 URL
differentcustomer.project1    ./www/data/...              OK                   differentcustomer.project1
differentcustomer.project2    ./www/data/...              OK                   differentcustomer.project2
```

Would that something to better distinguish between different customers?

**Comment by mavimedia** [comment]
Yes sure, that's the way i do now.

But there are so many folders in data/www/. I don't like this and would like to organize them a little bit better.

I will end up like this:
```
tools.phpmyadmin.loc
tools.apigen.loc
tools.model-generator.loc
tools.phpdocumentor.loc
tools.benchmarks.loc
tools.faq.loc
customers.customer1.loc
customers.customer2.loc
customers.customer3.loc
customers.customer4-www.loc
customers.customer4-crm.loc

... and many more
```
And i don't want foldername as subdomain all the time. Ok, i could rename customers to www. That would look a little bit better, but there are still many folders :( unorganized :(

**Comment by cytopia** [comment]
Another thought I just had.

You can have multiple `.env` files. I guess keeping the default and all other files simply overwrite `HOST_PATH_HTTPD_DATADIR` to whatever customer base directory. This way you can start up the devilbox with explicit settings per customer.

**Comment by mavimedia** [comment]
I also thought about it. This way is interesting for one more point. I can prepare settings for those projects, like PHP Version etc.

OK, i will give it a try.

**Comment by cytopia** [comment]
@mavimedia I haven't tried it myself yet. If you have a viable solution for using different `.env` files, could you please report back here with a few examples.

**Comment by mavimedia** [comment]
Here is a small tutorial.

Copy your .env file to 
```
cp .env php71.env
cp .env php56.env
```

or any other all in devilbox root directory. Open this files in your editor and change your config as you want.
In my case i have prepared these 2 files one with PHP 7.1 an the other with PHP 5.6. You can create config files with any combination you want.

Then make a shell-script `env.sh` with this content
```
#!/bin/bash

DIR="${BASH_SOURCE%/*}"
if [[ ! -d "$DIR" ]]; then DIR="$PWD"; fi

echo "RUNNING docker-compose down ..."
docker-compose down

echo "COPYING $1.env to .env"
cp $DIR/$1.env .env

echo "RUNNING docker-compose up -d ..."
docker-compose up -d
```

Don't forget to `chmod`
```
chmod +x env.sh
```

After this, you can call `./env.sh FILENAME`
In my case, these are `./env.sh php56` or  `./env.sh php71`

That's it.

**Comment by cytopia** [comment]
@mavimedia thanks for the feedback. :+1: 

The whole thing is going to be documented with new documentation setup: https://github.com/cytopia/devilbox/issues/157
