### ISSUE TITLE
Customized Nginx Conf hasn't applied

### ISSUE THREAD

**Issue by alivelimeli** [cytopia/devilbox#147]
**Note:** This issue have been resolved. While creating custom configuration based on templates don't use "\t" (TAB) characters on yml files. They will cause you some trouble :)

Original Issue:
--------------------
Hello,

I'm using Devilbox on Linux: Latest release, latest docker and latest docker-compose version.

I am using PHP 7.1, Nginx-Stable versions.

I've created `.devilbox` inside my project folder and put `nginx.yml`

And I put `fastcgi_read_timeout 300;` parameter.

But I get timeout while working on a PHP project.

So I've go inside the docker shell and check httpd settings.

I've checked `/etc/httpd/vhost.d/myproject.conf` file and the `fastcgi_read_timeout` settings it nowhere.

So maybe I'm doing something wrong or maybe there is a bug.

What do you think?

**Comment by cytopia** [comment]
@alivelimeli could you read through this issue here: https://github.com/cytopia/devilbox/issues/144

Maybe you have missed something.

**Comment by alivelimeli** [comment]
I've used the documentation as a reference: https://github.com/cytopia/devilbox/blob/master/docs/Configure.md#433-customize-the-vhost-configuration

> Copy all available templates from vhost-gen templates directory to a a sub directory in your projects dir (By default .devilbox/) and adjust those template files to your needs.

I've just copied nginx.yml to my project folder `./devilbox/data/www/myproject/.devilbox`

And I've expected to see the changes after devilbox restart, but it didn't worked.

So from issue #144 my understanding is; at the moment I cannot customize vhost configuration for specific project right?

**Comment by cytopia** [comment]
Sorry, wrong ticket number, I actually meant: https://github.com/cytopia/devilbox/issues/142

**Comment by alivelimeli** [comment]
Yes, I already check #142 also. I've applied same steps, but it didn't worked on my side.

1- Created a new project folder `/devilbox/data/www/myproject`
2- Created a new htdocs folder `/devilbox/data/www/myproject/htdocs`
3- Downloaded `nginx.yml` and copied into `/devilbox/data/www/myproject/.devilbox` folder.
4- Added required nginx related configurations to yml file (`fastcgi_read_timeout 300;`)
5- Restarted devilbox.
6- Still having timeout issues (in 60 seconds i guess, probably a default timeout value)

After I've tried these steps and it didn't worked, I've fixed my issue by going into nginx shell and changing `/etc/httpd/vhost.d/myproject.conf` by hand and reloading nginx (which solved timeout problem, because new configuration is worked). But it shouln't be done inside the shell, you've already developed that feature. But somehow it didn't worked.

Which part is wrong on these steps? Or are there any missing steps?

**Comment by cytopia** [comment]
Looks all good to me so far.

> 4- Added required nginx related configurations to yml file (fastcgi_read_timeout 300;)

Can you paste your yml file.

Also, whatever you added to the yml file. Did that show up inside your `myproject.conf` after devilbox restart?

**Comment by alivelimeli** [comment]
My yml file:
`---

# Nginx vHost Template defintion for vhost-gen.py
#
# The 'feature' section contains optional features that can be enabled via
# conf.yml and will then be replaced into the main vhost ('structure' section)
# into their corresponding position:
#
#    __XDOMAIN_REQ__
#    __PHP_FPM__
#    __ALIASES__
#    __DENIES__
#    __STATUS__
#
# The features itself also contain variables to be adjusted in conf.yml
# and will then be replaced in their corresponding feature section
# before being replaced into the vhost section (if enabled):
#
# PHP-FPM:
#    __PHP_ADDR__
#    __PHP_PORT__
# XDomain:
#    __REGEX__
# Alias:
#    __REGEX__
#    __PATH__
# Deny:
#    __REGEX__
# Status:
#    __REGEX__
#
# Variables to be replaced directly in the vhost configuration can also be set
# in conf.yml and include:
#    __VHOST_NAME__
#    __DOCUMENT_ROOT__
#    __INDEX__
#    __ACCESS_LOG__
#    __ERROR_LOG__
#    __PHP_ADDR__
#    __PHP_PORT__
#


###
### Basic vHost skeleton
###
vhost: |
  server {
      proxy_read_timeout 300;
      fastcgi_read_timeout 300;
      listen       __PORT____DEFAULT_VHOST__;
      server_name  __VHOST_NAME__;

      access_log   "__ACCESS_LOG__" combined;
      error_log    "__ERROR_LOG__" warn;

  __VHOST_DOCROOT__
  __VHOST_RPROXY__
  __PHP_FPM__
  __ALIASES__
  __DENIES__
  __SERVER_STATUS__
      # Custom directives
  __CUSTOM__
  }


###
### vHost Type (normal or reverse proxy)
###
vhost_type:
  # Normal vHost (-p)
  docroot: |
    # Define the vhost to serve files
    root         "__DOCUMENT_ROOT__";
    index        __INDEX__;

  # Reverse Proxy (-r)
  rproxy: |
    # Define the vhost to reverse proxy
    location __LOCATION__ {
	proxy_read_timeout 300;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_pass __PROXY_PROTO__://__PROXY_ADDR__:__PROXY_PORT__;
    }


###
### Optional features to be enabled in vHost
###
features:

  # PHP-FPM will not be applied to a reverse proxy!
  php_fpm: |
    # PHP-FPM Definition
    location / {
	proxy_read_timeout 300;
        try_files $uri $uri/ /index.php$is_args$args;
    }
    location ~ \.php?$ {
        try_files $uri = 404;
        include fastcgi_params;

        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_split_path_info ^(.+\.php)(.*)$;

        fastcgi_pass __PHP_ADDR__:__PHP_PORT__;

        fastcgi_index index.php;
        fastcgi_intercept_errors on;
	
	proxy_read_timeout 300;
	fastcgi_read_timeout 300;
    }

  alias: |
    # Alias Definition
    location ~ __ALIAS__ {
	proxy_read_timeout 300;
	fastcgi_read_timeout 300;
        root  __PATH__;
    __XDOMAIN_REQ__
    }

  deny: |
    # Deny Definition
    location ~ __REGEX__ {
        deny all;
    }

  server_status: |
    # Status Page
    location ~ __REGEX__ {
        stub_status on;
        access_log off;
    }

  xdomain_request: |
    # Allow cross domain request from these hosts
    if ( $http_origin ~* (__REGEX__) ) {
        add_header "Access-Control-Allow-Origin" "$http_origin";
        add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS';
        add_header 'Access-Control-Allow-Headers' 'DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Content-Range,Range';
        add_header 'Access-Control-Expose-Headers' 'DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Content-Range,Range';
        add_header 'Access-Control-Max-Age' 0;
        return 200;
    }`

No, those settings are not shoed on myproject.conf. Thats why I tried to solve it by modifying inside shell .

**Comment by cytopia** [comment]
Could you please also paste the final generated vhost config for `myproject.conf`

**Comment by alivelimeli** [comment]
Sure. Here it is:
```
# cat /etc/httpd/vhost.d/myproject.conf 
server {
    listen       80;
    server_name  myproject.loc;

    access_log   "/var/log/nginx-stable/myproject-access.log" combined;
    error_log    "/var/log/nginx-stable/myproject-error.log" warn;

    # Define the vhost to serve files
    root         "/shared/httpd/myproject/htdocs";
    index        index.php;


    # PHP-FPM Definition
    location / {
        try_files $uri $uri/ /index.php$is_args$args;
    }
    location ~ \.php?$ {
        try_files $uri = 404;
        include fastcgi_params;
    
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_split_path_info ^(.+\.php)(.*)$;
    
        fastcgi_pass php:9000;
    
        fastcgi_index index.php;
        fastcgi_intercept_errors on;
    }

    # Alias Definition
    location ~ /devilbox-api/ {
        root  /var/www/default/api;
        # Allow cross domain request from these hosts
        if ( $http_origin ~* (http(s)?://(.*)$) ) {
            add_header "Access-Control-Allow-Origin" "$http_origin";
            add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS';
            add_header 'Access-Control-Allow-Headers' 'DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Content-Range,Range';
            add_header 'Access-Control-Expose-Headers' 'DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Content-Range,Range';
            add_header 'Access-Control-Max-Age' 0;
            return 200;
        }
    }

    # Deny Definition
    location ~ /\.git {
        deny all;
    }
    
    # Deny Definition
    location ~ /\.ht.* {
        deny all;
    }


    # Custom directives

}
```

**Comment by cytopia** [comment]
What is the value of `HTTPD_TEMPLATE_DIR` in your `.env` file?

**Comment by cytopia** [comment]
And can you do an `ls -laR` inside your `myproject` directory.

**Comment by alivelimeli** [comment]
Its default value: `HTTPD_TEMPLATE_DIR=.devilbox`

Folder contents:
```
/devilbox/data/www/myproject $ ls -laR
.:
total 16
drwxr-xr-x  4 myuser myuser 4096 Nov 15 14:46 .
drwxr-xr-x 11 myuser myuser 4096 Nov 15 13:49 ..
drwxr-xr-x  2 myuser myuser 4096 Nov 15 19:35 .devilbox
drwxr-xr-x 17 myuser myuser 4096 Nov 15 19:00 htdocs

./.devilbox:
total 12
drwxr-xr-x 2 myuser myuser 4096 Nov 15 19:35 .
drwxr-xr-x 4 myuser myuser 4096 Nov 15 14:46 ..
-rw-r--r-- 1 myuser myuser 3556 Nov 15 19:35 nginx.yml

./htdocs:
total 120
drwxr-xr-x 17 myuser myuser  4096 Nov 15 19:00 .
drwxr-xr-x  4 myuser myuser  4096 Nov 15 14:46 ..
drwxr-xr-x  7 myuser myuser  4096 Nov 15 18:41 admin
-rw-r--r--  1 myuser myuser   149 Nov 15 18:31 config.inc.php
drwxr-xr-x  2 myuser myuser  4096 Nov 15 18:31 font
drwxr-xr-x  6 myuser myuser  4096 Nov 15 18:40 images
-rw-r--r--  1 myuser myuser   310 Oct 17 16:58 index.php
drwxr-xr-x  4 myuser myuser  4096 Nov 15 18:47 js
drwxr-xr-x  3 myuser myuser 12288 Nov 15 18:47 templates

...
...

and goes so on..
```

**Comment by alivelimeli** [comment]
Everything looks normal but inside httpd container standart nginx.conf is created:

```
# cat /etc/httpd/vhost.d/myproject.conf 
server {
    listen       80;
    server_name  myproject.loc;

    access_log   "/var/log/nginx-stable/myproject-access.log" combined;
    error_log    "/var/log/nginx-stable/myproject-error.log" warn;

    # Define the vhost to serve files
    root         "/shared/httpd/myproject/htdocs";
    index        index.php;


    # PHP-FPM Definition
    location / {
        try_files $uri $uri/ /index.php$is_args$args;
    }
    location ~ \.php?$ {
        try_files $uri = 404;
        include fastcgi_params;
    
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_split_path_info ^(.+\.php)(.*)$;
    
        fastcgi_pass php:9000;
    
        fastcgi_index index.php;
        fastcgi_intercept_errors on;
    }

    # Alias Definition
    location ~ /devilbox-api/ {
        root  /var/www/default/api;
        # Allow cross domain request from these hosts
        if ( $http_origin ~* (http(s)?://(.*)$) ) {
            add_header "Access-Control-Allow-Origin" "$http_origin";
            add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS';
            add_header 'Access-Control-Allow-Headers' 'DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Content-Range,Range';
            add_header 'Access-Control-Expose-Headers' 'DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Content-Range,Range';
            add_header 'Access-Control-Max-Age' 0;
            return 200;
        }
    }

    # Deny Definition
    location ~ /\.git {
        deny all;
    }
    
    # Deny Definition
    location ~ /\.ht.* {
        deny all;
    }


    # Custom directives

}
```

**Comment by alivelimeli** [comment]
Docker version:

```$ docker version
Client:
 Version:      17.05.0-ce
 API version:  1.29
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 22:06:06 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.05.0-ce
 API version:  1.29 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 22:06:06 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

docker-compose version:
```$ docker-compose -version
docker-compose version 1.17.1, build 6d101fb
```

**Comment by cytopia** [comment]
@alivelimeli could you set `DEBUG_COMPOSE_ENTRYPOINT` to `1` in `.env`.

As well as setting the `DEBUG_ENTRYPOINT` in `docker-compose.yml` to `2` only for the `httpd` section.

Then start up the devilbox, wait for httpd to add your vhost and please post the docker logs for httpd

**Comment by cytopia** [comment]
Apart from that you meet all the requirements which are at least:
```
Docker Engine 1.12.0+
Docker Compose 1.9.0+
```

**Comment by alivelimeli** [comment]
Here are the logs:

```$ docker-compose up httpd
WARNING: The MONGO_SERVER variable is not set. Defaulting to a blank string.
WARNING: The MEMCD_SERVER variable is not set. Defaulting to a blank string.
WARNING: The REDIS_SERVER variable is not set. Defaulting to a blank string.
WARNING: The PGSQL_SERVER variable is not set. Defaulting to a blank string.
devilbox_bind_1 is up-to-date
Starting devilbox_php_1 ... 
Starting devilbox_php_1 ... done
Starting devilbox_httpd_1 ... 
Starting devilbox_httpd_1 ... done
Attaching to devilbox_httpd_1
httpd_1  | [INFO] $DOCKER_LOGS not set. Logging errors and access to log files inside container.
httpd_1  | [INFO] Setting docker timezone to: Europe/Berlin
httpd_1  | root $ ln -sf /usr/share/zoneinfo/Europe/Berlin /etc/localtime
httpd_1  | [INFO] Docker date set to: Thu Nov 16 14:28:06 CET 2017
httpd_1  | [INFO] Changing user 'nginx' uid to: 1000
httpd_1  | root $ usermod -u 1000 nginx
httpd_1  | usermod: no changes
httpd_1  | [INFO] Changing group 'nginx' gid to: 1000
httpd_1  | root $ groupmod -g 1000 nginx
httpd_1  | [INFO] $MAIN_VHOST_DISABLE set to 0. Not disabling the default vhost.
httpd_1  | [INFO] $MAIN_VHOST_DOCROOT not specified. Keeping default: htdocs
httpd_1  | [INFO] $MAIN_VHOST_TPL not specified. Keeping default: cfg
httpd_1  | [INFO] $MAIN_VHOST_STATUS_ENABLE set to 1. Enabling httpd status.
httpd_1  | [INFO] Setting httpd status page to: '/devilbox-httpd-status'
httpd_1  | [INFO] $MASS_VHOST_ENABLE set to 1. Enabling mass vhosts.
httpd_1  | [INFO] $MASS_VHOST_TLD set to: .loc
httpd_1  | [INFO] $MASS_VHOST_DOCROOT is set to: htdocs
httpd_1  | [INFO] $MASS_VHOST_TPL is set to: cfg
httpd_1  | [INFO] $PHP_FPM_ENABLE set to 1. Enabling PHP-FPM.
httpd_1  | [INFO] $PHP_FPM_SERVER_ADDR is set to: php
httpd_1  | [INFO] $PHP_FPM_SERVER_PORT is set to: 9000
httpd_1  | root $ sed -i'' 's/__PHP_ENABLE__/yes/g' /etc/vhost-gen/conf.yml
httpd_1  | root $ sed -i'' 's/__PHP_ENABLE__/yes/g' /etc/vhost-gen/main.yml
httpd_1  | root $ sed -i'' 's/__PHP_ADDR__/php/g' /etc/vhost-gen/conf.yml
httpd_1  | root $ sed -i'' 's/__PHP_ADDR__/php/g' /etc/vhost-gen/main.yml
httpd_1  | root $ sed -i'' 's/__PHP_PORT__/9000/g' /etc/vhost-gen/conf.yml
httpd_1  | root $ sed -i'' 's/__PHP_PORT__/9000/g' /etc/vhost-gen/main.yml
httpd_1  | root $ sed -i'' 's/__DOCKER_LOGS_ERROR__/no/g' /etc/vhost-gen/conf.yml
httpd_1  | root $ sed -i'' 's/__DOCKER_LOGS_ERROR__/no/g' /etc/vhost-gen/main.yml
httpd_1  | root $ sed -i'' 's/__DOCKER_LOGS_ACCESS__/no/g' /etc/vhost-gen/conf.yml
httpd_1  | root $ sed -i'' 's/__DOCKER_LOGS_ACCESS__/no/g' /etc/vhost-gen/main.yml
httpd_1  | root $ sed -i'' 's/__ENABLE_STATUS__/yes/g' /etc/vhost-gen/main.yml
httpd_1  | root $ sed -i'' 's|__STATUS_ALIAS__|/devilbox-httpd-status|g' /etc/vhost-gen/main.yml
httpd_1  | root $ vhost_gen.py -n localhost -p /var/www/default/htdocs -c /etc/vhost-gen/main.yml -o /var/www/default/cfg -v -d -s
httpd_1  | vhostgen: [2017-11-16 14:28:06] Adding: localhost
httpd_1  | root $ sed -i'' 's/__DOCROOT_SUFFIX__/htdocs/g' /etc/vhost-gen/conf.yml
httpd_1  | root $ sed -i'' 's/__TLD__/.loc/g' /etc/vhost-gen/conf.yml
httpd_1  | root $ sed -i'' 's/__MASS_VHOST_TPL__/.devilbox/g' /etc/supervisord.conf
httpd_1  | root $ sed -i'' 's/__VERBOSE__/-v/g' /etc/supervisord.conf
httpd_1  | 2017-11-16 14:28:06,476 CRIT Set uid to user 0
httpd_1  | 2017-11-16 14:28:06,477 INFO supervisord started with pid 1
httpd_1  | 2017-11-16 14:28:07,479 INFO spawned: 'nginx' with pid 117
httpd_1  | 2017-11-16 14:28:07,480 INFO spawned: 'watcherd' with pid 118
httpd_1  | watcherd: [2017-11-16 14:28:07] Starting daemon.
httpd_1  | vhostgen: [2017-11-16 14:28:07] Adding: myproject.loc
httpd_1  | watcherd: [2017-11-16 14:28:07] [OK]  ADD: succeeded: /shared/httpd/myproject
httpd_1  | 2017/11/16 14:28:08 [notice] 155#155: signal process started
httpd_1  | watcherd: [2017-11-16 14:28:08] [OK]  TRIGGER succeeded: nginx -s reload
httpd_1  | watcherd: [2017-11-16 14:28:08] Using bash loop to watch for changes.
httpd_1  | 2017-11-16 14:28:09,309 INFO success: nginx entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
httpd_1  | 2017-11-16 14:28:09,310 INFO success: watcherd entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
```

**Comment by alivelimeli** [comment]
I think its replacing required configuration on supervisord.conf on this line:

`httpd_1  | root $ sed -i'' 's/__MASS_VHOST_TPL__/.devilbox/g' /etc/supervisord.conf`

But its somehow not working. Any ideas?

**Comment by alivelimeli** [comment]
I also tried to change folder name, logs created but it didn't worked again. (custom config is not applied)

```httpd_1  | vhostgen: [2017-11-16 15:10:39] Adding: myproject_.loc
httpd_1  | watcherd: [2017-11-16 15:10:40] [OK]  ADD: succeeded: /shared/httpd/myproject_
httpd_1  | watcherd: [2017-11-16 15:10:40] [OK]  DEL: succeeded: /shared/httpd/myproject
httpd_1  | 2017/11/16 15:10:40 [notice] 14033#14033: signal process started
httpd_1  | watcherd: [2017-11-16 15:10:40] [OK]  TRIGGER succeeded: nginx -s reload
httpd_1  | vhostgen: [2017-11-16 15:10:43] Adding: myproject.loc
httpd_1  | watcherd: [2017-11-16 15:10:43] [OK]  ADD: succeeded: /shared/httpd/myproject
httpd_1  | watcherd: [2017-11-16 15:10:43] [OK]  DEL: succeeded: /shared/httpd/myproject_
httpd_1  | 2017/11/16 15:10:43 [notice] 14066#14066: signal process started
httpd_1  | watcherd: [2017-11-16 15:10:43] [OK]  TRIGGER succeeded: nginx -s reload
```

**Comment by cytopia** [comment]
> I think its replacing required configuration on supervisord.conf on this line:
> httpd_1 | root $ sed -i'' 's/__MASS_VHOST_TPL__/.devilbox/g' /etc/supervisord.conf
> But its somehow not working. Any ideas?

Can you show the contents of `/etc/supervisord.conf` please

**Comment by alivelimeli** [comment]
Sure, here it is:
`# cat /etc/supervisord.conf `
```
[supervisord]
user=root
nodaemon=true

[program:nginx]
command=/usr/sbin/nginx -g 'daemon off;'
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
stdout_events_enabled=true
stderr_events_enabled=true

[program:watcherd]
command=watcherd -v -p /shared/httpd -a "vhost_gen.py -p %%p -n %%n -o %%p/.devilbox/ -s -v" -d "rm /etc/httpd/vhost.d/%%n.conf" -t "nginx -s reload"
#startsecs = 0
#autorestart = false
#startretries = 1
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
stdout_events_enabled=true
stderr_events_enabled=true
```

**Comment by cytopia** [comment]
Replacement of `sed -i'' 's/__MASS_VHOST_TPL__/.devilbox/g' /etc/supervisord.conf` is fine.
I will need to add some debug to `vhost-gen.py` itself for docker-logs.

**Comment by alivelimeli** [comment]
What do you advice me to do now? Will it take some time?

I think this will also probably solve my problem but its a hacky solution for now: https://github.com/cytopia/devilbox/issues/144#issuecomment-343698418

**Comment by cytopia** [comment]
One more thing. Could you give it a try with nginx-mainline instead of nginx-stable?

**Comment by alivelimeli** [comment]
I've tried with nginx-mainline, still same. The configuration from nginx.yml file inside /myproject/.devilbox folder not applied.

**Comment by cytopia** [comment]
> I think this will also probably solve my problem but its a hacky solution for now: #144 (comment)

Yes, use it for now, until I have more debug into `vhost-gen.py`

**Comment by alivelimeli** [comment]
I found the problem after I tried #144 

It looks like nginx.yml doesn't like tab characters.

It gave this error:

```
httpd_1  | [ERR] Error loading template [ERR] Error loading templatewhile scanning for the next token
httpd_1  | found character '\t' that cannot start any token
httpd_1  |   in "/etc/vhost-gen/templates/nginx.yml", line 95, column 1
```
I've removed #144 changes and start over with /myproject/.devilbox/nginx.yml file. Replaced tab characters with spaces.

And voila! It worked.

So tab characters caused trouble. Was it documented and maybe I've missed that point? Or should it be added on the documentation?

**Comment by cytopia** [comment]
In your above pasted `docker logs` I don't see any error message. So why didn't it work then?
And how did you trigger this error message?

> So tab characters caused trouble. Was it documented and maybe I've missed that point? Or should it be added on the documentation?

Should be added to the documentation for sure. 

Btw, could you put an *Update* section at your initial comment of this issue stating the problem and that it has been resolved.

I will also keep this issue open until it has been properly documented.

Good catch btw. :+1:

**Comment by alivelimeli** [comment]
> And how did you trigger this error message?

Well after I tried the instructions on  #144 it gave error while starting on docker logs. So I've checked the contents of nginx.yml file and found that to keep indentation I added custom lines with tab. So I've replaced tabs with spaces and tried again and it worked.

Later I revert my changes related to #144 and tried again with tab replacement and it worked.

**Comment by alivelimeli** [comment]
> Btw, could you put an Update section at your initial comment of this issue stating the problem and that it has been resolved.

I've updated initial comment.

Thanks.

**Comment by cytopia** [comment]
The whole thing is going to be documented with new documentation setup: https://github.com/cytopia/devilbox/issues/157

**Comment by cytopia** [comment]
Documented here: http://devilbox.readthedocs.io/en/documentation/tutorials/adding-subdomains.html
