### ISSUE TITLE
Project folder cannot contain numbers?

### ISSUE THREAD

**Issue by kanglinyao** [cytopia/devilbox#148]
It seems that project name cannot contain numbers. I try to create a project folder called drupal8, but Auto DNS won't create a DNS record in the host file. But creating a folder called drupal will give me a working drupal.loc vhost.

I am using the latest devilbox.

**Comment by cytopia** [comment]
@kanglinyao this works just fine on my machine.

![screenshot 2017-11-18 10-03-03 selection](https://user-images.githubusercontent.com/12533999/32978698-ba740588-cc47-11e7-8518-3431dba5253e.png)

**Comment by cytopia** [comment]
Could you provide any logs. Such as

* The ajax request on the vhost page
* docker logs

As well as what version you use of docker and docker-compose

**Comment by cytopia** [comment]
@kanglinyao I will close this due to missing information and inactivity. Feel free to re-open when you have more details
