### ISSUE TITLE
How to have another git repository inside project folder?

### ISSUE THREAD

**Issue by alivelimeli** [cytopia/devilbox#149]
Hello,

Maybe this question is not exactly related to devilbox but its an issue that I get while using devilbox.

As you know mostly users will have git repository for their projects.

But devilbox is installed using `git clone` command. Projects stay inside `/data/www` folder.

But that folder is in `.gitignore` :)

So how can I have another git repository on my project folder? ( like `/data/www/myproject` )

**Comment by cytopia** [comment]
Hi @alivelimeli this is exactly the reason why `.gitignore` is ignoring the `data` folder.
The devilbox git repository will ignore the data folder and does not care what you put into this. You can have your own git directories inside that folder and work normally.

If `.gitignore` was not ignoring that folder, it would show as changed for the devilbox git repository and not your owns.

Give it a try and add git repositories into that folder. It will all work as expected

**Comment by alivelimeli** [comment]
Hello,

Yes it looks like my fault :) I've somehow updated origin url of the git repo (devilboxs) and commited to my repo :)

Thank
