### ISSUE TITLE
devilbox_bind_1 exited with code 1

### ISSUE THREAD

**Issue by Geek-Daddy** [cytopia/devilbox#150]
I'm using Xubuntu 16.04 with 17.09.0-ce and docker-compose 1.17.1 and 90% of times I get:

`devilbox_bind_1 exited with code 1`

I don't have anything custom, just copied env-example to .env. What could be wrong?

**Comment by cytopia** [comment]
@Geek-Daddy could you please provide some more information:

* Docker version
* Docker Compose version
* Debug output of docker logs for bind

Btw, do you have a local DNS server listening on port 53?

**Comment by Geek-Daddy** [comment]
Docker is 17.09.0-ce
Docker-compose 1.17.1

docker-compose logs bind output:

bind_1   | [INFO] Starting BIND 9.10.3
bind_1   | [INFO] Adding wildcard DNS record: '*.loc' -> '172.16.238.11'
bind_1   | root $ echo 'include "/etc/bind/custom-named.conf.loc";' >> /etc/bind/named.conf
bind_1   | [INFO] Adding custom DNS forwarder: 8.8.8.8,8.8.4.4
bind_1   | root $ sed -i'' 's/^};$/	forwarders {
bind_1   | 		8.8.8.8;
bind_1   | 		8.8.4.4;
bind_1   | 	};
bind_1   | };/' /etc/bind/named.conf.options
bind_1   | [INFO] Starting BIND 9.10.3

And that repeats many times

Thats the output of netstat -tulpen | grep ':53':

tcp        0      0 127.0.1.1:53            0.0.0.0:*               LISTEN      0          22478       -               
udp        0      0 127.0.1.1:53            0.0.0.0:*                           0          22477       -               
udp        0      0 0.0.0.0:5353            0.0.0.0:*                           1000       385749      25465/spotify   
udp        0      0 0.0.0.0:5353            0.0.0.0:*                           111        21715       -               
udp6       0      0 :::5353                 :::*                                111        2171

**Comment by cytopia** [comment]
Is devilbox bind port listening on 53 or 5353?

**Comment by Geek-Daddy** [comment]
That is the HOST_PORT_BIND setting? If so it's set to 1053

**Comment by cytopia** [comment]
Can you check if any other local service is listening on port `1053`

**Comment by Geek-Daddy** [comment]
There is nothing on that port.

**Comment by cytopia** [comment]
@Geek-Daddy could you please append the following:

* Complete `.env` file
* `git log | head -1`

Also in your above `docker-compose logs bind` I don't see bind exiting. Could you add the full log here as well.

**Comment by jeffwhitfield** [comment]
I'm getting a similar result. Basically, if I simply stop Devilbox and then restart it, the problem with bind happens. If I stop it and then run the same `down` command again then bind will usually behave on restart. Sometimes have to use a `rm` command though. I'm running on Mac High Sierra with bind set to listen on port 53. Here's my log:

```
Attaching to devilbox_bind_1
bind_1   | [INFO] Adding wildcard DNS record: '*.dev' -> '127.0.0.1'
bind_1   | root $ echo 'include "/etc/bind/custom-named.conf.dev";' >> /etc/bind/named.conf
bind_1   | [INFO] Adding custom DNS forwarder: 8.8.8.8,8.8.4.4
bind_1   | root $ sed -i'' 's/^};$/	forwarders {
bind_1   | 		8.8.8.8;
bind_1   | 		8.8.4.4;
bind_1   | 	};
bind_1   | };/' /etc/bind/named.conf.options
bind_1   | [INFO] Starting BIND 9.10.3
bind_1   | [INFO] Adding wildcard DNS record: '*.dev' -> '127.0.0.1'
bind_1   | root $ echo 'include "/etc/bind/custom-named.conf.dev";' >> /etc/bind/named.conf
bind_1   | [INFO] Adding custom DNS forwarder: 8.8.8.8,8.8.4.4
bind_1   | root $ sed -i'' 's/^};$/	forwarders {
bind_1   | 		8.8.8.8;
bind_1   | 		8.8.4.4;
bind_1   | 	};
bind_1   | };/' /etc/bind/named.conf.options
bind_1   | [INFO] Starting BIND 9.10.3
bind_1   | [INFO] Adding wildcard DNS record: '*.dev' -> '127.0.0.1'
bind_1   | root $ echo 'include "/etc/bind/custom-named.conf.dev";' >> /etc/bind/named.conf
bind_1   | [INFO] Adding custom DNS forwarder: 8.8.8.8,8.8.4.4
bind_1   | root $ sed -i'' 's/^};$/	forwarders {
bind_1   | 		8.8.8.8;
bind_1   | 		8.8.4.4;
bind_1   | 	};
bind_1   | };/' /etc/bind/named.conf.options
bind_1   | [INFO] Starting BIND 9.10.3
```

**Comment by cytopia** [comment]
@Geek-Daddy @jeffwhitfield could you please try the following and see if it still occurs:

Run the container (explicitly specifying bind)
```shell
docker-compose up php httpd bind
```
Stop the container
```shell
docker-compose down
docker-compose kill
docker-compose rm -f
```
Run the container again (explicitly specifying bind)
```shell
docker-compose up php httpd bind
```

**Comment by jeffwhitfield** [comment]
Funny thing is that this is exactly what I'm doing now. Only thing I'm not doing is running a kill command when I shut things down. Kind sucks that a simple `down` command doesn't do it but, that's ok. I'm using simple shell scripts to automate things a bit so no biggie. :P 

If I use the `rm` command after shutting things down then it seems that bind usually behaves. I'll keep tabs on it and, if I notice any oddities, I'll save the logs and post them here.

**Comment by cytopia** [comment]
@jeffwhitfield do you explicitly specify `bind` when using `docker-compose up`?

Like this:
```
docker-compose up php bind httpd ...
```
Or do you let it auto-load without specifying it:
```
docker-compose up php httpd
```

**Comment by jeffwhitfield** [comment]
Yep! That's exactly what I'm doing. I think the `down` and `rm` commands in combination are what is keeping things in check though.

**Comment by cytopia** [comment]
Issue seems to have been fixed. Please get all relevant information from here: https://github.com/cytopia/devilbox/issues/163

I will close this ticket, but leave the other one open until the Docker image is merged.
