### ISSUE TITLE
web interface->virtual hosts (not work properly using 8080) on mac High Sierra

### ISSUE THREAD

**Issue by simiula** [cytopia/devilbox#151]
- [OSX] High Sierra 
- [lastest ] `docker version`
- [ lastest] `docker-compose version`

I setup using port 8080 because I'm running another web server in port 80.
I create a .loc site and its running using:
http://simiula.loc:8080
But when I go to the web interface of devilbox->virtual hosts
tells me 
"No Host DNS record found. Add the following to /etc/hosts:"
Maybe insert in docs that about using different ports is not working properly.

**Comment by cytopia** [comment]
@simiula good catch, I will have to take port changes into account.

**Comment by cytopia** [comment]
This is now fixed in latest commit of the master branch.

```shell
git fetch --all
git checkout master
git pull origin master
```
