### ISSUE TITLE
PHP FPM Curl Updates

### ISSUE THREAD

**Issue by alivelimeli** [cytopia/devilbox#152]
Hello,

I'm not sure if this is the correct place or https://github.com/cytopia/docker-php-fpm-7.1 project is the correct place for this issue.

There are lots of updates on Curl. (Please check: https://curl.haxx.se/changes.html#7_56_1 )

Is it possible to update Curl version on PHP-FPM Images?

Thanks

**Comment by cytopia** [comment]
@alivelimeli yes this is indeed a critical issue.
I am already working on the problem to solve it once and for all.

New Docker Images will be built by tavis-ci every 24 hours with latest software and patches and pushed to Dockerhub on success. This has already been done on three PHP images, but I still have to implement it for the rest as well:

* https://github.com/cytopia/docker-php-fpm-7.1/pull/28
* https://github.com/cytopia/docker-php-fpm-7.2/pull/8
* https://github.com/devilbox/docker-php-fpm-7.3

Once this is also done for 7.0, 5.6, 5.5 and 5.4 the problem will be gone.

I will close this ticket as the work is done on the Docker image repositories itself. Feel free to open up Issues on those repositories if you encounter other problems.
