### ISSUE TITLE
(Community Discussion) New PHP images: Post your required tools

### ISSUE THREAD

**Issue by cytopia** [cytopia/devilbox#154]
# Community Discussion: Required Tools

PHP-FPM images should be rebuild every night in order have latest patches and security updates applied.

*Acceptance Criteria*:

* PHP-FPM images are automatically built every night
* PHP-FPM images ship latest versions of common development tools

---

## Reference Implementation

**[https://github.com/devilbox/docker-php-fpm](https://github.com/devilbox/docker-php-fpm)**

---

## Required tools wishlist

If you have a wish for default installed tools, simply paste them in the comments, I will add it to all images and make sure they are always at the latest version.

* [x] nano
* [X] recent `git` version
* [X] recent `node` version
* [X] recent `composer` version
* [X] [linuxbrew](linuxbrew.sh)
* [x] [swoole](https://github.com/swoole/swoole-src) PHP module
* [x] git-flow
* [x] yarn
* [x] `jq`

---

**Update 1**:

 I have now moved all PHP images into one repository for easier maintenance. Builds already succeed and I will have to do some final tests. PR will be opened shortly to *beta-test*.

**Comment by mavimedia** [comment]
git-flow would be nice
https://github.com/petervanderdoes/gitflow-avh/wiki/Installation

**Comment by mavimedia** [comment]
Please could you also add "yarn"
https://yarnpkg.com/lang/en/docs/install/#linux-tab

**Comment by cytopia** [comment]
@mavimedia added to the list

**Comment by panigrc** [comment]
@mavimedia you were just by an hour faster :smile: cause I wanted to request yarn too

**Comment by cytopia** [comment]
I added instructions above how to use the latest reference implementation if you want a sneak preview of PHP-7.3. This will have the latest reference features requested here.

**Comment by cytopia** [comment]
`yarn` added

**Comment by cytopia** [comment]
I will create a new PR in the coming days to test the new container.

**Comment by cytopia** [comment]
It is ready for testing: https://github.com/cytopia/devilbox/pull/203

**Comment by dbrw** [comment]
wkhtmltopdf's dependencies will be nice!

**Comment by cytopia** [comment]
@dbrw this is coming: https://github.com/devilbox/docker-php-fpm/pull/55

**Comment by cytopia** [comment]
I will re-open and keep this issue open in order to serve as an ongoing discussion.

**Comment by cytopia** [comment]
@dbrw PR for `wkhtmltopdf` is open and should be merged later this day: https://github.com/cytopia/devilbox/pull/392

**Comment by llaville** [comment]
Would be nice to have [jq](https://stedolan.github.io/jq/) 
Its [tutorial page](https://stedolan.github.io/jq/tutorial/) explains how to use it.

**Comment by cytopia** [comment]
> Would be nice to have jq

That's true, there's no way around it nowadays

**Comment by cytopia** [comment]
@llaville jq is added, merged and available with the PHP container.

**Comment by llaville** [comment]
@cytopia yes i saw. Thanks

**Comment by aowrew-fp** [comment]
@cytopia would it be possible to add the apt package unixodbc-dev to the container? It is a requirement for mssql drivers

**Comment by cytopia** [comment]
@aowrew-fp  mssql support is now added

**Comment by cytopia** [comment]
I suppose the majority has been satisfied with required tools and I will simply close this issue.

Further discussions can be continued in the forum: https://devilbox.discourse.group/ 
And additional requests can have its own feature request issue here at GitHub.

**Comment by ozkanonur** [comment]
Would be nice to have geos the php extension. Is there any way to install & active it manually in container ?
