### ISSUE TITLE
(Community Discussion) Tutorials and blog posts

### ISSUE THREAD

**Issue by cytopia** [cytopia/devilbox#166]
# Community Discussion: Tutorials and Blogs

Hi everybody,

As the devilbox matures and more features are added, I am still a bit behind with the documentation. Sometimes it is good to read about a topic from different perspectives.

So, If anybody has written or is going to write a tutorial or blog post about the devilbox for a specific use case or in general, please let me know and I will link it to the Readme.

**Comment by cube-dan** [comment]
I'd be happy to blog about your Devilbox beastie! You've done a fantastic job. Hand's down it's the best of the best. No debate, no question, no better pain-free devstack. 

Devilbox has been a HUGE productivity to my development workflow. I no longer want to cut off my own fingers with dull pruning shears after fighting for hours homebrew. 

I came here to say thank you for your hard work but maybe the best way I can do that is stop writing here and start writing a blog post. I'll use all the spare time I have, now that I don't have to curse — loudly — at MAMP, Virtualbox, Parallels, that old LAMP blade I have laying around, macOS' built in stack, and homebrew. 

Thanks again for Devilbox. I'll get back in touch when I have a blog post URL for you. 

-Dan

**Comment by cytopia** [comment]
Really good to hear that it is such a helper :-)

**Comment by cytopia** [comment]
FYI: There was a talk at **DrupalCamp** in Ghent for anyone who's interested:

* https://www.youtube.com/watch?v=88Sr0aNvVm0
* [Slides](https://docs.google.com/presentation/d/1MvSwPlFL3TozWBtwpfNUTKVOvTbYzRY6GBQ9v2VS_GA/edit#slide=id.g45ef3f2bc6_2_54)

**Comment by cytopia** [comment]
## Migration note

### Community discussion will be continued on **[The Devilbox Forums](https://devilbox.discourse.group)** in its own category: **[HowTos Tutorials Resources Blogs and Videos](https://devilbox.discourse.group/c/howto-tutorials-resources-blogs-videos)**


---

mention: @cube-dan
