### ISSUE TITLE
How do I set xdebug.remote_autostart = 1?

### ISSUE THREAD

**Issue by Cipa** [cytopia/devilbox#167]
Hi,

I am trying to set xdebug.remote_autostart = 1 because I am not sure what else I can do to make Xdebug work. I even went into the php docker image and updated php.ini with the value above, and restarted. But http://localhost/info_php.php still shows xdebug.remote_autostart OFF

Is there a better way?

Thank you

Edit: I just found out about php.d. Will try to edit there but vi is pain in the *. Was hopping for nano or pico.

Edit2: even with 15-xdebug.ini after a down and up the value goes back to 0. How do i make it persistent?

Thank you

**Comment by Cipa** [comment]
Turns out I did not read the docs properly

# Copy to file ending by *.ini
$ cd cfg/php-fpm-5.6
$ cp devilbox-custom.ini-example devilbox-custom.ini

# Edit settings
$ vi devilbox-custom.ini

**Comment by cytopia** [comment]
@Cipa https://devilbox.readthedocs.io/en/latest/configuration-files/php-ini.html
