### ISSUE TITLE
Help with enabling https

### ISSUE THREAD

**Issue by mrpsiho** [cytopia/devilbox#170]
Please, point me out to the related article in the documentation or give a tip on how to enable using 'https' for my local development.

Thanks!

**Comment by cytopia** [comment]
@mrpsiho https is currently not yet supported. This is planned for the first quarter of the new year.

**Comment by mrpsiho** [comment]
Aha, thanks! Ok, I will wait then)
Once more, thanks a lot for such a nice dev tool! ;)
