### ISSUE TITLE
Documentation needed: How do I enable rewrite mod for apache2.4 and allowoverride all

### ISSUE THREAD

**Issue by gowrav-vishwakarma** [cytopia/devilbox#171]
Thanks for this wonderful project, I could setup my dev-env as quick as it could. Although, Mac CPU usage high issue is something docker should concern now. 

Well, I could not find any thing related to subject, to enable .htaccess in my projects I need to allowoverride and enable mod rewrite but from where to do that.

Or please guide to proper documentation.

**Comment by cytopia** [comment]
Hi @gowrav-vishwakarma .
this feature is currently not properly documented, however you can overwrite almost anything on a per vhost base or global base.

For now, please have a look here:
https://github.com/cytopia/devilbox/issues/142

**Comment by cytopia** [comment]
@gowrav-vishwakarma please paste your `.htaccess` I will make sure you get it to work.

**Comment by cytopia** [comment]
@gowrav-vishwakarma 

I also checked the vhost configuration which looks like this for Apache 2.4:

```
    <Directory "/shared/httpd/project1/htdocs">
        DirectoryIndex index.php

        AllowOverride All
        Options All

        RewriteEngine on
        RewriteBase /

        Order allow,deny
        Allow from all
        Require all granted
    </Directory>
```

So `rewrite` is enabled by default and already used. Also `AllowOverride` is set to allow everything.
`.htaccess` should work. So what error do you get?
