### ISSUE TITLE
Access sites using hosts IP

### ISSUE THREAD

**Issue by fathonyfath** [cytopia/devilbox#176]
Environment:
- MacOS High Sierra
- devilbox `master-branch`

It would be great if there is any way I can access my sites with hosts IP address since I'm using devilbox as my debug env to host my REST API and access it with my phone. It's hard to change `/etc/hosts` on my android phone without having root access.

Thank you.

**Comment by cytopia** [comment]
@fathonyfath unfortunately this is not easily possible. The devilbox is using [Named Virtual Hosts](https://httpd.apache.org/docs/2.2/vhosts/name-based.html) for both nginx and apache.

So in order to do so you need to set the DNS resolver of your mobile to the one Devilbox provides (if that is possible with some kind of app).

I cannot think of any other possibility.
Maybe somebody else might come up with a solution here.

**Comment by stepgr** [comment]
I was ready to ask the same question. I use also sometimes bitnami stacks for testing purposes and in their setup (at least in the apache module ) they have some rewrite rules to rewrite urls to the actual  location. This way you can access your environment even from WAN (if you want to show the work to an external user eg, but also inside the LAN  which is not possible now with devilbox). I wiil have a look into it if I can make anything out of it.

**Comment by cytopia** [comment]
@stepgr  I totally didn't think of rewrite rules. This is something that could for for `localhost`. Good one.

**Comment by stepgr** [comment]
@cytopia I tried to see how to make such rules for nginx but unfortunately my knowledge of docker is very limited I'm afraid. I can't figure out where  the configuration of nginx lies in the devilbox directory. If you want , I can send you the apache rewrite rules from htaccess  I also found a script online to convert it to nginx rules but I can't figure out where to put them to test!

**Comment by cytopia** [comment]
@stepgr sorry for the long waiting time. Please do send me those rules and I try to prepare something for you.

**Comment by cytopia** [comment]
## https://github.com/cytopia/devilbox/issues/248

I am already working on this problem. Please find all relevant information in the newly created issue: https://github.com/cytopia/devilbox/issues/248

To reach a broader audience I will close this ticket and link it to the new one (which will be done with multiple related issues as well).
