### ISSUE TITLE
./shell.sh not working

### ISSUE THREAD

**Issue by JoelSParker** [cytopia/devilbox#177]
Whenever running $ ./shell.sh I get the error:

env: C:/Program Files/Git/usr/bin/sh: No such file or directory

**Comment by kevindaus** [comment]
are you using windows or linux ?

**Comment by JoelSParker** [comment]
I am on Windows 10 Home using Docker Toolbox

**Comment by kevindaus** [comment]
I got mine executing via ```bash shell.sh```
I have cygwin installed here on my computer

**Comment by cytopia** [comment]
@JoelSParker does this work for you?

**Comment by uebmaster** [comment]
i can't run shell. sh

i get the next when i do _bash shell.sh_

_C:\Users\Uebmaster\Documents\GitHub\devilbox>bash shell.sh
shell.sh: line 2: $'\r': command not found
: No such file or directoryd/httpd
: invalid option
Usage:  bash [GNU long option] [option] ...
        bash [GNU long option] [option] script-file ...
GNU long options:
        --debug
        --debugger
        --dump-po-strings
        --dump-strings
        --help
        --init-file
        --login
        --noediting
        --noprofile
        --norc
        --posix
        --protected
        --rcfile
        --rpm-requires
        --restricted
        --verbose
        --version
Shell options:
        -irsD or -c command or -O shopt_option          (invocation only)
        -abefhkmnptuvxBCHP or -o option_

i am on windows 10 pro with docker for windows

**Comment by cytopia** [comment]
Can you give this a try:

```
docker-compose exec --user devilbox php bash
```

**Comment by cytopia** [comment]
This has been fixed by adding `shell.bat` for windows.

**Comment by maxi032** [comment]
On windows 10 I get:
λ shell.bat

docker-compose exec --user devilbox php  /bin/sh -c "cd /shared/httpd; exec bash -l"
Traceback (most recent call last):
  File "docker-compose", line 6, in <module>
  File "compose\cli\main.py", line 72, in main
  File "compose\cli\main.py", line 128, in perform_command
  File "compose\cli\main.py", line 491, in exec_command
  File "compose\cli\main.py", line 1469, in call_docker
  File "subprocess.py", line 172, in call
  File "subprocess.py", line 394, in __init__
  File "subprocess.py", line 644, in _execute_child
TypeError: environment can only contain strings
[4924] Failed to execute script docker-compose

I have Devilbox v1.6.1

**Comment by vikas5914** [comment]
@maxi032 This is issue with the Docker-compose. Download the v1.25.3 from this link: https://github.com/docker/compose/releases/tag/1.25.3

and replace the exe here: `C:\Program Files\Docker\Docker\Resources\bin\`

**Comment by ahmedch1** [comment]
For me on Windows 10 using Git Bash 
I used `winpty bash ./shell.sh`
and It works
