### ISSUE TITLE
Feature request - Varnish support ?

### ISSUE THREAD

**Issue by herewithme** [cytopia/devilbox#178]
Hello,

Thank you for this very interesting project.
Do you plan to support Varnish in the future?

Best,

**Comment by cytopia** [comment]
If this is a desired service, I will take it into the Roadmap.

https://github.com/cytopia/devilbox/issues/23

**Comment by herewithme** [comment]
Great !

**Comment by cytopia** [comment]
@herewithme FYI: Varnish and HAProxy SSL offloading has been merged and is available. See here for more information: https://devilbox.discourse.group/t/feature-haproxy-ssl-offloading/69

**Comment by cytopia** [comment]
@herewithme https://devilbox.readthedocs.io/en/latest/custom-container/enable-varnish.html
