### ISSUE TITLE
Cannot install Devilbox and Q: Will wp multi-network work locally?

### ISSUE THREAD

**Issue by GLOBALcloud** [cytopia/devilbox#180]
I didn't find any support forums or another place where to ask! 

I am new to Docker / Devilbox and have installed the recommended version of Docker on win10.

First to my question;

I've been trying to get the DNS to work to run multi-network locally on xampp, 
https://wordpress.org/plugins/wp-multi-network/
if you like to test it, the git version is the one to use:
https://github.com/stuttter/wp-multi-network

As it is windows, programs like dnsmasq can do but do not work on windows.
http://www.thekelleys.org.uk/dnsmasq/doc.html 

Acrylic works on windows but can't handle the multi-network DNS, I can't connect to the other networks, at least I've not been able to get it working!
http://mayakron.altervista.org/wikibase/show.php?id=AcrylicHome

When I was looking into BIND, DevilBox somehow popped up and I saw it mentioned BIND can be installed with Docker, therefore I would like to try the devilbox on my machine.

Any idea if DevilBox can run multi-network and make the networks accessible i.e. 
localhost/network.dev, <network root install>
localhost/network2.dev, <2nd multisite> 
localhost/network3.dev ? <3th multisite>

Now the issue!  I cannot proceed with the install!

I've installed Doker on Win 10 as described but,  there is no way I can proceed to step 2. Install Devilbox, 

In PowerShell: 
PS C:\WINDOWS\system32> docker run hello-world

Hello from Docker!
This message shows that your installation appears to be working correctly.

When I try to proceed to step 2 as instructed in the video, I get this error in red:

PS C:\WINDOWS\system32> $ git clone https://github.com/cytopia/devilbox
$ : The term '$' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path
was included, verify that the path is correct and try again.
At line:1 char:1
+ $ git clone https://github.com/cytopia/devilbox
+ ~
    + CategoryInfo          : ObjectNotFound: ($:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

What is it I am doing it wrong? Why can't I proceed with the install?

**Comment by kevindaus** [comment]
remove the dollar sign

**Comment by cytopia** [comment]
@GLOBALcloud did you try what @kevindaus suggested?

**Comment by GLOBALcloud** [comment]
HI, yes I did, I also tried all versions of the code, I will try again when I have spare time to play with it. Until then it has to be as is!

 I am more curious about the multi-network function if it will work locally?

**Comment by cytopia** [comment]
I am not a wordpress pro, but as far as I know, there shouldn't be a limitation to set it up like this.

If the `$` sign error is resolved, what is the current error on the wordpress multisite?

**Comment by cytopia** [comment]
@GLOBALcloud please provide the actual error and the expected outcome for wordpress multisite setup.

**Comment by cytopia** [comment]
Wordpress multi-sites can be achieved by using multiple sub-domains. I have added documentation for how to have unlimited subdomains: http://devilbox.readthedocs.io/en/documentation/tutorials/adding-subdomains.html

If you encounter any other problems, feel free to re-open
