### ISSUE TITLE
PHP warnings for 7 showing up when running 5.6

### ISSUE THREAD

**Issue by mwmllr** [cytopia/devilbox#182]
A few days ago I pulled this repo. One thing that confuses me is why, when running it with PHP 5.6 I get warnings like  

> Deprecated: Comments starting with '#' are deprecated

which is supposed to show up in PHP 7, not 5.6. Why does that happen?

When I 

`echo phpversion()`

I get

>  5.6.31

PHP 5.6
Apache 2.2
MySQL 5.5
PGSQL 9.1
Redis 2.8
Memcached 1.4.21
Mongo 2.8

Linux
Docker version 1.13.1, build 092cba3
docker-compose version 1.16.1, build 6d1ac21

**Comment by cytopia** [comment]
Can you check in two places:

* web interface (phpinfo)
* via shell (`./shell.sh`) and then `php --version`

**Comment by mwmllr** [comment]
`phpinfo` shows 

> PHP Version 5.6.31

`./shell.sh` then `php --version` shows 

> PHP 5.6.31 (cli) (built: Jul  6 2017 08:06:11)

**Comment by mwmllr** [comment]
I'm going to double-check this and get back to you.

**Comment by mwmllr** [comment]
`phpinfo` shows 

> PHP Version 5.6.31

`./shell.sh` then `php --version` shows 

> PHP 5.6.31 (cli) (built: Jul  6 2017 08:06:11)

I also checked that I could switch the php version in the .env file and I could, so that the above commands updated to, say, php 7.

**Comment by cytopia** [comment]
I don't think this is a PHP 5.6 issue. Here is someone with PHP 5.4 and the same problem: https://stackoverflow.com/questions/14074101/getting-comments-starting-with-are-deprecated-message-via-cli

Also have a look here: https://github.com/php/php-src/blob/c0891d9326dc6085626a9d5cb9fcb7e62902aedc/Zend/zend_ini_scanner.l#L642

This is from PHP 5.6
