### ISSUE TITLE
Custom virtual host docroot

### ISSUE THREAD

**Issue by nlemoine** [cytopia/devilbox#192]
Hi,

- [x]  OSX 10.11.6
- [x] `docker version` 17.12
- [x] `docker-compose version` 1.18

My projects folder structure doesn't match the Devilbox or Valet like structure so I can't use the default behavior: one folder == one domain.
I tried to add a virtual host with a custom `DocumentRoot` (e.g. disable the mass virtual host feature) using the `devil-custom.conf` file in the web server I'm using (Apache 2.4):
```apache
<VirtualHost *:80>
    ServerName mydomain.test
    DocumentRoot /shared/httpd/01-CLIENT/04-PROJECT/_www/web
</VirtualHost>
```
The `HOST_PATH_HTTPD_DATADIR` maps my `CLIENTS` folder (which is the parent of `01-CLIENT` in the example above).

I would like to be able to add as many vhost as needed. 

Is this something possible/a feature you would consider with Devilbox? For example a custom YAML config file that could rely on `vhost-gen`?

**Comment by cytopia** [comment]
> My projects folder structure doesn't match the Devilbox or Valet like structure so I can't use the default behavior: one folder == one domain.

What is the behavior you want?

**Comment by nlemoine** [comment]
My folder structure is like:
```
├── CLIENTS
│   ├── 01-CLIENT-NAME
│   │   ├── 01-CLIENT-PROJECT-01
│   │   │   ├── _www
│   │   │   │   ├── web
│   ├── 02-CLIENT-NAME
│   │   ├── 01-CLIENT-PROJECT-01
│   │   ├── 02-CLIENT-PROJECT-02
etc.
```
Where `web` is the document root. But this isn't always true. It sometimes can be `public`, `public_html` or `whatever`.

Sorry for mentioning my folder structure, this seems misleading. The global question is: how can I set a custom virtual host? With a custom `ServerName` and a custom `DocumentRoot`.

**Comment by cytopia** [comment]
Unfortunately this is not possible by the way `vhost-gen` currenty works. What you could do instead, is the following:

```
ln -s CLIENTS/01-CLIENT-NAME/* /path/to/devilbox/www/data
ln -s CLIENTS/02-CLIENT-NAME/* /path/to/devilbox/www/data
ln -s CLIENTS/03-CLIENT-NAME/* /path/to/devilbox/www/data
...
```
In each project it doesnt matter how the document root folder is named, simply symlink whatever the directory is called to `htdocs`:
```
cd  /path/to/devilbox/www/data/01-CLIENT-PROJECT-01
ln -s _www/web htdocs
```

This will require some manual work, as well as re-symlinking once you add new clients to your project dir, however it could be something for you to work out

**Comment by nlemoine** [comment]
But I still can't choose a custom `ServerName`?
This require indeed a little bit of manual setup. 

Thanks for the quick feedback.

**Comment by cytopia** [comment]
No, the servername will be according to your directory name. You can however customize each vhost on a per project base. The documentation is unfortunately still very basic: https://github.com/cytopia/devilbox/blob/master/docs/Configure.md#433-customize-the-vhost-configuration
