### ISSUE TITLE
how to disable ¿debug?

### ISSUE THREAD

**Issue by uebmaster** [cytopia/devilbox#193]
Hi, always that i open a page of my project i see that, how can i disable?

I tried with DEBUG_COMPOSE_ENTRYPOINT=0 and later docker-compose rm -f but still appearing :/

I am working on windows 10

![image](https://user-images.githubusercontent.com/5565506/36324184-375c3b5c-1319-11e8-8244-9ad1d590f7db.png)

**Comment by cytopia** [comment]
You can add custom `*.ini` files for each PHP version to configure it the way you need (in your case disable PHP warninigs):
https://github.com/cytopia/devilbox/blob/master/docs/Configure.md#12-the-devilbox-cfg-directory

**Comment by cytopia** [comment]
@uebmaster does this answer your question?

**Comment by uebmaster** [comment]
yes, although the warnings are appearing because in the configuration file of my script had on the error displaying.

Thanks.

**Comment by cytopia** [comment]
Glad that it solved your issue.

**Comment by cytopia** [comment]
https://devilbox.readthedocs.io/en/latest/intermediate/enable-disable-php-modules.html
