### ISSUE TITLE
SSH for windows

### ISSUE THREAD

**Issue by pbearne** [cytopia/devilbox#194]
This may be have sorted, but I can't see how to SSH into the install. All the dock say ti just run the shell.sh but this doesn't seem to work on windows. So the ask is how do windows users shell in or if we can't then update the DOC's to make it clear (docs for both)

Please also specify the following info:

- [Windows 10 ] Which operating system are you at (Linux, OSX or Windows)
- [18.02.0-ce ] `docker version`
- [ 1.19.0] `docker-compose version`

**Comment by cytopia** [comment]
Can you try this:
```
docker-compose exec --user devilbox php  /bin/sh -c "exec bash -l"
```

**Comment by cytopia** [comment]
Thanks
