### ISSUE TITLE
Issues  while connecting to mysql 5.7

### ISSUE THREAD

**Issue by dozzy100** [cytopia/devilbox#196]
When I try to connect to mysql I get the following error:

ERROR 1045 (28000): Access denied for user 'root'@'172.16.238.1' (using password: NO)

An existing MySQL database has been mounted for this mysql instance. Tried connecting from command line using:

mysql -h 127.0.0.1 -P 3306 -u root 

from inside the container.

**Comment by cytopia** [comment]
Try:
```
mysql -h 127.0.0.1 -P 3306 -u root -p
```
And hit enter when it asks for the pass

**Comment by dozzy100** [comment]
Still get the error

ERROR 1045 (28000): Access denied for user 'root'@'172.16.238.10' (using password: NO)

**Comment by cytopia** [comment]
Can you give it a try with a different mysql version

**Comment by dozzy100** [comment]
Tried using mysq 5.6, while starting it up get the following error:

devilbox_mysql_1 exited with code 1

Full log:

`$ docker-compose up mysql

WARNING: The REDIS_SERVER variable is not set. Defaulting to a blank string.
WARNING: The PGSQL_SERVER variable is not set. Defaulting to a blank string.
devilbox_bind_1 is up-to-date
devilbox_php_1 is up-to-date
devilbox_httpd_1 is up-to-date
Starting devilbox_mysql_1 ... 
Starting devilbox_mysql_1 ... done
Attaching to devilbox_mysql_1
mysql_1  | [INFO] Setting docker timezone to: Europe/Berlin
mysql_1  | root $ rm /etc/localtime
mysql_1  | root $ ln -s /usr/share/zoneinfo/Europe/Berlin /etc/localtime
mysql_1  | [INFO] Docker date set to: Tue Feb 20 13:06:48 CET 2018
mysql_1  | [INFO] Setting MySQL: [mysqld] general-log=1
mysql_1  | root $ sed -i'' 's|\[mysqld\]|\[mysqld\]
mysql_1  | general-log = 1|g' /etc/my.cnf.d/logging.cnf
mysql_1  | [INFO] Setting MySQL: [client] socket=/tmp/mysql/mysqld.sock
mysql_1  | root $ sed -i'' 's|\[client\]|\[client\]
mysql_1  | socket = /tmp/mysql/mysqld.sock|g' /etc/my.cnf.d/socket.cnf
mysql_1  | [INFO] Setting MySQL: [mysql] socket=/tmp/mysql/mysqld.sock
mysql_1  | root $ sed -i'' 's|\[mysql\]|\[mysql\]
mysql_1  | socket = /tmp/mysql/mysqld.sock|g' /etc/my.cnf.d/socket.cnf
mysql_1  | [INFO] Setting MySQL: [mysqld] socket=/tmp/mysql/mysqld.sock
mysql_1  | root $ sed -i'' 's|\[mysqld\]|\[mysqld\]
mysql_1  | socket = /tmp/mysql/mysqld.sock|g' /etc/my.cnf.d/socket.cnf
mysql_1  | root $ chown mysql:mysql /tmp/mysql
mysql_1  | root $ chmod 0777 /tmp/mysql
mysql_1  | root $ chown -R mysql:mysql /var/lib/mysql/
mysql_1  | root $ chown -R mysql:mysql /var/lib/mysql
mysql_1  | root $ chown -R mysql:mysql /var/log/mysql
mysql_1  | root $ chown -R mysql:mysql /var/run/mysqld
mysql_1  | root $ chown -R mysql:mysql /var/sock/mysqld
mysql_1  | root $ chmod 0775 /var/lib/mysql/
mysql_1  | root $ chmod 0775 /var/lib/mysql
mysql_1  | root $ chmod 0775 /var/log/mysql
mysql_1  | root $ chmod 0775 /var/run/mysqld
mysql_1  | root $ chmod 0775 /var/sock/mysqld
mysql_1  | root $ find /var/log/mysql/ -type f -exec chmod 0664 {} \;
mysql_1  | [INFO] Found existing data directory. MySQL already setup.
mysql_1  | [INFO] Starting mysqld  Ver 5.6.37 for Linux on x86_64 (MySQL Community Server (GPL))
mysql_1  | 2018-02-20 13:06:49 0 [Warning] TIMESTAMP with implicit DEFAULT value is deprecated. Please use --explicit_defaults_for_timestamp server option (see documentation for more details).
mysql_1  | 2018-02-20 13:06:49 0 [Note] mysqld (mysqld 5.6.37-log) starting as process 1 ...
devilbox_mysql_1 exited with code 1
`

**Comment by cytopia** [comment]
Can u check if there is already a container running?

Maybe even do the following for a fully fresh start:
```
docker-compose down
docker-compose kill
docker-compose rm -f
docker-compose up
```

**Comment by dozzy100** [comment]
Did all what you asked above, still get the error (somewhere in between the log):

devilbox_mysql_1 exited with code 1

**Comment by dozzy100** [comment]
While trying again with 5.7, if I do not try to use existing data then it works fine, but if I try to mount my existing databases I get the initial error.

**Comment by dozzy100** [comment]
It is working now with 5.7. Need to grant privileges to root for access from all hosts. 

GRANT ALL PRIVILEGES on *.* to root@'%';

You will have to log in to the mysql container. Using ./shell.sh will not work as it logs into the php container. Try using:

docker-compose exec --user root mysql env TERM=xterm /bin/sh -c "cd ${CWD}; exec bash -l"

**Comment by cytopia** [comment]
That's however very strange. The root user should be allowed to be accessed from all hosts. Thanks for the catch!

**Comment by dozzy100** [comment]
This happened because all my existing mysql databases were mounted, including the 'mysql' table with all restrictions set in the previous installations.

**Comment by sierrafayad** [comment]
This is happening again with new installations i tested from a fresh installation on this commit
a8eaabda4f3caaf9f36bc2bb92e4044006baca1b

**Comment by sierrafayad** [comment]
> This is happening again with new installations i tested from a fresh installation on this commit
> [a8eaabd](https://github.com/cytopia/devilbox/commit/a8eaabda4f3caaf9f36bc2bb92e4044006baca1b)

Nevermind it was a problem with my setup

**Comment by jun9** [comment]
> GRANT ALL PRIVILEGES on *.* to root@'%';
needs to be run on mysql 5.6.43 to get mysql connected.  @dozzy100 's  solution works. 
https://github.com/cytopia/devilbox/issues/196#issuecomment-366998578
