### ISSUE TITLE
How to remove devilbox completely?

### ISSUE THREAD

**Issue by thedevsaddam** [cytopia/devilbox#197]
I am using Mac and I want to remove devilbox completely. I have removed all the docker images and stopped containers. But when I start the docker it run the container.

**Comment by cytopia** [comment]
**Remove devilbox directory**

Make sure everything is stopped and removed
```
docker-compose stop
docker-compose rm -f
```
Then you will have to delete the `devilbox` git directory. The rest of it are just docker images that the devilbox uses. Some of them are official images and some of them are devilbox specific images.

**Remove docker images**

When you also want to remove docker images, have a look at various stackoverflow questions. https://stackoverflow.com/questions/17665283/how-does-one-remove-an-image-in-docker
