### ISSUE TITLE
Mailhog Integration

### ISSUE THREAD

**Issue by pleek91** [cytopia/devilbox#202]
This isn't a bug or issue but more of a help request. I'd like to use mailhog [https://github.com/mailhog/MailHog](url) instead of the built in mail catcher. I've followed the mailhog docs for installing and configuring it with php but can't seem to get it working. 

What do I need to do to have all mail traffic flow through a mailhog container? I've added mailhog  as a service in my docker-compose.yml file and I can access the mailhog browser interface. But I cannot seem to get emails to show up in mailhog. 

Thanks in advance!

**Comment by cytopia** [comment]
Every request (on the PHP container) which is send directly via postfix is catched-all and put into the local mailbox. The corresponding PHP.ini directive looks as follows:
```ini
[mail function]
sendmail_path = /usr/sbin/sendmail -t -i
;mail.force_extra_parameters =
mail.add_x_header = On
mail.log = /var/log/mail.log
```
This ensures the PHP mail function is using a local sendmail binary, which then interacts with postfix which does a catch-all.

The postfix settings are here: https://github.com/devilbox/docker-php-fpm/blob/master/Dockerfiles/prod/data/docker-entrypoint.d/31-postfix.sh#L74

Is there something you see should be changed to make it work with mailhog?

**Comment by Tuurlijk** [comment]
@pleek91 You can use mhsendmail, a small go executable that replaces sendmail and forwards mail to a mailhog instance: https://www.lullabot.com/articles/debugging-php-email-with-mailhog

**Comment by Tuurlijk** [comment]
https://github.com/devilbox/docker-php-fpm/pull/32

**Comment by cytopia** [comment]
Merged, container should be available in ~1-2 hours.

I will leave this open until I have added documentation to it.

**Comment by cytopia** [comment]
https://devilbox.readthedocs.io/en/latest/custom-container/integrate-mailhog.html
