### ISSUE TITLE
httpd not starting

### ISSUE THREAD

**Issue by dantopa** [cytopia/devilbox#205]
Devilbox is not working for me, this is what shows up:
httpd_1  | [ERR]  Wrong value for $DEBUG_ENTRYPOINT: '0'
httpd_1  | [ERR]  Allowed values: 0, 1 and 2
devilbox_httpd_1 exited with code 1

Then, if I config DEBUG_ENTRYPOINT to be 1 instead of 0, this shows:
httpd_1  | [ERR]  $MAIN_VHOST_DISABLE is set to  , but must be 0 or 1.

Please help me. I have configured devilbox for apache 2.4 and php 7.1, but I have also tried with apache 2.2 and the same happens. Also all images and containers have been pulled to latest version.

**Comment by cytopia** [comment]
Did u create a `.env` file?

**Comment by dantopa** [comment]
Yes, this is my .env: 

 ###

###  ---------------------------------------------------
###  D E V I L B O X   R U N - T I M E   S E T T I N G S
###  ---------------------------------------------------
###
###  All the following settings are applied during
###  $ docker-compose up
###
###  No need to rebuild any dockers!
###


###
### Show all executed commands in each
### docker image during docker-compose up?
###
### 1: Yes
### 0: No
DEBUG_COMPOSE_ENTRYPOINT=1


###
### Relative or absolute path to the devilbox repository.
### (Used as a prefix for all mount paths)
### There is no need to change this.
###
### The only exception is for OSX users wanting to use NFS
### mounts instead of Filesystem mounts due to degraded performance
### on OSX.
###
DEVILBOX_PATH=.


###
### At what IP address should the docker services listen
### on the Host computer?
###
### The specified default should be fine for Linux and OSX (127.0.0.1:).
### If you are on windows, you will probably have to change
### it to the IP address of the docker machine.
###
### a.) Leave blank, to listen on all interfaces (no trailing color ':')
###    LOCAL_LISTEN_ADDR=
### b.) If an IP is specified, note the trailing colon ':'
###    LOCAL_LISTEN_ADDR=127.0.0.1:
###
LOCAL_LISTEN_ADDR=127.0.0.1:


###
### This is the domain suffix your projects will be made available
### with mass-virtual-hosting.
### It is also required for the internal DNS server to be setup.
###
### Note: Only ALPHA ([a-zA-Z]+) characters are supported.
###
### Example:
###   TLD_SUFFIX=loc
### Makes your project available under xxxx.loc
###
### Example:
###   TLD_SUFFIX=local
### Makes your project available under xxxx.local
###
TLD_SUFFIX=loc


###
### TLD_SUFFIX domains are checked if they are set in the
### host computer /etc/hosts or available via attached DNS server.
### Timeout is done on vhosts.php (intranet) via ajax calls.
### In order to keep performance, set this to a low value.
### DNS checks might not succeed in time on slow machines.
### If DNS is valid, but timeout is expired, set this to a higher value.
###
### DNS_CHECK_TIMEOUT value is how many seconds to time out
### Default is to timeout after 1 second (DNS_CHECK_TIMEOUT=1)
###
DNS_CHECK_TIMEOUT=1


###
### Set your user id and group id
###
### This should be changed to the value of your local
### users uid and gid
###
### Type `id` on the terminal to find out your values
###
NEW_UID=1000
NEW_GID=1000


###
### Timezone for all dockers and service config files
###
TIMEZONE=Europe/Berlin



################################################################################
###
### 1. Choose Images (Version)
###
################################################################################

###
### You can choose any combination of httpd, mysql, postgresql or php.
### Each of them are fully compatible between one another.
###


###
### 1.1 Choose PHP Server Image
###
#PHP_SERVER=php-fpm-5.4
#PHP_SERVER=php-fpm-5.5
#PHP_SERVER=php-fpm-5.6
PHP_SERVER=php-fpm-7.1
#PHP_SERVER=hhvm-latest


###
### 1.2 Choose HTTPD Server Image
###
#HTTPD_SERVER=apache-2.2
HTTPD_SERVER=apache-2.4
#HTTPD_SERVER=nginx-stable
#HTTPD_SERVER=nginx-mainline


###
### 1.3 Choose MySQL Server Image
###
#MYSQL_SERVER=mysql-5.5
#MYSQL_SERVER=mysql-5.6
#MYSQL_SERVER=mysql-5.7
#MYSQL_SERVER=mysql-8.0
#MYSQL_SERVER=mariadb-5.5
#MYSQL_SERVER=mariadb-10.0
#MYSQL_SERVER=mariadb-10.1
#MYSQL_SERVER=mariadb-10.2
MYSQL_SERVER=mariadb-10.3


###
### 1.4 Choose PostgreSQL Server Image
###
#PGSQL_SERVER=9.1
#PGSQL_SERVER=9.2
#PGSQL_SERVER=9.3
#PGSQL_SERVER=9.4
#PGSQL_SERVER=9.5
PGSQL_SERVER=9.6


###
### 1.5 Choose Redis Server Image
###
#REDIS_SERVER=2.8
#REDIS_SERVER=3.0
REDIS_SERVER=3.2


###
### 1.6 Choose Memcached Server Image
###
MEMCD_SERVER=1.4.21
#MEMCD_SERVER=1.4.22
#MEMCD_SERVER=1.4.23
#MEMCD_SERVER=1.4.24
#MEMCD_SERVER=1.4.25
#MEMCD_SERVER=1.4.26
#MEMCD_SERVER=1.4.27
#MEMCD_SERVER=1.4.28
#MEMCD_SERVER=1.4.29
#MEMCD_SERVER=1.4.30
#MEMCD_SERVER=1.4.31
#MEMCD_SERVER=1.4.32
#MEMCD_SERVER=1.4.33
#MEMCD_SERVER=1.4.34
#MEMCD_SERVER=1.4.35
#MEMCD_SERVER=1.4.36
#MEMCD_SERVER=latest


###
### 1.7 Choose Mongo Server Image
###
#MONGO_SERVER=2.8
#MONGO_SERVER=3.0
#MONGO_SERVER=3.2
MONGO_SERVER=3.4
#MONGO_SERVER=3.5



################################################################################
###
### 2. Host Mounts (Your computer)
###
################################################################################

###
### Local filesystem path to www projects.
###
HOST_PATH_HTTPD_DATADIR=./data/www

###
### Local filesystem path to mysql/mariadb datadir.
###
### This can be an existing mysql data directory or empty.
### If it already is a mysql data directory with content,
### it will be mounted into the docker and used.
###
### If this directory is empty, a new mysql database will be
### created.
###
### Note: Inside this path, a subdirectory with the mysql|mariadb
###       version will be created where the actual data resides.
###       This is to protect databases from being altered by
###       newer or older mysql|mariadb server versions.
###
HOST_PATH_MYSQL_DATADIR=./data/mysql


###
### Local filesystem path to postgresql datadir.
###
### This can be an existing postgresql data directory or empty.
### If it already is a postgresql data directory with content,
### it will be mounted into the docker and used.
###
### If this directory is empty, a new postgresql database will be
### created.
###
### Note: Inside this path, a subdirectory with the postgresql
###       version will be created where the actual data resides.
###       This is to protect databases from being altered by
###       newer or older postgres server versions.
HOST_PATH_PGSQL_DATADIR=./data/pgsql


###
### Local filesystem path to mongodb datadir.
###
### This can be an existing mongodb data directory or empty.
### If it already is a mongodb data directory with content,
### it will be mounted into the docker and used.
###
### If this directory is empty, a new mongodb database will be
### created.
###
HOST_PATH_MONGO_DATADIR=./data/mongo



################################################################################
###
### 3. PHP Docker Settings
###
################################################################################

###
### Xdebug
###

# Enable/Disable Xdebug
PHP_XDEBUG_ENABLE=1

# Your local port (your computer host [not the docker])
# where your ide/editor is listening for xdebug connections.
PHP_XDEBUG_REMOTE_PORT=9000

# Your local IP address (your computer host [not the docker])
# where your ide/editor is listening for xdebug connections.
PHP_XDEBUG_REMOTE_HOST=192.168.0.215
## TODO: Check if it works by automatically sending it to the broadcast address



################################################################################
###
### 4. HTTPD Docker Settings
###
################################################################################

###
### Expose HTTPD Port to Host
###
HOST_PORT_HTTPD=80



################################################################################
###
### 5. MySQL Docker Settings
###
################################################################################

###
### MySQL root user password
###
### If $HOST_PATH_TO_MYSQL_DATADIR already contains an existing
### mysql datadir, enter the password for the existing mysql database
###
### If $HOST_PATH_TO_MYSQL_DATADIR is empty, choose a new password that
### will be applied
###
MYSQL_ROOT_PASSWORD=

###
### Custom MySQL Runtime Settings
###
MYSQL_GENERAL_LOG=1

###
### Expose MySQL Port to Host
###
HOST_PORT_MYSQL=3306



################################################################################
###
### 6. PostgreSQL Docker Settings
###
################################################################################

###
### PostgreSQL 'root' user name (usually postgres)
###
PGSQL_ROOT_USER=postgres

###
### PostgreSQL 'root' user password
###
PGSQL_ROOT_PASSWORD=

###
### Expose PostgreSQL Port to Host
###
HOST_PORT_PGSQL=5432



################################################################################
###
### 7. Redis Docker Settings
###
################################################################################

###
### Expose Redis Port to Host
###
HOST_PORT_REDIS=6379



################################################################################
###
### 8. Memcached Docker Settings
###
################################################################################

###
### Expose Memcached Port to Host
###
HOST_PORT_MEMCD=11211



################################################################################
###
### 9. MongoDB Docker Settings
###
################################################################################

###
### Expose MongoDB Port to Host
###
HOST_PORT_MONGO=27017



################################################################################
###
### 10. Bind Docker Settings
###
################################################################################

###
### Expose Bind Port to Host
###
HOST_PORT_BIND=1053

###
### Add comma separated DNS server from which you want to receive DNS
### You can also add DNS servers from your LAN (if any are available)
###
BIND_DNS_RESOLVER=8.8.8.8,8.8.4.4

I'm on Arch Linux with Docker 18.02

**Comment by cytopia** [comment]
What is your docker-compose version?

**Comment by cytopia** [comment]
I already see it. Looks like your `.env` file is outdated. When you have updated your git branch, also compare your `.env` file with the shipped `env-example`. You are missing a couple of values.

**Comment by dantopa** [comment]
Thanks for the reply, I have updated the .env so is the latest. but there are still problems. I also cloned a new devilbox git but the same happens. I was using devilbox perfectly before, my docker-compose version is 1.19. This is what shows up when trying to run:

[pde@arch devilbox]$ docker-compose up httpd php mysql bind
Creating devilbox_php_1   ... done
Creating devilbox_bind_1  ... 
Creating devilbox_httpd_1 ... done
Creating devilbox_httpd_1 ... 
Creating devilbox_mysql_1 ... done
Attaching to devilbox_bind_1, devilbox_php_1, devilbox_httpd_1, devilbox_mysql_1
bind_1   | [INFO] Adding wildcard DNS record: '*.loc' -> '172.16.238.11'
bind_1   | root $ echo 'include "/etc/bind/custom-named.conf.loc";' >> /etc/bind/named.conf
php_1    | [INFO] Changing user 'devilbox' uid to: 1000
mysql_1  | [INFO] Setting docker timezone to: Europe/Berlin
httpd_1  | [INFO] $DOCKER_LOGS not set. Logging errors and access to log files inside container.
bind_1   | [INFO] Adding custom DNS forwarder: 8.8.8.8,8.8.4.4
mysql_1  | root $ rm /etc/localtime
bind_1   | [INFO] Starting BIND 9.10.3
php_1    | root $ usermod -u 1000 devilbox
php_1    | usermod: no changes
mysql_1  | root $ ln -s /usr/share/zoneinfo/Europe/Berlin /etc/localtime
php_1    | [INFO] Changing group 'devilbox' gid to: 1000
php_1    | root $ groupmod -g 1000 devilbox
httpd_1  | [INFO] Setting docker timezone to: Europe/Berlin
httpd_1  | [INFO] Docker date set to: Thu Mar  8 16:19:26 CET 2018
httpd_1  | [INFO] Changing user 'daemon' uid to: 1000
php_1    | [WARN] $DOCKER_LOGS_ERROR not set.
php_1    | [WARN] Not logging errors to docker logs, using file inside container
httpd_1  | [INFO] Changing group 'daemon' gid to: 1000
mysql_1  | [INFO] Docker date set to: Thu Mar  8 16:19:27 CET 2018
php_1    | root $ chmod 0664 /var/log/php/www-error.log
httpd_1  | [INFO] $MAIN_VHOST_DISABLE set to 0. Not disabling the default vhost.
mysql_1  | [INFO] Setting MySQL: [mysqld] general-log=1
mysql_1  | root $ touch /etc/my.cnf.d/logging.cnf
php_1    | root $ chmod 0664 /var/log/php/php-fpm.err
httpd_1  | [INFO] $MAIN_VHOST_DOCROOT not specified. Keeping default: htdocs
php_1    | root $ chmod 0664 /var/log/php/www-slow.log
httpd_1  | [INFO] $MAIN_VHOST_TPL not specified. Keeping default: cfg
httpd_1  | [INFO] $MAIN_VHOST_STATUS_ENABLE set to 1. Enabling httpd status.
mysql_1  | root $ echo '[mysqld]' >> /etc/my.cnf.d/logging.cnf
httpd_1  | [INFO] Setting httpd status page to: '/devilbox-httpd-status'
php_1    | root $ chown devilbox:devilbox /var/log/php/www-error.log
httpd_1  | [INFO] $MASS_VHOST_ENABLE set to 1. Enabling mass vhosts.
php_1    | root $ chown devilbox:devilbox /var/log/php/php-fpm.err
httpd_1  | [INFO] $MASS_VHOST_TLD set to: .loc
php_1    | root $ chown devilbox:devilbox /var/log/php/www-slow.log
httpd_1  | [INFO] $MASS_VHOST_DOCROOT is set to: htdocs
php_1    | [WARN] $DOCKER_LOGS_ACCESS not set.
php_1    | [WARN] Not logging access to docker logs, using file inside container
php_1    | root $ chmod 0664 /var/log/php/www-access.log
php_1    | root $ chown devilbox:devilbox /var/log/php/www-access.log
php_1    | [WARN] $DOCKER_LOGS_XDEBUG not set.
php_1    | [WARN] Not logging xdebug to docker logs, using file inside container
httpd_1  | [INFO] $MASS_VHOST_TPL is set to: cfg
mysql_1  | root $ echo 'general-log = 1' >> /etc/my.cnf.d/logging.cnf
httpd_1  | [INFO] $PHP_FPM_ENABLE set to 1. Enabling PHP-FPM.
php_1    | root $ chmod 0664 /var/log/php/xdebug.log
httpd_1  | [INFO] $PHP_FPM_SERVER_ADDR is set to: php
php_1    | root $ chown devilbox:devilbox /var/log/php/xdebug.log
php_1    | [INFO] Setting docker timezone to: Europe/Berlin
httpd_1  | [INFO] $PHP_FPM_SERVER_PORT is set to: 9000
php_1    | root $ rm /etc/localtime
httpd_1  | vhostgen: [2018-03-08 16:19:26] Adding: localhost
php_1    | root $ ln -s /usr/share/zoneinfo/Europe/Berlin /etc/localtime
php_1    | [INFO] Setting PHP: timezone=Europe/Berlin
httpd_1  | 2018-03-08 16:19:26,925 CRIT Set uid to user 0
httpd_1  | 2018-03-08 16:19:26,930 INFO supervisord started with pid 1
php_1    | root $ sed -i'' 's|;*date.timezone[[:space:]]*=.*$|date.timezone = Europe/Berlin|g' /etc/php.ini
php_1    | [INFO] Docker date set to: Thu Mar  8 16:19:25 CET 2018
mysql_1  | [INFO] Setting MySQL: [client] socket=/tmp/mysql/mysqld.sock
php_1    | [INFO] Adding custom configuration files:
php_1    | root $ find /etc/php-custom.d -type f -iname "*.ini" -exec echo "Copying: {} to /etc/php.d/" \; -exec cp "{}" /etc/php.d/ \;
php_1    | Copying: /etc/php-custom.d/devilbox-custom.ini to /etc/php.d/
php_1    | root $ find /etc/php.d -name '*.ini' -exec chmod 0644 {} \;
php_1    | [INFO] Setting PHP: xdebug.remote_enable=1
php_1    | root $ echo 'xdebug.remote_enable=1' >> /etc/php.d/15-xdebug.ini
php_1    | [INFO] Setting PHP: xdebug.remote_connect_back=0
mysql_1  | root $ touch /etc/my.cnf.d/socket.cnf
php_1    | root $ echo 'xdebug.remote_connect_back=0' >> /etc/php.d/15-xdebug.ini
php_1    | [INFO] Setting PHP: xdebug.remote_port=9000
php_1    | root $ echo 'xdebug.remote_port=9000' >> /etc/php.d/15-xdebug.ini
php_1    | [INFO] Setting PHP: xdebug.remote_host=192.168.0.215
php_1    | root $ echo 'xdebug.remote_host=192.168.0.215' >> /etc/php.d/15-xdebug.ini
php_1    | [INFO] Setting PHP: xdebug.remote_log="/var/log/php/xdebug.log"
php_1    | root $ echo 'xdebug.remote_log="/var/log/php/xdebug.log"' >> /etc/php.d/15-xdebug.ini
php_1    | [INFO] Forwarding mysql:3306 to 127.0.0.1:3306 inside this docker.
php_1    | root $ /usr/bin/socat tcp-listen:3306,reuseaddr,fork tcp:mysql:3306 &
php_1    | [INFO] Forwarding pgsql:5432 to 127.0.0.1:5432 inside this docker.
php_1    | root $ /usr/bin/socat tcp-listen:5432,reuseaddr,fork tcp:pgsql:5432 &
php_1    | [INFO] Forwarding redis:6379 to 127.0.0.1:6379 inside this docker.
php_1    | root $ /usr/bin/socat tcp-listen:6379,reuseaddr,fork tcp:redis:6379 &
php_1    | [INFO] Forwarding memcd:11211 to 127.0.0.1:11211 inside this docker.
php_1    | root $ /usr/bin/socat tcp-listen:11211,reuseaddr,fork tcp:memcd:11211 &
php_1    | [INFO] Forwarding mongo:27017 to 127.0.0.1:27017 inside this docker.
php_1    | root $ /usr/bin/socat tcp-listen:27017,reuseaddr,fork tcp:mongo:27017 &
php_1    | [INFO] Enabling sending of emails.
php_1    | root $ chmod 0644 /var/mail/devilbox
php_1    | root $ chown devilbox:devilbox /var/mail/devilbox
php_1    | root $ sed -i'' 's/^inet_protocols.*/inet_protocols = ipv4/g' /etc/postfix/main.cf
php_1    | root $ echo 'virtual_alias_maps = pcre:/etc/postfix/virtual' >> /etc/postfix/main.cf
php_1    | root $ echo '/.*@.*/ devilbox' >> /etc/postfix/virtual
php_1    | root $ newaliases
mysql_1  | root $ echo '[client]' >> /etc/my.cnf.d/socket.cnf
mysql_1  | root $ echo 'socket = /tmp/mysql/mysqld.sock' >> /etc/my.cnf.d/socket.cnf
mysql_1  | [INFO] Setting MySQL: [mysql] socket=/tmp/mysql/mysqld.sock
mysql_1  | root $ echo '[mysql]' >> /etc/my.cnf.d/socket.cnf
mysql_1  | root $ echo 'socket = /tmp/mysql/mysqld.sock' >> /etc/my.cnf.d/socket.cnf
mysql_1  | [INFO] Setting MySQL: [mysqld] socket=/tmp/mysql/mysqld.sock
mysql_1  | root $ echo '[mysqld]' >> /etc/my.cnf.d/socket.cnf
mysql_1  | root $ echo 'socket = /tmp/mysql/mysqld.sock' >> /etc/my.cnf.d/socket.cnf
mysql_1  | root $ mkdir -p /tmp/mysql
mysql_1  | root $ chown mysql:mysql /tmp/mysql
mysql_1  | root $ chmod 0777 /tmp/mysql
mysql_1  | root $ chown -R mysql:mysql /var/lib/mysql/
mysql_1  | root $ chown -R mysql:mysql /var/lib/mysql
mysql_1  | root $ chown -R mysql:mysql /var/log/mysql
mysql_1  | root $ chown -R mysql:mysql /var/run/mysqld
mysql_1  | root $ chown -R mysql:mysql /var/sock/mysqld
mysql_1  | root $ chmod 0775 /var/lib/mysql/
mysql_1  | root $ chmod 0775 /var/lib/mysql
mysql_1  | root $ chmod 0775 /var/log/mysql
mysql_1  | root $ chmod 0775 /var/run/mysqld
mysql_1  | root $ chmod 0775 /var/sock/mysqld
mysql_1  | root $ find /var/log/mysql/ -type f -exec chmod 0664 {} \;
mysql_1  | [INFO] Found existing data directory. MySQL already setup.
mysql_1  | [INFO] Starting mysqld  Ver 10.3.4-MariaDB-log for Linux on x86_64 (MariaDB Server)
mysql_1  | 2018-03-08 16:19:27 0 [Note] mysqld (mysqld 10.3.4-MariaDB-log) starting as process 1 ...
httpd_1  | 2018-03-08 16:19:27,933 INFO spawned: 'apache' with pid 121
httpd_1  | 2018-03-08 16:19:27,936 INFO spawned: 'watcherd' with pid 122
httpd_1  | watcherd: [2018-03-08 16:19:27] Starting daemon.
httpd_1  | [Thu Mar 08 16:19:27.998165 2018] [mpm_event:notice] [pid 121:tid 140061447858048] AH00489: Apache/2.4.27 (Unix) configured -- resuming normal operations
httpd_1  | [Thu Mar 08 16:19:27.998678 2018] [core:notice] [pid 121:tid 140061447858048] AH00094: Command line: 'httpd -D FOREGROUND'
httpd_1  | vhostgen: [2018-03-08 16:19:28] Adding: colonialturismo.loc
httpd_1  | watcherd: [2018-03-08 16:19:28] [OK]  ADD: succeeded: /shared/httpd/colonialturismo
httpd_1  | vhostgen: [2018-03-08 16:19:28] Adding: edusar.loc
httpd_1  | watcherd: [2018-03-08 16:19:28] [OK]  ADD: succeeded: /shared/httpd/edusar
httpd_1  | vhostgen: [2018-03-08 16:19:28] Adding: juvips.loc
httpd_1  | watcherd: [2018-03-08 16:19:28] [OK]  ADD: succeeded: /shared/httpd/juvips
httpd_1  | vhostgen: [2018-03-08 16:19:28] Adding: moodle31.loc
httpd_1  | watcherd: [2018-03-08 16:19:28] [OK]  ADD: succeeded: /shared/httpd/moodle31
httpd_1  | vhostgen: [2018-03-08 16:19:28] Adding: moodle33.loc
httpd_1  | watcherd: [2018-03-08 16:19:28] [OK]  ADD: succeeded: /shared/httpd/moodle33
php_1    | root $ postfix start
httpd_1  | vhostgen: [2018-03-08 16:19:28] Adding: topspin.loc
httpd_1  | watcherd: [2018-03-08 16:19:28] [OK]  ADD: succeeded: /shared/httpd/topspin
httpd_1  | watcherd: [2018-03-08 16:19:28] [OK]  TRIGGER succeeded: /usr/local/apache2/bin/httpd -k restart
httpd_1  | [Thu Mar 08 16:19:28.471463 2018] [mpm_event:notice] [pid 121:tid 140061447858048] AH00494: SIGHUP received.  Attempting to restart
httpd_1  | watcherd: [2018-03-08 16:19:28] Using bash loop to watch for changes.
httpd_1  | [Thu Mar 08 16:19:28.481126 2018] [mpm_event:notice] [pid 121:tid 140061447858048] AH00489: Apache/2.4.27 (Unix) configured -- resuming normal operations
httpd_1  | [Thu Mar 08 16:19:28.481756 2018] [core:notice] [pid 121:tid 140061447858048] AH00094: Command line: 'httpd -D FOREGROUND'
php_1    | [INFO] $MYSQL_BACKUP_USER set for mysqldump-secure.
php_1    | [INFO] Changing to 'root'
php_1    | root $ sed -i'' 's/^user.*/user = root/g' /etc/mysqldump-secure.cnf
php_1    | [INFO] $MYSQL_BACKUP_PASS set for mysqldump-secure.
php_1    | [INFO] Changing to '********'
php_1    | root $ sed -i'' 's/^password.*/password = /g' /etc/mysqldump-secure.cnf
php_1    | [INFO] $MYSQL_BACKUP_HOST set for mysqldump-secure.
php_1    | [INFO] Changing to 'mysql'
php_1    | root $ sed -i'' 's/^host.*/host = mysql/g' /etc/mysqldump-secure.cnf
php_1    | root $ chown -R devilbox:devilbox /var/log/php
php_1    | root $ chmod 0755 /var/log/php
php_1    | root $ find /var/log/php -type f -exec chmod 0644 {} \;
php_1    | root $ rm -rf /var/lib/php/session
php_1    | root $ mkdir -p /var/lib/php/session
php_1    | root $ chown -R devilbox:devilbox /var/lib/php/session
php_1    | root $ chown devilbox:devilbox /shared/httpd
php_1    | root $ mkdir -p /shared/backups/mysql
php_1    | root $ mkdir -p /shared/backups/pgsql
php_1    | root $ mkdir -p /shared/backups/mongo
php_1    | root $ chown -R devilbox:devilbox /shared/backups
php_1    | root $ chown devilbox:devilbox /var/log/mysqldump-secure.log
php_1    | root $ chown devilbox:devilbox /etc/mysqldump-secure.conf
php_1    | root $ chown devilbox:devilbox /etc/mysqldump-secure.cnf
php_1    | root $ mv /home/devilbox /home/devilbox.old
php_1    | root $ mkdir /home/devilbox
php_1    | root $ mv /home/devilbox.old/.bash* /home/devilbox/
php_1    | root $ rm -rf /home/devilbox.old
php_1    | root $ chown -R devilbox:devilbox /home/devilbox
php_1    | [INFO] Starting PHP 7.1.9 (fpm-fcgi) (built: Aug 30 2017 20:08:00)
httpd_1  | 2018-03-08 16:19:29,483 INFO success: apache entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
httpd_1  | 2018-03-08 16:19:29,483 INFO success: watcherd entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)


Apparently when I enter localhost devilbox is showing well, but when I try to enter a website, shows me: "Error stablishing a database connection", and this happens with every website I have done. No idea what's the problem.

**Comment by cytopia** [comment]
> "Error stablishing a database connection" 

That just means that your database credentials are wrong at some place. Can u connect from your host machine or from within the php container via `mysql` binary and check if users still exist with correct permissions.

Alternatively use PHPMyAdmin on intranet.

**Comment by dantopa** [comment]
Yes, finally found what happened. I set a different mariadb version, so my databases weren't there. Now I finally set the correct version, and all is working fine.

Thanks!!!

**Comment by cytopia** [comment]
good to here.
