### ISSUE TITLE
Change docroot in .env

### ISSUE THREAD

**Issue by johnwbaxter** [cytopia/devilbox#206]
I am trying to change the docroot of an existing devilbox in the .env file.

The docs say to change the value and restart devilbox which i have done. (docker-compose down and then up)

I had: HTTPD_DOCROOT_DIR=public
I want: HTTPD_DOCROOT_DIR=deploy/public

I seem to get this error in the output which i don't normally:

httpd_1  | vhostgen: [2018-03-09 14:36:32] Adding: localhost
httpd_1  | sed: -e expression #1, char 31: unknown option to `s'
devilbox_httpd_1 exited with code 1

**Comment by cytopia** [comment]
@johnwbaxter good catch, this is indeed an error with `sed`. I will fix this in the container.

Looking at your special case, I think it can be done more easily.
Keep `HTTPD_DOCROOT_DIR` at the default (`htodcs`). and simply simlink `htdocs` to `deploy/public`.

Have a look at the CakePHP setup at step 4: https://github.com/cytopia/devilbox/blob/master/docs/Examples.md#21-setup-cakephp

Let me know if this resolves your problem for now.

**Comment by johnwbaxter** [comment]
Ha! I didn't think about a symlink! Nice, i'll do just that :) Thanks!!

**Comment by johnwbaxter** [comment]
Hmm, not sure why, but my symlink isn't working here. Everything looks right, but, no luck. I'll just wait until you have a fix for this one and then go back to it.

**Comment by cytopia** [comment]
Hmm this should actually work as it is a standard feature and I do it all the time.

What OS are you on and can you also show me the symlink via `ls -la` and the error it throws when opening the project in the browser

**Comment by johnwbaxter** [comment]
I'm on OSX.
ls -la gives me:
lrwxrwxrwx 1 devilbox devilbox   33 Mar 11 12:43 public -> site2018/webroot/deploy/public/

And the error it gives is:

403 Forbidden
nginx/1.12.1

**Comment by cytopia** [comment]
And `site2018/webroot/deploy/public/` site is in the same directory as the `public` dir?

Also by default the docroot name must be `htdocs`, did you change that to `public`?

**Comment by johnwbaxter** [comment]
I changed it to "public" in my .env originally so all projects use that folder name as the webroot.

See screenshot for the folder setup as that will explain better!
![screen shot 2018-03-11 at 14 39 22](https://user-images.githubusercontent.com/338729/37254749-27abf160-253a-11e8-9494-fa32b9a474e9.png)

**Comment by cytopia** [comment]
Public needs to point to `webroot/deploy/public/` and not to `site2018/webroot/deploy/public/`

**Comment by johnwbaxter** [comment]
I have changed it to that and still get the same error.

I ran `ls-ls` and get:
`lrwxrwxrwx 1 devilbox devilbox   22 Mar 11 14:47 public -> webroot/deploy/public/`

It's ok, i'll change my setup for now. Thanks!

**Comment by cytopia** [comment]
OK, one other thing that I see just now. Looks like your symlink is inside a directory called `public`, remove that directory and create the symlink on the same level as the rest:

```
ls -la
lrwxrwxrwx 1 devilbox devilbox 22 Mar 11 14:47 public -> webroot/deploy/public/
drwxrwxrwx 1 devilbox devilbox 22 Mar 11 14:47 webroot                                                                          
```

**Comment by cytopia** [comment]
You should use symlinks for this kind of stuff, because changing `HTTPD_DOCROOT_DIR` will change it globally for ALL projects

**Comment by johnwbaxter** [comment]
Yep, just caught that one myself!
All good now :D

Yep happy to use symlinks, but all my projects do follow the same directory structure, so it wouldn't have been an issue.

Thanks!!!!

**Comment by cytopia** [comment]
Fix is coming

* https://github.com/devilbox/docker-nginx-stable/pull/7
* https://github.com/devilbox/docker-nginx-mainline/pull/8
* https://github.com/devilbox/docker-apache-2.2/pull/7
* https://github.com/devilbox/docker-apache-2.4/pull/7

**Comment by johnwbaxter** [comment]
Cool, thanks again!
