### ISSUE TITLE
XDEBUG on Windows not working

### ISSUE THREAD

**Issue by sonicviz** [cytopia/devilbox#209]
- [ ] Which operating system are you at (Linux, OSX or Windows)
Windows 10 Pro 1709 16299.248
- [ ] `docker version`
Version 17.12.0-ce-win47 (15139)
- [ ] `docker-compose version`
1.18.0

I'm trying Devilbox as an alternative to other Docker Wordpress setups I've been using.
I'm managed to get it working up to the point of a WordPress install, all hooked up and working fine.
It's very fast, much better than 10ups Docker for WP.

However, I can't get XDEBUG from VSCode to attach. Without debug, it's pretty much useless.
I'm pretty certain I need to use the vEthernet Default Switch IP address, and Code is definitely listening on port 9000 when I enter debug mode. But it doesn't hit breakpoints at all, so it's obviously not connecting.

Could it be the path mappings are wrong in the Launch Config?
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
    
        {
            "name": "Listen for XDebug",
            "type": "php",
            "request": "launch",
            "port": 9000,
            "pathMappings": {
                "/shared/httpd/wordpress1": "${workspaceRoot}/data/www/wordpress1/htdocs"
            }
        },
        {
            "name": "Launch currently open script",
            "type": "php",
            "request": "launch",
            "program": "${file}",
            "cwd": "${fileDirname}",
            "port": 9000
        }
    ]
}

Any tips?

**Comment by cytopia** [comment]
```json
"pathMappings": {
            "/shared/httpd/wordpress1": "${workspaceRoot}/data/www/wordpress1/htdocs"
        }
```

From an initial view, the paths don't match. Shouldn't the left be `"/shared/httpd/wordpress1/htdocs"`.

Also here is some other information I just found: https://stackoverflow.com/questions/37478387/how-to-setup-xdebug-and-phpstorm-with-docker-for-windows-beta

Are you using native Docker or Toolbox for windows?.

Either way I am happy to get this sorted with u as i am currently writing the documentation for xdebug and windows is still the missing part.

**Comment by cytopia** [comment]
What you should do is:

1. Use the new php images from this PR: https://github.com/cytopia/devilbox/pull/203
    - This PR contains description for how to check it out
    - It will be merged soon, but is different from current master (which will be deprecated)

2. in the new PR, there is no `.env` setting for xdebug, you need to add this to php.ini yourself.
    - go to `cfg/php-fpm-5.6` (or any other version u require)
    - create a file `xdebug.ini` with the following content:

```ini
xdebug.remote_connect_back=0
xdebug.remote_host=192.168.246.1 
```

### But wait

You need to change the IP address and use your own.

**How to get your IP address**:

In a Windows command-line, run “ipconfig” and look for the IP4 address in “DockerNAT” entry. 192.168.246.1 in my case

Let me know if this works

**Comment by sonicviz** [comment]
I've had a similar issue in the past with 10UP Docker and solved it as outlined here https://github.com/10up/wp-local-docker/pull/53 but it recently broke again. Pita to fix.
Which is why I'm trying Devilbox.

I'll try out the above and see if I can get it working. ty.

**Comment by sonicviz** [comment]
I got XDebug working with the PR: #203 but with some modification to your instructions.
At least, I successfully got a breakpoint hit in a phpinfo.php test file in the root of htdocs.

Here's the configuration, assuming you are using PR: #203
xdevbug.ini in E:\Source Control\Docker\devilbox1\cfg\php-fpm-7.1\
xdebug.remote_enable = 1
xdebug.remote_connect_back=0
xdebug.remote_autostart = 1
xdebug.remote_host=192.x.y.z

Note: xdebug.remote_host should be the IP Address of the Hyper-V Virtual Ethernet Adaptor, not DockerNat IP address

VSCode Launch.json
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
    
        {
            "name": "Listen for XDebug",
            "type": "php",
            "request": "launch",
            "port": 9000,
            "pathMappings": {
                "/shared/httpd/wordpress1/htdocs": "${workspaceRoot}/data/www/wordpress1/htdocs"
            }
        },
        {
            "name": "Launch currently open script",
            "type": "php",
            "request": "launch",
            "program": "${file}",
            "cwd": "${fileDirname}",
            "port": 9000
        }
    ]
}

**Comment by cytopia** [comment]
Great, I will add it to the documentation. New docs are going to be around here, but are still under development: http://devilbox.readthedocs.io/en/documentation/

**Comment by cytopia** [comment]
Generalized Xdebug documentation now available: https://devilbox.readthedocs.io/en/latest/intermediate/configure-php-xdebug.html

**Comment by cytopia** [comment]
@erythro thanks for pointing this out. I will reopen this issue until the documentation is updated accordingly.
Can you supply a screen shot of the Hypver-V Virtual Ethernet Adaptor and the command how to display this on windows.

**Comment by cytopia** [comment]
@erythro could you also check to see if the following `php.ini` setting works equally well?

```ini
xdebug.remote_enable = 1
xdebug.remote_connect_back=0
xdebug.remote_autostart = 1
xdebug.remote_host = host.docker.internal
```

**Comment by erythro** [comment]
Hi @cytopia thanks, I'll give a more full explanation here, though I'm a bit out of my depth.  I slightly misunderstood the comment I quoted.

I suspect the problem might have been related to some messing around with virtualisation I did ages ago with the hyper-v manager.  I wanted to create an ubuntu virtual machine, but followed a guide, and part of that guide was creating a virtual switch so my virtual machine could have access to the internet (iirc).

Here's an anonymised screenshot of the output of ipconfig:

![image](https://user-images.githubusercontent.com/1539822/54022508-8f7ae900-418a-11e9-97ee-6b7389308ddb.png)

The thing that finally worked for me was setting the remote_host to 192.168.0.12, the value from "New Virtual Switch".  So is it possible I set up that virtual switch in such a way that it interfered with the Devilbox and/or Docker?

Here's a screenshot of the configuration of the switch:

![image](https://user-images.githubusercontent.com/1539822/54022892-732b7c00-418b-11e9-9e41-2abaec0b50ac.png)

So the settings you asked me to use didn't work for me, but I assume that's because I wasn't actually using vEthernet (Default Switch).

**Comment by cytopia** [comment]
@erythro thanks for the screenshots, I have added the information to the documentation and differentiated between two case:

1. No custom switch
2. Custom switch

Documentation:

* https://devilbox.readthedocs.io/en/latest/intermediate/configure-php-xdebug/windows/atom.html#gather-host-ip-address
* https://devilbox.readthedocs.io/en/latest/intermediate/configure-php-xdebug/windows/phpstorm.html#gather-host-ip-address
* https://devilbox.readthedocs.io/en/latest/intermediate/configure-php-xdebug/windows/sublime.html#gather-host-ip-address
* https://devilbox.readthedocs.io/en/latest/intermediate/configure-php-xdebug/windows/vscode.html#gather-host-ip-address

**Comment by sonicviz** [comment]
This is broken for me again now and I can no longer get XDebug to work

**Comment by lj3lj3** [comment]
Using IP address of vEthernet (Default Switch) instead of DockerNAT works for me on windows with docker desktop!

**Comment by cytopia** [comment]
I have rewritten the documentation and hope it does no present what actually needs to be done in Release v1.0.1 

https://github.com/cytopia/devilbox/releases/tag/v1.0.1

**Comment by sonicviz** [comment]
It's suddenly no longer working for again. 

The instructions also seem different again as well. 

eg: now in Launch.Json you say
                "/shared/httpd/mytest/htdocs": "${workspaceRoot}/htdocs"

but it used to be

                "/shared/httpd/mytest/htdocs": "${workspaceRoot}/data/www/mytest/htdocs" 

Xdbug is set up correctly, it's listening on 9000 as verified in Windows Resource monitor but it won't jump into a breakpoint doing a simple test with phpinfo.

I just pulled the latest Devilbox as well. This is really frustrating as Xdebug is a critical need atm.

**Comment by sonicviz** [comment]
Update: To test if it was a problem with my machine and/or Docker I've installed https://github.com/10up/wp-local-docker-v2 and successfully connected to XDebug

I still can't get Devilbox working again so sadly will have to switch to 10up, as XDebug is essential to me. 
I can't understand why Devilbox is so twitchy here though, It works, then it doesn't work and I literally spend hours trying to figure out why.
