### ISSUE TITLE
Redis config

### ISSUE THREAD

**Issue by mrpsiho** [cytopia/devilbox#210]
Hi,

Is it possible to have my own config for redis? Edit the default maybe?

I believe that this approach will help me with my issue https://laracasts.com/discuss/channels/laravel/redis-cache-for-multiple-sites-on-same-server But I am not sure where to put it.

Please, suggest. Thanks!

**Comment by cytopia** [comment]
@mrpsiho 

**Redis server config**

As I am using the official Redis  Docker image, you need to rely on them what's possible.
By reading their documentation it looks like you can mount a custom config: https://hub.docker.com/_/redis/

If you provide a working `redis.conf` I will integrate it and make it configurable

**Redis config on PHP side**

The link you have provided is just using different Redis db's by setting it via PHP redis functions. This is something you could just do within your PHP project as described in the example.

**Comment by cytopia** [comment]
I will close this issue as the question seems answered.
