### ISSUE TITLE
[Warning] World-writable config file '/etc/mysql/docker-default.d/my.cnf' is ignored

### ISSUE THREAD

**Issue by BenWaNH** [cytopia/devilbox#212]
Hi, 

i can't run mysql container because i've this error log : 

```
2018-04-03T08:57:39.958911Z 0 [Warning] TIMESTAMP with implicit DEFAULT value is deprecated. Please use --explicit_defaults_for_timestamp server option (see documentation for more details).
2018-04-03T08:57:39.968277Z 0 [Warning] Setting lower_case_table_names=2 because file system for /var/lib/mysql/ is case insensitive
2018-04-03T08:57:40.476536Z 0 [ERROR] InnoDB: Operating system error number 22 in a file operation.
2018-04-03T08:57:40.476620Z 0 [ERROR] InnoDB: Error number 22 means 'Invalid argument'
2018-04-03T08:57:40.476680Z 0 [ERROR] InnoDB: File ./ib_logfile101: 'aio write' returned OS error 122. Cannot continue operation
2018-04-03T08:57:40.476737Z 0 [ERROR] InnoDB: Cannot continue operation.
```

So, I try to override my mysql config, with my cnf file in cfg/mysql-5.7/my.cnf with this content : 
```
[mysqld]
sql-mode="STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION"
character-set-server=utf8
explicit_defaults_for_timestamp=true
innodb_use_native_aio=off
```

But..... after restart all, i've this message in my log container : 
`[Warning] World-writable config file '/etc/mysql/docker-default.d/my.cnf' is ignored`
I don't understand why... And my error above isn't corrected... Obviously...

I use docker on Windows 7 with Docker toolbox 
My version docker is v17.10.0-ce
And my docker-compose file is the default so it's a 2.1 version

Anyone have already encounter a similar issue?

Thanks for your help
Ben.

**Comment by cytopia** [comment]
@BenWaNH can you do paste the output of:

```
ls -la cfg/mysql-5.7/
```

I need to see your file permissions.

**Comment by BenWaNH** [comment]
Thanks
```
$ ls -la cfg/mysql-5.7/
total 14
drwxr-xr-x 1 bhenache 1052102   0 avr.   3 09:10 ./
drwxr-xr-x 1 bhenache 1052102   0 déc.  18 12:27 ../
-rw-r--r-- 1 bhenache 1052102   0 déc.  18 12:27 .keepme
-rw-r--r-- 1 bhenache 1052102  55 déc.  18 12:27 devilbox-custom.cnf-example
-rw-r--r-- 1 bhenache 1052102 222 avr.   3 09:14 my.cnf
```

**Comment by cytopia** [comment]
Could you `chmod` the `my.cnf` file to `0444` to see if it makes a difference.

```
chmod 0444 cfg/mysql-5.7/my.cnf
```

**Comment by BenWaNH** [comment]
Ok! Respect!!
It works, I don't understand why.... But that fix it.... -_-
Why 0444 ??

**Comment by cytopia** [comment]
It was complaining about `[Warning] World-writable config file '/etc/mysql/docker-default.d/my.cnf' is ignored`, so my first guess was to remove any write-able part from the file :-)

**Comment by cytopia** [comment]
It will be part of the new documentation. Thanks for reporting.

**Comment by nuriqbalamrillah** [comment]
I'm sorry because I don't know how to ask the right question like what and thank you
