### ISSUE TITLE
Update Adminer

### ISSUE THREAD

**Issue by LostNCG** [cytopia/devilbox#213]
Adminer version now is 4.3.1, I would like to update it to latest version, but seem like it cant set up through cfg path, currently I revise the setting in folder ./devilbox. I know this is not a good practice, am I missed up some correct solution to change the file adminer.XXX.php?

**Comment by cytopia** [comment]
I will add a new version soon. Are there any urgent features of the new version you rely on?

For now, you could just place the new version in: `.devilbox/www/htdocs/vendor/adminer-X.Y.Z-en.php` and adjust `.devilbox/www/include/lib/Html.php`

```php
<?php
    'path' => '/vendor/adminer-X.Y.Z-en.php',
```

**Comment by LostNCG** [comment]
@cytopia not urgent case, I'm doing it like that right now, but it is not a good practice btw

**Comment by cytopia** [comment]
@LostNCG  FYI:
Updated to latest version in upcoming PR (will be merged this weekend): https://github.com/cytopia/devilbox/pull/203
