### ISSUE TITLE
xdebug log timestamp error: 

### ISSUE THREAD

**Issue by 1298799999** [cytopia/devilbox#214]
![image](https://user-images.githubusercontent.com/31656350/38355500-a8fc14c0-38ef-11e8-9c89-54297d5318d7.png)

**Comment by cytopia** [comment]
That's really odd. Could you paste all related xdebug settings you have made. Also compare your local host operating system time and the one from the PHP container.

**Comment by cytopia** [comment]
@1298799999 any update on that?

**Comment by cytopia** [comment]
### This issue will be closed due to staleness.

Add required information in order to have it re-opened.
