### ISSUE TITLE
[Questions] local devilbox management / setup

### ISSUE THREAD

**Issue by danemorgan** [cytopia/devilbox#216]
1. Is there any reason I wouldn't want to put my devilbox in a dropbox folder to allow me to work on a sync'd copy between my desktop and my laptop?

2. If I need more than one configuration. EG. one with PHP 7.0 and Apache and another with PHP 7.1 and Nginx. what would be the best way to do this? Do I do something like this:
- sites
  - apahche
    - devilbox
      - www
  - nginx
     - devilbox
       - www
Or is there a way to have one devilbox folder with multiple configurations below it?

If I do use the organization above, is there any reason I can't remove one level by renaming the devilbox folder once the clone has finished?

**Comment by cytopia** [comment]
1. This is totally fine. You could also just sync your projects (if they are outside the Devilbox git directory). I am just now writing the documentation for that.

2. There is no need to separate your projects into that way. The configuration for all services are independent of project organization. Just have one main place on your file system where your projects reside. This will work for any combination of versions.

**Comment by danemorgan** [comment]
Can you point me to where I can read about how to configure so that one site gets Apache and another gets nginx?

**Comment by danemorgan** [comment]
Or do I need to change the commenting in the .env file each time I want to work with a different combination?

**Comment by cytopia** [comment]
Yes, versions need to be set in the `.env` file. Whenever you want to switch versions, you need to do that in the `.env` file and restart the Devilbox.

Have a look at the new documentation regarding change of versions: http://devilbox.readthedocs.io/en/documentation/tutorials/change-container-versions.html

Let me know if this explains it well enough or needs to be extended.

**Comment by danemorgan** [comment]
Okay. I understand that.

But the way I'm looking at it, the devilbox folder is only ~100MB - not so big.

So if I keep a separate copy of it for each combination I use, I only have to
1. stop the devilbox
2. cd to the other folder
3. start the devilbox
Then I don't have to do the editing each time, and I don't worry about typos ( I am the typo king ).

Does that make sense or is there a potential problem I'm not seeing?

**Comment by cytopia** [comment]
This could work as well. Make sure to point all of your data (project datadir, mysql-, mongo- and pgsql datadir) to a common location on all devilbox instances.

You could alternatively also have multiple `.env` files that you always copy or symlink into the Devilbox directory

**Comment by cytopia** [comment]
You could also write a small shell script, which does the copying. I will close it now. Hope everything is answered.
