### ISSUE TITLE
Make MySQL hostname persist

### ISSUE THREAD

**Issue by danemorgan** [cytopia/devilbox#217]
Each time I stop and then restart devilbox the MySQL hostname changes. Is there any way to have this set up so that I do not have to change my wp-config each time?

**Comment by cytopia** [comment]
The mysql hostname should simply be `127.0.0.1`. This way it is reachable from within the PHP container as well as from the host (if you switch to a host-based LAMP stack). No need to change the config afterwards.

**Comment by danemorgan** [comment]
Ah. Thank you. I tried localhost, but didn't think to try 127.0.0.1 after I saw the hostname in the database info page.

**Comment by cytopia** [comment]
Thanks for pointing that out. I made it more clear in the documentation: http://devilbox.readthedocs.io/en/documentation/getting-started/best-practice.html#php-project-hostname-settings
