### ISSUE TITLE
how to add Optional NoSQL stack 

### ISSUE THREAD

**Issue by ardanirohman** [cytopia/devilbox#22]
how to add redis and memcached on docker-compose.yaml?
thanks

**Comment by cytopia** [comment]
Hi @ardanirohman 

currently the NoSQL stack is not yet implemened.
Only the dockers which are displayed as a link can be enabled.
The NoSQL stack is planned for release 1.0.

The upcoming release is 0.8, so you will have to wait a few weeks.

**Comment by cytopia** [comment]
See [ROADMAP](https://github.com/cytopia/devilbox/issues/23)
