### ISSUE TITLE
I wonder how to connect to mysql 

### ISSUE THREAD

**Issue by ProjectKarol** [cytopia/devilbox#221]
I love devilbox a lot  , I am looking for some solution with  I don't know how to resolve,
I have wordpress installation and would like use this script "wordmove" (https://github.com/welaika/wordmove) , to  deploy do server.
I don't know  how to set up connection to mysql .
Installed wordmove globally on my linux machine. 
I use ubuntu 16.04, Docker version 18.03.0-ce, docker-compose version 1.20.0-rc1
I wonder do it possible. 
Than you for you great product.

**Comment by cytopia** [comment]
To connect to mysql, just use `127.0.0.1` as its host address, user: `root` and the password you have specified in `.env` (which is empty by default)

**Comment by cytopia** [comment]
You will have to connect to `127.0.0.1` when Devilbox MySQL is running.

For the Ruby version, please open up an issue here: https://github.com/devilbox/docker-php-fpm

**Comment by cytopia** [comment]
I added an issue there for you: https://github.com/devilbox/docker-php-fpm/issues/19
