### ISSUE TITLE
Adding extra containers to the stack

### ISSUE THREAD

**Issue by mijgame** [cytopia/devilbox#222]
Is it possible to add additional containers to the devilbox setup? In my case I want to add a laravel-echo-server (websocket server) container to the base stack, since I need this for a project I'm working on. I know I can add it to the docker-compose.yml, but I don't know if this would cause any problems (since it says -- DO NOT EDIT THIS FILE -- right at the top).

Thanks in advance.

**Comment by mijgame** [comment]
Ah, it was under 'Hacking' in the documentation! I didn't see it there, maybe you could make it a top-level documentation point? I would think a lot of people would like to add custom (personal) containers to devilbox.

**Comment by cytopia** [comment]
Yes, that's a valid point. Thanks for the feedback.

**Comment by cytopia** [comment]
@pedrosanta @mijgame Documentation is on the way: https://github.com/cytopia/devilbox/pull/231
