### ISSUE TITLE
Docker version 18.03.0-ce-win59: unable to finish Pulling bind (cytopia/bind:0.11) as unauthorized: incorrect username or password

### ISSUE THREAD

**Issue by alzen8work** [cytopia/devilbox#223]
I have done the check list as being inform,

I have check with another machine with older version of docker (Docker version 17.12.1-ce, build 7390fc6), This issue does not occur.

However, at my machine This issue occur:
<img width="607" alt="error" src="https://user-images.githubusercontent.com/20431509/38789447-ce690986-416c-11e8-8091-01b9f5071f78.png">

Perhaps, It would be great if there is any advice to further debug the root cause?

My Machine information:
Docker Version:
Version 18.03.0-ce-win59 (16762)
Channel: stable
D70d80d
- [Docker 18.03.0-ce]
(https://github.com/docker/docker-ce/releases/tag/v18.03.0-ce)
- [Docker Machine 0.14.0](https://github.com/docker/machine/releases/tag/v0.14.0)
- [Docker compose 1.20.1](https://github.com/docker/compose/releases/tag/1.20.1)
- [Notary 0.6.0](https://github.com/docker/notary/releases/tag/v0.6.0)

**Comment by cytopia** [comment]
@alzen8work are you by any chance logged into a different or private docker repository?

Can you check if any of those work separately:
```bash
docker pull cytopia/bind:0.11
```
```bash
docker pull devilbox/php-fpm:7.2-work
```

**Comment by alzen8work** [comment]
<img width="201" alt="screenshot_1" src="https://user-images.githubusercontent.com/20431509/38794643-7298e510-4188-11e8-892f-84e3c0acdbb0.png">

wow, that's seems to be the root cause, i've sign out from docker hub and it work marvelously...
wierd thing though it has no issue if i din sign out from docker version 17.12.1-ce...

**Comment by cytopia** [comment]
Lucky shot, but good to hear
