### ISSUE TITLE
Documentation update: Container DNS issues on Linux (With systemd-resolve)

### ISSUE THREAD

**Issue by science695** [cytopia/devilbox#225]
The documentation for Auto-DNS mentions that for linux you can manually add 127.0.0.1 to your /etc/resolv.conf

I had difficulties with that setup, but was able to find another way of making it work.
1)
Do not manually edit `/etc/resolv.conf` (the file says "DO NOT EDIT THIS FILE BY HAND -- YOUR CHANGES WILL BE OVERWRITTEN").

Add those lines to this file: `/etc/resolvconf/resolv.conf/head`
And then run:
```
resolvconf --enable-updates
resolvconf -u
```

2)
I still had dns troubles with this, but I was able to find out how to get docker to use both the bind server, and your dhcp given dns servers:

Add this to your `/etc/docker/daemon.json` (replace the 127.0.0.53 with the 127* address that your resolv.conf file has:
```
{
    "dns" : ["127.0.0.53"]
}
```

Then, in the `/etc/resolvconf/resolv.conf/head` add:
```
nameserver 172.16.238.100
```

These two things combined let me use my networks dns via systemd-resolved, and the bind container's dns.

Note: This is specifically for linux, where the system is running its own resolve server (i.e.: systemd-resolv)

Thanks for the work on this great tool.

**Comment by cytopia** [comment]
Good job!!! I will update the documentation. Can you also let me know what Linux/Distribution you're using.

**Comment by science695** [comment]
This is from Ubuntu 17.10, but any distribution that uses systemd-resolved should have this same affect. (Ubuntu started in 16.10)

**Comment by cytopia** [comment]
@science695 I just checked. I am using a Debian system, but the files you have mentioned are not available on my system. In the first the directory does not even exist.

```bash
$ ls -l /etc/resolvconf/
total 4
drwxr-xr-x 2 root root 4096 Mar 27 13:11 update-libc.d/
```

```bash
$  ls -l /etc/docker/
total 4
-rw------- 1 root root 244 Jan  8 16:02 key.json
```

**Comment by cytopia** [comment]
What about adding the following line at the very top to `/etc/dhcp/dhclient.conf`
```
prepend domain-name-servers 127.0.0.1;
```

and restart network manager afterwards via
```bash
$ sudo service network-manager restart
```

**Comment by cytopia** [comment]
http://devilbox.readthedocs.io/en/latest/configuration-global/auto-dns.html#linux

Please re-open in case this does not work

**Comment by science695** [comment]
That would appear to be proper instructions if your particular flavor of linux is **not** using systemd-resolve.

I would recommend including both sets of instructions labeled as With vs Without Systemd-resolve.

**Comment by cytopia** [comment]
OK, looks like I somehow misunderstood that and took it for `systemd` in general instead of `systemd-resolve`. I will re-open and add your instructions ass well. Thanks for clarifying.

**Comment by science695** [comment]
If I shutdown system-resolved and made those updates, it seems to be working properly.

however, I had to manually shutdown system-resolved. just 

> systemctl restart NetworkManager

 didn't do it. Its possible that a restart would make it work properly
