### ISSUE TITLE
How to get user_id and group_id in Windows 10 ?

### ISSUE THREAD

**Issue by nikoslyk2093** [cytopia/devilbox#230]
I am reading the documentation now to install Devilbox but in a section you mention that i need to set the UID kai GID but it provides the commands for linux only. How can i get these on Windows 10 ?

> The values for those two variables refer to your local (on your host operating system) user id and group id. To find out what the values are required in your case, issue the following commands on a terminal:
> 
> 1.5.1. Find your user id
> host> id -u
> 1.5.2. Find your group id
> host> id -g

**Comment by cytopia** [comment]
@nikoslyk2093 this is indeed very true. I googled a while and couldn't really find anything on that topic either. This might even be totally obsolete on Docker for Windows. Can you try to set this to `1000` (both uid and gid) and afterwards to `1001` (both), just to see how different values impact.

I will update the documentation afterwards.

**Comment by nikoslyk2093** [comment]
@cytopia I already tried that and Devilbox can't even start. It shows errors about user permissions. I suppose this is the problem.

**Comment by cytopia** [comment]
Can you please provide Docker and Docker Compose version as well as the full dump of docker-compose logs that show the errors. (Are you using Docker Toolbox or Docker for Windows?)

**Comment by cytopia** [comment]
@nikoslyk2093 I have just checked it on Windows 10 with `Docker Toolbox`. There is a dedicated Docker terminal where commands like `id -u` or `id -g` work normally. Is this the same for Docker for Windows? Is there also a dedicated Docker Terminal?

**Comment by cytopia** [comment]
@nikoslyk2093 I have now also checked this for **Docker for Windows**. There is no such concept as uid/gid and I have tried different settings, which did not make a difference.

So for Docker for Windows, just keep the defaults and do not make any settings there, it just works fine.
I will add this to the documentation as well

**Comment by DasserGIT** [comment]
@cytopia 

Hi , Good work on the devilbox stack, looks really good.  i'm expermenting with for my magento 2 local development environment.   

I am also using windows 10 as my host,  and having the same issue getting the user_id and group _id as per docs

1.5.1. Find your user id
host> id -u
1.5.2. Find your group id
host> id -g

I get id not reconised as a command,  I'm using Docker desktop 4.17 is this step not required and should i leave as the default values?

thanks

**Comment by vikas5914** [comment]
@DasserGIT

1. if you are using windows with Hyper-V, use `1000` for both. 
2. if you are using WSL, then open wsl and then run the command.
