### ISSUE TITLE
local subdomain instead of suffix

### ISSUE THREAD

**Issue by stefanlesik** [cytopia/devilbox#233]
I'd like to use local as the sub domain rather that .local as the domain suffix. Is this possible? So local.myproject.com not www.myproject.local. Thanks!

**Comment by cytopia** [comment]
## TLD_SUFFIX

This is unfortunately not how DNS works. You can only have it as a prefix (when relying on DNS).

Alternatively you can use `com` as your TLD and name your project: `local.myproject`. That would result in the name you want. However, then you are stuck to `com` for all projects.

## Vhost overwrite

You could also alter the vhost configuration itself. This allows you to use any domain for any project: http://devilbox.readthedocs.io/en/latest/tutorials/adding-subdomains.html#adding-www-sub-domain

**Comment by stefanlesik** [comment]
Thanks for the speedy reply. @cytopia. I'll start reconfiguring all my projects that are local. then! Cheers

**Comment by cytopia** [comment]
Welcome, I will close this issue then. Feel free to reopen if you hit problems on that approach.

**Comment by science695** [comment]
@stefanlesik: With the latest DNS features cytopia has added, you could do this now.

http://devilbox.readthedocs.io/en/latest/configuration-files/env-file.html#env-extra-hosts

`EXTRA_HOSTS='loc.myproject.com=172.16.238.11`
or
`EXTRA_HOSTS='loc.myproject.com=172.16.238.11,loc.mysecondproject.com=172.16.238.11`
