### ISSUE TITLE
ssh command not available when using composer

### ISSUE THREAD

**Issue by Remo** [cytopia/devilbox#235]
I'm using `shell.bat` to get into my docker console where I'd like to use `composer install` to install some dependencies of my projects. This works fine for most packages, but fails for some private packages. I've got a section like this in my `composer.json`:

```
    "repositories": [
        {
            "type": "vcs",
            "url": "git@bitbucket.org:user/repo.git"
        }
    ]
```

This fails with this error:

```

  [RuntimeException]
  Failed to execute git clone --no-checkout 'git@bitbucket.org:user/package.git' '/shared/httpd/project/vendor/user/package' && cd '/shared/httpd/project/vendor/user/package' && git remote add composer 'git@bitbucket.org:user/user-package.git' && git fetch composer

  Cloning into '/shared/httpd/project/vendor/user/package'...
  fatal: cannot run ssh: No such file or directory
  fatal: unable to fork
```

This is not really a surprise, when I type `ssh` it also fails. I think we should have access to ssh in the shell.

- `operating system` Windows 10
- `docker version` 18.03.1-ce
- `docker-compose version` 1.21.0, build 5920eb08

**Comment by Remo** [comment]
I've installed it myself, it's simple, but I still think it should be part of the distribution:
```
sudo su -
apt-get update
apt-get install ssh
```

**Comment by cytopia** [comment]
Makes more than sense. Didn't even know it was not available.

**Comment by cytopia** [comment]
ssh binary is on the way: https://github.com/devilbox/docker-php-fpm/pull/16/files

**Comment by Remo** [comment]
thanks a lot for that quick fix!

**Comment by cytopia** [comment]
When the build has succeeded: https://travis-ci.org/devilbox/docker-php-fpm, do a:

```bash
docker-compose pull php
```

**Comment by mateussantin** [comment]
Eu estou com um problema com isso, esta bloqueando minha chave de acesso ao github por exemplo, alguém pode ajudar?
![erro](https://user-images.githubusercontent.com/40871048/118196659-c2ccf880-b423-11eb-8b61-ca1a6cd04b50.png)
