### ISSUE TITLE
Connect external container to devilbox

### ISSUE THREAD

**Issue by fe3dback** [cytopia/devilbox#244]
- [x] Which operating system are you at (Linux, OSX or Windows)
Linux
- [x] `docker version`
Docker version 17.06.2-ce, build cec0b72
- [x] `docker-compose version`
docker-compose version 1.14.0, build c7bdf9e

----

Hello, i read this docs:
https://devilbox.readthedocs.io/en/latest/tutorials/communicating-with-external-hosts.html

but is not resolve my problem.

I have external container (https://prometheus.io/docs/prometheus/latest/installation/) and i want to connect port 9090 between devilbox, prometheus and host.

I try this, but is not working.

Dockerfile:
```Dockerfile
FROM prom/prometheus
ADD prometheus.yml /etc/prometheus/
```

```bash
docker build -t cm-prometheus .
docker run \
  -d \
  -p 9090:9090 \
  --name=cm-prometheus \
  --network=devilbox_app_net \
  --link devilbox_php_1 \
  cm-prometheus
```

this working only for host <-> prometheus. 

How to connect 9090 port to devilbox (php app), i need to send data wia curl from php container to prometheus container.

**Comment by cytopia** [comment]
So what hostname are you using to connect to the prometheus container?

Btw, alternatively, you cann add the prometheus definition to `docker-compose.override.yml` and make it part of your devilbox distribution: http://devilbox.readthedocs.io/en/latest/configuration-files/docker-compose-override-yml.html

**Comment by fe3dback** [comment]
> docker-compose.override.yml
thx, this is my solution, it works fine

**Comment by Tuurlijk** [comment]
@cytopia This ticket can be closed

**Comment by cytopia** [comment]
Good to know.

@fe3dback @Tuurlijk Documentation for how to connect to external hosts will also be available in more detail soon. Preview already available here:

https://devilbox.readthedocs.io/en/restructure-documentation/advanced/connect-to-host-os.html

**Comment by science695** [comment]
The docker compose override file is a great option. But if anyone has a situation where that is complicated, you can add it to the docker network.

docker compose creates a network called: "devilbox_app_net"

You can add the container to the network (everytime you re-create the container):
`docker network connect devilbox_app_net YOURCONTAINERNAMEHERE`

**Comment by cytopia** [comment]
@science695 thanks for that, didnt think of it. I will also add it to the docs
