### ISSUE TITLE
(Community Discussion) Discourse forum - requirements inside

### ISSUE THREAD

**Issue by cytopia** [cytopia/devilbox#245]
# Community Discussion: Discourse Forum

As more and more questions arise as normal issues I was looking into different forum software. The most modern approach would be to use **[discourse](https://www.discourse.org)** as it offers various auth methods.

**[Discourse](https://www.discourse.org)** only has paid plans, but allows for self hosting as well. I did however find an offer by them where they grant free hosting to open source projects:

https://blog.discourse.org/2016/03/free-discourse-forum-hosting-for-community-friendly-github-projects/

**The requirements for this are:**

* Hosted on Github
* 2000+ stars
* 30+ contributors

---

Let me know if a forum is a good idea at this point and if so, spread the word that the Devilbox can get **2000 stars** in order to qualify for [free discourse hosting](https://blog.discourse.org/2016/03/free-discourse-forum-hosting-for-community-friendly-github-projects/).

If you have alternative forum suggestions, let me know as well.

Thanks

**Comment by panigrc** [comment]
Well we need 1000 stars more.
Is it easy to set it up on own server ? 
If yes then we could get a 2.5 euro / month VPS at Hetzner.

**Comment by cytopia** [comment]
The 2.5/month won't be a problem, its rather self-hosted vs SaaS. I personally don't want to bother additionally with regular security updates, backups etc as it is a time killer and I'd rather spent time on improving the Devilbox itself.

Discourse must also not be the only choice, I personally am fine with what everybody likes most. Also needs to be clarified if this is actually in need at the current stage anyway.

**Comment by cytopia** [comment]
I was now granted a forum by discourse: https://devilbox.discourse.group/
