### ISSUE TITLE
autodns / WILDCARD_DNS with mac's lack of bridge network

### ISSUE THREAD

**Issue by science695** [cytopia/devilbox#246]
I am trying to get my devilbox setup to work on a mac, and have run into a problem with autodns that I'm not sure what the best solution is.

Since Mac OS X doesn't do the bridged network right, the docs say to bind all the ports to 127.0.0.1: but then the autodns keeps resolving all the vhosts to 172.16.238.11 which the mac cannot access.

I tried setting the WILDCARD_DNS=TLD=127.0.0.1 but then the docker containers cannot talk to each other using the vhost urls.  (i.e.: the www.loc vhost on php can't curl api.loc because it resolves to 127.0.0.1 which is the php container not apache)

I know I have a more complicated setup than normal, but do you have any ideas on how I can solve this?

I was able to hack it to work by spinning up a second bind container, one internal with 172.16.238.11 and one external with 127.0.0.1, but I feel that is less than optimal.

I will do some more tinkering with the mac os setup next week (unfortunately, I don't have access to it today).

I also noticed that the docs don't mention the wildcard_dns variable. Is that supposed to be internal use only?

**Comment by cytopia** [comment]
> Since Mac OS X doesn't do the bridged network right, the docs say to bind all the ports to 127.0.0.1: but then the autodns keeps resolving all the vhosts to 172.16.238.11 which the mac cannot access.

What happens if you bind to all interfaces nonetheless?

> I also noticed that the docs don't mention the wildcard_dns variable. Is that supposed to be internal use only?

Yes, its actually internal and hidden from the user as its value will be: ``<TLD_SUFFIX>=<DNS_SERVER_IP>

Another thing I haven't rolled out yet (as it requires more successful reportings) is this change: https://github.com/cytopia/devilbox/pull/138/files

This was reported by some macOS users to work, however it was not yet validated on Windows.

**Comment by science695** [comment]
Ah yes, that Pull request.

I must've undone those changes when pulling in the latest update. Thank you!

I would recommend listing those two changes in docs for other mac users, even if you don't pull it into the mainstream branch.

Thanks!

**Comment by cytopia** [comment]
What about binding to all interfaces instead?

**Comment by science695** [comment]
I will check that on Monday. But I thought that the apple host couldn't reach the docker network unless ports were forwarded?

**Comment by cytopia** [comment]
I always assumed this will depend on if you use Docker Toolbox (VirtualBox) or Docker for Mac (native)

**Comment by science695** [comment]
Okay, we are running on native presently. I'll due some sleuthing on Monday.

**Comment by science695** [comment]
Okay, my previous statement was while running on docker for mac (native), and is binding on all interfaces. Without that pull request which switches DNS (tested with 127.0.0.1), the lack of a bridge network prevents network connectivity.

(Note, I implemented that pull request in the docker-compose.override.yml file with great success)
