### ISSUE TITLE
Manually Add Another Services

### ISSUE THREAD

**Issue by isogram** [cytopia/devilbox#25]
If you encounter a bug and something does not work, make sure you have done the following and check those boxes before submitting an issue - thank you!

- [x] Pull latest dockers (e.g.: `docker pull cytopia/<used_docker>`) before running `docker-compose up`
- [X] Specify used docker versions (php, web and database)
- [X] Attach logs for php, mysql and webserver (found in `log/` directory)
- [X] Start with debug mode and attach docker-compose output (`.env` setting `DEBUG_COMPOSE_ENTRYPOINT=1`)
- [x] Never use different mysql|mariadb versions on the same `HOST_PATH_TO_MYSQL_DATADIR` on existing database files. Different mysql|mariadb versions might upgrade/corrupt existing database files. If you have done that already, start with a different path of `HOST_PATH_TO_MYSQL_DATADIR` (to an empty directory) and try again.

Please also specify the following info:

- [OSX] Which operating system are you at (Linux, OSX or Windows)
- [1.12.5] `docker version`
- [1.9.0] `docker-compose version`

First of all, I want to say many thanks for you. You have made awesome project.

I want to add some services like supervisor & beanstalk for queue, python with virtualenv, ruby for my rails project. Can I do that? Honestly I want to create `docker-compose` like [scotchbox vagrant](https://box.scotch.io/) .

**Comment by cytopia** [comment]
Most of the things you have mentioned are on the ROADMAP (except supervisor & beanstalk). I am still trying to figure out a good way that is compatible with many setups.

Not everybody wants or needs a ruby or python container, but some do.
So far I have thought about a shell script which is able to create/alter the docker-compose.yml depending on all the container you want to add.

If you have any good ideas about it, please feel free to post everything that comes to your mind.

**Comment by cytopia** [comment]
Similar to #31

@isogram Do you have any docker-compose examples for the above listed services. Could you also let me know in more detail how they should be integrated.

**Comment by cytopia** [comment]
@isogram multiple/different container base has now been setup with the current release. Next release will integrate various queuing services: beanstalk, kafka, etc

**Comment by isogram** [comment]
great work @cytopia 👍

**Comment by cytopia** [comment]
@isogram  I will close this ticket. Queuing services are scheduled for the next release. Manually adding services will be possible. I will add some documentation for that.

**Comment by yoshkin** [comment]
@cytopia Hi! Did you wrote documentation? Or when you will add queuing service like beanstalk ? Thanks!
