### ISSUE TITLE
PHP 5.3 Container

### ISSUE THREAD

**Issue by panigrc** [cytopia/devilbox#254]
Hi,
is it possible to include a php 5.3 container ?
This would be great for refactoring and testing old applications.

Greetings

**Comment by cytopia** [comment]
Think that should easily be accomplished

**Comment by panigrc** [comment]
Oh I see you already started ! https://github.com/devilbox/docker-php-fpm-5.3

**Comment by cytopia** [comment]
Yes, this is a backport of the base image. Currently trying to add it to the standard images as well.

**Comment by cytopia** [comment]
https://github.com/devilbox/docker-php-fpm/pulls, However looks like I need to write the intranet a bit, as most new syntax is not known by PHP 5.3

**Comment by cytopia** [comment]
https://github.com/cytopia/devilbox/pull/264
