### ISSUE TITLE
Add ssl CA to dockers

### ISSUE THREAD

**Issue by science695** [cytopia/devilbox#259]
I am getting self-signed troubles with curl calls inside devilbox (in the httpd container).

When you generate the ca cert, can you run an equivalent to this in the php container?

(This example is for a dockerfile, but that wouldn't work with devilbox. Could the docker entrypoint do something equivalent?)
```
ADD /ca/devilbox-ca.crt /usr/local/share/ca-certificates/devilbox-ca.crt
RUN update-ca-certificates
```

**Comment by cytopia** [comment]
Good catch.

Hard-coding is not a good idea, as the CA will be regenerated if it does not exist, this also allows the user to add his/her own CA.

I will rather add it to the startup script and load it, if it is not already loaded.

**Comment by science695** [comment]
Yes, I agree that hard coding is not an option. That was just the best example I could find.

Thanks for adding this, otherwise all my curl calls have to have CURLOPT_SSL_VERIFYPEER set to false. Which I would prefer to not have in production.
