### ISSUE TITLE
Fresh install fails to load MySQL 5.7 on Xubuntu

### ISSUE THREAD

**Issue by maikeldaloo** [cytopia/devilbox#26]
Hi,

First of all, I want to say what an awesome idea this is. Great job.

I just performed a fresh installation of Devilbox and MySQL wouldn't run.

All I've done so far is follow the installation instructions, and I cloned the `master` branch.

I tried `cytopia/mysql-5.5`, `cytopia/mysql-5.6` and `cytopia/mysql-5.7`.
5.5 and 5.6 just don't run at all. And 5.7 exits soon after it starts.

There are no logs generated that are relevant to the MySQL issue.

Check below for screenshots of the MySQL exiting and the Devilbox main page showing MySQL isn't running.
http://imgur.com/a/IpyzX

I'm running Xubuntu 16.04.
Docker version 1.12.3, build 6b644ec
docker-compose version 1.9.0, build 2585387

**Comment by cytopia** [comment]
Can u please check out the latest tag instead of master branch.
The master branch is still work in progress.

**Comment by cytopia** [comment]
I just checked the latest master branch on Debian.

Can you try the following combination:

* PHP 7.0
* MariaDB 10.1
* Nginx-Stable
* PGSQL 9.6

Please make sure to delete any existing data, run and log directories before that and also do `docker-compose rm`

**Comment by maikeldaloo** [comment]
Hi @cytopia, thanks for the prompt response.

I tried the original combination I mentioned above on the `0.8.1-pre` tag. MySQL still exited soon after it started.

I also tried your suggested combination (minus Postgres), on `0.8.1-pre`, and that's working fine.


I would have continued with your suggested combination, but my shared hosting doesn't allow me to use Nginx nor MariaDB, but I just tried it with Apache and that's working fine.

**Comment by cytopia** [comment]
If I understood you correct, it only fails (on `0.8.1-pre` tag or on `master` branch) if you choose MySQL 5.7 and all other MySQL/MariaDB versions succeed? Can you confirm this again please.

I also setup extensive travis checks now, which points out a problem with MySQL 5.7
https://travis-ci.org/cytopia/devilbox/builds/186852503

**Comment by cytopia** [comment]
I have set a different Database server as default in `env-default`.
MySQL 5.7 seems to have problems with the current docker version.
Its own build even fails after doing a retry on travis-ci, although the same build succeeded before.

**Comment by maikeldaloo** [comment]
I've been away from server-side dev for a while, I didn't realise that MariaDB is the new flavour of MySQL.
I'm using MariaDB and all is working fine.

I'm currently using `apache-2.4`, `mariadb-10.1`, and `php-fpm-7.0` on the `0.8.1-pre` tag.

**Comment by cytopia** [comment]
@maikeldaloo I have pushed a new version of mysql 5.7 to remote. could you `docker pull` it and check if it is working now

**Comment by cytopia** [comment]
Latest fix is on the way:

https://github.com/cytopia/docker-mysql-5.7/pull/3

build should show results here:

https://github.com/cytopia/devilbox/pull/36

**Comment by cytopia** [comment]
Has been fixed via https://github.com/cytopia/docker-mysql-5.7/pull/3

Please pull `latest` mysql-5.7 docker image.
