### ISSUE TITLE
Documentation Improvement: HTTPS Devilbox Root CA

### ISSUE THREAD

**Issue by science695** [cytopia/devilbox#260]
The documentation shows how to add the root ca to each browser on your computer.
An alternate way to do that is to add the root CA to your OS' registry / keychain, etc...

I found a page showing how to add the ca cert on all 3 major OS':

https://manuals.gfi.com/en/kerio/connect/content/server-configuration/ssl-certificates/adding-trusted-root-certificates-to-the-server-1605.html

**Comment by cytopia** [comment]
Thanks for the merge btw!
