### ISSUE TITLE
is it possible use devilbox in production environment ?

### ISSUE THREAD

**Issue by bigxu** [cytopia/devilbox#262]
if i use devilbox in a  production environment and i have multiple sites, many sites.
then:
     1, how to create CA for each site. should i add  https://github.com/Neilpang/acme.sh ?
     2, how to remove xdebug module ?
else if, You don't  recommend use devilbox in production env. 
      do you have a good option ?

thank you ~

**Comment by cytopia** [comment]
> 1, how to create CA for each site.

What exactly do you want to do

> 2, how to remove xdebug module ?

I am working on this feature: https://github.com/cytopia/devilbox/issues/270

> else if, You don't recommend use devilbox in production env. do you have a good option ?

This depends on your use case. Is there anything you require for production use?

**Comment by cytopia** [comment]
@bigxu any updates on your "production" requirements?

**Comment by cytopia** [comment]
# Devilbox production usage.

I can already start working on that feature. The only part that is missing are the actual **requirements for production**. Let me know what the goal for a productionized Devilbox is and I can integrate that feature.

**Comment by gowrav-vishwakarma** [comment]
Okay, let me share my requirements, we are an ERP/CRM solution provider and We have drag and drop based website and E-comm builder with It's own template system (With template designer system inbuilt). System is hosted (SaaS) as well s in-premises installation allowed. 

Our other options Docker, But finding good skills with docker is lacking and I myself, finds it too much changing technology. And our requirement is too easy, LAMP Stack. 

For hosted service: 1. We have a main domain and any body can create their own instance of XEC (Xavoc ERP and CRM) with a subdomain abcd.xavoc.com so technically, It's a virtual host with wildcard subdomain hosting. As for CA, technically we are using acme.sh for subdomains.

2. If anybody want that instance on particular domain, User can park any domain to its instance, so Actually it's another domain pointing to same web root accessing same SaaS instance and application underneath detects and deliver proper website, XEC instance. 

So, as per both points, we are technically having no virtual roots but everything pointing to same document base. And rest work is done by application. 

3. We are looking for better options for scaling, Mariadb master-master replication is a pain in a**. (we have to be Strictly on 10.1 )

4. For production we may want xdebug, but for production, definitely not.

5. For scaling, network filesystem is required to replicate folder structure live on number of servers.

6. Adding multiple domain may required to create another Certificate for that domain also, needed to be monitored separately) 

Why I am saying all here, It's not about technology but the approach. I loved your approach of easiness. Even my simple technician could able to setup development environment with devilbox. I tries to use it on production but all requirements could not matched. Specially, I wanted every domain to point to one default document root (that's our requirement though). Its more like no virtual host at all and just divert every domain with wildcard to same server in dns.

I'll try to edit/add more details. But this should be good idea. We also tried to implement devilbox on our another product AI enabled CMS (xepan.org, deprecated in favour of new product) but the same issues restricted us.

**Comment by bigxu** [comment]
https support: https://github.com/bigxu/nginx-acme
i can't say it clearly. now,i am study english.  
i like devilbox very much except its name

**Comment by cytopia** [comment]
@gowrav-vishwakarma 

For 1. and 2. you can disable the intranet, so the *default* virtual host will then be removed, leaving you to set a default virtual host yourself:

1. Disable Intranet: https://devilbox.readthedocs.io/en/latest/configuration-files/env-file.html#devilbox-ui-enable
2. Customize you vhost depending on your needs: https://devilbox.readthedocs.io/en/latest/vhost-gen/customize-specific-virtual-host.html#vhost-gen-customize-specific-virtual-host

For 3. (scaling the Database), I would not suggest the Devilbox setup as it hasn't been layed out for that. I would even consider to use an external database (not dockerized) and then go with something like MySQL Galera cluster. If you have trouble getting an external database connected to the Devilbox read up here: https://devilbox.readthedocs.io/en/latest/corporate-usage/use-external-databases.html

For 4. you can disable Xdebug (and other modules) easily, see here: https://devilbox.readthedocs.io/en/latest/intermediate/enable-disable-php-modules.html

For 5., I honestly don't know

For 6., See what @bigxu has created: https://devilbox.readthedocs.io/en/latest/third-party/nginx-acme.html

I will nonetheless close this discussion here, as GitHub should primarily be used for Bug reports and all other discussions should go into the Forum, this makes it easier for me to respond to bugs quicker: https://devilbox.discourse.group
