### ISSUE TITLE
I use devilbox in internet. can i disable xdebug module?

### ISSUE THREAD

**Issue by 1298799999** [cytopia/devilbox#270]
I like devilbox. it is very convenient.
I want to install it on our company's servers. 
how to remove xdebug module?

**Comment by cytopia** [comment]
At the moment disabling extensions is not supported. I will however provide an option to disable any extension.

**Comment by cytopia** [comment]
New feature is merged:

* Update master branch
* Pull new PHP images
* Disable xdebug: https://devilbox.readthedocs.io/en/latest/configuration-files/env-file.html#php-modules-disable
