### ISSUE TITLE
Which MongoDB tools are available?

### ISSUE THREAD

**Issue by mrpsiho** [cytopia/devilbox#271]
Hi,

Basically, the questions is which tools are available? I tried mongod, mongos... Well, I am lost. I would like to create a new db but don't know how to do that. Also, please suggest whether it is possible to use Studio 3T software, connect to mongodb somehow?

From the docs: 

mongo* | Various MongoDB client tools.

Thanks!

**Comment by mrpsiho** [comment]
Oh, my bad. I have just overcomplicated everything))))) Yes, Studio 3T works just perfect. I am able to connect, create etc.

Looks like I just need to complain a bit and then... bump! everything is resolved! :)

**Comment by mrpsiho** [comment]
Hi again,

I still need an advice here. Please, suggest which tools are available inside php container which I can connect to?

Also, I have this issue:
![mongo](https://user-images.githubusercontent.com/2705129/40267350-998e7294-5b63-11e8-9406-5121d37966a5.gif)
Why it can happen?

Thanks!

**Comment by cytopia** [comment]
Available command lines tools:
* `mongo`
* `mongoexport`
* `mongoimport`
* `mongorestore`
* `mongotop`
* `mongodump`
* `mongofiles`
* `mongoperf`
* `mongostat`

Additionally you can also Adminer to connect to MongoDB: http://localhost/vendor/adminer-4.6.2-en.php

**Comment by mrpsiho** [comment]
Thanks!
So I immediately tried to create a DB and got this: " Fatal error: Uncaught Error: Call to undefined function create_database() in /var/www/default/htdocs/vendor/adminer-4.6.2-en.php on line 1795".

**Comment by cytopia** [comment]
Which MongoDB version are you using? And did you get any errors from docker-compose logs for MongoDB?

**Comment by mrpsiho** [comment]
No, no errors.

**Comment by cytopia** [comment]
Hmm either I am missing some files itself from Adminer or some PHP modules are not properly in place for all the mongo functionality. I need to check on this. Which PHP version did you use?

**Comment by mrpsiho** [comment]
PHP 7.2

Ok, I have also found that maybe I missed some docs about mongo itself. I connected to PHP container, used `mongo` and created a new DB and dummy collection inside this DB. And now this db is persistent. Sorry, I did not know that newly created DB has to have at least one collection to not disappear.

In essence, adminer interface does not work for me. But I can live with that :) MongoDB works ok!

**Comment by cytopia** [comment]
Good to hear. I leave that open to fix Adminer.

**Comment by cytopia** [comment]
@mrpsiho can u pull latest PHP Docker images. This now works for me.

**Comment by cytopia** [comment]
I will close this due to inactivity. Feel free to re-open if the new PHP Docker images did not fix this for you.
