### ISSUE TITLE
Error: httpd cannot start service - error starting userland proxy (EADDRINUSE)

### ISSUE THREAD

**Issue by l4ci** [cytopia/devilbox#273]
- [x] Pull latest dockers 
- [x] Specify used docker versions (php `7.2`, web `nginx-stable` and database `maria-db-10.1`)
- [x] Attach logs - only php-fm folder exists - but is just waiting for connection
- [x] Start with debug mode and attach docker-compose output (`.env` setting `DEBUG_COMPOSE_ENTRYPOINT=1`) - no output found
- [x] Never use different mysql|mariadb versions on the same `HOST_PATH_MYSQL_DATADIR` 

Please also specify the following info:

- [x] Which operating system are you at (Linux, OSX or Windows): `OSX 10.13.4`
- [x] `docker version`
```
Client:
 Version:      18.03.1-ce
 API version:  1.37
 Go version:   go1.9.5
 Git commit:   9ee9f40
 Built:        Thu Apr 26 07:13:02 2018
 OS/Arch:      darwin/amd64
 Experimental: false
 Orchestrator: swarm

Server:
 Engine:
  Version:      18.03.1-ce
  API version:  1.37 (minimum version 1.12)
  Go version:   go1.9.5
  Git commit:   9ee9f40
  Built:        Thu Apr 26 07:22:38 2018
  OS/Arch:      linux/amd64
  Experimental: true
```
- [x] `docker-compose version`
```
docker-compose version 1.21.1, build 5a3f1a3
docker-py version: 3.3.0
CPython version: 3.6.4
OpenSSL version: OpenSSL 1.0.2o  27 Mar 2018
```

Full Error Message in the console
```
devilbox_bind_1 is up-to-date
devilbox_php_1 is up-to-date
Starting devilbox_httpd_1 ... error

ERROR: for devilbox_httpd_1  Cannot start service httpd: driver failed programming external connectivity on endpoint devilbox_httpd_1 (504c0a31457e391a0711119dcd2f7cd565bbff2e5cdaa9bc4f323654ea934c91): Error starting userland proxy: Bind for 0.0.0.0:80: unexpected error (Failure EADDRINUSE)

ERROR: for httpd  Cannot start service httpd: driver failed programming external connectivity on endpoint devilbox_httpd_1 (504c0a31457e391a0711119dcd2f7cd565bbff2e5cdaa9bc4f323654ea934c91): Error starting userland proxy: Bind for 0.0.0.0:80: unexpected error (Failure EADDRINUSE)
ERROR: Encountered errors while bringing up the project.
```

I already search the issues and tried several things with no effect:
- reinstalling everything
- changing `HOST_PORT_BIND=53` in `.env`
- entering `nameserver 127.0.01` to `/etc/resolv.conf`
- searched for `dnsmasq` but it doesnt seem to be running/or installed

Attached my `.env`, which I only renamed for uploading.
[.env](https://github.com/cytopia/devilbox/files/2019587/env.txt)

**Comment by cytopia** [comment]
> ```
> unexpected error (Failure EADDRINUSE)
>```

Port `80` seems already in use

**Comment by cytopia** [comment]
Your host operating system is already occupying port `80` for some service running on your host operating system.

1. Either stop that service
2. Or change the Devilbox HTTP port: https://devilbox.readthedocs.io/en/latest/configuration-files/env-file.html#host-port-httpd
