### ISSUE TITLE
Slow file access from php based cms

### ISSUE THREAD

**Issue by johnwbaxter** [cytopia/devilbox#274]
php7
nginx-stable
mariadb-10.0

OSX High Sierra
Docker: 18.03.1-ce-mac65 (24312)
Compose - 1.21.1

Running a CMS on Devilbox gives me really slow response times. I installed a NewRelic type app to see what was going on, and as far as i can see, the issue seems to boil down to slow file read writes (see attached).

Is this something you are aware of with Docker on Osx? Is there any known fix?
![screen shot 2018-05-20 at 11 00 36](https://user-images.githubusercontent.com/338729/40277839-d9c5044e-5c1d-11e8-9afd-c10919a22c17.png)

**Comment by cytopia** [comment]
This is a known issue how OS(X) has implemented Docker itself. One workaround is to use **[docker-sync](https://github.com/EugenMayer/docker-sync/wiki/2.-Configuration)**. See also this issue: https://github.com/cytopia/devilbox/issues/105
I still need support from people on OSX to actually implement this (even though it should be fairly easy)

**Comment by johnwbaxter** [comment]
Ah ok, i'll look into docker-sync!

Thanks :)

**Comment by cytopia** [comment]
I will close this one as it duplicates #105
