### ISSUE TITLE
Permission denied

### ISSUE THREAD

**Issue by RobbiNespu** [cytopia/devilbox#279]
If you encounter a bug and something does not work, make sure you have done the following and check those boxes before submitting an issue - thank you!

- [x] Pull latest dockers (e.g.: `docker pull cytopia/<used_docker>`) before running `docker-compose up`
- [x] Specify used docker versions (php, web and database)
- [x] Attach logs for php, mysql and webserver (found in `log/` directory)
- [x] Start with debug mode and attach docker-compose output (`.env` setting `DEBUG_COMPOSE_ENTRYPOINT=1`)
- [x] Never use different mysql|mariadb versions on the same `HOST_PATH_MYSQL_DATADIR` on existing database files. Different mysql|mariadb versions might upgrade/corrupt existing database files. If you have done that already, start with a different path of `HOST_PATH_MYSQL_DATADIR` (to an empty directory) and try again.

Please also specify the following info:

- [x] Which operating system are you at (Linux, OSX or Windows) : Linux (Fedora 28)
```
$ uname -a
Linux robbinespu 4.16.12-300.fc28.x86_64 #1 SMP Fri May 25 21:13:28 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
$ cat /etc/fedora-release 
Fedora release 28 (Twenty Eight)
```

- [x] `docker version` : 
```
$ docker -v
Docker version 1.13.1, build 1ab62f1-unsupported
```
- [x] `docker-compose version`
```
$ docker-compose -v
docker-compose version 1.20.1, build 5d8c71b
```

I getting problem with permission from you devilbox docker

- chown: cannot read directory '/data/db': Permission denied
- chown: cannot read directory '/var/lib/postgresql/data/pgdata
- touch: cannot touch '/var/log/php/php-fpm.access': Permission denied
- genrsa: Can't open "/ca/devilbox-ca.key" for writing, Permission denied
- touch: cannot touch '/var/log/mysql/query.log': Permission denied

I am part of docker group
```
$ id
uid=1000(rnm) gid=1000(rnm) groups=1000(rnm),10(wheel),974(bumblebee),1001(docker) context=unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023
```

attached 
[log.txt](https://github.com/cytopia/devilbox/files/2046974/log.txt) and [.env](https://github.com/cytopia/devilbox/files/2046975/env.txt) (renamed for upload to github)

**Comment by cytopia** [comment]
Can you show me the output of:
```
ls -la /path/to/devilbox/
```
and

```
ls -la /path/to/devilbox/data
```

**Comment by RobbiNespu** [comment]
```bash
$ ls -la /home/rnm/Workspaces/devilbox
total 164
drwxrwxr-x. 15 rnm rnm  4096 May 29 21:19 .
drwxrwxr-x. 10 rnm rnm  4096 May 29 16:28 ..
drwxrwxr-x.  2 rnm rnm  4096 May 29 13:00 backups
drwxrwxr-x.  2 rnm rnm  4096 May 29 13:00 bash
drwxrwxr-x.  2 rnm rnm  4096 May 29 13:00 ca
drwxrwxr-x. 33 rnm rnm  4096 May 29 13:00 cfg
-rw-rw-r--.  1 rnm rnm   564 May 29 13:00 CONTRIBUTING.md
drwxrwxr-x.  6 rnm rnm  4096 May 29 13:50 data
drwxrwxr-x.  4 rnm rnm  4096 May 29 13:00 .devilbox
-rw-rw-r--.  1 rnm rnm   743 May 29 13:00 docker-compose.override.yml-example
-rw-rw-r--.  1 rnm rnm 11745 May 29 13:00 docker-compose.yml
drwxrwxr-x. 15 rnm rnm  4096 May 29 13:00 docs
-rw-rw-r--.  1 rnm rnm 14938 May 29 15:48 .env
-rw-rw-r--.  1 rnm rnm 14933 May 29 13:00 env-example
drwxrwxr-x.  8 rnm rnm  4096 Jun  5 14:40 .git
drwxrwxr-x.  2 rnm rnm  4096 May 29 13:00 .github
-rw-rw-r--.  1 rnm rnm  2517 May 29 13:00 .gitignore
-rw-rw-r--.  1 rnm rnm  1064 May 29 13:00 LICENSE.md
drwxrwxr-x.  8 rnm rnm  4096 May 29 13:50 log
drwxrwxr-x.  8 rnm rnm  4096 May 29 13:00 mod
-rw-rw-r--.  1 rnm rnm 22434 May 29 13:00 README.md
-rw-rw-r--.  1 rnm rnm    86 May 29 13:00 shell.bat
-rwxrwxr-x.  1 rnm rnm    59 May 29 13:00 shell.sh
drwxrwxr-x.  3 rnm rnm  4096 May 29 13:00 templates
drwxrwxr-x.  2 rnm rnm  4096 May 29 13:00 .tests
-rw-rw-r--.  1 rnm rnm  4168 May 29 13:00 .travis.yml
-rwxrwxr-x.  1 rnm rnm  3001 May 29 13:00 update-docker.sh

$ ls -la /home/rnm/Workspaces/devilbox/data/
total 24
drwxrwxr-x.  6 rnm  rnm  4096 May 29 13:50 .
drwxrwxr-x. 15 rnm  rnm  4096 May 29 21:19 ..
-rw-rw-r--.  1 rnm  rnm     0 May 29 13:00 .keepme
drwxr-xr-x.  3 root root 4096 May 29 13:50 mongo
drwxr-xr-x.  3 root root 4096 May 29 13:50 mysql
drwxr-xr-x.  3 root root 4096 May 29 13:50 pgsql
drwxr-xr-x.  2 root root 4096 May 29 13:33 www
```
@cytopia  have a look

**Comment by cytopia** [comment]
> ```
> $ ls -la /home/rnm/Workspaces/devilbox/data/
> total 24
> drwxrwxr-x.  6 rnm  rnm  4096 May 29 13:50 .
> drwxrwxr-x. 15 rnm  rnm  4096 May 29 21:19 ..
> -rw-rw-r--.  1 rnm  rnm     0 May 29 13:00 .keepme
> drwxr-xr-x.  3 root root 4096 May 29 13:50 mongo
> drwxr-xr-x.  3 root root 4096 May 29 13:50 mysql
> drwxr-xr-x.  3 root root 4096 May 29 13:50 pgsql
> drwxr-xr-x.  2 root root 4096 May 29 13:33 www
> ```
The last 4 are owned by root, but should be owned by `rnm`. Did you make those changes manually or how comes it is owned by root?

**Comment by cytopia** [comment]
This has been addressed via: https://github.com/cytopia/devilbox/pull/294

Either checkout the Devilbox from scratch or use `sudo` to change permissions of `data/www`.

Mongo, MySQL and PgSQL all run as root, so their data directory will be owned by root. This is nothing to worry about. Only keep in mind that if you want to delete those directories later, you need to use `sudo`.
