### ISSUE TITLE
Error in requests via SOAP

### ISSUE THREAD

**Issue by mozgbrasil** [cytopia/devilbox#280]
Good afternoon

If you can help me, thank you.

I am making requests via SOAP and the errors are being displayed as images

![captura de tela de 2018-05-29 20-22-51](https://user-images.githubusercontent.com/17202780/40690655-4b6277b4-637e-11e8-8af1-20416adc8ccf.png)
![captura de tela de 2018-05-29 20-22-55](https://user-images.githubusercontent.com/17202780/40690656-4b89646e-637e-11e8-967a-720d9b6c5cd9.png)

**Comment by cytopia** [comment]
The log does not show any errors. Can you upload the web server log files as well. (especially error logs)

**Comment by mozgbrasil** [comment]
Good afternoon

What file path do you need?

See that the apache folder is empty

![captura de tela de 2018-06-12 14-54-37](https://user-images.githubusercontent.com/17202780/41307853-b4545c10-6e50-11e8-8a69-d5e6a5bb17cf.png)

**Comment by science695** [comment]
Try

> docker-compose logs --since "1m" -f > docker.log
Leave it running while you do the request and then ctrl+c it and upload that docker.log file

**Comment by mozgbrasil** [comment]
Good Morning

See return as images

![captura de tela de 2018-06-13 11-16-10](https://user-images.githubusercontent.com/17202780/41356915-51d5ef94-6efb-11e8-8404-ff20dbb60890.png)
![captura de tela de 2018-06-13 11-16-23](https://user-images.githubusercontent.com/17202780/41356916-51fdca14-6efb-11e8-9b85-ca6816d76958.png)

**Comment by science695** [comment]
Start up devilbox, start this log command, trigger the error with your soap call, and then ctrl+c and upload those logs.

**Comment by mozgbrasil** [comment]
Good afternoon

The following error was appearing

     [proxy_fcgi:error] [pid 359:tid 139779979048704] (70007)The timeout specified has expired

Has been edited the file /devilbox/cfg/apache-2.4/devilbox-custom.conf

Changing the item

     Timeout 600
