### ISSUE TITLE
How can I change the Composer mirror address globally?

### ISSUE THREAD

**Issue by qlmlove** [cytopia/devilbox#281]
I`m chinese，I need to change the mirror address to speed up the download
How can I change the Composer mirror address globally?

**Comment by cytopia** [comment]
I am not a Composer export, so how do you change the Composer mirror anyway?

**Comment by cytopia** [comment]
@qlmlove any update on this?

**Comment by science695** [comment]
There should be a way to mount a composer config file from your host / computer into the docker into the global user config.

And you could mount that file in the docker-compose.overrides.yml file

**Comment by cytopia** [comment]
### This issue will be closed due to staleness.

Add required information in order to have it re-opened.
