### ISSUE TITLE
No php error logs

### ISSUE THREAD

**Issue by mrpsiho** [cytopia/devilbox#286]
Hi,

I am experiencing the issue so no error logs are generated in php in www-error.log file. I tried different versions - both 7.1 and 7.2 - switched over these versions, but no luck. It does not log anything at all.

I also tried 7.3 - never used it before - but it did not created empty log files at all. So '/log/php-fpm-7.3' folder is empty.

Please, help!

**Comment by science695** [comment]
Are the logs being forwarded to the web server logs? check the apache or ngingx folders inside log.

Apache logs the proxy forwarded logs in its log as well.

**Comment by mrpsiho** [comment]
I am using NGINX, so there is no folder for apache logs. 'nginx-stable' folder is empty as well.

**Comment by cytopia** [comment]
Looks like it works for 7.0. I will have to dig into the newer versions.

**Comment by mrpsiho** [comment]
Sorry, it was my mistake, actually. What confused is this setting:

###
### Log to file or Docker logs.
###
### Logging to file means log files are available under log/
### on your host operating system.
### Logging to Docker logs means log files are streamed to
### stdout and stderr.
###
### 1: Log to Docker logs
### 0: Log to file
###
DOCKER_LOGS=0

Well, you know '0' looks like something that is disabled, so I put it to '1' and forgot. But today I decided to study every setting and so on. Basically, putting it to '0' solved this my issue. And it works for PHP 7.2 for me. So, I think this issue may be closed.

**Comment by cytopia** [comment]
OK, then I must have mistaken it as well.
