### ISSUE TITLE
DEVILBOX_PATH for NFS

### ISSUE THREAD

**Issue by berkayunal** [cytopia/devilbox#287]
Hi,

Can you show an example how to set DEVILBOX_PATH for an NFS export?

Thanks

**Comment by science695** [comment]
Can you clarify what you are trying to do?

DEVILBOX_PATH is the folder on your machine where the devilbox files are stored.

If you have devilbox on a NFS mount, then it needs to be the path where that NFS mount is located (drive letter, etc...)

**Comment by cytopia** [comment]
@berkayunal please provide more information

**Comment by cytopia** [comment]
### This issue will be closed due to staleness.

Add required information in order to have it re-opened.

**Comment by Vincent-Ntriga** [comment]
I guess the question here was: What are the steps needed to run Devilbox with NFS? 
Is it possible to add this to the docs?
