### ISSUE TITLE
Using for WordPress development

### ISSUE THREAD

**Issue by tracyfloyd** [cytopia/devilbox#29]
In order for this to work for WordPress development I had to use php-fpm-7.0 - when I tried to use php-fpm-7.1 The WP site returns a 503 error and I get the following in the log/apache-2.4/other-error.log file:

```
[proxy_fcgi:error] [pid 91] (104)Connection reset by peer: [client 172.16.238.1:39940] AH01075: Error dispatching request to :
```

Ultimately, I was unable to get it working with php-fm-7.1 - but I did want to leave a note here for any other WordPress devs looking to use this setup.

operating system: OS X (10.12.2)
docker version: 1.12.16
docker-compose version: 1.9.0

**Comment by cytopia** [comment]
@tracyfloyd Thanks for the info. I will investigate this.
Btw, did you try to use nginx and php-fpm 7.1?

**Comment by tracyfloyd** [comment]
I didn't - the prod server was running apache so was trying to stay as close to that as possible. I'll give it a try and report back.

**Comment by cytopia** [comment]
@tracyfloyd I have updated all PHP container. can you try again with php-fpm 7.1 (on devilbox master branch)

**Comment by cytopia** [comment]
@tracyfloyd 
Can you try with the new devilbox release. v0.9.
I just setup latest wordpress on PHP-7.1, Apache-2.2 and MariaDB-10.1

Only thing you will have to do is create a database prior running the wordpress installer.
