### ISSUE TITLE
Need artisan tool installed inside the container

### ISSUE THREAD

**Issue by sharafat** [cytopia/devilbox#290]
The doc says:
> If you are in need of other tools, open up an issue at Github and ask for it, this can usually be implemented very quickly.

For Laravel developers, it's pretty common to use `artisan` commands. So I'd love to see it pre-installed inside the container.

**Comment by cytopia** [comment]
Sure. Only thing I found is: https://laravel.com/docs/5.6/artisan

But how do you actually install artisan?

**Comment by sharafat** [comment]
I see. It seems artisan is installed via `composer install`, and it must be executed from project root directory. So basically there's no other way to install it. Cool, my bad, should've dug into it more beforehand.
