### ISSUE TITLE
Bind container not starting / auto_dns / Windows 10 / Docker for Windows

### ISSUE THREAD

**Issue by bezin** [cytopia/devilbox#291]
If you encounter a bug and something does not work, make sure you have done the following and check those boxes before submitting an issue - thank you!

- [X] Pull latest dockers (e.g.: `docker pull cytopia/<used_docker>`) before running `docker-compose up`
- [X] Specify used docker versions (php, web and database) *PHP 7.2, Apache 2.4, MariaDB 10.1* 
- [ ] Attach logs for php, mysql and webserver (found in `log/` directory)
- [X] Start with debug mode and attach docker-compose output (`.env` setting `DEBUG_COMPOSE_ENTRYPOINT=1`)
- [X] Never use different mysql|mariadb versions on the same `HOST_PATH_MYSQL_DATADIR` on existing database files. Different mysql|mariadb versions might upgrade/corrupt existing database files. If you have done that already, start with a different path of `HOST_PATH_MYSQL_DATADIR` (to an empty directory) and try again.

Please also specify the following info:

- [X] Which operating system are you at (Linux, OSX or Windows)    *Windows 10 Pro (17134)*
- [X] `docker version`    *18.03.1-ce*
- [X] `docker-compose version`    *1.21.1*

Hi there,

unfortunately AUTO_DNS is not working for me on Windows 10 (with Docker For Windows), yet I fail to get it up and running. The bind container fails to start with the following error message:

```bind_1   | /etc/bind/devilbox-wildcard_dns.localhost.conf:1: zone 'localhost': already exists previous definition: /etc/bind/named.conf.default-zones:10```

I followed [instructions in the docs](https://devilbox.readthedocs.io/en/latest/configuration-global/auto-dns.html), i.e. I configured my network adapater and set HOST_PORT_BIND and LOCAL_LISTEN_ADDR accordingly.

I would really appreciate some help :) Please let me know if I should provide anything more. 

Best

**Comment by science695** [comment]
What is your settings for these .env variables?:

> TLD_SUFFIX
> EXTRA_HOSTS
