### ISSUE TITLE
(Community Discussion) Default enabled PHP modules

### ISSUE THREAD

**Issue by cytopia** [cytopia/devilbox#299]
# Community Discussion: Default enabled PHP modules

As it is now possible to enable and disable PHP modules via `.env` settings, it is time to find a sane default of enabled PHP modules.

Enable/disable modules: https://devilbox.readthedocs.io/en/latest/configuration-files/env-file.html#php-modules-enable

Currently all modules except `ioncube` are enabled. This however might be a bit heavy and slow down the PHP-FPM process as well as introduce some risk.

So it's up to us to come up with all default required modules.

Please have a look here and let me know what modules are required by default:

https://github.com/devilbox/docker-php-fpm#php-modules

**Comment by Dibbyo456** [comment]
**PHP 7.2** - Because 7.2 brings 14% performance improvements over 7.1 along with security patches.

**Comment by cytopia** [comment]
@Dibbyo456 thanks for the feedback. However, this ticket is about enabled PHP **modules** (regardless of version - the Devilbox tries to ship every version by default). ;-)

**Comment by cytopia** [comment]
The current README now reflects all default enabled PHP modules, those that are static (cannot be disabled) and all that can be disabled: https://github.com/cytopia/devilbox#available-php-modules

I would propose to disable any exotic modules by default as well as `xdebug` via [PHP_MODULES_DISABLE](https://devilbox.readthedocs.io/en/latest/configuration-files/env-file.html#php-modules-disable) in the `.env` file.

Any thoughts around this?

**Comment by cytopia** [comment]
## Migration note

### Community discussion will be continued on **[The Devilbox Forums](https://devilbox.discourse.group)** in topic: **[Default enabled/disabled modules](https://devilbox.discourse.group/t/default-enabled-disabled-php-modules/20)**


---

mention: @Dibbyo456
