### ISSUE TITLE
Error on run with Windows

### ISSUE THREAD

**Issue by LeG3nDz** [cytopia/devilbox#30]
Hi community,

I use devilbox on my Ubuntu perfectly, but on Windows, when i run `docker-compose up`, i've this error :

```
Creating devilbox_mysql_1
Creating devilbox_postgres_1

ERROR: for postgres  Cannot create container for service postgres: invalid bind mount spec "D:\\Docker\\devilbox\\log\\postgres-9.6:/var/log/postgresql:rw": invalid volume specification: 'D:\Docker\devilbox\log\postgres-9.6:/var/log/postgresql:rw'

ERROR: for mysql  Cannot create container for service mysql: invalid bind mount spec "D:\\Docker\\devilbox\\log\\mysql-5.7:/var/log/mysql:rw": invalid volume specification: 'D:\Docker\devilbox\log\mysql-5.7:/var/log/mysql:rw'
[31mERROR[0m: Encountered errors while bringing up the project.
```

I don't need use postgre :(
Do you know if i can disable postgre ?

- [ Windows ] Which operating system are you at (Linux, OSX or Windows)
- [ Client 1.12.6 // Server 1.13.0 ] `docker version`
- [ 1.9.0 ] `docker-compose version`

**Comment by cytopia** [comment]
Hi @LeG3nDz ,

PostgreSQL is currently only in HEAD.
Switch back to the latest tag inside the repository. This does not contain PostgreSQL yet.

Can u give it a try and report back how this behaves on Windows

**Comment by LeG3nDz** [comment]
Yop @cytopia,

I've test with HEAD branch, but no result :

```
[0B8e6f1cff: Already exists
[0Bd3e4142d: Pulling fs layer
[0B852fff7f: Pulling fs layer
Digest: sha256:a3a11321b42ec223e5bc022a63c9c2b7c28c87da2be89e82c778eb27b8467baa85.35 MB/85.35 MBB
Status: Downloaded newer image for cytopia/apache-2.4:0.8
Creating devilbox_db_1

ERROR: for db  Cannot create container for service db: invalid bind mount spec "D:\\Docker\\devilbox\\log\\mysql-5.7:/var/log/mysql:rw": invalid volume specification: 'D:\Docker\devilbox\log\mysql-5.7:/var/log/mysql:rw'
[31mERROR[0m: Encountered errors while bringing up the project.
```

**Comment by cytopia** [comment]
Hi @LeG3nDz I meant not HEAD, but the latest git tag `0.8.1-pre`.

**Comment by LeG3nDz** [comment]
@cytopia Yes, sorry, typing error :/ I'm on tag `0.8.1-pre`.

**Comment by cytopia** [comment]
@LeG3nDz 
Could you switch to a database other than MySQL 5.7 (this still has some problems).

Also, if this doesn't help, try to comment out all logging mounts inside the `Dockerfile`.

**Comment by LeG3nDz** [comment]
@cytopia 

Same error with mysql5.6 :( Is it possible to not use mysql ?

**Comment by cytopia** [comment]
You could simply comment out all mysql stuff in `Dockerfile`
Also have a look at the [other windows-tagged bugs@devilbox](https://github.com/cytopia/devilbox/issues?q=label%3Ahost%3Awindows+is%3Aclosed).

**Comment by valix85** [comment]
Hi guys, i always obtain this erro when try docker-compose up

`C:\Docker\docker\wpfull\devilbox>docker-compose up
Recreating 4a6a7ff5a0fa_4a6a7ff5a0fa_4a6a7ff5a0fa_4a6a7ff5a0fa_devilbox_mysql_1
Starting 86b061bd0e31_devilbox_postgres_1

ERROR: for mysql  Cannot create container for service mysql: invalid bind mount spec "7bc0653178880226216df9bc06f8986986202138f24f195e474bd742294a40a0:etc/mysql/docker-default.d:rw": invalid volume specification: '7bc0653178880226216df9bc06f8986986202138f24f195e474bd742294a40a0:etc/mysql/docker-default.d:rw': invalid mount config for type "volume": invalid mount path: 'etc/mysql/docker-default.d' mount path must be absolute
ERROR: Encountered errors while bringing up the project.`

I run it on window 10. what can I do?
thank you

**Comment by cytopia** [comment]
@valix85 

Can you replace all occurrances of `mysql_socket_volume` and `pgsql_socket_volume` with a writeable path inside the `docker-compose.yml`. And also remove the complete volumes section:

https://github.com/cytopia/devilbox/blob/master/docker-compose.yml#L302

**Comment by valix85** [comment]
but this step isn't in guide...

**Comment by cytopia** [comment]
@valix85 

I have just read somewhere that windows might have problems with volumes, so I suggested this as a quick workaround (simply by removing all the volume entries). And yes, it is not (yet) documented, I just came up with it.

I thought this might fix the issue, in case you succeed I might have to create two `docker-compose.yml` files. One for windows and one for unix.

**Comment by cytopia** [comment]
Hi guys,

Could you give it another try in the newly release v.09 version.
I have removed named volume from docker-compose.yml. Hopefully it will work now.

**Comment by cytopia** [comment]
@LeG3nDz 

> Same error with mysql5.6 :( Is it possible to not use mysql ?

Yes, now it is possible to selectively start what you need.

@valix85 

Also the socket mounts have been removed and it should work fine.

**Comment by cytopia** [comment]
I will close due to inactivity and due to fix already submitted.

If this particular issues still persists, let me know if you are using [Docker Toolbox](https://docs.docker.com/toolbox/overview/) or [Docker for Windows](https://docs.docker.com/docker-for-windows/install/#download-docker-for-windows)
