### ISSUE TITLE
Can the project folders be placed outside of the devilbox folder?

### ISSUE THREAD

**Issue by danemorgan** [cytopia/devilbox#301]
Such as 

```
- devilbox
  - data
    - mysql
- projects
  - dev.project
    - public_html
```

**Comment by cytopia** [comment]
Yes, set the following values in your `.env`:
```
HOST_PATH_HTTPD_DATADIR=../projects/
```

**Comment by cytopia** [comment]
https://devilbox.readthedocs.io/en/latest/getting-started/best-practice.html#move-data-out-of-devilbox-directory

**Comment by diego-betto** [comment]
Correct link 
https://devilbox.readthedocs.io/en/latest/howto/devilbox/move-projects-to-different-directory.html
