### ISSUE TITLE
(Community Discussion) Default settings for PHP and Apache/Nginx

### ISSUE THREAD

**Issue by cytopia** [cytopia/devilbox#302]
# Community Discussion: Default settings for PHP and Apache/Nginx

I would like to standardize sane default settings for PHP and Apache/Nginx across all of their versions.

---

### Webserver

* [ ] timeout
* [x] timeout to upstream PHP-FPM connection: 180sec
* [ ] body/post size

---

### PHP

Defaults for PHP are available here: 
* https://github.com/devilbox/docker-php-fpm/blob/master/build/ansible/group_vars/all.yml#L26
* https://github.com/devilbox/docker-php-fpm/tree/master/build/ansible/CONFIGURATION

#### php-fpm.conf
```ini
[global]
log_level = notice

[www]
request_terminate_timeout = 120s
listen.backlog = 1024
pm = ondemand
pm.max_children = 50
pm.start_servers = 4
pm.min_spare_servers = 2
pm.max_spare_servers = 6
pm.max_requests = 500
pm.process_idle_timeout = 10s
```

#### php.ini
```ini
memory_limit		= 512M

max_execution_time      = 120
max_input_time          = 120

post_max_size           = 72M
upload_max_filesize     = 64M
max_file_uploads        = 20

variables_order         = EGPCS
max_input_vars          = 8000
max_input_nesting_level = 64

error_reporting         = E_ALL | E_NOTICE | E_STRICT | E_DEPRECATED
xmlrpc_errors           = Off
report_memleaks         = On
display_errors          = On
display_startup_errors  = On
track_errors            = On
log_errors              = On
html_errors             = On

xdebug.default_enable   = Off
xdebug.profiler_enable  = Off
xdebug.remote_enable    = Off
xdebug.remote_autostart = Off
```

**Comment by Tuurlijk** [comment]
for MySQL I have found these settings help:
```
max_allowed_packet=64M
tmpdir=/dev/shm
```
max_allowed_packet helps when importing dumps with long lines. It prevents the 'mysql has gone away' message.

For PHP
```
[PHP]
; Memory
memory_limit = 512M

; Timeouts
max_execution_time = 240
max_input_time = 240

; Uploads
post_max_size = 256M
upload_max_filesize = 256M

; Vars
max_input_vars = 8000

; Error reporting
display_errors = On
track_errors = On

; Opcache boost
opcache.max_accelerated_files = 10000
opcache.memory_consumption = 128
opcache.interned_strings_buffer = 16
opcache.validate_timestamps = 0

; Mailhog
sendmail_path = '/usr/local/bin/mhsendmail --smtp-addr="mailhog:1025"'
```

**Comment by jukben** [comment]
Hey! It would be awesome to create one config file (or maybe as a part of .env) for those general configurations (as upload_max_filesize) to share them automatically across versions depend on your configuration. That would help me a lot 👍 What do you think?

**Comment by cytopia** [comment]
@jukben those standard settings will be baked into each container by default, once they have been defined. So there will be no need for the user to apply standard settings, only to change those.

**Comment by jukben** [comment]
On the other hand, yep, that would definitely solve my problem why I had to mess with config in the first place https://github.com/cytopia/devilbox/issues/323 Thanks for working on this. 🙌

**Comment by cytopia** [comment]
# php.ini defaults

* PR: https://github.com/devilbox/docker-php-fpm/pull/39
* Base image defaults: https://github.com/devilbox/docker-php-fpm/blob/1b6799da58dea474f5d20e111258c2b22524d842/build/ansible/CONFIGURATION/php-base.ini
* Prod image defaults: https://github.com/devilbox/docker-php-fpm/blob/1b6799da58dea474f5d20e111258c2b22524d842/build/ansible/CONFIGURATION/php-prod.ini
* Work image defaults: https://github.com/devilbox/docker-php-fpm/blob/1b6799da58dea474f5d20e111258c2b22524d842/build/ansible/CONFIGURATION/php-work.ini


## How it works

1. Every flavour inherits from the its previous flavor (prod from base and work from prod).
2. Every flavour can overwrite previous flavour values (e.g. work overwrites base error_reporting settings)

**Comment by cytopia** [comment]
Quick update: PHP defaults PR has been merged and new Images should be available in 1-2 hours.

**Comment by cytopia** [comment]
I am adding new PHP-FPM settings: https://github.com/devilbox/docker-php-fpm/pull/40

```
pm.max_children = 50
pm.start_servers = 5
pm.min_spare_servers = 5
pm.max_spare_servers = 35
pm.max_requests = 500
```

**Comment by cytopia** [comment]
## Migration note

### Community discussion will be continued on **[The Devilbox Forums - Default settings for PHP-FPM](https://devilbox.discourse.group/t/default-settings-for-php-fpm/19)**

---

mention: @Tuurlijk @jukben @9034725985
