### ISSUE TITLE
Deploy Node.js App

### ISSUE THREAD

**Issue by jebog** [cytopia/devilbox#310]
Hello, 
Thanks for the great Job.
I'm looking for a way to deploy Node js App with devilbox. is it possible ? and how to do it ?

#### ISSUE TYPE

 - Question

**Comment by cytopia** [comment]
@jebog not exactly sure what the actual goal is. Does it relate to: https://github.com/cytopia/devilbox/issues/240

**Comment by science695** [comment]
Are you wanting to run the node app inside a container in the same local domain as your devilbox setup?

**Comment by jebog** [comment]
Yes it's what i'm trying to do

**Comment by cytopia** [comment]
This is marked as duplicate. Please continue in the linked issue: https://github.com/cytopia/devilbox/issues/240

**Comment by cytopia** [comment]
@jebog NodeJS support is almost done. PR here: https://github.com/cytopia/devilbox/pull/449

All further information in above PR or this issue: https://github.com/cytopia/devilbox/issues/240
