### ISSUE TITLE
Add codeception to PHP container

### ISSUE THREAD

**Issue by pvantilb** [cytopia/devilbox#313]
#### ISSUE TYPE

 - Feature request

#### SUMMARY

Per the documentation on devilbox available tools page (https://devilbox.readthedocs.io/en/latest/readings/available-tools.html) I am requesting that codeception be added globally to the php container for easier use and execution of automated tests.
Currently, to utilize we would have to add this package to our composer files to download with the rest of the dependencies but we only utilize this tool during development so would prefer to not add to composer files if we didn't have too.  Being a little lazy, i know, but having some testing tools baked into the container would be helpful as they would be globally installed.

**Comment by cytopia** [comment]
@pvantilb 
Should be ready shortly: https://github.com/devilbox/docker-php-fpm/pull/33

**Comment by cytopia** [comment]
@pvantilb merged.Should be ready by today (~3 hours, depending how many jobs are currently running in my travis plan)

**Comment by pvantilb** [comment]
Thanks, works well!
