### ISSUE TITLE
Add ansible to PHP container

### ISSUE THREAD

**Issue by pvantilb** [cytopia/devilbox#315]
#### ISSUE TYPE

 - Feature request

#### SUMMARY

please add ansible to the php container as we utilize ansible-vaults to store information for some of our projects and having this in the container so it can easily be utilized to access/update those ansible vaults and/or test running playbooks would be extremely helpful.

**Comment by cytopia** [comment]
PR created: https://github.com/devilbox/docker-php-fpm/pull/35

**Comment by cytopia** [comment]
Merged. Docker images will be available in 1-3 hours.
