### ISSUE TITLE
"ICU outdated", says symfony/requirements-checker

### ISSUE THREAD

**Issue by RoestVrijStaal** [cytopia/devilbox#316]
#### ISSUE TYPE

 - Question

#### SUMMARY

Hi,

I set up a brandnew symfony project in devilbox, and after running check.php from "symfony/requirements-checker" (see https://symfony.com/doc/current/reference/requirements.html), I get the recommendation that ICU needs an update. 

> intl ICU version installed on your system is outdated (57.1) and does not match the ICU data bundled with Symfony (62.1)
> To get the latest internationalization data upgrade the ICU system package and the intl PHP extension.

What would be the best approach to cope with it?

**Comment by cytopia** [comment]
What PHP versions are affected by this issue?

**Comment by RoestVrijStaal** [comment]
Unfortunately I didn't test out all php versions. I'm used to stick to the most fresh but stable version. Thus in my situation: php 7.2

**Comment by cytopia** [comment]
@RoestVrijStaal 
I just tried it with PHP 7.2

```
host> ./shell.sh
$ cd /shared/httpd/my-symfony/symfony
$ composer require symfony/requirements-checker
$ ./vendor/symfony/requirements-checker/bin/requirements-checker

Symfony Requirements Checker
~~~~~~~~~~~~~~~~~~~~~~~~~~~~

> PHP is using the following php.ini file:
WARNING: No configuration file (php.ini) used by PHP!

> Checking Symfony requirements:
............................W.....W..


 [OK]
 Your system is ready to run Symfony projects


Optional recommendations to improve your setup
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

 * short_open_tag should be disabled in php.ini
   > Set short_open_tag to off in php.ini*.

Note  The command console could use a different php.ini file
~~~~  than the one used with your web server. To be on the
      safe side, please check the requirements from your web
      server using the public/check.php script.
```

I have also tried the URL version: http://my-symfony.loc/check.php

![screenshot 2018-07-28 11-36-51 selection](https://user-images.githubusercontent.com/12533999/43355317-9d8003e4-925a-11e8-8e2e-1eaa05ed4343.png)


Did you pull the latest PHP images?

**Comment by cytopia** [comment]
@RoestVrijStaal can you check again. I have done several updates.

Check out latest git on `master` branch and let me know if the problem is resolved.

**Comment by cytopia** [comment]
### This issue will be closed due to staleness.

Add required information in order to have it re-opened.
