### ISSUE TITLE
creating vhost fails

### ISSUE THREAD

**Issue by srattay** [cytopia/devilbox#318]
#### ISSUE TYPE

 - Bug Report

#### OS / ENVIRONMENT

* Host operating system: macOS HigH Sierra 10.13.5
* Native Docker or Docker Toolbox: Native Docker
* Docker version: Docker version 18.03.1-ce, build 9ee9f40
* Docker Compose version: docker-compose version 1.21.1, build 5a3f1a3

#### SUMMARY

create vhost fails

output of docker-compose logs httpd:
<<
Attaching to devilbox_httpd_1
[36mhttpd_1  |[0m [0;33m[WARN] Group with 20 already exists: dialout[0m
[36mhttpd_1  |[0m 2018-07-24 17:51:51,123 CRIT Set uid to user 0
[36mhttpd_1  |[0m 2018-07-24 17:51:51,127 INFO supervisord started with pid 1
[36mhttpd_1  |[0m 2018-07-24 17:51:52,131 INFO spawned: 'httpd' with pid 198
[36mhttpd_1  |[0m 2018-07-24 17:51:52,134 INFO spawned: 'watcherd' with pid 199
[36mhttpd_1  |[0m [Tue Jul 24 17:51:52.203815 2018] [mpm_event:notice] [pid 198:tid 139958998861696] AH00489: Apache/2.4.33 (Unix) OpenSSL/1.0.2l configured -- resuming normal operations
[36mhttpd_1  |[0m [Tue Jul 24 17:51:52.204055 2018] [core:notice] [pid 198:tid 139958998861696] AH00094: Command line: 'httpd -D FOREGROUND'
[36mhttpd_1  |[0m 2018-07-24 17:51:53,206 INFO success: httpd entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
[36mhttpd_1  |[0m 2018-07-24 17:51:53,206 INFO success: watcherd entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
[36mhttpd_1  |[0m watcherd: [2018-07-24 17:51:55] Starting daemon.
[36mhttpd_1  |[0m /usr/local/bin/create-vhost.sh: line 14: 8: unbound variable
[36mhttpd_1  |[0m watcherd: [2018-07-24 17:51:55] [ERR] ADD: failed:    /shared/httpd/my-drupal
[36mhttpd_1  |[0m watcherd: [2018-07-24 17:51:55] Using bash loop to watch for changes.
>>

ls -alh ./data/www
drwxr-xr-x  3 myUserName  staff    96B 24 Jul 15:29 my-drupal

ls -alh ./data/www/my-drupal
drwxr-xr-x  2 stefanrattay  staff    64B 24 Jul 15:29 htdocs

#### STEPS TO REPRODUCE

run docker-compose up

#### OTHER INFORMATION

see attached .env file - renamed to env.txt
[env.txt](https://github.com/cytopia/devilbox/files/2227025/env.txt)

i do not have any custom vhost-gen templates in place

**Comment by cytopia** [comment]
@srattay 
Good catch.

Some parsing is wrong when debug is turned off.

In your `.env` file, turn on debug again as a quick fix:
```
DEBUG_COMPOSE_ENTRYPOINT=1
```
This will avoid the error.
I will dig into this and let you know once you can turn it off again.

**Comment by cytopia** [comment]
@srattay 
Good catch.

Some parsing is wrong when debug is turned off.

In your `.env` file, turn on debug again as a quick fix:
```
DEBUG_COMPOSE_ENTRYPOINT=1
```
This will avoid the error.
I will dig into this and let you know once you can turn it off again.

**Comment by cytopia** [comment]
Fixes for webserver are building

* https://github.com/devilbox/docker-apache-2.2/pull/13
* https://github.com/devilbox/docker-apache-2.4/pull/13
* https://github.com/devilbox/docker-nginx-stable/pull/13
* https://github.com/devilbox/docker-nginx-mainline/pull/14

**Comment by srattay** [comment]
thanks for fixing!
