### ISSUE TITLE
Symbolic link not allowed or link target not accessible - can't make use of symbolic link for project

### ISSUE THREAD

**Issue by GiorgosK** [cytopia/devilbox#32]
I have successfully setup a project my_project and setup /etc/hosts and it works on the browser

I want to setup my system so that I keep all HTML in a seperate folder and not inside ./data/www using symlink's but it seems to not work 

I am using ubuntu 16.04 and as a demonstration that it does not work I have done the following 
in short I creating a symlink of proj/htdocs > my_project/htdocs 

```shell 
> giorgos@glaptop:/home/giorgos/share/gwebsites/devilbox/data/www$ ls -lah
total 12K
drwxr-xr-x 3 giorgos giorgos 4,0K Φεβ  16 08:36 .
drwxr-xr-x 5 root    root    4,0K Φεβ  14 19:05 ..
drwxrwxr-x 3 giorgos giorgos 4,0K Φεβ  14 17:11 my_project
giorgos@glaptop:/home/giorgos/share/gwebsites/devilbox/data/www$ ls my_project -lah
total 12K
drwxrwxr-x 3 giorgos giorgos 4,0K Φεβ  14 17:11 .
drwxr-xr-x 3 giorgos giorgos 4,0K Φεβ  16 08:36 ..
drwxrwxr-x 4 giorgos giorgos 4,0K Φεβ  15 06:48 htdocs
giorgos@glaptop:/home/giorgos/share/gwebsites/devilbox/data/www$ mkdir proj2
giorgos@glaptop:/home/giorgos/share/gwebsites/devilbox/data/www$ ln -s /home/giorgos/share/gwebsites/devilbox/data/www/my_project/htdocs proj2/htdocs
giorgos@glaptop:/home/giorgos/share/gwebsites/devilbox/data/www$ ls proj2 -lah
total 12K
drwxrwxr-x 2 giorgos giorgos 4,0K Φεβ  16 08:38 .
drwxr-xr-x 4 giorgos giorgos 4,0K Φεβ  16 08:37 ..
lrwxrwxrwx 1 giorgos giorgos   65 Φεβ  16 08:38 htdocs -> /home/giorgos/share/gwebsites/devilbox/data/www/my_project/htdocs
```
I have also entered proj2.loc in `/etc/hosts`

but going to `http://localhost/vhosts.php` displays 

>proj2	./data/www/proj2/htdocs	ERR	Missing htdocs directory in: ./data/www/proj2/
my_project	./data/www/my_project/htdocs	OK	my_project.loc

and visiting http://proj2.loc displays 

> 403 Forbidden
You don't have permission to access / on this server.

but when visiting http://my_project.loc I get 
> hello
 
from `my_project/htdocs/index.php` 

The permissions and owner/group seem to be the same for my_project and proj2

EDIT1:
but in the `./log/apache2.4/other-error.log` I see 
> [Thu Feb 16 08:39:42.120040 2017] [core:error] [pid 95] [client 172.16.238.1:35924] AH00037: Symbolic link not allowed or link target not accessible: /shared/httpd/proj2/htdocs

EDIT2:
I have followed some of the advices here http://unix.stackexchange.com/questions/20993/symbolic-link-not-allowed-or-link-target-not-accessible-apache-on-centos-6

and all the parent folders have x set for owner/group/other (1st answer)
and the directory is not encrypted (2nd answer) 
looking for a way to put `FollowSymLinks` in a custom `httpd.conf`

EDIT3:
As it it suggested on 3rd answer from the link above I have put in `./etc/apache-2.4 /httpd.conf` and `./cfg/apache-2.4 /httpd.conf` 
>Options +ExecCGI +FollowSymlinks -SymLinksIfOwnerMatch

on 2 seperate tries stopping and restarting the containers each time with `docker-compose stop` and `docker-compose up -d` but it does not help 

actually I am not sure the locations of `httpd.conf` are correct so I will wait for further input (maintainer probably)

**Comment by jpuck** [comment]
This would be a very convenient option to solve so that one could have the flexibility of storing projects anywhere on the filesystem instead of grouped in `$HOST_PATH_TO_WWW_DOCROOTS`

**Comment by cytopia** [comment]
@GiorgosK 

You can set the main path of your www folders inside `.env` file:

```
HOST_PATH_TO_WWW_DOCROOTS=/home/giorgos/share/gwebsites/devilbox/data/www
```

Correct me if I understood something wrong.

**Comment by jpuck** [comment]
For me, I've got projects all over my file system that I'd like to be able to load in devilbox.

```
/var/www/project1
/srv/project2
/home/jeff/project3
```

I'd like to be able to symlink to these projects from `HOST_PATH_TO_WWW_DOCROOTS`

```
mkdir -p /devilbox/data/www && cd /devilbox/data/www
mkdir project1 project2 project3
ln -s /var/www/project1 project1/htdocs
ln -s /srv/project2 project2/htdocs
ln -s /home/jeff/project3 project3/htdocs
```
but this doesn't work because symlinks to real paths outside `/devilbox/data/www` are not followed.

**Comment by cytopia** [comment]
Are those symlinked directories actually present inside the docker after startup?

**Comment by jpuck** [comment]
I don't think so. I guess this could be a limitation of docker whereby volumes can't follow symlinks.

**Comment by cytopia** [comment]
@jpuck I am sorry to hear, then there is not much I can do about it.

**Comment by cytopia** [comment]
Might be related to: https://github.com/cytopia/devilbox/issues/90
