### ISSUE TITLE
Custom httpd (nginx-stable) configuration results into ERR_EMPTY_RESPONSE

### ISSUE THREAD

**Issue by jukben** [cytopia/devilbox#323]
First of all, thanks for this stellar project! I've promised my father that I will build him a webpage with Wordpress – and It's madness again (!!!, I don't know why I'm hurting myself like this). However, this project is helping me survive. It's ridiculously easy to create a project on a custom domain with SSL support, enter the container and then handle rest of it with `wp` CLI. Just awesome. ❤️

#### ISSUE TYPE

 - Bug Report

#### OS / ENVIRONMENT

* Host operating system: macOS 10.13.6
* Native Docker or Docker Toolbox: 0.15
* Docker version: Docker version 18.06.0-ce, build 0ffa825
* Docker Compose version: docker-compose version 1.22.0, build f46880f

#### SUMMARY
Hey, I hope this is issue because there is some problem with merging of configurations. However if I use in config only this:

```
client_max_body_size 8M;
```

which was the reason why I have to approach the configuration in the first place, everything is OK. 

So I'm not blocked although I would have assumed that default configuration will work.

#### STEPS TO REPRODUCE
Apply default configuration on your nginx

```bash
cp cfg/nginx-stable/devilbox-custom.conf-example cfg/nginx-stable/devilbox.conf
```

#### OTHER INFORMATION

Relevant dump `docker-compose logs httpd`
```
httpd_1  | 2018/07/27 11:32:41 [emerg] 228#228: "keepalive_timeout" directive is duplicate in /etc/httpd-custom.d/devilbox.conf:14
httpd_1  | nginx: [emerg] "keepalive_timeout" directive is duplicate in /etc/httpd-custom.d/devilbox.conf:14
httpd_1  | watcherd: [2018-07-27 11:32:41] [ERR] TRIGGER failed:    nginx -s reload
httpd_1  | watcherd: [2018-07-27 11:32:41] Using bash loop to watch for changes.
httpd_1  | 2018-07-27 11:32:43,681 INFO spawned: 'httpd' with pid 247
httpd_1  | 2018/07/27 11:32:43 [emerg] 247#247: "keepalive_timeout" directive is duplicate in /etc/httpd-custom.d/devilbox.conf:14
httpd_1  | nginx: [emerg] "keepalive_timeout" directive is duplicate in /etc/httpd-custom.d/devilbox.conf:14
httpd_1  | 2018-07-27 11:32:43,699 INFO exited: httpd (exit status 1; not expected)
httpd_1  | 2018-07-27 11:32:46,706 INFO spawned: 'httpd' with pid 272
httpd_1  | 2018/07/27 11:32:46 [emerg] 272#272: "keepalive_timeout" directive is duplicate in /etc/httpd-custom.d/devilbox.conf:14
httpd_1  | nginx: [emerg] "keepalive_timeout" directive is duplicate in /etc/httpd-custom.d/devilbox.conf:14
httpd_1  | 2018-07-27 11:32:46,725 INFO exited: httpd (exit status 1; not expected)
httpd_1  | 2018-07-27 11:32:47,726 INFO gave up: httpd entered FATAL state, too many start retries too quickly
```

**Comment by cytopia** [comment]
Hi @jukben 
```
cp cfg/nginx-*/devilbox-custom.conf-example devilbox.conf
cp: target 'devilbox.conf' is not a directory
```
What shell are you using? Besides, you are copying nginx stable and mainline into the root Devilbox directory. Two files into the same location at a path where it is not picked up anyway.

So which of the two files did you put into what Nginx conf directory?

**Comment by jukben** [comment]
@cytopia sorry, that was more like "pseudocode" ... with typo 🤣 

```cp cfg/nginx-stable/devilbox-custom.conf-example cfg/devilbox.conf```

Should work I guess. The issue is about when you source the default conf to nginx.

**Comment by cytopia** [comment]
OK, got it. I will have a look and get this sorted.
