### ISSUE TITLE
subdomains not accessible

### ISSUE THREAD

**Issue by ftaiolivista** [cytopia/devilbox#324]
#### ISSUE TYPE

 - Bug Report

#### OS / ENVIRONMENT

* Host operating system: Linux 64 (arch)
* Native Docker or Docker Toolbox: Docker
* Docker version: 18.05.0-ce, build f150324782
* Docker Compose version: 1.22.0

#### SUMMARY

I need to access a vhost with an additional subdomain name

My folders structure:
* /vhosts/a/www
* /vhosts/sub.a -> (symlink to /vhosts/a)

In the intranet I correctly see
a.loc [OK]
sub.a.loc [OK]

If I navigate to a.loc I correctly see the vhost website, but if I navigate to sub.a.loc I got the devilbox intranet website.

#### STEPS TO REPRODUCE

Try a structure like mine. Using devilbox master.

**Comment by cytopia** [comment]
There is documentation about creating subdomains:
https://devilbox.readthedocs.io/en/latest/vhost-gen/example-add-subdomains.html

Does this solve your issue?

**Comment by ftaiolivista** [comment]
I don't want to create a custom subdomain configuration. I'm following this folder structure:

https://devilbox.readthedocs.io/en/latest/vhost-gen/example-add-subdomains.html?highlight=sub%20domain#single-sub-domain-for-one-project

**Comment by cytopia** [comment]
Got it.

> /vhosts/a/www
> /vhosts/sub.a -> (symlink to /vhosts/a)

1. Is this a relative or absolute symlink?
2. Are you able to access it on your host os?
3. Are you able to access it in the PHP container?

**Comment by ftaiolivista** [comment]
I think is a relative symlink. And yes I can access it on PHP container
![see screenshot](https://i.imgur.com/jw1lPMl.png)

**Comment by cytopia** [comment]
1. Do you have `htdocs` directory or symlink insides `/vhosts/a/www` and `/vhosts/sub.a`?
2. What does http://127.0.0.1/vhosts.php show?

**Comment by ftaiolivista** [comment]
.env confing:
HOST_PATH_HTTPD_DATADIR=/home/vista/www
HTTPD_DOCROOT_DIR=www

In the filesystem I have the folders 
/home/vista/www/apimart
/home/vista/www/apimart/www

And the symlink
/home/vista/www/api.apimart -> /home/vista/www/apimart

Vhost show:

apimart | /home/vista/www/apimart/www | OK | apimart.fbn.vista.it
api.apimart | /home/vista/www/api.apimart/www | ERR | No Host DNS record found. Add the following to /etc/hosts:127.0.0.1 api.apimart.fbn.vista.it

P.S. I have added 127.0.0.1 api.apimart.fbn.vista.it to my localhost

**Comment by cytopia** [comment]
> And the symlink
> `/home/vista/www/api.apimart -> /home/vista/www/apimart`

This is an absolute symlink which won't be available in the container.
Inside the container there is no such path: ` /home/vista/www/apimart`

You should use a relative symlink for that

**Comment by ftaiolivista** [comment]
Sorry, I wrote it as an absolute but in reality is relative.

ls (host machine):
lrwxrwxrwx 1 vista wheel 7 Jul 27 13:51 api.apimart -> apimart

ls from inside container:
devilbox@php-5.6.37 in /shared/httpd $ ls -lahd api*
drwxr-xr-x 3 devilbox uucp 4.0K Oct  9  2017 apimart/
lrwxrwxrwx 1 devilbox uucp    7 Jul 27 13:51 api.apimart -> apimart/

**Comment by cytopia** [comment]
The `api.apimart` must be a directory and not a symlink.

So how to get this working:

```
mkdir api.apimart
cd api.apimart
ln -s ../apimart/www htdocs
```
This works on my machine.

**Comment by ftaiolivista** [comment]
The proposed way works good. Thank you!

**Comment by cytopia** [comment]
Good to know.
I've adjusted the documentation for that: https://devilbox.readthedocs.io/en/latest/vhost-gen/example-add-subdomains.html#example
