### ISSUE TITLE
Email Panel Code Injection (XSS)

### ISSUE THREAD

**Issue by TACIXAT** [cytopia/devilbox#326]
#### ISSUE TYPE

 - Bug Report

#### OS / ENVIRONMENT

* Host operating system: Not sure
* Native Docker or Docker Toolbox: Not sure
* Docker version: Not sure
* Docker Compose version: Not sure

#### SUMMARY

A friend posted a link to their site that was displaying the admin panel. So I sent myself an email with the body `<script>alert(0)</script>`. This caused an XSS.

#### STEPS TO REPRODUCE

Send an email with a script in the body.

#### OTHER INFORMATION

![screenshot from 2018-07-27 19-20-18](https://user-images.githubusercontent.com/982598/43352083-cdb19dc6-91d2-11e8-8527-5b6c0bfc1470.png)

I happily accept paypal for the exorbitant bug bounty this vulnerability warrants. Thanks!

**Comment by cytopia** [comment]
@douggard thank you very much for reporting this security issue.

> I happily accept paypal for the exorbitant bug bounty this vulnerability warrants. Thanks!

As this is a completely free project without monetization I cannot offer you any money. However if you are willing to regulariy check this project and its Docker images for security problems I will credit you properly and accordingly.
