### ISSUE TITLE
PhpMyAdmin requires PHP 5.5+

### ISSUE THREAD

**Issue by jpuck** [cytopia/devilbox#33]
I was recently handed a maintenance job on an old app running PHP 5.4. So I booted up devilbox with PHP 5.4 no problem (thank you), but when trying to load PhpMyAdmin, I get the following error:

> PHP 5.5+ is required. 
> Currently installed version is: 5.4.45

Is there someway to load a compatible version of PhpMyAdmin?

-----------

Please also specify the following info:

- [X] Which operating system are you at (Linux, OSX or Windows)

> Linux Desktop
> Distributor ID:	Ubuntu
> Description:	Ubuntu 16.04.2 LTS
> Release:	16.04
> Codename:	xenial

- [X] `docker version`

> Client:
>  Version:      17.03.0-ce
>  API version:  1.26
>  Go version:   go1.7.5
>  Git commit:   60ccb22
>  Built:        Thu Feb 23 11:02:43 2017
>  OS/Arch:      linux/amd64
> 
> Server:
>  Version:      17.03.0-ce
>  API version:  1.26 (minimum version 1.12)
>  Go version:   go1.7.5
>  Git commit:   60ccb22
>  Built:        Thu Feb 23 11:02:43 2017
>  OS/Arch:      linux/amd64
>  Experimental: false

- [X] `docker-compose version`

> docker-compose version 1.11.2, build dfed245
> docker-py version: 2.1.0
> CPython version: 2.7.13
> OpenSSL version: OpenSSL 1.0.1t  3 May 2016

**Comment by cytopia** [comment]
Good point. As a quick work-around I suggest you use `adminer` which is also included (and I hope it works with php 5.4) or you use an sql client.

However this will need fixing.

**Comment by cytopia** [comment]
@jpuck this is going to be fixed in #37

**Comment by cytopia** [comment]
merged #37
