### ISSUE TITLE
Change PHP hostname

### ISSUE THREAD

**Issue by rodolfobubb** [cytopia/devilbox#331]
#### QUESTION

 - My php application uses getHostName function, and it's returning **04b17f369316**, it's possible to change this?

**Comment by science695** [comment]
Yes, you can add the setting in a docker-compose.overrides.yml file:

php:
  hostname: newhostname

**Comment by cytopia** [comment]
I will probably provide an PR that auto-sets the hostnames to its service name:

| Service | Host name |
|----------|-----------------|
| PHP | `php` |
| Web server | `httpd` |
| MySQL \| Maria \| Percona | `mysql` |
| MongoDB | `mongo` |
| Redis | `redis` |
| DNS | `bind` |
| PostgreSQ: | `pgsql` |
| Memcached | `memcd` |

I first need to check on compatibility issues with older Docker or Docker Compose versions.

**Comment by cytopia** [comment]
@rodolfobubb you could try out this PR #333 and check if this solves your issues.

```
docker-compose down
docker-compose rm -f
git checkout ensure-hostnames-are-fix
docker-compose up
```

**Comment by cytopia** [comment]
Merged

**Comment by rodolfobubb** [comment]
Solved! thanks!
