### ISSUE TITLE
mailcatcher renders raw html on devilbox dashboard

### ISSUE THREAD

**Issue by uabassguy** [cytopia/devilbox#337]
#### ISSUE TYPE

 - Bug Report

#### OS / ENVIRONMENT

1. Host operating system: OSX 10.13.6
2. Native Docker or Docker Toolbox: Native
3. Docker version: 18.06.0-ce, build 0ffa825
4. Docker Compose version: 1.22.0, build f46880f
5. What containers are running: devilbox_bind_1 devilbox_php_1 devilbox_httpd_1 devilbox_mysql_1 devilbox_memcd_1 devilbox_mongo_1 devilbox_redis_1 devilbox_pgsql_1
6. Container versions: ?

#### SUMMARY

When viewing an email in the devilbox dashboard, the email is shown as raw html

#### STEPS TO REPRODUCE

Using Magento 2 to send an email, mailcatcher gets the email and it is shown in the dashboard, but when I expand the email only raw html is shown

#### EXPECTED BEHAVIOUR

The email should render

#### ACTUAL BEHAVIOUR

Email does not render

#### OTHER INFORMATION

No customization

**Comment by cytopia** [comment]
@uabassguy 
Currently a bit more complicated as expected, because HTML emails will corrupt the layout (due to their own css styles).

Working on an iframe-based solution atm.

**Comment by uabassguy** [comment]
I was thinking an iframe would work too

**Comment by cytopia** [comment]
This might take longer than expected, however to read HTML mails, you could also use MailHog which has been integrated recently:

https://devilbox.readthedocs.io/en/latest/custom-container/integrate-mailhog.html

**Comment by uabassguy** [comment]
No rush. I've been copy pasting them into html files and opening them in a
browser for now. It works fine. Besides I don't always have an immediate
need for this. I was simply reporting the issue.
