### ISSUE TITLE
Add CraftCMS setup to documentation

### ISSUE THREAD

**Issue by richardcantwell** [cytopia/devilbox#341]
#### ISSUE TYPE

 - Documentation

#### SUMMARY
Add CraftCMS setup to documentation

#### Goal
Be able to easily set up Craft CMS

**Comment by richardcantwell** [comment]
I've just added a Craft CMS install - with asset building done by Blendid (https://github.com/vigetlabs/blendid) on a Windows 10 machine - no real difference to those other frameworks you have listed - i actually followed your WP one (https://devilbox.readthedocs.io/en/latest/examples/setup-wordpress.html) ...

winpty ./shell.bat
mkdir craft-demo
cd craft-demo
yarn init (https://github.com/vigetlabs/blendid)
yarn add blendid
yarn run blendid -- init-craft (https://github.com/vigetlabs/blendid/wiki/Craft-Setup)
exit exit

... back out of container (as i'm using Craft 2.6 so it's only available as a downloaded ZIP) and download Craft 2,6 from https://craftcms.com/support/download-previous-versions

- add contents of downloaded '/craft/' to '/craft/'
- add contents of downloaded '/public/' to '/public/'

... also do a few misc tasks whilst out of container ..

- Add to hosts ("127.0.0.1 craft-demo.loc")
- Update browserSync.proxy with dev URL (craft-demo.loc) - never got browserSync.proxy working!
- Add Blendid helpers to templates (https://github.com/vigetlabs/blendid/wiki/Craft-Setup)

... back into container ...

winpty ./shell.bat
cd craft-demo
ln -s public/ htdocs (Symlink /public/ folder)
mysql -u root -h 127.0.0.1 -p -e 'CREATE DATABASE craft_demo;'

... test compiling of assets ..

yarn run blendid

exit exit

... out of container ...

- http://craft-demo.loc:8080/admin (install Craft)
- activate 'Rev' plugin (https://github.com/vigetlabs/blendid/wiki/Craft-Setup)
- confirm everything works - http://craft-demo.loc:8080/

**Comment by cytopia** [comment]
I will add it and let you know in this issue.

**Comment by cytopia** [comment]
Documentation for Installation is done via `composer`

**Comment by richardcantwell** [comment]
Sorry dont follow?

**Comment by cytopia** [comment]
I meant instead of using `yarn` to install CraftCMS, I am using `composer` (as they also recommend this method on their documentation).

Docs will be available in ~1 hour. I let you know. Feel free to address any issues with it then.

**Comment by richardcantwell** [comment]
OH yeah absolutely - sorry my particular requirement was using an older version of Craft as in that procedure i added above - but yeah Craft 3 - perfect

**Comment by cytopia** [comment]
https://devilbox.readthedocs.io/en/latest/examples/setup-craftcms.html

**Comment by richardcantwell** [comment]
Seriously amazing how quick you evolve Devilbox!
