### ISSUE TITLE
phpmyadmin error - 'Wrong permissions on configuration file, should not be world writable!'

### ISSUE THREAD

**Issue by richardcantwell** [cytopia/devilbox#342]
#### ISSUE TYPE

 - Bug Report

#### OS / ENVIRONMENT

1. Host operating system:  Windows 10
2. Native Docker or Docker Toolbox:  Native
3. Docker version: 18.06.0-ce-win72 (19098)
4. Docker Compose version: 1.22.0
5. What containers are running: devilbox_mysql_1, devilbox_httpd_1, devilbox_php_1, devilbox_bind_1
6. Container versions: 

#### SUMMARY

Fresh install then when i go to http://127.0.0.1:8080/vendor/phpmyadmin-4.8/index.php from the Intranet tab (http://127.0.0.1:8080), i get 'Wrong permissions on configuration file, should not be world writable!'

#### STEPS TO REPRODUCE

- http://127.0.0.1:8080
- Tools
- PHPMyadmin

#### EXPECTED BEHAVIOUR

PHPMyadmin to show login screen

#### ACTUAL BEHAVIOUR

'Wrong permissions on configuration file, should not be world writable!'

#### OTHER INFORMATION

No - straight forward 5 minute install.

on some forums i see some people suggested adding a setting in '/var/www/default/htdocs/vendor/phpmyadmin-4.8' of ...

$cfg['CheckConfigurationPermissions'] = false;

I tried to do this by sudo logging into my PHP container ..

sudo su -
cd /var/www/default/htdocs/vendor/phpmyadmin-4.8
chmod 755 config.inc.php
vi config.inc.php

.... but all this directory is 'read only' .. so i couldn't test whether this works.

**Comment by cytopia** [comment]
@richardcantwell thanks for the bug report.

Can you try to alter the file (from your host computer in the Devilbox git directory, while the Devilbox is not running): `.devilbox/www/htdocs/vendor/phpmyadmin-4.8/config.inc.php`

**Comment by richardcantwell** [comment]
Wow BINGO!

docker-compose down
cd devilbox
vi .devilbox/www/htdocs/vendor/phpmyadmin-4.8/config.inc.php
i
.... add line $cfg['Servers'][$i]['CheckConfigurationPermissions'] = false;

[ESC] wq!
chmod 555 .devilbox/www/htdocs/vendor/phpmyadmin-4.8/config.inc.php
docker-compose up -d httpd php mysql

... and it worked! I've just removed the '$cfg['Servers'][$i]['CheckConfigurationPermissions'] = false;' and this made no difference - it's the 'chmod 555' that  made the difference!

Thanks a million cytopia!

**Comment by cytopia** [comment]
kk, cheers. I will add this and push the new permissions.

**Comment by cytopia** [comment]
I just checked it on my machine. Nothing complains. Do you have a screenshot of yours under what section I can see the warning message.

**Comment by richardcantwell** [comment]
Sorry I’ve just left the office - but the week was on http://127.0.0.1/vendor/phpmyadmin-4.8/index.php - literally fresh pull then navigated to intranet -> tools -> phpmyadmin - and the error was on that page

**Comment by EresDev** [comment]
I am facing this issue in windows 10. Trying out devilbox for the first time and stuck on this.

**Comment by EresDev** [comment]
Ok, It worked for me when I have added following line at the top of file:

`$cfg['CheckConfigurationPermissions'] = false;`

It was not working when I have added the above line to the bottom.

**Comment by cytopia** [comment]
Its fixed. Thanks for the info.

**Comment by cytopia** [comment]
FYI: I cannot add file permissions to git except for executable or not executable, so I will have to add `$cfg['CheckConfigurationPermissions'] = false;` to make sure it works everywhere.

**Comment by MissakaI** [comment]
> Ok, It worked for me when I have added following line at the top of file:
> 
> `$cfg['CheckConfigurationPermissions'] = false;`
> 
> It was not working when I have added the above line to the bottom.
> 
> File location: .devilbox\www\htdocs\vendor\phpmyadmin-4.8\config.inc.php

This works if you are working on ntfs file system on linux as well. Because ntfs does not support file permissions using chmod

**Comment by mamlzy** [comment]
> Ok, It worked for me when I have added following line at the top of file:
> 
> `$cfg['CheckConfigurationPermissions'] = false;`
> 
> It was not working when I have added the above line to the bottom.
> 
> File location: .devilbox\www\htdocs\vendor\phpmyadmin-4.8\config.inc.php

thank you so much, it solved my issue, i was facing this when running phpmyadmin in docker
