### ISSUE TITLE
Rsync - 'Command not found'

### ISSUE THREAD

**Issue by richardcantwell** [cytopia/devilbox#343]
#### ISSUE TYPE

 - Question

#### SUMMARY

This may be a fairly basic question (apologies in advance) but i need to run an 'rsync' from a remote server to my local PHP container ....

rsync -auv USER@IP:REMOTEPATHl/public/files/* LOCALPATH/files/

When i enter my PHP container (after 'docker-compose up -d httpd php mysql') and try run this - i get 'Command not found' in reference to 'rysnc'.

Is it just a case of running 'apt install rsync' as a sudo user in the container? Or is there a local config (.env pr php.ini) that i can edit? 

#### Goal

Be able to transfer files from a remote server to my PHP container.

**Comment by cytopia** [comment]
Should be ready in ~1 hour.

**Comment by richardcantwell** [comment]
This is crazy how good you are! How good Devilbox is!

**Comment by cytopia** [comment]
Its available now, just update Devilbox git to latest master

**Comment by richardcantwell** [comment]
Amazing! Thanks you so much!
