### ISSUE TITLE
Browser Sync from

### ISSUE THREAD

**Issue by richardcantwell** [cytopia/devilbox#344]
Just wondering does anyone know how to operate Browser Sync from within a container?

I’ve read https://stackoverflow.com/questions/42456424/browsersync-within-a-docker-container and there’s is a solution there - just wondering what the best configuration for Devilbox would be - a docker-compose.yml.override?

**Comment by cytopia** [comment]
At the moment `docker-compose.override.yml` is your best option.

Having auto-vhosts for reverse proxies is not yet implemented, but on the agenda.
I will close this ticket in favour of the main one: https://github.com/cytopia/devilbox/issues/240

If you encounter  any issues with the worok-around method, please add it to the above mentioned ticket.

**Comment by richardcantwell** [comment]
Hi,

I'm just trying to get BrowserSync to work for my next project and just
wanted to get your advice on something. If i create a
docker-compose.override.yml file and expose a few more ports (think
browserSync uses 3000 and 3001 by default) - what is the actual procedure?
If i remove all my images and containers first then do a *docker-compose up
-d httpd php mysql* again - i won't lose my databases will i? I haven't
touched the initial docker install - it's just as per the documentation.

Listen i know this is possibly a docker based question - but i just wanted
to check first

Thanks again

**Comment by cytopia** [comment]
@richardcantwell just to get you up to speed.

Anything can now be reverse proxied into/out of the Devilbox, this will also be true for BrowserSync

* https://devilbox.readthedocs.io/en/latest/reverse-proxy/reverse-proxy-with-https.html
* https://devilbox.readthedocs.io/en/latest/vhost-gen/virtual-host-vs-reverse-proxy.html

Here is an actual example setup for NodeJS:

* https://devilbox.readthedocs.io/en/latest/examples/setup-reverse-proxy-nodejs.html

**Comment by richardcantwell** [comment]
This is so good

**Comment by howdu** [comment]
@cytopia apologies for referencing an old issue but I'm having issues understanding what's required to get BrowserSync working? I've copied the default nginx vhost to: ~/devilbox/data/www/project/.devilbox/nginx.yml

Testing this standard webpack/browsersync boilderplate setup:
https://github.com/WeAreAthlon/frontend-webpack-boilerplate
