### ISSUE TITLE
How to allow connections to the webserver from additional containers.

### ISSUE THREAD

**Issue by hoeler** [cytopia/devilbox#353]
#### ISSUE TYPE

 - Question

#### SUMMARY

How can I allow access from additional containers to vhosts? (e.g. via curl on port 80)

#### Goal

I am using devilbox with PHPStorm and have problems using the integrated docker support of the IDE when running TestCases for PHPUnit.

When running TestCases that make use of curl calls to the webserver I always get the following error:
"Failed to connect to my-application.local on port 80: Connection refused"

I already configured the Docker PHP CLI in PHPStorm to add the container to "devilbox_app_net" (which solved my initial problems with accessing the database from the launched php container) but this does not seem to help with the vhosts.

I also checked the vhost .conf file for my project on the httpd container (in my case apache 2.4) which correctly states "Allow from all" and "Require all granted" for that host.

I am at a loss as to what else do I need to configure to make this work. Any help would be greatly appreciated.

**Comment by cytopia** [comment]
@hoeler there are a few chapters in the documentation covering this topic:

* [Connect to Host OS](https://devilbox.readthedocs.io/en/latest/advanced/connect-to-host-os.html#connect-to-host-os)
* [Connect to other Docker container](https://devilbox.readthedocs.io/en/latest/advanced/connect-to-other-docker-container.html)
* [Conncet to external host](https://devilbox.readthedocs.io/en/latest/advanced/connect-to-external-hosts.html)

If however you want to access a specific **vhost** at the Devilbox web server, you require valid dns, i.e. the vhost name you want to access must resolve to the IP address of the Devilbox Webserver or at the IP address where its port is exposed.

A good reading for this would be: [Shared Devilbox server in LAN](https://devilbox.readthedocs.io/en/latest/corporate-usage/shared-devilbox-server-in-lan.html)

Let me know if this answers your question.

**Comment by hoeler** [comment]
@cytopia Using the "--add-host" parameter in PHPStorm on the container to resolve the vhost to the IP address of the webserver did the trick. Thank your for your quick help and keep up the good work!

**Comment by cytopia** [comment]
@hoeler good that this issue is resolved. Could you paste a screenshot of this setting please, I can then hopefully add this stuff to the documentation

**Comment by hoeler** [comment]
@cytopia sure!
This is my current configuration for container startup in PHPStorm:
![image](https://user-images.githubusercontent.com/1442905/44090905-06dbc49e-9fcc-11e8-9315-c6e996d57c0d.png)

Everything else I simply set up as shown here:
https://www.youtube.com/watch?v=I7aGWO6K3Ho&t=1s
