### ISSUE TITLE
Display Custom Container Status

### ISSUE THREAD

**Issue by llaville** [cytopia/devilbox#359]
#### ISSUE TYPE

 - Feature request

#### SUMMARY

Display Custom Container Status

#### Goal

I don't know if it's possible or not, but with new cool feature  to add easily other custom container (i like it!) with `docker-compose.override.yml`.

It will be nice and usefull to allow to see all additional services status (rabbitMQ, Solr, ...), on the same page (https://github.com/cytopia/devilbox/blob/master/.devilbox/www/htdocs/index.php) as default services.

Thanks for this great project/contribution to Open Source Community :-)

**Comment by cytopia** [comment]
This is not easily possible. The PHP container somehow needs to be able to see what Docker container are currently running in the Devilbox network.

So if this issue can be solved, the integratoin will become straight forward.

**Comment by llaville** [comment]
Thanks for your answer. I've an idea. I'll try it and keep you aware of my tests and results.

**Comment by cytopia** [comment]
OK, let me know if you find something interesting.

**Comment by cytopia** [comment]
Does this work from within the PHP container? Or did you run it on your host os?

**Comment by llaville** [comment]
I've run it from my host os

**Comment by cytopia** [comment]
The Devilbox intranet is running inside the PHP container and this is the major issue. It cannot act as a direct Docker client (and would probably not be able to read out the above shown information).

So the main goal is to find some means to gather those information from within the PHP container.

**Comment by cytopia** [comment]
I marked it as `wontfix`. Just in case you find something let me know. I like this idea still

**Comment by llaville** [comment]
@cytopia ok. If i found a solution (I'll continue to search), I'll keep you aware (promised) !

**Comment by science695** [comment]
Technically, you can run docker commands from within containers, but you have to map the docker socket inside the container...and it kindof reduces the security (because that container could break into another container)

**Comment by llaville** [comment]
@cytopia is it possible, as devilbox required at least [Docker Engine 1.12.0+](https://docs.docker.com/compose/compose-file/compose-versioning/#version-21) to think to implement [healthcheck](https://docs.docker.com/compose/compose-file/compose-versioning/#version-21) feature. Disable/Enable via dotenv file.

This could be a nice new devilbox feature, even if it's not use to solve this one! Tell me what you think about it ?

**Comment by science695** [comment]
@llaville healthcheck helps docker know if a container service is still running properly. But it does not solve the problem of communicating to a container the status of all the other containers.

Currently, devilbox runs all of its code inside a container and therefore is extremely cross-OS compliant. It seems like this feature would require a script to be running on the main host (which would lose that benefit).

@cytopia you have something similar to this on the vhosts page, could something similar work for these other services? maybe a healthcheck url in the .env file for each service?

**Comment by llaville** [comment]
@science695 I agree with you, and i did not misunderstood docker healthcheck feature.

I think it could be a nice add-on. Probably as you described (with an url in dotenv file for each service)
