### ISSUE TITLE
Kirby CMS Error

### ISSUE THREAD

**Issue by illycz** [cytopia/devilbox#361]
#### ISSUE TYPE

 - Bug Report

#### OS / ENVIRONMENT

1. Host operating system: macos high sierra
2. Native Docker or Docker Toolbox: native docker
3. Docker version: Version 18.06.0-ce-mac70 (26399)
4. Docker Compose version: 1.22.0, build f46880f
5. What containers are running: all
6. Container versions: 

#### SUMMARY

When I try run my existing Kirby CMS website (https://github.com/getkirby/kirby) I get `Fatal error: Cannot redeclare go() in /shared/httpd/pardus-bike/pardus-bike/kirby/vendor/getkirby/toolkit/helpers.php on line 29`. I 'm not a developer so I don't understand where is the problem. Everything works in MAMP...

Thanks

**Comment by cytopia** [comment]
Can you provide some more details on the PHP/Webserver versions you use, also do you have any custom configs in place?

**Comment by illycz** [comment]
1. Latest installation of Devilbox and Kirby CMS.
2. My actual env: https://gist.github.com/illycz/de201a23240b0c57336e23d8d6a4bc8f (I tested also default setting with same result)
3. Kirby is cloned from Github and folder structure is same as in WordPress tutorial (htdocs symlinked to Kirby)

Something else?

Thanks a lot!

**Comment by cytopia** [comment]
Please provide more detailed instructions for how to set it up the way you did it. I currently have:
```
/shared/httpd/ $ mkdir kirby
/shared/httpd/ $ cd kirby
/shared/httpd/kirby $ git clone https://github.com/getkirby/kirby
/shared/httpd/kirby $ ln -s kirby htdocs
/shared/httpd/kirby $ tree -L 1
.
├── htdocs -> kirby
└── kirby

2 directories, 0 files
```
```bash
/shared/httpd/kirby $ curl -I kirby.loc/
HTTP/1.1 404 Not Found
Date: Wed, 22 Aug 2018 10:58:18 GMT
X-Powered-By: PHP/7.2.8
Content-Type: text/html; charset=UTF-8
```
However, the framework is not accessable via web browser. There doesnt seem to be an `index.php`
```
$ find . -name 'index.php'
```
does not find anything.

Where should the symlink point to and how to get the index.php

**Comment by illycz** [comment]
It's better clone starterkit: `git clone --recursive https://github.com/getkirby/starterkit.git kirby`.
Kirby uses submodules for Core and Panel (administration interface).

I think you clone only Core of Kirby...

**Comment by cytopia** [comment]
@illycz the function `go()` is already provided by some PHP module. I could not yet figure out which one.

However, if you simply create a new empty project with an `index.php`

```php
<?PHP

function go() {
        echo 'test';
}
go();
```
You will also get this error:

Fatal error: Cannot redeclare go() in /shared/httpd/test/htdocs/index.php on line 5

**Comment by cytopia** [comment]
I figured it. The `go()` function is already implemented in recent versions of [swoole](https://github.com/swoole/swoole-src)

So in order to mitigate this issue, simply disable `swoole` in env like so:
```
PHP_MODULES_DISABLE=swoole
```

**Comment by illycz** [comment]
Fantastic! Thanks for your investigation work :)

**Comment by cytopia** [comment]
@illycz Fix is coming to have swoole disabled by default as it is rarely used.
