### ISSUE TITLE
Postfix catch-all not working

### ISSUE THREAD

**Issue by hoeler** [cytopia/devilbox#365]
#### ISSUE TYPE

 - Bug Report

#### OS / ENVIRONMENT

1. Host operating system: Windows 10
2. Native Docker or Docker Toolbox: Native Docker
3. Docker version: Docker version 18.06.0-ce, build 0ffa825
4. Docker Compose version: docker-compose version 1.22.0, build f46880fe
5. What containers are running: php
6. Container versions: devilbox/php-fpm:7.0-work-0.32, devilbox/apache-2.4:0.22

#### SUMMARY

Catch-all of postfix server does not work as expected. Whenever sending a mail, it is not written to the devilbox mailbox and `/var/log/mail.log` reads:
`warning: specify "strict_mailbox_ownership = no" to ignore mailbox ownership mismatch`
`cannot update mailbox /var/mail/devilbox for user devilbox. destination /var/mail/devilbox is not owned by recipient`

full mail.log:
`Aug 27 10:13:33 php postfix/postfix-script[1939]: starting the Postfix mail system
Aug 27 10:13:33 php postfix/master[1941]: daemon started -- version 3.1.8, configuration /etc/postfix
[27-Aug-2018 10:14:19 Europe/Berlin] mail() on [/var/www/default/htdocs/mail.php:12]: To: info@example.com -- Headers:
Aug 27 10:14:19 php postfix/pickup[1942]: 7F0C53244C9: uid=1000 from=<devilbox>
Aug 27 10:14:19 php postfix/cleanup[2148]: 7F0C53244C9: message-id=<20180827081419.7F0C53244C9@f5cc1b5f5df0.c.eco-emissary-99515.internal>
Aug 27 10:14:19 php postfix/qmgr[1943]: 7F0C53244C9: from=<devilbox@f5cc1b5f5df0.c.eco-emissary-99515.internal>, size=414, nrcpt=1 (queue active)
Aug 27 10:14:19 php postfix/local[2152]: warning: specify "strict_mailbox_ownership = no" to ignore mailbox ownership mismatch
Aug 27 10:14:19 php postfix/local[2152]: 7F0C53244C9: to=<devilbox@f5cc1b5f5df0.c.eco-emissary-99515.internal>, orig_to=<info@example.com>, relay=local, delay=0.06, delays=0.03/0.01/0/0.02, dsn=4.2.0, status=deferred (cannot update mailbox /var/mail/devilbox for user devilbox. destination /var/mail/devilbox is not owned by recipient)`

#### STEPS TO REPRODUCE

Send a mail from php container in any way and check `/var/mail/devilbox`

#### EXPECTED BEHAVIOUR

Mails are written to devilbox mailbox.

#### ACTUAL BEHAVIOUR

Postfix denies update of mailbox because destination is not owned by recipient.

#### OTHER INFORMATION

Maybe this issue only occurs on windows and is connected to the general permission handling?
`/var/mail/devilbox` is owned by `root:root` and it also did not help to remove the file and hard-resetting all containers (`docker-compose down && docker-compose rm -f`)
Setting `strict_mailbox_ownership = no` for postfix might just be the simplest solution?

**Comment by cytopia** [comment]
Fix is on the way: https://github.com/devilbox/docker-php-fpm/pull/49

**Comment by cytopia** [comment]
@hoeler this issue has been fixed in the latest master branch

**Comment by hoeler** [comment]
@cytopia thanks for the quick fix! Love using devilbox.
