### ISSUE TITLE
php-fpm latest versions not update

### ISSUE THREAD

**Issue by llaville** [cytopia/devilbox#367]
#### ISSUE TYPE

 - Bug Report

#### OS / ENVIRONMENT

1. Host operating system: Ubuntu 16.04
2. Native Docker or Docker Toolbox:  native
3. Docker version: 18.06.1-ce
4. Docker Compose version: version 1.18.0, build 8dd22a9
5. What containers are running: 
6. Container versions: 
7. Devilbox version 0.15  https://github.com/cytopia/devilbox/commit/acac4f0459b33ffcdc827e77b758e26dc82d4d5f
8. Git branch version:  master 8913fd4 Merge pull request #358 from cytopia/docker-blackfire

#### SUMMARY

I wanted to update to latest PHP 7.1(.21) base image but it was impossible.
This version is available with release 0.35 of https://github.com/devilbox/docker-php-fpm
But not with release 0.32

#### STEPS TO REPRODUCE

./update.sh

#### EXPECTED BEHAVIOUR

Be able to get always the latest PHP version

#### ACTUAL BEHAVIOUR

PHP 7.1.20 version installed

#### OTHER INFORMATION

I've searched before to find where it came from.

https://github.com/cytopia/devilbox/blob/master/docker-compose.yml#L98
Tell us 
```yaml
 php:
    image: devilbox/php-fpm:${PHP_SERVER:-7.0}-work-0.32
```
I've replaced `work-0.32` by `work-0.35` and all is good

**Comment by cytopia** [comment]
@llaville I was already a bit ahead with creating new PHP versions and removed the old once from nightly auto-building without adding the new one to the Devilbox. PR is coming today.

**Comment by llaville** [comment]
@cytopia I won't reopen this issue, but I'll keep you aware that you should think on a solution to provide Docker PHP-FPM images with latest PHP versions.

Actually either devilbox/php-fpm:7.2-work or devilbox/php-fpm:7.2-work-0-42 contains only PHP 7.2.10 version.
I've not checked other images, but I'm pretty sure there are not up-to-date too !

PHP 7.2.11 was released on Oct 11, 2018.  PHP 7.1.23 was released also the same day

**Comment by llaville** [comment]
@cytopia Hello; I've just tested release v0.44 (with changing line https://github.com/cytopia/devilbox/blob/master/docker-compose.yml#L98), and it works : 

- like a charm for PHP 7.1.23
- like a charm for PHP 7.2.11

- but i'm surprised with PHP 7.3, when I enter php container I see `devilbox@php-7.3.0-dev in /shared/httpd $`

Confirmed with command `php -v`

```
PHP 7.3.0-dev (cli) (built: Jul 27 2018 20:16:57) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.0-dev, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.3.0-dev, Copyright (c) 1999-2018, by Zend Technologies
```

Latest version is 7.3.0RC4 (25-Oct)

**Comment by cytopia** [comment]
> Latest version is 7.3.0RC4 (25-Oct)

Yes, this is due to the fact that I am building PHP 7.3 out of the github source myself, as it wasnt available by the time I've added it to the Devilbox. I will switch this to the official RC the coming days and add the current state of PHP 7.4 to the stack

**Comment by llaville** [comment]
@cytopia I've just test release v0.46 with PHP 7.3, and noticed a little change in php container prompt since previous unofficial version (see my [comment](https://github.com/cytopia/devilbox/issues/367#issuecomment-435296526))

See `devilbox@php-7.3.0 in /shared/httpd $`

And command `php -v` give

```
PHP 7.3.0RC4 (cli) (built: Oct 26 2018 20:43:47) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.0-dev, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.3.0RC4, Copyright (c) 1999-2018, by Zend Technologies
```
Is it not suppose to see prompt with `devilbox@php-7.3.0RC4` ?

**Comment by cytopia** [comment]
> Is it not suppose to see prompt with devilbox@php-7.3.0RC4 ?

Looks like I forgot to also parse upper case. PR on the way: https://github.com/devilbox/docker-php-fpm/pull/61
