### ISSUE TITLE
Please include "unzip" and "patch"

### ISSUE THREAD

**Issue by jasonhildebrand** [cytopia/devilbox#369]
#### ISSUE TYPE

 - Feature request

#### SUMMARY
Please include the "unzip" and "patch" packages in php images.  When installing Drupal modules using drush, some need to be unzipped, and it is common to apply patches via drush make.  This fails because unzip and patch are not installed.

#### Goal

As with all the other awesome things that devil box does, Drush should "just work".

**Comment by jasonhildebrand** [comment]
Super!  Thanks for your work on devilbox!

**Comment by cytopia** [comment]
@jasonhildebrand this issue has been fixed in the latest master branch
