### ISSUE TITLE
I would like to suggest that the graphviz feature is already present in DevilBox

### ISSUE THREAD

**Issue by mozgbrasil** [cytopia/devilbox#376]
#### ISSUE TYPE

 - Feature request

#### SUMMARY

I'm testing this application that uses the "graphviz"

https://github.com/beyondcode/laravel-er-diagram-generator

#### Goal

Good afternoon

I need to use graphviz

https://www.graphviz.org/

I would like to suggest that the graphviz feature is already present in DevilBox

Thanks for listening

**Comment by cytopia** [comment]
@mozgbrasil update the Devilbox master branch. New images will automatically come with graphviz support

**Comment by mozgbrasil** [comment]
Hello good afternoon

I was able to use the feature successfully

Thank you very much

![captura de tela de 2018-09-12 16-29-29](https://user-images.githubusercontent.com/17202780/45448628-32a1e880-b6a9-11e8-8cdf-799169eda0c4.png)
