### ISSUE TITLE
Add "Deployer" to available tools and option for linking SSH keys from host OS

### ISSUE THREAD

**Issue by carcade** [cytopia/devilbox#378]
#### ISSUE TYPE

 - Feature request

#### SUMMARY

Add Deployer (https://deployer.org/) to available tools, and add a possibility to link host system's SSH keys to container (needed by deployer to connect to remote hosts).

**Comment by carcade** [comment]
Have seen you added deployer, but how to bypass ssh keys from host system?

**Comment by cytopia** [comment]
I am still thinking of a better solution.

As of now, you could add your ssh keys into `bash/id_rsa` directory and from within the container use it via `ssh -i /etc/bashrc-devilbox.d/id_rsa`

**Comment by cytopia** [comment]
@carcade 

The current idea is to extend the currently existing `bash/` directory within the Devilbox git dir with the following structure:

```
bash/
    bash/       # <-- where you scripts to customize bash go
    ssh/         # <-- where you can put ssh keys
```

This way it is easier to further extend it with other stuff as requests come in.

**Comment by martinbertinat** [comment]
@cytopia I really like the second idea.

@carcade Did you have any progress on this? I'm also using deployer

**Comment by carcade** [comment]
> @carcade
> 
> The current idea is to extend the currently existing `bash/` directory within the Devilbox git dir with the following structure:
> 
> ```
> bash/
>     bash/       # <-- where you scripts to customize bash go
>     ssh/        # <-- where you can put ssh keys
> ```
> This way it is easier to further extend it with other stuff as requests come in.
> 
> **Update**
> 
> Second thought.
> 
> I could actually do a **one-to-one** mapping: Anything you put into `bash/` will be added to the `devilbox` users home directory. So as an example:
> 
> ```
> bash/
>     .config/nvim/init.vim
>     .gitconfig
>     .ssh/
>         config
>         id_rsa.pub
>         id_rsa
> ```
> This will then be available inside the PHP container by the same names in the `devilbox` home directory. That way you could add any configuration files and stuff you want.

Thanks for great support! But, unfortunately, i had switched from Devilbox to raw Apache + PHP installation.



> @cytopia I really like the second idea.
> 
> @carcade Did you have any progress on this? I'm also using deployer

Hello. As I said, I had switched from Devilbox to raw Apache + PHP, and I'm using system installed deployer.

**Comment by carcade** [comment]
If that is all, you can close the issue. Thanks!

**Comment by nicholas-a-clark** [comment]
Is this feature enabled I have a use to setup ssh keys for authenticating with SVN

**Comment by cytopia** [comment]
The above proposed directory structure is going to require some more heavy lifting on PHP-FPM images than initially thought.

But in order to make this possible for you, I have a quick-fix which should satisfy your need until this feature hits the master branch:

Add your ssh key into the `bash/` directory and use the auto-start mechanism of the Devilbox to always copy (not move), this key to `/home/devilbox/.ssh/`. This allows all the magic happen automatically during `docker-compose up`/

See here for how to add custom autostart scripts: https://devilbox.readthedocs.io/en/latest/autostart/custom-scripts-globally.html

**Comment by nicholas-a-clark** [comment]
I found a way to use my local .ssh and .composer keys from my local linux home directory I just did the following in the docker-composer.yaml file

- /home<username>/.composer:/home/devilbox/.composer:rw${MOUNT_OPTIONS}

In this way the docker image can see my ssh keys and use them as they are mount under /home/devilbox/ folder

Not sure if this helps anyone with this or not.

**Comment by nicolabeghin** [comment]
Any news on this? I added this in the php section of `docker-compose.yml` in order to inherit my git config and ssh keys:

```
- ~/.gitconfig:/home/devilbox/.gitconfig
- ~/.ssh:/home/devilbox/.ssh
```

I don't think it's a long-term solution since it's editing the git-indexed `docker-compose.yml`. Any better suggestion? :D

**Comment by nicolabeghin** [comment]
@cytopia any suggestion? really appreciate devilbox, it's not part of my daily workflow :D

**Comment by science695** [comment]
@nicolabeghin You can use docker-compose.overrides.yml to append these volumes to the docker container without directly editing the main yml file.

The overrides yml file is merged into the base file so you can override any setting.

**Comment by nicolabeghin** [comment]
thanks @science695 I assumed if a new `volume:` block is available in `docker-compose.overrides.yml` it would override the whole pre-existing `volume:` ??

**Comment by science695** [comment]
Actually, the way I have seen it working is that the 2 arrays are merged, which makes it very easy to add new volumes, but very difficult to remove / modify volumes.

**Comment by nicolabeghin** [comment]
thanks a lot @science695 , all good!

**Comment by cytopia** [comment]
Configurable directory for mounting ssh keys is now available.
