### ISSUE TITLE
Problem with Drush Version 9

### ISSUE THREAD

**Issue by MariusE** [cytopia/devilbox#384]
#### ISSUE TYPE

 - Question

#### SUMMARY

Is there a way to use more than one drush Version or to define the version to use?

#### Goal

It looks as you updated drush to the latest version (8.x -> 9.x). This Version is a absolute breaking change. Many things are no longer possible to do with the basic drush installation in version 9. According to that, my whole workflow is broken.
It would be amazing, when I got the possibility to select the version I want to use for my projects.

Thanks for your help!

**Comment by cytopia** [comment]
Something I could imagine is adding them as `drush8` and `drush9` and having `drush` always symlinked to the latest version.

**Comment by cytopia** [comment]
@Trogie its currently building and should be available shortly.

**Comment by MariusE** [comment]
Amazing 👍 
Thanks for your great work on this tool, @cytopia

**Comment by Trogie** [comment]
Super!! Verifying now :
