### ISSUE TITLE
How to compile custom PHP extension (ex: Kafka)

### ISSUE THREAD

**Issue by innobrig** [cytopia/devilbox#385]
#### ISSUE TYPE

 - Question

#### SUMMARY
How can I add a custom PHP extension to devilbox?

#### Goal
I am trying to customize devilbox to support kafka. Adding zookeeper and kafka to docker-compose.override.yml is no problem but it's not clear to me what I need to do in order to compile the php-rdkafka extension and then link this into the PHP version I wish to use (7.2). Any info on how to achieve this would be much appreciated.

**Comment by cytopia** [comment]
@innobrig I think easiest solution is if i just bake it in by default

**Comment by cytopia** [comment]
@innobrig once the above PR is merged, Kafka PHP module will be available
