### ISSUE TITLE
Intranet request fails: Attempt to connect to 172.16.238.10:9000 (php) failed

### ISSUE THREAD

**Issue by innobrig** [cytopia/devilbox#386]
#### ISSUE TYPE

 - Bug Report

#### OS / ENVIRONMENT

1. Host operating system: Ubuntu 18.04
2. Native Docker or Docker Toolbox: Docker version 18.06.1-ce, build e68fc7a
3. Docker version: Docker version 18.06.1-ce, build e68fc7a
4. Docker Compose version: docker-compose version 1.17.1, build unknown
5. What containers are running: httpd php
6. Container versions: 
 - apache 2.4
 - php 7.2

#### SUMMARY
[Wed Sep 26 22:32:10.492719 2018] [proxy:error] [pid 209:tid 140670038112000] (111)Connection refused: AH00957: FCGI: attempt to connect to 172.16.238.10:9000 (php) failed
[Wed Sep 26 22:32:10.492812 2018] [proxy_fcgi:error] [pid 209:tid 140670038112000] [client 172.16.238.1:39742] AH01079: failed to make connection to backend: php

#### STEPS TO REPRODUCE
1) Clone devilbox repo
2) cp env-example  .env
3) edit .env and set
  - PHP_SERVER=7.2
  - HTTPD_SERVER=apache-2.4
4) docker-compose up httpd php
5) Hit http://172.16.238.11/ in browser
BTW, local (ie: host-OS) apache has been stopped/disabled

#### EXPECTED BEHAVIOUR
I think this should give me the intranet page

#### ACTUAL BEHAVIOUR
In browser:

    Service Unavailable
    The server is temporarily unable to service your request due to maintenance downtime or capacity problems. Please try again later.

In log file /devilbox/log/apache-2.4:

    [Wed Sep 26 22:32:10.492719 2018] [proxy:error] [pid 209:tid 140670038112000] (111)Connection refused: AH00957: FCGI: attempt to connect to 172.16.238.10:9000 (php) failed
    [Wed Sep 26 22:32:10.492812 2018] [proxy_fcgi:error] [pid 209:tid 140670038112000] [client 172.16.238.1:39742] AH01079: failed to make connection to backend: php

#### OTHER INFORMATION
I got this to work the other day without any issues on my laptop (which I've since unfortunately re-installed) but on my desktop machine I'm getting this problem. My guess is that I'm doing something wrong but I've been banging my head against this one for a while now and would appreciate any help you can offer. Apologies in advance if I'm making a bonehead mistake.

#### Console log output:
root@rxg:/usr/local/docker/devilbox# docker-compose up httpd php
devilbox_bind_1 is up-to-date
Recreating devilbox_php_1 ... 
Recreating devilbox_php_1 ... done
Recreating devilbox_httpd_1 ... 
Recreating devilbox_httpd_1 ... done
Attaching to devilbox_php_1, devilbox_httpd_1
php_1    | AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.16.238.10. Set the 'ServerName' directive globally to suppress this message
httpd_1  | [INFO] Debug level: 1
httpd_1  | [INFO] Runtime debug: 1
php_1    | AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.16.238.10. Set the 'ServerName' directive globally to suppress this message
httpd_1  | [INFO] Changing user 'daemon' uid to: 1000
php_1    | [Wed Sep 26 20:31:58.784451 2018] [mpm_prefork:notice] [pid 1] AH00163: Apache/2.4.25 (Debian) PHP/7.2.10 configured -- resuming normal operations
php_1    | [Wed Sep 26 20:31:58.784492 2018] [core:notice] [pid 1] AH00094: Command line: 'apache2 -D FOREGROUND'
httpd_1  | [INFO] Changing group 'daemon' gid to: 1000
httpd_1  | [INFO] Setting container timezone to: Europe/Berlin
httpd_1  | [INFO] Docker date set to: Wed Sep 26 22:32:00 CEST 2018
httpd_1  | [INFO] $DOCKER_LOGS disabled. Logging errors and access to log files inside container.
httpd_1  | [INFO] PHP 5.2 compatibility mode: Disabled
httpd_1  | [INFO] PHP-FPM: Enabled
httpd_1  | [INFO] PHP-FPM: Server address: php
httpd_1  | [INFO] PHP-FPM: Server port: 9000
httpd_1  | [INFO] PHP-FPM: Timeout: 180
httpd_1  | [INFO] Main vhost: Enabled
httpd_1  | [INFO] Main vhost: Setting SSL type to: http and https
httpd_1  | [INFO] Main vhost: Enable automatic generation of SSL certificates
httpd_1  | [INFO] Main vhost: SSL CN: localhost,*.localhost,devilbox,*.devilbox
httpd_1  | [INFO] $MAIN_VHOST_DOCROOT not specified. Keeping default: htdocs
httpd_1  | [INFO] $MAIN_VHOST_TPL not specified. Keeping default: cfg
httpd_1  | [INFO] Main vhost: Enabling httpd status page
httpd_1  | [INFO] Main vhost: Changing status page alias to: /devilbox-httpd-status
httpd_1  | [INFO] Mass vhost: Enabled
httpd_1  | [INFO] Mass vhost: Setting SSL type to: http and https
httpd_1  | [INFO] Mass vhost: Enable automatic generation of SSL certificates
httpd_1  | [INFO] Mass vhost: changing tld to: .loc
httpd_1  | [INFO] Mass vhost: changing document root to: htdocs
httpd_1  | [INFO] Mass vhost: changing template dir to: .devilbox
httpd_1  | [INFO] Disabling PHP 5.2 compat mode
httpd_1  | [INFO] vhost-gen: no customized template found
httpd_1  | vhostgen: [2018-09-26 22:32:00] Adding: localhost
httpd_1  | $ openssl req -newkey rsa:2048 -nodes -extensions v3_req -keyout /etc/httpd/cert/main/localhost.key -subj '/C=DE/ST=Berlin/L=Berlin/O=Devilbox/OU=Devilbox/CN=localhost/emailAddress=admin@localhost' -out /etc/httpd/cert/main/localhost.csr
httpd_1  | $ openssl x509 -req -extensions v3_req -extfile <(printf '[ req ]\nreq_extensions = v3_req\n[ v3_req ]\nsubjectAltName=DNS.1:localhost,DNS.2:localhost,DNS.2:*.localhost,DNS.2:devilbox,DNS.2:*.devilbox\n') -days 3650 -in /etc/httpd/cert/main/localhost.csr -CA /ca/devilbox-ca.crt -CAkey /ca/devilbox-ca.key -CAcreateserial -out /etc/httpd/cert/main/localhost.crt
httpd_1  | Certificate:
httpd_1  |     Data:
httpd_1  |         Version: 3 (0x2)
httpd_1  |         Serial Number:
httpd_1  |             be:96:83:9d:cb:d9:2e:be
httpd_1  |     Signature Algorithm: sha256WithRSAEncryption
httpd_1  |         Issuer: C=DE, ST=Berlin, L=Berlin, O=Devilbox, OU=Devilbox, CN=Devilbox Root CA/emailAddress=cytopia@devilbox.org/dnQualifier=KqxjBj8EDUAdEyjXjUy+tmtvChs=
httpd_1  |         Validity
httpd_1  |             Not Before: Sep 26 20:32:00 2018 GMT
httpd_1  |             Not After : Sep 23 20:32:00 2028 GMT
httpd_1  |         Subject: C=DE, ST=Berlin, L=Berlin, O=Devilbox, OU=Devilbox, CN=localhost/emailAddress=admin@localhost
httpd_1  |         Subject Public Key Info:
httpd_1  |             Public Key Algorithm: rsaEncryption
httpd_1  |                 Public-Key: (2048 bit)
httpd_1  |                 Modulus:
httpd_1  |                     00:bc:17:e7:2b:6b:9a:42:25:b7:fe:be:99:67:e4:
httpd_1  |                     c8:c4:20:0d:ee:6e:f8:9c:a0:2f:81:cb:ae:85:39:
httpd_1  |                     92:91:cd:8b:9f:c5:dc:c6:2a:f5:68:4c:0b:c6:78:
httpd_1  |                     7e:bd:59:43:d2:df:29:5d:42:83:cb:fd:4f:5c:96:
httpd_1  |                     dc:3f:0d:9a:6f:26:17:32:5e:b1:79:8a:4e:3e:49:
httpd_1  |                     5e:e7:2e:1d:99:a8:5c:ff:9b:e1:fb:53:12:c8:ea:
httpd_1  |                     fa:90:b9:0e:46:ff:41:4f:e4:da:83:22:35:54:57:
httpd_1  |                     d8:d5:e6:1e:dd:7c:61:b5:8d:91:d0:4f:f6:17:73:
httpd_1  |                     80:8a:c1:90:bd:05:19:cd:d3:b2:78:5e:87:aa:39:
httpd_1  |                     83:bd:45:5f:6b:65:97:af:9d:38:fe:bf:6a:b2:54:
httpd_1  |                     3b:ea:47:fa:58:70:90:64:15:54:08:79:8a:21:f7:
httpd_1  |                     f2:46:f7:a2:9a:b9:7f:b4:37:76:cd:17:73:47:1b:
httpd_1  |                     bd:3a:b3:c9:1c:19:da:51:f2:ba:41:ea:46:0e:1b:
httpd_1  |                     68:f8:f0:00:8c:c7:9c:b2:15:16:2d:a7:c2:ca:17:
httpd_1  |                     b6:07:1b:ec:99:68:3b:e7:60:e2:57:a9:a2:e6:ba:
httpd_1  |                     5c:13:8f:11:a5:49:1c:e5:fc:b2:df:d4:fe:c5:21:
httpd_1  |                     74:5e:49:2c:dd:3b:0e:9a:1a:3f:03:d8:38:8f:51:
httpd_1  |                     71:6b
httpd_1  |                 Exponent: 65537 (0x10001)
httpd_1  |         X509v3 extensions:
httpd_1  |             X509v3 Subject Alternative Name: 
httpd_1  |                 DNS:localhost, DNS:localhost, DNS:*.localhost, DNS:devilbox, DNS:*.devilbox
httpd_1  |     Signature Algorithm: sha256WithRSAEncryption
httpd_1  |          66:89:62:52:16:c2:16:fc:3c:c8:fe:3b:1e:e0:53:67:00:cb:
httpd_1  |          51:33:b3:28:04:be:0c:be:bb:6c:7f:f9:ae:0e:d9:95:97:f0:
httpd_1  |          5d:e1:1f:43:d7:6f:7c:cc:71:e2:bf:16:eb:df:f9:85:b4:bb:
httpd_1  |          d9:e9:6c:28:d2:3d:c5:22:f7:a4:e1:8d:3a:d9:40:ba:54:37:
httpd_1  |          88:da:03:b0:0e:d1:0d:de:85:3f:c3:2c:a8:f9:8b:92:cb:45:
httpd_1  |          82:86:c9:a2:40:5b:75:a4:e1:4b:a4:81:2d:87:c5:be:96:74:
httpd_1  |          e5:08:4c:77:17:d5:48:62:dc:d2:4d:b8:d5:6c:17:58:64:ff:
httpd_1  |          63:cb:3a:30:d4:1a:e3:86:31:e7:c4:57:50:f8:15:c9:9f:c1:
httpd_1  |          83:f0:89:da:46:b2:b4:b0:5b:ef:61:6c:37:be:bf:3b:dd:e2:
httpd_1  |          3e:58:6d:9e:d0:08:e7:f2:92:01:1e:36:67:ac:ba:ed:22:18:
httpd_1  |          c0:eb:2f:22:f9:9a:7c:57:83:9b:38:ed:0e:05:23:cc:77:2a:
httpd_1  |          71:a0:11:c8:9a:e1:f6:ee:63:bf:39:56:08:34:2d:51:67:46:
httpd_1  |          c0:02:c6:20:9c:a9:f6:4b:14:98:3f:30:83:2f:08:fd:15:64:
httpd_1  |          e2:f3:51:c7:68:2b:3d:fb:10:27:0e:28:5c:b9:1c:45:04:17:
httpd_1  |          bb:7a:c4:7f
httpd_1  | /etc/httpd/cert/main/localhost.crt: OK
httpd_1  | [INFO] Starting supervisord: 3.0
httpd_1  | 2018-09-26 22:32:00,648 CRIT Set uid to user 0
httpd_1  | 2018-09-26 22:32:00,649 INFO supervisord started with pid 1
httpd_1  | 2018-09-26 22:32:01,651 INFO spawned: 'httpd' with pid 204
httpd_1  | 2018-09-26 22:32:01,654 INFO spawned: 'watcherd' with pid 205
httpd_1  | [Wed Sep 26 22:32:01.683170 2018] [mpm_event:notice] [pid 204:tid 140670146242432] AH00489: Apache/2.4.34 (Unix) OpenSSL/1.0.2l configured -- resuming normal operations
httpd_1  | [Wed Sep 26 22:32:01.683486 2018] [core:notice] [pid 204:tid 140670146242432] AH00094: Command line: 'httpd -D FOREGROUND'
httpd_1  | 2018-09-26 22:32:02,683 INFO success: httpd entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
httpd_1  | 2018-09-26 22:32:02,684 INFO success: watcherd entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
httpd_1  | watcherd: [2018-09-26 22:32:04] Starting daemon.
httpd_1  | watcherd: [2018-09-26 22:32:04] Using bash loop to watch for changes.

**Comment by cytopia** [comment]
I did the exact steps you have described and it works like a charm on my machine (Debian).

What bugs me a bit is the docker-compose output of the php container:
```
php_1 | AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.16.238.10. Set the 'ServerName' directive globally to suppress this message
php_1 | [Wed Sep 26 20:31:58.784451 2018] [mpm_prefork:notice] [pid 1] AH00163: Apache/2.4.25 (Debian) PHP/7.2.10 configured -- resuming normal operations
php_1 | [Wed Sep 26 20:31:58.784492 2018] [core:notice] [pid 1] AH00094: Command line: 'apache2 -D FOREGROUND'
```
It looks like you have a totally wrong php container. This one wants to start Apache, but there should not be an Apache server inside the PHP container.

Are you on the latest **master** branch of the Devilbox?

**Comment by innobrig** [comment]
Yes, I'm on master, see git output:

    root@rxg:/usr/local/docker/devilbox# git branch
    * master
    root@rxg:/usr/local/docker/devilbox# git log
    commit 35a5a38a9a20182174a7bb60a79a55aecbfc2f82 (HEAD -> master, origin/master, origin/HEAD)
    Merge: c84235c6 dd4eff2e
    Author: cytopia <cytopia@everythingcli.org>
    Date:   Fri Sep 14 14:33:09 2018 +0200
        Merge pull request #379 from cytopia/update-php-images
        Refs #378: Add tool: Deployer

    commit dd4eff2efde737f5540fc867dabd12ff8f61a160
    Author: cytopia <cytopia@everythingcli.org> 
    Date:   Fri Sep 14 08:58:16 2018 +0200
        Refs #378: Add tool: Deployer

Please find attached my .env file ...

[env.zip](https://github.com/cytopia/devilbox/files/2423641/env.zip)

**Comment by cytopia** [comment]
Do you have a custom `docker-compose.override.yml` in place?

**Comment by innobrig** [comment]
No I don't. This is literally the checked-out git master branch with the the .env I sent you ... no other/custom changes were applied.

**Comment by cytopia** [comment]
Can you `./shell.sh` into the php container and do a `php -v` and paste everything here. (all of the output)

**Comment by innobrig** [comment]
Sorry for the late reply, I was away all weekend. 

OK, something changed on the master branch which seems to have fixed things. I left my setup untouched and did a 'git pull' and this showed me the following: 

    From https://github.com/cytopia/devilbox
       35a5a38a..ad66bdc9  master               -> origin/master
     + d3a56490...956a1210 docker-volumes       -> origin/docker-volumes  (forced update)
     * [new branch]        update-php-container -> origin/update-php-container
     Updating 35a5a38a..ad66bdc9
    Fast-forward
     .devilbox/www/config.php              |  2 +-
     .github/ISSUE_TEMPLATE/bug_report.md  | 57 ++++++++++++++++++++++++++++++++++++++++++++-------------
     .github/ISSUE_TEMPLATE/question.md    |  2 +-
     README.md                             |  2 +-
     docker-compose.yml                    |  2 +-
     docs/configuration-files/env-file.rst | 10 +++++-----
     env-example                           |  2 +-

After this I did a 

    docker-compose up httpd php

and it pulled down a bunch of new files/container images and now it works again. So I guess we can consider this resolved. Thank you.

**Comment by cytopia** [comment]
OK, Enjoy using it.

**Comment by pigraphic** [comment]
Hi, I encountered the same issue and I solved it not starting postfix setting PHP_MAIL_CATCH_ALL=0 in my .env file.
I hope this could be helpful to anyone reaching this page looking for a solution. 

php_1    | root $ postconf -e 'strict_mailbox_ownership=no'
php_1    | root $ postconf -e 'inet_protocols=ipv4'
php_1    | root $ postconf -e 'myhostname=localhost'
php_1    | root $ postconf -e 'virtual_alias_maps=pcre:/etc/postfix/virtual'
php_1    | root $ echo '/.*@.*/ devilbox' >> /etc/postfix/virtual
php_1    | root $ newaliases
php_1    | newaliases: fatal: /etc/mailname: file has 47 hard links
devilbox_php_1 exited with code 75
