### ISSUE TITLE
About creating volumes for all versions of all databases in docker-volume branch

### ISSUE THREAD

**Issue by bgultekin** [cytopia/devilbox#388]
#### ISSUE TYPE
 - Feature request

#### SUMMARY
Hi , I am using docker-volume branch so I think devilbox creates volumes for all versions of all databases. Probably they don't keep any significant place on harddisk when they are not used but is this necessary? Wouldn't be better if it just creates for selected versions?

#### Goal
Fast setup, start. Getting rid of unnecessary volumes.

**Comment by cytopia** [comment]
@bgultekin yes that was my initial goal, however the volume section in a docker-compose.yml file does not support variables, so I have to add everything by default to make sure whatever version you choose, there is a volume available by default.

If I don't do that, the Devilbox won't start

**Comment by bgultekin** [comment]
Ok thanks for the information.
