### ISSUE TITLE
Is it possible to adjust worker_processes or worker_connections ?

### ISSUE THREAD

**Issue by drupalshift** [cytopia/devilbox#393]
Hi there, 

Was wondering is it possible to adjust this numbers?
```
worker_connections
worker_processes
```
I want to test some Redis transactions with a lot of simultaneous requests I get an error on worker_connections, I tired cfg folder but doesn't work

**Comment by drupalshift** [comment]
Yes I mean Nginx configs for worker_processes and worker_connections

**Comment by cytopia** [comment]
@drupalshift I have now set `workder_processes` to `auto`, which will then make use of all of your local CPU cores (a bit of a delay though on my side xD).

* PR: https://github.com/cytopia/devilbox/pull/520

---

Can you explain the need to change `worker_connections` and what your currently preferred setting would be?

**Comment by cytopia** [comment]
@drupalshift PR is open and will be merged as soon as CI tests pass: https://github.com/cytopia/devilbox/pull/521

## New environment variables

| Variable | Type | Default | Description |
|----------|------|---------|-------------|
| HTTPD_NGINX_WORKER_CONNECTIONS | int    | `1024`    | [worker_connections](https://nginx.org/en/docs/ngx_core_module.html#worker_connections) |
| HTTPD_NGINX_WORKER_PROCESSES   | int or `auto` | `auto`  | [worker_processes](https://nginx.org/en/docs/ngx_core_module.html#worker_processes) |
