### ISSUE TITLE
How config code sniffer in phpstorm

### ISSUE THREAD

**Issue by krllgranin** [cytopia/devilbox#398]
#### ISSUE TYPE

 - Question

#### SUMMARY
How config code sniffer in phpstorm?
Cli interpreter settings https://s.mail.ru/8UmQ/jTnbmykF1
Code sniffer settings https://s.mail.ru/JQEm/MHBTVoHJd

**Comment by cytopia** [comment]
The codesniffer binary resides inside the Docker container for cli usage. If you want to configure that with your IDE (on your host operating system), I suppose you also need to install codesniffer on the host and point your IDE to that path (on the host)

**Comment by krllgranin** [comment]
node js and npm also install on the host, if I want use "Run/Debug configuration" https://s.mail.ru/Ey7c/Baa1mCJwk in the phpstorm?

**Comment by cytopia** [comment]
Basically everything you want to run on the host, must also be present on the host.

The Devilbox already ships a lot of development binaries by default. They can be used if you're going to do that from the cli inside the container. (e.g.: `npm install`, `drush dl`, `git pull`). If however you want to leave all those actions to your IDE, then they must exist on your host operating system as well.

However, I heard that PHPStorm has pretty good Docker support and maybe it has a way to use binaries from inside a Container, but unfortunately this is beyond my knowledge (pure vim user here).

If you want to dig into this topic, I would suggest asking those questions on a PHPStorm forum, people will most likely give you a much more informative answer regarding what is possible with PHPStorm.

**Comment by krllgranin** [comment]
Thanks for answers.
