### ISSUE TITLE
Add support to ctop

### ISSUE THREAD

**Issue by llaville** [cytopia/devilbox#403]
#### ISSUE TYPE

 - Feature request

#### SUMMARY

Add support to [ctop](https://github.com/bcicen/ctop) tools. Top-like interface for container metrics.

#### Goal

`ctop` provides a concise and condensed overview of real-time metrics for multiple containers
as well as an single container view for inspecting a specific container.

Easy to explore containers. ALA `tig` for GIT

**Comment by cytopia** [comment]
@llaville I suppose you will have to run this on the host os in order to see the running container. I guess it would not make much sense to have this tool inside the container or?

**Comment by llaville** [comment]
Yes you're right in standard use case. But if you run Docker inside a Docker container !
BTW, I've discover this tool recently, and it was also an occasion to share it !

**Comment by cytopia** [comment]
Running ctop inside the PHP container only displays this:

![screenshot 2018-10-26 17-49-10 selection](https://user-images.githubusercontent.com/12533999/47577874-3c756780-d948-11e8-9b42-5271a5f70fd8.png)

> But if you run Docker inside a Docker container !

This might be true, but the Devilbox is not mounting the docker socket to allow Docker in Docker. This would also introduce in a big security risk: https://stackoverflow.com/questions/40844197/what-is-the-docker-security-risk-of-var-run-docker-sock

**Comment by llaville** [comment]
You right. For security reason, we cannot adopt this tool. I'll close this request.
