### ISSUE TITLE
does devilbox have any easy way to use letsencrypt ?

### ISSUE THREAD

**Issue by aiai982** [cytopia/devilbox#405]
i use devilobx on our production platform.

**Comment by cytopia** [comment]
At the moment there are no letsencrypt scripts inside the PHP images.
Can you be more specific what exactly you want do use/do and what you consider *easy*?

**Comment by aiai982** [comment]
> At the moment there are no letsencrypt scripts inside the PHP images.
> Can you be more specific what exactly you want do use/do and what you consider _easy_?

i want our company official site to use https with a simple way.
but now i consider that nginx, letscrypt in the docker container as a reverse proxy in front of devilbox.

**Comment by cytopia** [comment]
> but now i consider that nginx, letscrypt in the docker container as a reverse proxy in front of devilbox.

A reverse Proxy might be a good choice to securely serve Devilbox to the outside. Joomla has done something similar described here: https://docs.joomla.org/PR_Testing_Platform

**Comment by cytopia** [comment]
@aiai982 also have a look here for general discussions about a productionized setup: https://github.com/cytopia/devilbox/issues/262

**Comment by bigxu** [comment]
@aiai982 
https://github.com/bigxu/nginx-acme

**Comment by aiai982** [comment]
> @aiai982
> https://github.com/bigxu/nginx-acme

thank you @bigxu @cytopia . perfect well.

**Comment by cytopia** [comment]
@bigxu I will add this to the documentation: https://github.com/cytopia/devilbox/pull/526

**Comment by cytopia** [comment]
Documentation available here: https://devilbox.readthedocs.io/en/latest/third-party/nginx-acme.html

Feel free to enhance it with more details.
