### ISSUE TITLE
apache2.4 redirect loop

### ISSUE THREAD

**Issue by syst0m** [cytopia/devilbox#418]
### ISSUE TYPE
 - Bug Report

### Checklist
.env - https://pastebin.com/AcMGMPiM
docker-compose.override.yml - https://pastebin.com/cpAiDsDN
cfg/apache2.4/devilbox-custom.conf - https://pastebin.com/17Krnea0
cfg/php-fpm-5.6/devilbox-fpm.conf - https://pastebin.com/DZDf2Ljq
docker-compose logs - https://pastebin.com/8vrE4y6b

### OS / ENVIRONMENT
1. Host operating system and version: macOS Mojave v10.14.1 (18B75)
2. (Windows) Native Docker or Docker Toolbox: 
3. Docker version: 18.06.1-ce-mac73 (26764)
4. Docker Compose version: 1.22.0, build f46880f
5. (Linux) Is SELinux enabled?:
6. What git commit hash are you on?: c3af49f401eb00c5deb857240390364ef6499eab

### SUMMARY
Doing a GET request on base URL sends apache into a 302 redirect loop chain.

### STEPS TO REPRODUCE
Fetching the base URL from the browser or with curl triggers a redirect loop.
Using an .htaccess file for the apache rewrites: https://pastebin.com/FcRzFK4C

### EXPECTED BEHAVIOUR
HTTP 200

### ACTUAL BEHAVIOUR
HTTP 302 loop

#### Start command
```
$ docker-compose up...
```

#### File and user permissions (Linux & MacOS)

```
502 ```

<!-- File permissions of the Devilbox directory -->
```
drwxr-xr-x```

```
drwxr-xr-x```

**Comment by cytopia** [comment]
@syst0m thank you for this well written bug report. I will try to reproduce your setup and figure out why this is happening

**Comment by cytopia** [comment]
@syst0m  I tried to reproduce your environment.

* `.htaccess` file in place
* custom Apache configuration in place
* vhost `cytopia.loc`

I've added an `index.php` with the following content:
```php
<?php
echo 'hello world';
```

When I access the url it works all fine:
```bash
$ curl -I  http://cytopia.loc
HTTP/1.1 200 OK
Date: Sat, 17 Nov 2018 15:27:21 GMT
Server: Apache/2.4.34 (Unix) OpenSSL/1.0.2l
X-Powered-By: PHP/5.6.38
Content-Type: text/html; charset=UTF-8
```

Also for index.php directly:
```bash
$ curl -I  http://cytopia.loc/index.php
HTTP/1.1 200 OK
Date: Sat, 17 Nov 2018 15:27:21 GMT
Server: Apache/2.4.34 (Unix) OpenSSL/1.0.2l
X-Powered-By: PHP/5.6.38
Content-Type: text/html; charset=UTF-8
```


Can you post the exact GET command and maybe also the `index.php` file or framework you have in place

**Comment by syst0m** [comment]
Hi,

thanks for taking the time to test it, I really appreciate it.
I think tha the issue on my side is caused by the PHP application.
Seems that when it can't connect to the database, it enters a 301 loop.

Thanks so much!
