### ISSUE TITLE
PWA Requirement / http2 

### ISSUE THREAD

**Issue by wolfwahl** [cytopia/devilbox#431]
Hi,

could you provide a sample on how to configure devilbox to serve request on apache and nginx via http/2 ?

tnx!

**Comment by science695** [comment]
Hello @wolfwahl,

Currently devilbox is setup to use nginx or apache, not both.

However, the docs have a good explaination about where you can choose which web server to run:
https://devilbox.readthedocs.io/en/latest/getting-started/change-container-versions.html?highlight=nginx#change-web-server-version

**Comment by science695** [comment]
I'm sorry if I misunderstood you, I wasn't fully sure what you were asking for.

Okay, you are asking about http/2.

I am not super familiar with http/2 configuration, but I believe to do that you need to change the virtualhost configuration in nginx or apache.

WIth devilbox, you can customize the generated virtual hosts. Here is the document page for that:
https://devilbox.readthedocs.io/en/latest/vhost-gen/customize-all-virtual-hosts-globally.html?highlight=nginx

**Comment by cytopia** [comment]
@wolfwahl I myself do not have any experience with http2 yet. Do you have some example configurations for nginx/apache as well as what modules are required to make it work?

**Comment by wolfwahl** [comment]
@cytopia maybe that would provide a good start?

https://geekflare.com/http2-implementation-apache-nginx/

Would really appreciate an (maybe optional) implementation of http2

**Comment by daancart2quote** [comment]
@cytopia @wolfwahl 
I added the following lines to `devilbox/cfg/apache-2.4/devilbox-custom.conf`
```
LoadModule http2_module modules/mod_http2.so
Protocols h2 h2c http/1.1
ProtocolsHonorOrder Off
```
(The last one isn't required, but I like it)

Now it just works :) (Only on HTTPS, as required by HTTP2)

**Comment by wolfwahl** [comment]
@daancart2quote great! Cheers mate!

@cytopia -> Browser -> Developer Tools -> Networking -> enable Protocol (Chrome: right click Table-Header)

**Comment by cytopia** [comment]
@wolfwahl Awesome!

I've also tried it with Nginx its as simple as:

```
    listen       443 ssl http2 default_server;
```

However when editing vhost-gen configs this will be added to http and https configs and then http will stop working. I will built this into [vhost-gen](https://github.com/devilbox/vhost-gen) so it will be correctly configured depending on SSL or not

**Comment by wolfwahl** [comment]
@cytopia This is not working for me - results in the same error I run in during my first attempt.

Added your line to nginx stable: 

2019/01/05 14:31:15 [emerg] 237#237: "listen" directive is not allowed here in /etc/httpd-custom.d/devilbox-custom.conf:18
httpd_1  | nginx: [emerg] "listen" directive is not allowed here in /etc/httpd-custom.d/devilbox-custom.conf:18
httpd_1  | watcherd: [2019-01-05 14:31:15] [ERR] TRIGGER failed:    nginx -s stop
httpd_1  | watcherd: [2019-01-05 14:31:15] Using bash loop to watch for changes.
httpd_1  | 2019-01-05 14:31:18,084 INFO spawned: 'httpd' with pid 264
httpd_1  | 2019/01/05 14:31:18 [emerg] 264#264: "listen" directive is not allowed here in /etc/httpd-custom.d/devilbox-custom.conf:18
httpd_1  | nginx: [emerg] "listen" directive is not allowed here in /etc/httpd-custom.d/devilbox-custom.conf:18
httpd_1  | 2019-01-05 14:31:18,091 INFO exited: httpd (exit status 1; not expected)
httpd_1  | 2019-01-05 14:31:22,097 INFO spawned: 'httpd' with pid 297

...and looping

**Comment by cytopia** [comment]
@wolfwahl this setting does not go into `cfg/nginx-stable|mainline` but rather as a vhost-gen customization. See here for example: https://devilbox.readthedocs.io/en/latest/vhost-gen/example-add-subdomains.html#nginx

**Comment by wolfwahl** [comment]
@cytopia cheers! Got it working - had to specify the server_name also.

Still get an error(?), but it serves h2 - so I'm fine.

httpd_1  | nginx: [emerg] a duplicate default server for 0.0.0.0:443 in /etc/httpd/vhost.d/yaspi.conf:3
httpd_1  | watcherd: [2019-01-06 09:34:01] [ERR] TRIGGER failed:    nginx -s stop
httpd_1  | watcherd: [2019-01-06 09:34:01] Using bash loop to watch for changes.

**Comment by cytopia** [comment]
My bad, the example was shown for the **default** server and there can only always be one (which is used for the devilbox intranet on localhost itself). For all other vhosts, just omit the `default_server`:
```
    listen       443 ssl http2;
```

**Comment by cytopia** [comment]
@wolfwahl I've now made it the default for all SSL connections. Checkout the open PR: https://github.com/cytopia/devilbox/pull/462

It does not work on Apache 2.2 though (too old).

Also keep in mind that vhost-gen templates in `cfg/vhost-gen/*` have been adjusted, so if you have already customized templates in place (per project or globally), ensure to diff and update them accordingly.
