### ISSUE TITLE
Blackfire integration seems incomplete?

### ISSUE THREAD

**Issue by runedalton** [cytopia/devilbox#451]
#### ISSUE TYPE

 - Question

#### SUMMARY
Support for Blackfire seems to be incomplete. After adding Blackfire through the instructions, the profiling returns an error "Probe not found, invalid signature".

It seems like Blackfire PHP is not being installed? If I install it - along with the agent - manually, nothing works either.

Are there any of these steps which are missing in the configuration, so Blackfire starts correctly when issuing "docker-compose up"?
* https://blackfire.io/docs/integrations/docker
* https://blackfire.io/docs/up-and-running/installation
* https://blackfire.io/docs/book/06-installation

#### Goal
To be able to run Blackfire profiling on my local Devilbox Docker environment.

Thank you in advance.

**Comment by cytopia** [comment]
> It seems like Blackfire PHP is not being installed? If I install it - along with the agent - manually, nothing works either.

Can you provide the **exact** steps you have done to install it manually.

**Comment by runedalton** [comment]
Thanks for replying.

The steps are as follows:

1. Copied **compose/docker-compose.override.yml-blackfire** to **docker-compose.override.yml** in the Devilbox root.
2. Added the following to the **.env** file for my Devilbox root:
```
BLACKFIRE_SERVER_ID=myid
BLACKFIRE_SERVER_TOKEN=mytoken
#BLACKFIRE_SERVER=1.12.0
#BLACKFIRE_SERVER=1.13.0
#BLACKFIRE_SERVER=1.14.0
#BLACKFIRE_SERVER=1.14.1
#BLACKFIRE_SERVER=1.15.0
#BLACKFIRE_SERVER=1.16.0
#BLACKFIRE_SERVER=1.17.0
#BLACKFIRE_SERVER=1.17.1
#BLACKFIRE_SERVER=1.18.0
BLACKFIRE_SERVER=latest
```
3. Restarted Docker and fired up Devilbox with the following command: **docker-compose up -d bind httpd php mysql memcd blackfire**
4. Installed the Blackfire Chrome extension
5. Navigated to my localhost Devilbox project, and clicked the red "Profile" button in the Blackfire extension.
6. Received the following Blackfire error: "Probe not found, invalid signature."

Please let me know if there's anything else you need in order to debug it. Thank you.

**Comment by cytopia** [comment]
@runedalton can you check out the `blackfire` branch and see if it now works: https://github.com/cytopia/devilbox/pull/457

**Comment by sonicviz** [comment]
I'm getting a variant of this:
Are you authorized to profile this page? Probe not found, invalid signature (HTTP 200)

Blackfire container looks aok, keys are set etc

**Comment by llaville** [comment]
@sonicviz Hello. I've the same issue on PHP 7.1, but I found how to solve it. 
Let me try to see if it's also possible with PHP 7.2 and 7.3, and I'll publish my solution.

**Comment by sonicviz** [comment]
Great, look forward to it. ty!

**Comment by llaville** [comment]
Ok, here is my solution to follow - hope it will help ! 

TESTed with :

* devilbox/php-fpm:7.1-work-0.71
* devilbox/php-fpm:7.2-work-0.71
* devilbox/php-fpm:7.3-work-0.71

Following official recommandations at https://devilbox.readthedocs.io/en/latest/custom-container/enable-blackfire.html
Be sure to remove `blackfire` from **PHP_MODULES_DISABLE** entry in your `.env` file.

First check versions available : 
```
devilbox@php-7.3.1 in /shared/httpd $ blackfire-agent -v
blackfire-agent 1.22.0 linux amd64 gc 2019-01-10T15:10:13+0000
```

```
devilbox@php-7.3.1 in /shared/httpd $  php --ri blackfire
Extension 'blackfire' not present.
```
With such response, you must add `blackfire.ini` file in devilbox `cfg/cfg/php-ini-7.X` (X is your PHP minor version) with such content 

NOTE: I've activated debug verbosity level to see what happens (in case of problem)

```
[blackfire]
extension=blackfire.so
; On Windows use the following configuration:
; extension=php_blackfire.dll


; Sets the socket where the agent is listening.
; Possible value can be a unix socket or a TCP address.
; Defaults to unix:///var/run/blackfire/agent.sock on Linux,
; unix:///usr/local/var/run/blackfire-agent.sock on MacOSX,
; and to tcp://127.0.0.1:8307 on Windows.
;blackfire.agent_socket = unix:///var/run/blackfire/agent.sock

blackfire.agent_timeout = 0.25

; Log verbosity level (4: debug, 3: info, 2: warning, 1: error)
blackfire.log_level = 4

; Log file (STDERR by default)
blackfire.log_file = /tmp/blackfire.log

; Sets fine-grained configuration for Probe.
; This should be left blank in most cases. For most installs,
; the server credentials should only be set in the agent.
;blackfire.server_id =

; Sets fine-grained configuration for Probe.
; This should be left blank in most cases. For most installs,
; the server credentials should only be set in the agent.
;blackfire.server_token =
```
WARNING: Don't forget to restart php container 

Then you should have something like 

```
devilbox@php-7.3.1 in /shared/httpd $ php --ri blackfire
Sun Jan 13 10:15:59 2019 (2060): [Info] oci8 extensions is not loaded, Blackfire SQL analyzer will be disabled for oci SQL queries
Sun Jan 13 10:15:59 2019 (2060): [Warning] Extension 'Xdebug' can conflict with Blackfire. It is recommended to disable it

blackfire

Blackfire => enabled
Blackfire => 1.24.2~linux-x64-non_zts73
Timing measurement => cgt
Sessions support => enabled
Num of CPU => 4
Profiling heap memory => 0 Kb
Main instance trigger mode => HTTP header triggered
Main instance => disabled

Directive => Local Value => Master Value
blackfire.agent_socket => unix:///var/run/blackfire/agent.sock => unix:///var/run/blackfire/agent.sock
blackfire.agent_timeout => 0.25 => 0.25
blackfire.env_id => no value => no value
blackfire.env_token => no value => no value
blackfire.log_level => 4 => 4
blackfire.log_file => /tmp/blackfire.log => /tmp/blackfire.log
blackfire.server_id => no value => no value
blackfire.server_token => no value => no value


Blackfire developed by Blackfire
```

Configure your agent with such command 
```
devilbox@php-7.3.1 in /shared/httpd $ sudo blackfire-agent -register
```
Then don'f forget to start or restart your agent with command
```
devilbox@php-7.3.1 in /shared/httpd $ sudo /etc/init.d/blackfire-agent start
```

And you'll be able to run blackfire profiling in CLI mode or even HTTP if you've install Chrome/Firefox Companion

**Comment by sonicviz** [comment]
Awesome, ty!

Q: -> ; extension=php_blackfire.dll

I'm on Win 10, so do I need to download the dll from blackfire site, as you can't seem to install it via normal sudo method?

**Comment by llaville** [comment]
No. You don't have to use the DLL, because you are on docker env and not on native windows platform. Even if you used it on win10.

**Comment by cytopia** [comment]
Hi everybody,

I've re-opened this issue as it wasn't fully clear how to enable it, as well as documentation is slightly wrong.

#### Enable blackfire

1. To enable blackfire, you must ensure to remove it from `PHP_MODULES_DISABLE`
2. Additionally you need to add it to `PHP_MODULES_ENABLE=blackfire`

No custom ini configuratoin is required, this is currently due to wrong configuration. I will fix it so that only step 2 will be needed (step 1 is currently just a misconfiguration).

#### Configure blackfire

Thanks to @llaville :

1. `sudo blackfire-agent -register`
2 `sudo /etc/init.d/blackfire-agent start`

Now the next step would be to figure out, how to headless configure it without human interaction. Is there a way to run `blackfire-agent -register` that does NOT prompt for input, but reads its values from a config file?

If this would work, I can add a script, that does everything automatically via startup and only `docker-compose up` will be left todo. This will be done via the autostart feature: https://devilbox.readthedocs.io/en/latest/autostart/custom-scripts-per-php-version.html#custom-scripts-per-php-version

**Comment by cytopia** [comment]
> It might be good to also have config automatically switch between XDebug and Blackfire (if possible) as it seems they are incompatible.

This is something that will need to be added to the documentation, as it would be impossible for me to figure out which of all the available modules will conflict with each other. Also it's better not to do any black magic in the background that the user is not aware of. People might spend hours trying to figure out why xdebug has been disabled, by enabling blackfire (of also with other incompatible modules).

**Comment by sonicviz** [comment]
I've tried PHP_MODULES_ENABLE=blackfire in .env and it still doesn't work.

php -m doesn't show it as a module. 
blackfire-agent -register also says I'm already registered aok, and blackfire-agent -d shows the config alright. 

I'm a little confused now. Maybe I'll wait till you redo the docs.

**Comment by cytopia** [comment]
@sonicviz are you on the latest Devilbox master? I've tried it just now with PHP 7.2. Ensure that blackfire is not disabled in `PHP_MODULES_DISABLE` and remove any custom `*.ini` files that mention blackfire.

**Comment by sonicviz** [comment]
Ah, not on the latest master but I changed php image to image: 'devilbox/php-fpm:${PHP_SERVER}-work-0.66' 

So must be some other things as well. I'll pull it down tomorrow and retest it, late here now.

**Comment by cytopia** [comment]
Current latest is `    image: devilbox/php-fpm:${PHP_SERVER}-work-0.71`

**Comment by sonicviz** [comment]
let me try that quickly

**Comment by sonicviz** [comment]
I just keep getting " Are you authorized to profile this page? Probe not found, invalid signature (HTTP 200)"

**Comment by sonicviz** [comment]
blackfire-agent -d showed it was set up correctly. 

I even tested reauthorizing manually with blackfire-agent -register and it was successful.

**Comment by cytopia** [comment]
What about `php -m | grep -i blackfire` inside the PHP container?

**Comment by sonicviz** [comment]
Nothing on that. 

I'm using DockStation, added the following to my docker-compose.yml

  # ------------------------------------------------------------
  # Blackfire
  # ------------------------------------------------------------
  blackfire:
    image: blackfire/blackfire:${BLACKFIRE:-latest}
    hostname: blackfire
    environment:
      - BLACKFIRE_SERVER_ID=${BLACKFIRE_SERVER_ID:-id}
      - BLACKFIRE_SERVER_TOKEN=${BLACKFIRE_SERVER_TOKEN:-token}
    networks:
      app_net:
        ipv4_address: 172.16.238.200
    depends_on:
      - bind
      - php
      - httpd 

Container shows up an running, but not showing on the Devilbox console.

**Comment by cytopia** [comment]
> Nothing on that.

Then your `.env` configuration is wrong. Can you attach it here.

> I'm using DockStation, added the following to my docker-compose.yml

This one I don't know

**Comment by sonicviz** [comment]
https://github.com/DockStation/dockstation

Copy of env with redacted keys
[envfile.txt](https://github.com/cytopia/devilbox/files/2753204/envfile.txt)

**Comment by cytopia** [comment]
Your `.env` is fine. If `php -m | grep -i blackfire` (executed inside the PHP container) is not showing anything, then something else is wrong with your setup. Can you show me the output of `docker ps` when the stack is running.

> I'm wondering if it's because blackfire has no ports configured.

@llaville you had it working or? What's your setup regarding exposed ports?

**Comment by llaville** [comment]
@cytopia My platform is Ubuntu 16.04 and latest version of devilbox without ports changed. All works fine for me as explained previously

**Comment by sonicviz** [comment]
What I don't understand is why php -m | grep -i blackfire or php -m doesn't show blackfire as a module but blackfire is obviously installed as the blackfire commands work. Should blackfire show as being an active module?

**Comment by cytopia** [comment]
@sonicviz Try if the following works inside the PHP container:

```
sudo docker-php-ext-enable blackfire
php -m | grep -i blackfire
```

If this works, something might still be wrong with `.env` or `ini` configuration or you might not be on the latest master commit.

**Comment by sonicviz** [comment]
Now it works, I have to say it's pretty impressive - especially demoing the full features. Not cheap, but worth it in the right circumstances. 

Have you thought about adding support for free profilers like https://github.com/tideways/php-xhprof-extension ?

**Comment by cytopia** [comment]
> I also had to disable xdebug in .env

I will add this to the documentation as well

> Bottom line is just enabling blackfire in .env doesn't enable the module, it also needs to be added in php.ini as outlined by @llaville.

This is actually supposed to work, as I am doing exactly this on my machine without any trouble.

> Fwiw blackfire also doesn't show up on the Devilbox intranet page but works fine doing the above.

That's correct, it doesn't as it is an additional stack via the override for which no intranet section has been created.

---

So currently what's left to do is:

1. Figuring out why it does not work for you via `.env` configuration
2. Figuring out the startup commands for the daemon without user interaction

**Comment by sonicviz** [comment]
>>So currently what's left to do is:
Figuring out why it does not work for you via .env configuration
Figuring out the startup commands for the daemon without user interaction

Not sure about either of those but let me know if you want me to try something. 
It's working now, but I have to re-authorise manually every time I restart docker. Not too big of a deal though.

**Comment by cytopia** [comment]
> but I have to re-authorise manually every time I restart docker. Not too big of a deal though.

This is something you can actually automate via custom startup-scripts: https://devilbox.readthedocs.io/en/latest/autostart/custom-scripts-per-php-version.html#custom-scripts-per-php-version

Once the script is in place it will automatically execute any commands during `docker-compose up`.

However, those commands must not be interactive, ie. not waiting for user input, but rather fully automatic.

---

Is there something as a free trial license for blackfire? If so I could actually try it out to finish the documentation.

**Comment by llaville** [comment]
@cytopia 

Remember, when I wrote that you should run the following command
```
devilbox@php-7.1.25 in /shared/httpd $ sudo blackfire-agent -register

	---------------------------------------------------------------------
	Welcome to the registration assistant of the Blackfire Agent
	---------------------------------------------------------------------

	Please, get your server id and token on:
	https://blackfire.io/my/settings/credentials#server

	Enter your server ID: xxxxxxxxxxxxxxxxxxxxxxxxxxxx
	Enter your server token: xxxxxxxxxxxxxxxxxxxxxxxxxxxx
	Verifying credentials...
	------------------------------------------------------------------------------
	The following configuration has been updated successfully
	/etc/blackfire/agent
	Please now restart the blackfire-agent service to use the generated configuration

	sudo /etc/init.d/blackfire-agent restart

	Thank you for using Blackfire
	------------------------------------------------------------------------------
```
You have to manually enter : 
- server ID (server-id=)
- server Token (server-token=)
and it will produces a ready `/etc/blackfire/agent` (INI format) file well configured

So if you can write such file with preconfigured values (server ID, server Token), then you may bypass manual process.

**Comment by cytopia** [comment]
OK, I have added a blackfire startup script: `autostart/run-blackfire-agent.sh-example`. This file must be renamed to `autostart/run-blackfire-agent.sh` and will then automatically configure and run the blackfire-agent.

**Steps:**

1. `git checkout documentation-blackfire`
2. `git pull origin documentation-blackfire`
3. `cp compose/docker-compose.override.yml-blackfire docker-compose.override.yml`
4.  Add `BLACKFIRE_SERVER_ID=add-value-here` to `.env`
5.  Add `BLACKFIRE_SERVER_TOKEN=add-value-here` to `.env`
6. `docker-compose up php httpd bind blackfire`

Then you can verify that `blackfire-agent` is running inside PHP container and its config file is configured properly:

```bash
# Enter the PHP container
host> ./shell.sh
# List stuff inside the PHP container
php-7.2> ps auxw grep blackfire-agent
php-7.2> cat /etc/blackfire/agent
```

**Info**:

* How the `autostart/*.sh` works: https://devilbox.readthedocs.io/en/latest/autostart/custom-scripts-globally.html#custom-scripts-globally

**Comment by cytopia** [comment]
### Blackfire client configuration (Update)

I've also added the blackfire client configuration automatism. Works as above (one single autostart file).

Only thing you have to do is:

1. Copy again latest blackfire docker-compose.override.yml-example (now also contains client env vars)
2. Add `BLACKFIRE_CLIENT_ID=` to `.env`
3. Add `BLACKFIRE_CLIENT_TOKEN=` to `.env`

Then in the PHP container you can do:
```bash
php-7.2> blackfire status
```

Now you can use the browser, as well as the `blackfire` cli inside the container

**Comment by cytopia** [comment]
## Update

**Having second thoughts here and think I've done it the wrong way.** The server (`blackfire-agent`) is already configured and running in its own Docker container and does not need to be started separately in the PHP container (only the `blackfire` cli needs to be configured if it is required to be used from within the PHP container).

So what really needs to be done is a change in the PHP.ini to tell the blackfire PHP module where the agent is listening:
`cfg/php-ini-7.2/blackfire.ini`:
```ini
[blackfire]
blackfire.agent_socket = tcp://blackfire:8707
```

I will update the PR accordingly with:

* [ ] Adjust autostart script to only configure `blackfire` cli (and not start or configure the server/agent)
* [ ] Provide an example php.ini for blackfire
* [ ] Update the documentation accordingly

**Comment by cytopia** [comment]
## Blackfire update merged

@sonicviz @llaville @runedalton 

It's now merged to master!

* Documentation: https://devilbox.readthedocs.io/en/latest/custom-container/enable-blackfire.html

## Tested:

* [X] Tested via Browser plugin
* [X] Tested via `blackfire` cli

## Usefulness

Please let me know how understandable and useful the altered documentation now is. Please also mentioned every bit that is unclear, so I can make it rock-solid

**Comment by sonicviz** [comment]
Thanks. 

It would be clearer if the documentation explained a little more about how the docker-compose.override.yml interacts with docker-compose.yml

Is that incorporated automatically if you run docker-compose.override.yml?

Last time I just manually added the blackfire specific code to my own docker-compose.yml as I'm using dockstation.

**Comment by cytopia** [comment]
> It would be clearer if the documentation explained a little more about how the docker-compose.override.yml interacts with docker-compose.yml

@sonicviz I already have that documented the basics here: https://devilbox.readthedocs.io/en/latest/configuration-files/docker-compose-override-yml.html

I have also just now extended that documentation explaining what `docker-compose.override.yml` does and linked it to the override tutorials.

Changes are here:

* https://devilbox.readthedocs.io/en/latest/configuration-files/docker-compose-override-yml.html#how-does-docker-compose-override-yml-work
* https://devilbox.readthedocs.io/en/latest/custom-container/enable-blackfire.html (The seealso box)

**Comment by cytopia** [comment]
> Is that incorporated automatically if you run docker-compose.override.yml?

Yes. This is now also reflected in the documentation and I will close this issue. If anything else is unclear, let me know here and I will reopen.

**Comment by llaville** [comment]
@cytopia Sorry to reply so late, but i was busy. 
I've just tested blackfire via CLI and browser plugin, following your documentation. And all run fine like a charm :) Thanks a lot for all your work and make it so easy especially with autostart script !!!

**Comment by sonicviz** [comment]
I hope to test it today.
Thanks for the hard work resolving this.

**Comment by sonicviz** [comment]
I tested it with DockStation (I find it more productive than working in CL)

The docker-compose.override.yml-blackfire doesn't work with DockStation for some reason, so I needed to add the code into my docker-compose.override.yml for it to work correctly

Successful blackfire test after that.
