### ISSUE TITLE
Public URLs for local projects

### ISSUE THREAD

**Issue by cs16lover** [cytopia/devilbox#453]
#### ISSUE TYPE

 - Feature request

#### SUMMARY

It would be nice to have public URLs for the projects that is accessible from internet and available on demand.

#### Goal

Sometimes we need to show the progress on the project.
There are some commercial with free tier and open source tools that you can publish your localhost to internet.
Here are some examples:
https://ngrok.com/  (Most popular one)
https://localtunnel.github.io/www/
https://pagekite.net/
https://serveo.net/
https://portmap.io/
https://github.com/fatedier/frp
https://github.com/mmatczuk/go-http-tunnel

**Comment by cytopia** [comment]
It should actually be possible right away to expose your vhosts via `ngrok` to the internet.

1. pick a specific subdomain for ngrok: https://ngrok.com/docs#subdomain
2. add an additional server alias/server name to vhost-gen config: https://devilbox.readthedocs.io/en/latest/vhost-gen/example-add-subdomains.html
3. start ngrok

**Comment by cytopia** [comment]
@cs16lover did the above example work out for you?

**Comment by cytopia** [comment]
@cs16lover Ngrok and corresponding documentation will be available in a few hours. PR is here: https://github.com/cytopia/devilbox/pull/522

**Comment by cytopia** [comment]
# Documentation

* https://devilbox.readthedocs.io/en/latest/custom-container/enable-ngrok.html
* https://devilbox.readthedocs.io/en/latest/corporate-usage/showcase-over-the-internet.html

**Comment by llaville** [comment]
One again, i like the documentation you produces @cytopia. BTW, could you tell us, which software you used to make such nice architecture diagram, and perharps include picture in final doc !
Thanks in advance for your great work

**Comment by cytopia** [comment]
Thanks! I use http://draw.io to create the diagrams and logos. Everything I do is publicly available here: https://github.com/devilbox/artwork

Each logo/diagram has a `.xcf` file (in the `raw/` directory) which can be loaded into draw.io to edit it.


>  and perharps include picture in final doc 

what exactly should I include?

**Comment by llaville** [comment]
I'd like to see architecture diagrams you built with https://github.com/devilbox/artwork (thanks to share)

**Comment by nathanbriggs** [comment]
Could you add support for ngrok's hostname parameter, please?
https://ngrok.com/docs#custom-domains

I believe an optional 4th parameter for a tunnel in HTTP_TUNNELS could work

**Comment by paul-gene** [comment]
Is there a way to use ngrok with `-host-header=rewrite`?

**Comment by ptmrio** [comment]
Hey sorry, did I miss something? I followed the setup from the docs but i can't access `localhost:4040`, nothing comes up. Just to be clear, I do have to install ngrok separately?

Simply edit `docker-compose.override.yml`, add a few constants to `.env`, then `docker-compose up bind httpd ngrok mysql php` and there SHOULD be an interface at port 4040?

Note:  `sudo lsof -i -P -n | grep LISTEN` also does not imply that 4040 is somehow active

Also: is really great to see the devilbox evolve, great work @cytopia

**Comment by hmontes** [comment]
I have this error on docker

 {"err":"Your ngrok-agent version \"2.3.29\" is too old. The minimum supported agent version for your account is \"3.2.0\". Please update to a newer version with `ngrok update`, by downloading from https://ngrok.com/download, or by updating your SDK version. Paid accounts are currently excluded from minimum agent version requirements. To begin handling traffic immediately without updating your agent, upgrade to a paid plan: https://dashboard.ngrok.com/billing/subscription.\r\n\r\nERR_NGROK_121\r\n","lvl":"eror","msg":"terminating with error","obj":"app","t":"2024-06-29T19:54:12.615341Z"}
 
 Ngrok is outdated

**Comment by hmontes** [comment]
I have this error on docker

 {"err":"Your ngrok-agent version \"2.3.29\" is too old. The minimum supported agent version for your account is \"3.2.0\". Please update to a newer version with `ngrok update`, by downloading from https://ngrok.com/download, or by updating your SDK version. Paid accounts are currently excluded from minimum agent version requirements. To begin handling traffic immediately without updating your agent, upgrade to a paid plan: https://dashboard.ngrok.com/billing/subscription.\r\n\r\nERR_NGROK_121\r\n","lvl":"eror","msg":"terminating with error","obj":"app","t":"2024-06-29T19:54:12.615341Z"}
 
 Ngrok is outdated
