### ISSUE TITLE
Include ZIP into the php-fpm container

### ISSUE THREAD

**Issue by mrbig00** [cytopia/devilbox#471]
#### ISSUE TYPE

 - Feature request

#### SUMMARY

Some of our deploy scripts uses the `zip` command, it would be nice to use it in the php-fpm container, especially because the `unzip` is available. Or some kind of workaround would be good.  

#### Goal

Make `zip` command available

**Comment by cytopia** [comment]
I will bundle both with the next release of PHP-FPM docker images.

In order for you to already have them available now add an autostart script as described here: https://devilbox.readthedocs.io/en/latest/autostart/custom-scripts-globally.html

The script will probably look like this:
```bash
apt-get update
apt-get install -y zip unzip
```

Once this is in place, everytime you run `docker-compose up`, this script will be executed and the two packages will be installed during start-up automatically.
