### ISSUE TITLE
Yaml syntax error in vhost_gen template causes silent failure

### ISSUE THREAD

**Issue by science695** [cytopia/devilbox#472]
### ISSUE TYPE
 - Bug Report

### SUMMARY
Vhost gen.py does not report an error if there is a yaml syntax error in a per-site custom template.

api/.devilbox/apache24.yml

My editor had put a tab instead of spaces in which broken the yaml syntax.
I would expect some kind of error to be logged in docker-compose logs,
Instead it just skipped over the custom template and used the global template.

(Note: it does error out if the global template has an error)

I think that the vhost_gen.py should be a little more fatal if there is a custom template and there is an error. (or at least log it as an error).

https://github.com/devilbox/vhost-gen/blob/master/bin/vhost_gen.py#L801

This is what it logged while skipping over the syntax error of my custom template:
```
vhost_gen.py -p "/shared/httpd/silex-api" -n "silex-api" -c /etc/vhost-gen/mass.yml -o "/shared/httpd/silex-api/.devilbox/" -s -v -m both
vhostgen: [2019-01-15 07:49:19] Adding: silex-api.loc.ncscredit.com
watcherd: [2019-01-15 07:49:19] [OK]  ADD: succeeded: /shared/httpd/silex-api
```

My recommendation is that it at least print out the contents of `err` if it exists. If there was some way for it to more aggressively tell you there was an error, that could be useful as well.

Thanks!

**Comment by cytopia** [comment]
I can confirm this:

* Wrong templates specified with `-t` (global) error out.
* Wrong templates specified with `-o` (local) do not error out.

**Comment by cytopia** [comment]
The new behaviour will be:

* If `*.yml` exists and is valid, it will abort
* If override directory exists, but no according `*.yml` file, it will give a warning and continue without overriding

**Comment by cytopia** [comment]
@science695 can you check out the PR branch: https://github.com/cytopia/devilbox/pull/474 and see if it now works as expected for you.
