### ISSUE TITLE
Cannot start mysql service

### ISSUE THREAD

**Issue by mrpsiho** [cytopia/devilbox#473]
### ISSUE TYPE

 - Bug Report

### Checklist

* [ ] `.env` file is attached
* [ ] `docker-compose.override.yml` is attached (if it exists)
* [ ] Custom configs from `cfg/` dir are attached (if customized)
* [ ] `docker-compose logs` and `log/` output is added
* [ ] I've looked through the docs: https://devilbox.readthedocs.io/en/latest/
* [ ] I've looked through existing issues: https://github.com/cytopia/devilbox/issues

[error.log](https://github.com/cytopia/devilbox/files/2759929/error.log)

### OS / ENVIRONMENT

1. Host operating system and version:  MacOS 10.14.2
2. (Windows) Native Docker or Docker Toolbox: 
3. Docker version: 2.0.0.2
4. Docker Compose version: 1.23.2
5. (Linux) Is SELinux enabled?:
6. What git commit hash are you on?:

### SUMMARY
mysql service is not started

### STEPS TO REPRODUCE
run `docker-compose up -d httpd bind php mysql`

### EXPECTED BEHAVIOUR
mysql service started

### ACTUAL BEHAVIOUR
mysql services is not started

### OTHER INFORMATION
run `docker-compose up --verbose mysql` outputs this:
```
...
mysql_1  | root $ chmod 0775 /var/sock/mysqld
mysql_1  | root $ find /var/log/mysql/ -type f -exec chmod 0664 {} \;
mysql_1  | [INFO] Found existing data directory. MySQL already setup.
mysql_1  | [INFO] Starting mysqld  Ver 10.3.4-MariaDB for Linux on x86_64 (MariaDB Server)
mysql_1  | 2019-01-15 15:51:35 0 [Note] mysqld (mysqld 10.3.4-MariaDB) starting as process 1 ...
compose.cli.verbose_proxy.proxy_callable: docker inspect_container <- ('cccc98e18e4e3297f6a44c197f4c72a097463d0119e79ff5c9a79698f394af69')
compose.cli.verbose_proxy.proxy_callable: docker wait <- ('cccc98e18e4e3297f6a44c197f4c72a097463d0119e79ff5c9a79698f394af69')
urllib3.connectionpool._make_request: http://localhost:None "POST /v1.24/containers/cccc98e18e4e3297f6a44c197f4c72a097463d0119e79ff5c9a79698f394af69/wait HTTP/1.1" 200 30
urllib3.connectionpool._make_request: http://localhost:None "GET /v1.24/containers/cccc98e18e4e3297f6a44c197f4c72a097463d0119e79ff5c9a79698f394af69/json HTTP/1.1" 200 None
compose.cli.verbose_proxy.proxy_callable: docker wait -> {'Error': None, 'StatusCode': 1}
compose.cli.verbose_proxy.proxy_callable: docker inspect_container -> {'AppArmorProfile': '',
 'Args': [],
 'Config': {'ArgsEscaped': True,
            'AttachStderr': False,
            'AttachStdin': False,
            'AttachStdout': False,
            'Cmd': None,
            'Domainname': '',
            'Entrypoint': ['/docker-entrypoint.sh'],
            'Env': ['DEBUG_COMPOSE_ENTRYPOINT=1',
...devilbox_mysql_1 exited with code 1
```

#### Start command

```
$ docker-compose up -d httpd bind php mysql
```

#### File and user permissions (Linux & MacOS)

```
$ id
uid=501(mrpsiho) gid=20(staff) groups=20(staff),701(com.apple.sharepoint.group.1),12(everyone),61(localaccounts),79(_appserverusr),80(admin),81(_appserveradm),98(_lpadmin),702(com.apple.sharepoint.group.2),33(_appstore),100(_lpoperator),204(_developer),250(_analyticsusers),395(com.apple.access_ftp),398(com.apple.access_screensharing),399(com.apple.access_ssh)
```

```
$ ls -la
total 360
drwxr-xr-x  34 mrpsiho  staff   1088 Jan 15 14:44 .
drwxr-xr-x   9 mrpsiho  staff    288 Dec 11 15:48 ..
-rw-r--r--@  1 mrpsiho  staff  14340 Jan 15 14:42 .DS_Store
drwxr-xr-x   7 mrpsiho  staff    224 Dec 27  2017 .devilbox
-rw-r--r--@  1 mrpsiho  staff  16488 Jan 15 14:44 .env
drwxr-xr-x  16 mrpsiho  staff    512 Jan 15 14:12 .git
drwxr-xr-x   4 mrpsiho  staff    128 Oct  7 12:54 .github
-rw-r--r--   1 mrpsiho  staff   3656 Jan  4 09:53 .gitignore
drwxr-xr-x   8 mrpsiho  staff    256 Jan  4 09:53 .tests
-rw-r--r--   1 mrpsiho  staff   9510 Jan  4 09:53 .travis.yml
-rw-r--r--   1 mrpsiho  staff    894 Oct  7 12:54 CONTRIBUTING.md
-rw-r--r--   1 mrpsiho  staff   1064 Sep 21  2017 LICENSE.md
-rw-r--r--   1 mrpsiho  staff  55047 Jan 15 14:12 README.md
drwxr-xr-x   4 mrpsiho  staff    128 Jan  4 09:53 autostart
drwxr-xr-x@  6 mrpsiho  staff    192 Apr 16  2018 backups
drwxr-xr-x   4 mrpsiho  staff    128 Sep 21  2017 bash
drwxr-xr-x@  6 mrpsiho  staff    192 May  7  2018 ca
drwxr-xr-x  50 mrpsiho  staff   1600 Jan  4 09:53 cfg
drwxr-xr-x   8 mrpsiho  staff    256 Oct  7 12:54 compose
drwxr-xr-x@ 11 mrpsiho  staff    352 Oct 14 09:09 data
-rw-r--r--   1 mrpsiho  staff    743 Apr 25  2018 docker-compose.override.yml-example
-rw-r--r--   1 mrpsiho  staff  12815 Jan 15 14:12 docker-compose.yml
drwxr-xr-x  38 mrpsiho  staff   1216 Jan  4 09:53 docs
-rw-r--r--@  1 mrpsiho  staff  17222 Jan 15 14:12 env-example
drwxr-xr-x   8 mrpsiho  staff    256 Dec 24 10:32 log
drwxr-xr-x@  4 mrpsiho  staff    128 Jan 12 13:40 mail
drwxr-xr-x  10 mrpsiho  staff    320 Jun  6  2018 mod
-rw-r--r--@  1 mrpsiho  staff    250 Feb 17  2018 nginx.conf
-rw-r--r--   1 mrpsiho  staff   3754 May  7  2018 nginx.yml
-rw-r--r--   1 mrpsiho  staff     86 Mar  5  2018 shell.bat
-rwxr-xr-x@  1 mrpsiho  staff     59 Apr 16  2018 shell.sh
drwxr-xr-x   4 mrpsiho  staff    128 May 11  2018 templates
-rwxr-xr-x   1 mrpsiho  staff   2375 Oct  7 12:54 update-docker.sh
-rw-r--r--@  1 mrpsiho  staff     66 Jan 27  2018 wp.txt
```

**Comment by cytopia** [comment]
1.  Does this also happen, when MySQL does not have any data yet?
2.  You're using Dokcer version 2.x, what about Docker version 1.x?
3.  Last but not least, can you give the following PR a shot to see if it eliminates the problem: https://github.com/cytopia/devilbox/pull/383

**Comment by mrpsiho** [comment]
Thanks!

I tried option 3 and now mysql service is running. Looks ok. The only problem I did not make backups through phpmyadmin and everything I have are the files under `data/mysql/mariadb-10.3` folder. But this data is not visible in phpmyadmin, like it does not exist. Could you suggest how to import it? I have several DBs and would like to restore them.

**Comment by cytopia** [comment]
You can always go back to the previous Devilbox branch to have them loaded. But then again you hit your current issue.

So, I guess we have to continue digging on the original issue. Did that just appear out of the blue and was working fine before? Any changes you have applied?

Additionally you can try to start another MySQL container (and only a MySQL container, without the Devilbox) on that directory and dump everything. Obviously you should backup that folder before you try anything.

In general, to prevent stuff like that in the future, you should periodically run `mysqldump-secure` within the PHP container: https://devilbox.readthedocs.io/en/latest/maintenance/backup-and-restore-mysql.html#mysqldump-secure

So let me know how restoring with a different or just single MySQL container works.

**Comment by mrpsiho** [comment]
Well, I am not sure. My laptop has been restarted automatically two times, so I decided to clean it a bit with cleanmymac software. I don't know whether this is the reason and caused by that operation. But now my laptop works fine at least. Also, I updated to Docker 2.0.0.2 and then tried to start Devilbox as usually.  This is where the issue has arisen.

For the restoration process, well, I was crying a bit :) then grabbed a beer and started thinking whether I have any other backups at all and is that info was so important. Come to the conclusion that it wasn't. :)

**Comment by mrpsiho** [comment]
Thanks for the suggestion though! Will be doing that now periodically!

**Comment by cytopia** [comment]
It might also just solve the issue by going back to Docker 1.x

**Comment by cytopia** [comment]
@mrpsiho Is this solved with the new proposed branch?

**Comment by cytopia** [comment]
@mrpsiho could you try out the release branch: https://github.com/cytopia/devilbox/pull/416 Please pay special attention to the instructions in the PR description.

**Comment by cytopia** [comment]
@mrpsiho any updates from your side?

**Comment by cytopia** [comment]
@mrpsiho see also here: https://github.com/cytopia/devilbox/issues/542

**Comment by cytopia** [comment]
> I tried option 3 and now mysql service is running. Looks ok

@mrpsiho , sorry did totally overlook that this was already solved.
