### ISSUE TITLE
How additional tools are update in php container ?

### ISSUE THREAD

**Issue by llaville** [cytopia/devilbox#475]
#### ISSUE TYPE

 - Question

How additional tools such as `jq` are update in php container ?

#### SUMMARY

Actually in php container version 0.71 (PHP 7.1.26) when I ask version of `jq`, I got **jq-1.5-1-a5b5cbe**

A recent version 1.6 is available since November 2018, 1st

**Comment by cytopia** [comment]
The whole PHP-FPM images are built from scratch every night. This is then also true for their bundled additional tools. Most of those tools come from the Debian apt repositories and are as up-to-date as Debian provides it.

Debian is quick on security updates, but not as bleeding edge as other distributions (e.g.: Arch, Ubuntu...), so it might not hold the latest versions of packages that it provides.

I do install some tools independently of the Debian apt sources, as they are pretty old.

For the above mentioned `jq`, do you need that very recent version?

**Comment by llaville** [comment]
@cytopia Thanks to clarify the situation. And no there are no hurry. No need to have the most up-to-date version. 
I'll only be sure that the process is correct, and there is no problem to update components !

**Comment by cytopia** [comment]
OK, I will close this one then. Just reply here again if anything is missing and I will re-open.
