### ISSUE TITLE
Include root password in phpmyadmin config

### ISSUE THREAD

**Issue by mrbig00** [cytopia/devilbox#476]
#### ISSUE TYPE

 - Feature request

#### SUMMARY
I'm sure that most of the developers are lazy like me :) So my suggestion would be to include in the phpmyadmins config the root password which is available in the .env file so this way we could set an auto login for phpmyadmin and we could skip a few extra clicks. Since the main purpose of the Devilbox is mainly for development the security doesn't really maters here. And if somebody is using for production, I'm sure there is some workaround to don't expose phpmyadmin to public.

And also a symlink to localhost/vendor/phpmyadmin/ would be good, to skip the actual version number, because I'm sure that many of us has this link in browser history and if the version is changed the link in the history will be 404 :)

If you agree with this suggestion I could create a pull request.

#### Goal
Enable auto login for phpmyadmin

**Comment by cytopia** [comment]
@mrbig00 sounds good to me.

Keep in mind that there are 2 phpMyAdmin;s (one recent one, and one for older PHP versions). Additionally the CI checks currently do a headless curl login, into phpMyAdmin and might also need to be adjusted: https://github.com/cytopia/devilbox/blob/master/.tests/intra-tests/vendor-phpmyadmin.sh#L112

**Comment by mrbig00** [comment]
I'm not a docker wizard, so what do you think about adding this one liner to the startup script and it will create a symlink with for the correct phpmyadmin version?

`rm phpmyadmin && if [[ $(printenv PHP_VERSION)  < 5.5 ]] ; then ln -s phpmyadmin-4.8.4 phpmyadmin; else ln -s phpmyadmin-4.0 phpmyadmin ; fi
`

**Comment by cytopia** [comment]
PR was merged.

**Comment by cytopia** [comment]
@mrbig00 FYI: The same feature will come for phpPgAdmin: https://github.com/cytopia/devilbox/pull/489

**Comment by mrbig00** [comment]
@cytopia Happy to hear that :)

Sorry, I don't  have much time in the next few days, but I would love to contribute more to the code.
