### ISSUE TITLE
Cannot create Symlink in container - Docker Toolbox

### ISSUE THREAD

**Issue by fkaminski** [cytopia/devilbox#479]
#### ISSUE TYPE

 - Documentation

#### SUMMARY
As mentioned here:
https://devilbox.readthedocs.io/en/latest/howto/docker-toolbox/docker-toolbox-and-the-devilbox.html?highlight=toolbox%20shared#mount-shared-folders

When you setup another shared directory say "d:/" with name "d" in Virtualbox it might be possible that symlinking is not allowed within the docker container - See:
https://www.virtualbox.org/ticket/10085

You have to allow symlinking for this shared directory manually via VboxManage:
- Check it with "VboxManage getextradata default enumerate"
- Set it with "VBoxManage setextradata **default** VBoxInternal2/SharedFoldersEnableSymlinksCreate/**d** 1"
- Here "**default**" is the name of the VM and "**d**" the name of the shared directory in Virtualbox
- Check it again with "VboxManage getextradata default enumerate"

You should get something like this:
```
Key: VBoxInternal2/SharedFoldersEnableSymlinksCreate/c/Users, Value: 1
Key: VBoxInternal2/SharedFoldersEnableSymlinksCreate/d, Value: 1

```
Then symlinking is allowed/possible again ...

#### Goal

Maybe you could update the Documentation for Docker Toolbox User with the infos above ...

**Comment by cytopia** [comment]
@krebbi not exactly sure what the issue is with this

**Comment by krebbi** [comment]
nevermind, just my stupidity in combination with too less sleep.
there was a wrong set symlink which I just had to delete and it worked like a charm.

**Comment by cytopia** [comment]
@fkaminski thanks for the info, I've updated the documentation accordingly:

* https://devilbox.readthedocs.io/en/latest/howto/docker-toolbox/docker-toolbox-and-the-devilbox.html#symlinks
* https://devilbox.readthedocs.io/en/latest/support/troubleshooting.html#ln-creating-symbolic-link-foo-read-only-file-system
