### ISSUE TITLE
Use EditorConfig

### ISSUE THREAD

**Issue by mrbig00** [cytopia/devilbox#481]
#### ISSUE TYPE

Use [.editorconfig](https://editorconfig.org/) to maintain a unified code style (for example I see a lot of comment in PRs from @cytopia where he suggests to use  tabs instead of spaces)

#### Goal

Place a **.editorconfig** file in the root of the project and configure to the project needs

**Comment by llaville** [comment]
I use personaly .editorConfig and i always use space ident for all files (php ...) except for Makefile that must be tab indent.

**Comment by cytopia** [comment]
Let's not start the discussion about spaces vs tabs ;-)

Currently the intranet as well as all shell scripts use tabs (locally configured as 4 space sizes) and everything else uses spaces. As for bundled vendors or libraries that might differ depending on what they've used.

For now I don't want to change all indentations, but just to make sure that `.editorconfig` is written correctly to reflect the current changes and therefore making it easier for new contributors to stick to what is available as @mrbig00 suggested.

**Comment by mrbig00** [comment]
I'm not an .editorconfig guru, but the config looks okay to me.

Neither do I see any reason to start a space vs. tabs war here, so I would suggest what you think it's the best.

**Comment by cytopia** [comment]
Thanks again for the idea. It's now merged to master.
