### ISSUE TITLE
Duplication of env variables passed to docker-compose

### ISSUE THREAD

**Issue by andreyors** [cytopia/devilbox#49]
There is no need to mention value of env vars in docker-compose, it will automatically pass it to service, it will take from .env automatically:

i.e. instead of
environment:
    - DEBUG_COMPOSE_ENTRYPOINT=${DEBUG_COMPOSE_ENTRYPOINT}

do 
environment:
    - DEBUG_COMPOSE_ENTRYPOINT

**Comment by cytopia** [comment]
@andreyors Thanks for the info. Didn't know yet.
