### ISSUE TITLE
Update wkhtmltopdf version

### ISSUE THREAD

**Issue by martinbertinat** [cytopia/devilbox#493]
#### ISSUE TYPE

 - Feature request

#### SUMMARY
Update wkhtmltopdf to last version with patched qt (adds some features). Current version is: 0.12.3.2

#### Goal
Some usefull features of wkhtmltopdf (like footer-html and header-html options) are only included in the "qt patched" version of wkhtmltopd. Goal version at least 0.12.4

To install the patched qt version inside the php container I followed these steps:

`sudo apt-get purge wkhtmltopdf`
`wget https://github.com/wkhtmltopdf/wkhtmltopdf/releases/download/0.12.4/wkhtmltox-0.12.4_linux-generic-amd64.tar.xz`
`tar xvf wkhtmltox-0.12.4_linux-generic-amd64.tar.xz`
`sudo mv wkhtmltox/bin/wkhtmltopdf /usr/bin/wkhtmltopdf`
`sudo mv wkhtmltox/bin/wkhtmltoimage /usr/bin/wkhtmltoimage`

**Comment by cytopia** [comment]
@martinbertinat PR is open and ready to be tested: https://github.com/cytopia/devilbox/pull/518
