### ISSUE TITLE
Fix YARN global commands

### ISSUE THREAD

**Issue by mrbig00** [cytopia/devilbox#496]
#### ISSUE TYPE

 - Feature request

I'm using some yarn packages globally, and I've seen that the global packages aren't accessible from command line. Setting the yarn prefix dir and adding it to the PATH fixes the issue 

[Related SO question](https://stackoverflow.com/questions/40317578/yarn-global-command-not-working)

#### SUMMARY

Add these to the startup script:

```
su -c 'yarn config set prefix ~/.yarn' -l devilbox
su -c 'export PATH="$PATH:`yarn global bin`"' -l devilbox
```

#### Goal

Make yarn global commands accessible

**Comment by cytopia** [comment]
I will rewrite the NodeJS, nvm, yarn, npx installation more properly and will also integrate the above mentioned paths.

There's also another NodeJS related issue open, which might also be interesting/answerable for you: https://github.com/cytopia/devilbox/issues/499

Once I have enough background knowledge regarding this topic (still a NodeJS beginner), I will make this rewrite.

---

To already have your current issue solved (without the need for rewrite), please use the autostart feature to populate the bash configuration: https://devilbox.readthedocs.io/en/latest/autostart/custom-scripts-globally.html

**Comment by cytopia** [comment]
@mrbig00  can you try out the branch from the PR to see if this resolves the issue: https://github.com/cytopia/devilbox/pull/528

**Comment by mrbig00** [comment]
@cytopia I confirm that it works 

Great job!
