### ISSUE TITLE
Use host node version

### ISSUE THREAD

**Issue by felixmosh** [cytopia/devilbox#498]
#### ISSUE TYPE

 - Feature request

#### SUMMARY

Sometimes there are node libs that requires compilation, such as `sass-node`, and if you node app was built with host version that is different from current docker version (`8`) it will fail.

**Comment by cytopia** [comment]
Maybe I am getting this wrong, but if not then:

That's not possible at all. I can't know the hosts node version of every potential user. And secondly why would you build it on the host in the first place, instead of building it directly inside the container?

**Comment by felixmosh** [comment]
Thank u for the quick response, sometimes I need to work without reverse proxy, containers etc, so I work on the node service it self.

**Comment by cytopia** [comment]
If the node service itself is dockerized (if not consider it for a moment), you also attach this container to the Devilbox and use both, your node service port and the reverse proxy feature of the Devilbox itself: https://devilbox.readthedocs.io/en/latest/reverse-proxy/reverse-proxy-for-custom-docker.html

Independent of that, you could always just boot up a node container which has the appropriate node version you require (if or if not linked to devilbox)

**Comment by felixmosh** [comment]
Cool, sound a good solution, thank u!

**Comment by cytopia** [comment]
OK, glad its solved for now. Let me know when there's trouble with reverse-proxying custom docker containers.
