### ISSUE TITLE
Add nvm (Node Version Manager) to PHP container tools

### ISSUE THREAD

**Issue by az09asdf** [cytopia/devilbox#499]
#### ISSUE TYPE

 - Feature request

#### SUMMARY

Add nvm to PHP container tools (Ubuntu 18.04 example).

install nvm script:
`curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.11/install.sh | bash`

`export NVM_DIR="$HOME/.nvm"`
`[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm`
`[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion`

install the latest LTS version:
`nvm install --lts`

install the latest available version of node.js:
`nvm install node`

#### Goal

It would be nice to have multiple node.js versions to select from,  instead of just the latest node.js lts version.

**Comment by cytopia** [comment]
@az09asdf I will probably need a bit of support here as I am not too familiar with NodeJS and NVM.

Currently I am already installing a couple of NodeJS packages via (`yarn`, which could also be changed back to `npm`). The question is how will this conflict with the above listed method of having multiple NodeJS versions available? Do I need to explicitly specify directories when installing stuff globally?

I think it is a general good idea to also have multiple NodeJS versions available, could you list a few common once, just that I get an idea here.

**Comment by az09asdf** [comment]
@cytopia 

while learning some front-end frameworks, sometimes it was a requirement to have the latest node version

so, I found instruction for instaling node using nvm [here](https://linuxize.com/post/how-to-install-node-js-on-ubuntu-18.04/), installed it on the php container, tried it and it looks good

it is realy simple to install and use

the first thing I do before installing nvm and node versions needed is to uninstall node from the php container:
`sudo apt remove nodejs npm`

and then as per my previous post

if your project needs version 11.10.0 (which you previously installed using `nvm install 11.10.0`) you need this:
`nvm use 11.10.0`

and that's it: from now on you have that version on your php container

`devilbox@php-7.2.15 in /shared/httpd/react-redux/code $ nvm current`
`v11.10.0`
`devilbox@php-7.2.15 in /shared/httpd/react-redux/code $ nvm ls`
`       v10.15.1`
`->     v11.10.0`
`default -> node (-> v11.10.0)`
`node -> stable (-> v11.10.0) (default)`
`stable -> 11.10 (-> v11.10.0) (default)`
`iojs -> N/A (default)`
`lts/* -> lts/dubnium (-> v10.15.1)`
`lts/argon -> v4.9.1 (-> N/A)`
`lts/boron -> v6.16.0 (-> N/A)`
`lts/carbon -> v8.15.0 (-> N/A)`
`lts/dubnium -> v10.15.1`
`devilbox@php-7.2.15 in /shared/httpd/react-redux/code $ nvm use 10.15.1`
`Now using node v10.15.1 (npm v6.4.1)`
`devilbox@php-7.2.15 in /shared/httpd/react-redux/code $ nvm use 11.10.0`
`Now using node v11.10.0 (npm v6.7.0)`
`devilbox@php-7.2.15 in /shared/httpd/react-redux/code $`

all juggling with installed node versions is handled by nvm

the only thing which is changed is that on the devilbox home page now we have:
node    not installed
npm     not installed

I hope this will be of some help

keep up the good work

**Comment by cytopia** [comment]
@az09asdf Thanks for the explanation. When uninstalling nodejs and npm, what will happen to the already globally installed npm packages?

**Comment by az09asdf** [comment]
@cytopia 
I'm not sure, but probably not (the trouble is as it seems to get rid of them).

However, according to [https://github.com/creationix/nvm#system-version-of-node](https://github.com/creationix/nvm#system-version-of-node) it seems that removing already installed version on node (pre nvm) is not needed: you could switch to it by
`nvm use system`

That would mean you could just add nvm install after already installed stuff (node also) to PHP image and either leave it as it is  or (better) at least install current LTS version of node (`nvm install --lts`).

The best course of action while creating PHP image might be as follows:
1.  do not install node
2.  install nvm
3.  install current LTS node version: it will be automatically set to default version (`nvm install --lts`) 
4. install all global packages you need

That way, user will have at least current LTS already installed, and if they need another node version - no problem, nvm is already installed so it is really easy to do (and how to for example transfer global packages to another version if you need them is described [here](https://github.com/creationix/nvm#usage)).

**Comment by cytopia** [comment]
@az09asdf can you try out the branch from the PR to see if this resolves the issue: https://github.com/cytopia/devilbox/pull/528

**Comment by tikoflano** [comment]
This is still needed. Would be nice to have it added.

**Comment by cytopia** [comment]
> This is still needed. Would be nice to have it added.

If it is still needed, feel free to use it then ;-) It is already available since a long time. Did you miss out any updates?

```bash
$ devilbox@php-7.4.1 in /shared/httpd $ nvm --version
0.35.2
```

**Comment by tikoflano** [comment]
I was logging in as root and that is why the `nvm` command wasn't found! I'm using Devilbox (best tool ever) for developing in Visual Code and it logged in as root by default. I had to add the line `"remoteUser": "devilbox"` to my container's configuration file inside Visual Code in order to log in as devilbox user and have access to `nvm`. 

Sory for the mistake and thanks for your time :)

**Comment by Luc45** [comment]
I still get `nvm: command not found`, both in bash and zsh inside the container in Devilbox

**Comment by Luc45** [comment]
I ran the `nvm` installer script and it's running now. `curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.3/install.sh | bash`

As Cytopia said in another issue, it seems to be because `nvm` is registered as a bash/zsh function, rather than an actual executable available in the $path. This seems to cause some issues.

**Comment by krebbi** [comment]
when trying to change the node version I get write permission errors:

`nvm install lts/*
Downloading and installing node v14.17.3...
mkdir: cannot create directory ‘/opt/nvm/.cache/bin’: Permission denied
creating directory /opt/nvm/.cache/bin/n`

**Comment by yfridelance** [comment]
same permission issue when trying install current lts

nvm install --lts
Installing latest LTS version.
Downloading and installing node v16.13.0...
/bin/mkdir: cannot create directory ‘/opt/nvm/.cache/bin’: Permission denied
creating directory /opt/nvm/.cache/bin/node-v16.13.0-linux-x64/files failed
Downloading https://nodejs.org/dist/v16.13.0/node-v16.13.0-linux-x64.tar.xz...
Warning: Failed to create the file                                                                                                                         
Warning: /opt/nvm/.cache/bin/node-v16.13.0-linux-x64/node-v16.13.0-linux-x64.ta
Warning: r.xz: No such file or directory

**Comment by Lenitr** [comment]
@krebbi @yfridelance 

For anyone running into the permission issue when trying to install node versions that are not available in the `nvm use X` command, try running `sudo chmod -R 777 /opt/nvm` before you run the install.

**Comment by Lenitr** [comment]
@cytopia  to reproduce it:

- `./shell.sh` into the php container (I don't change the user, so logged in as `devilbox`)
- `nvm install 12` (or any other version that is not installed
- In my case currently 
```
nvm install 12
Downloading and installing node v12.22.12...
mkdir: cannot create directory ‘/opt/nvm/.cache/bin’: Permission denied
creating directory /opt/nvm/.cache/bin/node-v12.22.12-linux-x64/files failed
Downloading https://nodejs.org/dist/v12.22.12/node-v12.22.12-linux-x64.tar.xz...
Warning: Failed to create the file
Warning: /opt/nvm/.cache/bin/node-v12.22.12-linux-x64/node-v12.22.12-linux-x64.
Warning: tar.xz: No such file or directory

curl: (23) Failed writing body (0 != 1112)
Binary download from https://nodejs.org/dist/v12.22.12/node-v12.22.12-linux-x64.tar.xz failed, trying source.
grep: /opt/nvm/.cache/bin/node-v12.22.12-linux-x64/node-v12.22.12-linux-x64.tar.xz: No such file or directory
Provided file to checksum does not exist.
Binary download failed, trying source.
Detected that you have 4 CPU core(s)
Running with 3 threads to speed up the build
mkdir: cannot create directory ‘/opt/nvm/.cache/src’: Permission denied
creating directory /opt/nvm/.cache/src/node-v12.22.12/files failed
Downloading https://nodejs.org/dist/v12.22.12/node-v12.22.12.tar.xz...
Warning: Failed to create the file
Warning: /opt/nvm/.cache/src/node-v12.22.12/node-v12.22.12.tar.xz: No such
Warning: file or directory

curl: (23) Failed writing body (0 != 1108)
Binary download from https://nodejs.org/dist/v12.22.12/node-v12.22.12.tar.xz failed, trying source.
grep: /opt/nvm/.cache/src/node-v12.22.12/node-v12.22.12.tar.xz: No such file or directory
Provided file to checksum does not exist.
```
Changing the permission like I mentioned in the previous comment is what allows me to run the install though. (777 is a bit much, but it confirms the issue is somewhere with the permissions)

The first error encountered suggest the root of the issue is in the creation of a new folder, which isn't allowed.

**Comment by cytopia** [comment]
> @cytopia to reproduce it:
> 
> * `./shell.sh` into the php container (I don't change the user, so logged in as `devilbox`)
> * `nvm install 12` (or any other version that is not installed

That is exactly what I did. Everything works fine.
What PHP version are you using?

**Comment by Lenitr** [comment]
I'm running php `8.0.7`

```
total 300
drwxr-xr-x 1 1000 1000   4096 Jun 16  2021 ./
drwxr-xr-x 1 root root   4096 Jul  1 11:54 ../
drwxr-xr-x 3 1000 1000   4096 Jun 16  2021 alias/
drwxr-xr-x 1 1000 1000   4096 Jun 16  2021 .cache/
drwxr-xr-x 8 1000 1000   4096 Jun 16  2021 .git/
drwxr-xr-x 3 1000 1000   4096 Jun 16  2021 .github/
drwxr-xr-x 9 1000 1000   4096 Jun 16  2021 test/
drwxr-xr-x 1 1000 1000   4096 Jun 16  2021 versions/
-rw-r--r-- 1 1000 1000   2201 Jun 16  2021 bash_completion
-rw-r--r-- 1 1000 1000   5424 Jun 16  2021 CODE_OF_CONDUCT.md
-rw-r--r-- 1 1000 1000   1057 Jun 16  2021 CONTRIBUTING.md
-rw-r--r-- 1 1000 1000   3723 Jun 16  2021 Dockerfile
-rw-r--r-- 1 1000 1000    140 Jun 16  2021 .dockerignore
-rw-r--r-- 1 1000 1000    523 Jun 16  2021 .editorconfig
-rw-r--r-- 1 1000 1000      9 Jun 16  2021 .gitattributes
-rw-r--r-- 1 1000 1000    253 Jun 16  2021 .gitignore
-rwxr-xr-x 1 1000 1000  14926 Jun 16  2021 install.sh
-rw-r--r-- 1 1000 1000   1113 Jun 16  2021 LICENSE.md
-rw-r--r-- 1 1000 1000     51 Jun 16  2021 .mailmap
-rw-r--r-- 1 1000 1000   5361 Jun 16  2021 Makefile
-rw-r--r-- 1 1000 1000     19 Jun 16  2021 .npmrc
-rwxr-xr-x 1 1000 1000    344 Jun 16  2021 nvm-exec
-rw-r--r-- 1 1000 1000 134284 Jun 16  2021 nvm.sh
-rw-r--r-- 1 1000 1000   2228 Jun 16  2021 package.json
-rw-r--r-- 1 1000 1000  39200 Jun 16  2021 README.md
-rwxr-xr-x 1 1000 1000   1235 Jun 16  2021 rename_test.sh
-rw-r--r-- 1 1000 1000    882 Jun 16  2021 ROADMAP.md
-rw-r--r-- 1 1000 1000   2713 Jun 16  2021 .travis.yml
-rwxr-xr-x 1 1000 1000   2364 Jun 16  2021 update_test_mocks.sh
```

I see my owner is different, looks like the default Docker user.
Could it be related to the host system being different? I'm running Docker Desktop `4.9.1` on Mac OS

**Comment by krebbi** [comment]
With PHP_SERVER=8.1

https://user-images.githubusercontent.com/3884521/176902083-8c1ad15f-b27e-4ff2-9c0a-6a80a6e77b0f.mov

**Comment by cytopia** [comment]
> total 300
> drwxr-xr-x 1 1000 1000   4096 Jun 16  2021 ./
> drwxr-xr-x 1 root root   4096 Jul  1 11:54 ../
> drwxr-xr-x 3 1000 1000   4096 Jun 16  2021 alias/
> drwxr-xr-x 1 1000 1000   4096 Jun 16  2021 .cache/
> drwxr-xr-x 8 1000 1000   4096 Jun 16  2021 .git/
> drwxr-xr-x 3 1000 1000   4096 Jun 16  2021 .github/

The owner does look different.

Can you post the output from `id` command from your host system and from within the PHP container as devilbox user

**Comment by Lenitr** [comment]
On my host 
```
uid=501(MYNAME) gid=20(staff) groups=20(staff),12(everyone),61(localaccounts),79(_appserverusr),80(admin),81(_appserveradm),98(_lpadmin),701(com.apple.sharepoint.group.1),33(_appstore),100(_lpoperator),204(_developer),250(_analyticsusers),395(com.apple.access_ftp),398(com.apple.access_screensharing),399(com.apple.access_ssh),400(com.apple.access_remote_ae)
```
In devilbox
```
uid=501(devilbox) gid=20(devilbox) groups=20(devilbox)
```
Interestingly, @krebbi  seems to be on Mac OS too, wonder if that's causing the difference here

**Comment by cytopia** [comment]
OK, got it. Afaik the entrypoint script is not taking care about `/opt/nvm` permissions. Will have to fix it, so that it `chowns` this directory to the correct uid and gid

**Comment by Lenitr** [comment]
@cytopia You're awesome, thanks a bunch!

**Comment by cytopia** [comment]
The build will take quite a lot of hours though: https://github.com/devilbox/docker-php-fpm/pull/243

**Comment by cytopia** [comment]
Changing ownership during startup takes >5min, so I am changing file system permission during build time and make them wide open. Kinda dirty, but I don't see a better way.

**Comment by cytopia** [comment]
PR went through, now need to wait for the tagged build: https://github.com/devilbox/docker-php-fpm/releases/tag/0.141

**Comment by Lenitr** [comment]
Just FYI, did a test on my Linux machine, there was still and older PHP container there. On the Linux host this problem didn't occur at all it seems, so that explains why for some people it occurred and for others didn't. 
(both host and container do have uid 1000 here so that's probably why).

Thanks for fixing the issue for the other hosts.

**Comment by cytopia** [comment]
> On the Linux host this problem didn't occur at all

Reason is that by default the first user being created on Linux gets uid 1000 and gid 1000 (it increments with additional users). This is also the default uid/gid used inside the PHP container.

**Comment by cytopia** [comment]
Reopened as not yet released for Devilbox
