### ISSUE TITLE
upgrade Percona server to 8.0

### ISSUE THREAD

**Issue by normance** [cytopia/devilbox#501]
#### ISSUE TYPE

  Propose Percona Server for MySQL 8.0.13-4

#### SUMMARY

 Max current version in .env is percona-5.7. But the 8.0 exists here https://hub.docker.com/r/percona/percona-server/tags/ (8.0.13 had been released on January 17th, 2019 

#### Goal

Use an mysql alternative with Percona tools

**Comment by cytopia** [comment]
It is currently under development.

**Comment by cytopia** [comment]
This has been merged. You should switch to the release branch: https://github.com/cytopia/devilbox/pull/416

Pay attention to how to use it in the PR comment.
