### ISSUE TITLE
How to enable "Nginx mod_rewrite"

### ISSUE THREAD

**Issue by mozgbrasil** [cytopia/devilbox#504]
#### ISSUE TYPE

How to enable "Nginx mod_rewrite"

You could leave this option as default

![captura de tela de 2019-02-11 14-36-16](https://user-images.githubusercontent.com/17202780/52578132-bf90cf80-2e0a-11e9-8753-84bfef3953d3.png)
![captura de tela de 2019-02-11 14-36-20](https://user-images.githubusercontent.com/17202780/52578134-bf90cf80-2e0a-11e9-8126-768cbfb3cbac.png)
![captura de tela de 2019-02-11 14-36-22](https://user-images.githubusercontent.com/17202780/52578135-bf90cf80-2e0a-11e9-9145-5c99127797d2.png)

**Comment by mrbig00** [comment]
Nginx does not support .htaccess or mod_rewrite

**Comment by mozgbrasil** [comment]
Thank you for the tip
