### ISSUE TITLE
mysql 5.7 can`t run

### ISSUE THREAD

**Issue by Bobbydum** [cytopia/devilbox#52]
cytopia/mysql-5.7
```
db_1     | [INFO] Setting MySQL: [client] socket=/tmp/mysql/mysqld.sock
db_1     | [INFO] Setting MySQL: [mysql] socket=/tmp/mysql/mysqld.sock
db_1     | [INFO] Setting MySQL: [mysqld] socket=/tmp/mysql/mysqld.sock
php_1    | [INFO] Setting PHP: mysql.default_socket=/tmp/mysql/mysqld.sock
db_1     | [INFO] No existing MySQL data directory found. Setting up MySQL for the first time.
php_1    | [INFO] Setting PHP: mysqli.default_socket=/tmp/mysql/mysqld.sock
db_1     | 2017-04-26T09:04:15.887777Z 0 [Warning] TIMESTAMP with implicit DEFAULT value is deprecated. Please use --explicit_defaults_for_timestamp server option (see documentation for more details).
php_1    | [INFO] Setting PHP: pdo_mysql.default_socket=/tmp/mysql/mysqld.sock
db_1     | 2017-04-26T09:04:15.889054Z 0 [ERROR] --initialize specified but the data directory has files in it. Aborting.
php_1    | [INFO] Enabling sending of emails.
db_1     | 2017-04-26T09:04:15.889075Z 0 [ERROR] Aborting
db_1     | 
devilbox_db_1 exited with code 1
```

**Comment by cytopia** [comment]
@Bobbydum 
Can you paste your docker and docker-compose versions as well as operating system and what git tag/branch you are using.

Also try to switch (if not already) to the git master branch and pull latest docker. There have been some problems in the past with mysql 5.7 which should be fixed by the latest version.
```shell
git checkout master
git pull origin master
docker-compose pull
```

**Comment by Bobbydum** [comment]
How i can disable starting  POSTGRES?
$ docker-compose pull
WARNING: The DEVILBOX_PATH variable is not set. Defaulting to a blank string.
WARNING: The LOCAL_LISTEN_ADDR variable is not set. Defaulting to a blank string.
WARNING: The HOST_PORT_HTTPD variable is not set. Defaulting to a blank string.
WARNING: The HOST_PATH_TO_POSTGRES_DATADIR variable is not set. Defaulting to a blank string.
WARNING: The POSTGRES_USER variable is not set. Defaulting to a blank string.
WARNING: The POSTGRES_PASSWORD variable is not set. Defaulting to a blank string.
WARNING: The POSTGRES_SERVER variable is not set. Defaulting to a blank string.
WARNING: The HOST_PORT_POSTGRES variable is not set. Defaulting to a blank string.
WARNING: The HOST_PORT_MYSQL variable is not set. Defaulting to a blank string.
ERROR: The Compose file './docker-compose.yml' is invalid because:
services.mysql.ports is invalid: Invalid port ":3306", should be [[remote_ip:]remote_port[-remote_port]:]port[/protocol]
services.postgres.ports is invalid: Invalid port ":5432", should be [[remote_ip:]remote_port[-remote_port]:]port[/protocol]
services.httpd.ports is invalid: Invalid port ":80", should be [[remote_ip:]remote_port[-remote_port]:]port[/protocol]

**Comment by cytopia** [comment]
You have invalidated your `.env` file.
Do not comment out any stuff. Everything inside this file is required. And you will have to decide upon one version of each service.

Currently you cannot disable a single service. The only way to do so is to remove Postgres from the `docker-compose.yml` file. 

The upcoming release (in about 2-3 weeks) will have the ability to selectively decide which containers to start :-)

**Comment by Bobbydum** [comment]
On last master everything works fine/
