### ISSUE TITLE
Run php/nginx with same UID/GUID (my home user 1000)

### ISSUE THREAD

**Issue by fe3dback** [cytopia/devilbox#53]
Hello, i have file cms, this script very love to save/edit random files in random place in document root. Every modified files saved with docker uid/gid (like this):

```bash
~/server/project/htdocs/tmp/cache (master)
> ls -la
total 68
drwxrwxrwx 17 neo neo 4096 апр 26 09:58 . // neo:neo is my home user
drwxrwxr-x 19 neo neo 4096 апр 25 18:10 ..
drwxr-xr-x  2  48  48 4096 апр 25 18:02 08 // 48:48 is docker user (not exist in host machine)
drwxr-xr-x  2  48  48 4096 апр 25 18:02 09
```
```bash
> id 
uid=1000(neo) gid=1000(neo) groups=1000(neo),4(adm),24(cdrom),27(sudo),30(dip),46(plugdev),113(lpadmin),128(sambashare),999(docker)
```

How to use same uid/gid (user 1000) in docker containers? When cms save any files, i lose ownership on it in host system, and get many other problem with ownership.

**Comment by cytopia** [comment]
Hi @fe3dback 
Currently does not work. This will however be integrated into the next version (in around 2-3 weeks).

I am afraid, for you you will have to manually change ownership from time to time:
```shell
sudo chown -R neo:neo ~/server/project/htdocs/
```

**Comment by cytopia** [comment]
## Current workaround

You can clone all you required docker containers from my github account.
Each repository contains `build/docker-build.sh` script to easily build/rebuild your containers.

Bevor you do this however, you can change the UID/GID in each required container. As an example have a look at this Dockerfile:

https://github.com/cytopia/docker-php-fpm-7.0/blob/master/Dockerfile#L26

Simply change `MY_UID` and `MY_GID` to your desired value and execute `build/docker-build.sh` afterwards.

**Comment by fe3dback** [comment]
This is good solution for my at this moment. Work perfectly.

**Comment by cytopia** [comment]
UID/GID integration is on the way.
https://github.com/cytopia/docker-php-fpm-5.4/pull/16

Will be applied to all php container once the PR is feature-complete and bug-free

**Comment by fe3dback** [comment]
cool, i can test this, when php >= 7.0 will be ready.

**Comment by cytopia** [comment]
@fe3dback Now included in the devilbox by default
