### ISSUE TITLE
Add @vue/cli + @vue/cli-service-global

### ISSUE THREAD

**Issue by giantbits** [cytopia/devilbox#536]
#### ISSUE TYPE

 - Feature request

#### SUMMARY
Add [@vue/cli + @vue/cli-service-global](https://cli.vuejs.org/) to enable MEVN-Stack. 

#### Goal
As MEAN isn't the only way to go these days it would be great to have full @vue/cli + @vue/cli-service-global integration to enable development using MEVN stack.

**Comment by cytopia** [comment]
Sounds good, I hope I can still squeeze it into the release. In order to satisfy you already, you can use the autostart feature to have it installed on every `docker-compose up` automatically: https://devilbox.readthedocs.io/en/latest/autostart/custom-scripts-globally.html
