### ISSUE TITLE
write /var/lib/docker/tmp/GetImageBlob220119603: no space left on device

### ISSUE THREAD

**Issue by krebbi** [cytopia/devilbox#539]
It seems that devilbox reached the maximum docker size on my mac.

write /var/lib/docker/tmp/GetImageBlob220119603: no space left on device

running ./update-docker.sh results in:

![Bildschirmfoto 2019-03-12 um 21 52 39](https://user-images.githubusercontent.com/3884521/54235284-322bc280-4511-11e9-80b7-f02be6ecb65f.png)

**Comment by krebbi** [comment]
oh, and is it really 64GB in total? 

![Bildschirmfoto 2019-03-12 um 21 56 01](https://user-images.githubusercontent.com/3884521/54235540-bb42f980-4511-11e9-89a0-d661438ff171.png)

**Comment by cytopia** [comment]
This is not related to the Devilbox, but rather due to the Docker implementation on MacOS. You can either remove unused images or increase the volume size for all your Docker images:

https://gist.github.com/stefanfoulis/5bd226b25fa0d4baedc4803fc002829e

**Comment by krebbi** [comment]
In case anybody else is running into this problem, at docker they are discussing this since August 2016. 

https://github.com/docker/for-mac/issues/371#issuecomment-315385246

Increasing the disk image size will not solve the issue.

**Comment by cytopia** [comment]
That seems to be the solution so far: https://github.com/docker/for-mac/issues/371#issuecomment-242047368

**Comment by krebbi** [comment]
I'm trying https://github.com/docker/for-mac/issues/371#issuecomment-407878884 right now. 

If you want i'll let you know if it works or not.

**Comment by cytopia** [comment]
Sure let me know.

When I was still on MacOS (~3 years back), I had the same issue. I was pretty sure, that deleting images solved that problem.

**Comment by cytopia** [comment]
@krebbi did that work?

**Comment by krebbi** [comment]
will have to look at it over some time to see if the image is growing or if it has a stable size. 

coming back to you in a few days.

**Comment by cytopia** [comment]
Here is some more input as well: https://forums.docker.com/t/no-space-left-on-device-error/10894/17

I will nonetheless close this issue, as it is not Devilbox related.

**Comment by cytopia** [comment]
https://devilbox.readthedocs.io/en/latest/support/troubleshooting.html#no-space-left-on-device
