### ISSUE TITLE
Add jpeg support to GD PHP module.

### ISSUE THREAD

**Issue by skylundy** [cytopia/devilbox#544]
#### ISSUE TYPE

 - Feature request

#### SUMMARY
The GD PHP module included is incomplete and does not have JPEG Support or libJPEG version listed in PHP Info. GD would be better with jpeg support.

#### Goal
I'm not sure where else this would have an effect but the CMS I develop with (ProcessWire) is throwing an error because it relies on the jpeg functionality of GD for image uploads/processing. This may solve more problems elsewhere as well. Would make Devilbox usable for development for more people.

**Comment by cytopia** [comment]
Valid point and good catch. I will have to dig a bit how to actually include it.

**Comment by cytopia** [comment]
@skylundy I just double checked the compile options for gd:

```
--with-gd --with-webp-dir=/usr --with-jpeg-dir=/usr --with-png-dir=/usr --with-zlib-dir=/usr --with-xpm-dir=/usr --with-freetype-dir=/usr --enable-gd-jis-conv --enable-gd-native-ttf
```

It should actually bundle jpeg:

* https://github.com/devilbox/docker-php-fpm/blob/master/build/ansible/group_vars/all/mods.yml#L283
* https://github.com/devilbox/docker-php-fpm/blob/master/Dockerfiles/mods/Dockerfile-7.1#L171

Do you see anything which is done wrong here?

**Comment by cytopia** [comment]
Also looking at the phpinfo() output, jpeg is bundled.

![Screenshot 2019-03-16 11-48-16  selection](https://user-images.githubusercontent.com/12533999/54474143-78b74080-47e1-11e9-9952-ebea041e6604.png)

**Comment by skylundy** [comment]
Yours looks right, mine looks wrong... Not sure what the fix is. I've pulled the latest version.

![Screenshot from 2019-03-17 08-47-30](https://user-images.githubusercontent.com/1612665/54493824-73b1ca00-4891-11e9-8105-a20c64e6b650.png)

**Comment by cytopia** [comment]
So which PHP version are you using and on which Devilbox git commit are you on?

**Comment by skylundy** [comment]
I'm on the latest commit. I did find the solution though- I was on PHP 7.4, I went down to 7.3 and jpeg support is now available.

**Comment by cytopia** [comment]
7.4 and 8.0 are not stable and thus not fully supported by this project as well. I will close this issue. If you find a way to integrate full jpeg support into PHP 7.4 please do so via PR, I would be happy to review.

**Comment by skylundy** [comment]
Thanks for your fast response, my mistake on this!
