### ISSUE TITLE
use .localhost instead of .loc

### ISSUE THREAD

**Issue by icf20** [cytopia/devilbox#545]
now that google "owns" .dev 
maybe is time to consider using something that never gets to be a top level domain, so maybe want to change from .loc to .localhost

**Comment by tzimpel** [comment]
.localhost does not work properly in some browsers. Maybe .local or any of the other reserved domains from RFC 2606 is an alternative.

I'm personally using .local

**Comment by cytopia** [comment]
@icf20 see here: https://devilbox.readthedocs.io/en/latest/configuration-files/env-file.html?highlight=tld_suffix#tld-suffix

**Comment by Luc45** [comment]
+1 to .localhost, as it works out-of-the-box with systemd-resolved: https://www.freedesktop.org/software/systemd/man/systemd-resolved.service.html#Synthetic%20Records
