### ISSUE TITLE
ODBC Driver Installation via Autostart Commands on Windows Host

### ISSUE THREAD

**Issue by ianwatters** [cytopia/devilbox#549]
### ISSUE TYPE

 - Bug Report

### Checklist

* [x] `.env` file is attached
* [ ] `docker-compose.override.yml` is attached (if it exists)
* [ ] Custom configs from `cfg/` dir are attached (if customized)
* [x] `docker-compose logs` and `log/` output is added
* [x] I've looked through the docs: https://devilbox.readthedocs.io/en/latest/
* [x] I've looked through existing issues: https://github.com/cytopia/devilbox/issues
* [x] I've read troubleshooting: https://devilbox.readthedocs.io/en/latest/support/troubleshooting.html

### OS / ENVIRONMENT

1. Host operating system and version: Windows 10 Build 17134
2. (Windows) Native Docker or Docker Toolbox: Docker for Windows
3. Docker version: Docker version 18.09.2, build 6247962
4. Docker Compose version: docker-compose version 1.23.2, build 1110ad01
5. (Linux) Is SELinux enabled?: N/A
6. What git commit hash are you on?: 3cbbdb35

### SUMMARY

The php autostart commands for php do not appear to be working correctly with Windows installations. I've followed all installation steps listed in the documentation for prerequisites and the like, but when I try to enable the ODBC driver for sqlsrv/pdo_sqlsrv via autostart scripts, localhost starts returning a 402 error. 

### STEPS TO REPRODUCE

I don't have the resources to test on other machines, but I've found this issue to be present with minor modification to devilbox as is, using the example .env with only small changes to update the root directory (in my case to the location of our repo, one directory up from where I have devilbox) and enable the PHP sqlsrv and PDO_sqlsrv modules. 

For the unixODBC autostart commands .sh file, I used the example given in the documentation.

### EXPECTED BEHAVIOUR

Expected behavior would be the unixODBC being enabled in the environment, and sqlsrv/PDO_sqlsrv running correctly.

### ACTUAL BEHAVIOUR

Attempts to connect to localhost addresses result in a 402 error.

### OTHER INFORMATION
Logs are attached as required, however I found the below excerpt to be related. 

[33mphp_1    |[0m [0;34m[INFO] Executing custom startup script: 02-ms-odbc-driver.sh[0m
[33mphp_1    |[0m /startup.1.d/02-ms-odbc-driver.sh: line 9: $'\r': command not found
[33mphp_1    |[0m /startup.1.d/02-ms-odbc-driver.sh: line 10: $'\r': command not found
[33mphp_1    |[0m /startup.1.d/02-ms-odbc-driver.sh: line 14: $'\r': command not found
[33mphp_1    |[0m /startup.1.d/02-ms-odbc-driver.sh: line 19: $'\r': command not found
[33mphp_1    |[0m /startup.1.d/02-ms-odbc-driver.sh: line 20: $'\r': command not found
[33mphp_1    |[0m /startup.1.d/02-ms-odbc-driver.sh: line 21: $'\r': command not found
[33mphp_1    |[0m /startup.1.d/02-ms-odbc-driver.sh: line 25: $'\r': command not found
[33mphp_1    |[0m /startup.1.d/02-ms-odbc-driver.sh: line 30: $'\r': command not found
[33mphp_1    |[0m /startup.1.d/02-ms-odbc-driver.sh: line 31: $'\r': command not found
[33mphp_1    |[0m /startup.1.d/02-ms-odbc-driver.sh: line 61: syntax error: unexpected end of file
[33mphp_1    |[0m [0;31m[ERR]  Failed to execute script[0m
...
[36mhttpd_1  |[0m 2019/03/21 20:31:10 [emerg] 259#259: host not found in upstream "php" in /etc/httpd/conf.d/localhost.conf:41
[36mhttpd_1  |[0m nginx: [emerg] host not found in upstream "php" in /etc/httpd/conf.d/localhost.conf:41

I can't say I'm very personally familiar with bash scripts, but the start process doesn't seem to be parsing the .sh files correctly. A similar installation running on a linux ubuntu vm had no problems with the autostart scripts.

Also worth noting, I am able to get the unixODBC commands running via:
```
docker-compose exec --user devilbox php bash -l
```
Followed by (from a feature request post, prior to the implementation of autostart scripts):
```
MSODBC_URL="https://packages.microsoft.com/debian/8/prod/pool/main/m/msodbcsql17/"
MSODBC_DEB="$( curl -sS "${MSODBC_URL}" | grep -Eo 'msodbcsql[-._0-9]+?_amd64\.deb' | tail -1 )"
curl -sS "${MSODBC_URL}${MSODBC_DEB}" > "/tmp/${MSODBC_DEB}"
sudo ACCEPT_EULA=Y  dpkg -i "/tmp/${MSODBC_DEB}"
rm -f "/tmp/${MSODBC_DEB}"
```

#### Start command

```
$ docker-compose up httpd php
```

#### File and user permissions (Linux & MacOS)
N/A

[Env.txt](https://github.com/cytopia/devilbox/files/2993950/Env.txt)
[log.zip](https://github.com/cytopia/devilbox/files/2993969/log.zip)

**Comment by cytopia** [comment]
@ianwatters it seems that something is wrong with this script.

Can you do the following please:

1. Check your current setup just without the custom autostart file (everything else as you've configured already) and see if it does at least startup properly and you're able to see the intranet
2. Additionally as a second step (once you have checked the above), please revert everything to stock configuration (`.env` file - except uid/gid), any other customizations done and just test your autostart script with this.

Once you've checked the above two cases we can probably already cancel out a few options.

**Comment by ianwatters** [comment]
@cytopia 

I can confirm that everything runs correctly and as expected without the autostart file, with and without my customizations to the .env file. I am able to view the intranet via localhost in both cases.

In the case of the stock configuration .env **with** the autostart script, I still encounter the issue as described above, with the same errors regarding the script. It may be worth noting that I am using the example script: cfg/php-startup-7.2/02-ms-odbc-driver.sh-example with no additional modification.

**Comment by cytopia** [comment]
The example script works fine here. Also note that "without any modifications* the example script won't run at all, as you explicitly need to set `ACCEPT_EULA=Y`, otherwise it will just skip everything.

```
[33mphp_1 |[0m [0;34m[INFO] Executing custom startup script: 02-ms-odbc-driver.sh[0m
[33mphp_1 |[0m /startup.1.d/02-ms-odbc-driver.sh: line 9: $'\r': command not found
[33mphp_1 |[0m /startup.1.d/02-ms-odbc-driver.sh: line 10: $'\r': command not found
```
All the error lines printed above are actually all empty lines within the script. The `$\r` indicates that there might be an issue with newlines. Did you alter or re-save this script within Windows with Windows linefeeds enabled?

Can you attach the exact file you have in place.

**Comment by ianwatters** [comment]
That was it! While I am aware of the ACCEPT_EULA line, when I said without modification I meant I simply changed the file extension of the example script from .sh-example to .sh within file explorer, just to see if I could get the script to process without any of the "$'\r': command not found" errors, given that line 9 and 10 in the file occur before the EULA acceptance. What I was not aware of is that changes to a file name/extension via Windows explorer actually changes the linefeeds. 

Suffice to say, saving the file via Notepad++ and enforcing the Unix LF fixed the problem. Thank you for your assistance!

**Comment by cytopia** [comment]
Good to hear. I've invalidated this issue as being a bug and will close it as it is solved.
