### ISSUE TITLE
how to custom root path for subdomain

### ISSUE THREAD

**Issue by dev-vadym** [cytopia/devilbox#556]
Hello
How to custom root path for subdomain?
example:

project.loc
devilbox/data/www/project/htdocs/

api.project.loc
devilbox/data/www/project/api/

**Comment by cytopia** [comment]
You can achieve this via custom vhost-gen configuration. For this specific use case there is already an example in the documentation: https://devilbox.readthedocs.io/en/latest/vhost-gen/example-add-subdomains.html
