### ISSUE TITLE
Add angular cli (ng) and open port 4200 for ng serve

### ISSUE THREAD

**Issue by doingwebthings** [cytopia/devilbox#557]
#### ISSUE TYPE

 - Feature request

#### SUMMARY

Add angular cli (ng) and open port 4200 for ng serve

#### Goal

Thanks for developing devilbox, it´s an amzing experience so far :)

It would be very helpful if ng was available as a tool inside of the php-container. While you can use npx ( for example ``` npx @angular/cli new frontend```) as a workaround it would feel more natural to use ng directly.

Also ```ng serve``` runs on port 4200, so it would be nice if 4200 would be exposed to the host. 

Is ist possible to expose ports via .env-file?

Cheers

**Comment by cytopia** [comment]
Hi @doingwebthings 

I will ship `ng` with the next PHP images.

For the exposure of `4200` there are already two ways to do it:

1. Docker Compose Override: https://devilbox.readthedocs.io/en/latest/configuration-files/docker-compose-override-yml.html
2. Reverse Proxy: https://devilbox.readthedocs.io/en/latest/examples/setup-reverse-proxy-nodejs.html
