### ISSUE TITLE
Add Lumen PHP Micro-framework by Laravel

### ISSUE THREAD

**Issue by handripangestiaji** [cytopia/devilbox#559]
Please kindly add Lumen by Laravel, thanks

**Comment by cytopia** [comment]
Is there anything missing which prevents you to use Lumen?

**Comment by handripangestiaji** [comment]
Nothing is missing, i just need to use Lumen micro framework with Lumen CLI / installer. But nevermind i think i can use composer instead to create all my lumen projects

**Comment by cytopia** [comment]
Can you please provide some more information on what you are actually intending to have on the Devilbox.

**Comment by vikas5914** [comment]
I think just like laravel installer, We should include the lumen installer as well. 

https://lumen.laravel.com/docs/5.8

**Comment by handripangestiaji** [comment]
Like @vikas5914 said, there's lumen installer like laravel installer. Sorry if my request doesn't clear enough

**Comment by vikas5914** [comment]
I created an issue on  https://github.com/devilbox/docker-php-fpm/issues/109
