### ISSUE TITLE
[Request / Voting] what tools should be available in the php container by default?

### ISSUE THREAD

**Issue by cytopia** [cytopia/devilbox#56]
In order to work completely inside the `php` container to run database migrations, drush, composer etc, there will have to be a set of pre-installed tools available inside this container.

Let me know what tools you would like to have in each php container as well as if you need different versions of those tools.

**Current list (will be extended)**

* [x] [drush](https://www.drupal.org/project/drush)
* [x] [drupal console](https://drupalconsole.com/)
* [x] [composer](https://getcomposer.org/)

**Comment by alexd73** [comment]
Sorry, but I can`t vote (checkbox is disabled). And I want add to the list a [Drupal console](https://drupalconsole.com/). (however, if will be added Composer, I can install Drupal console manuality)

- [ ] Drupal console

**Comment by cytopia** [comment]
@alexd73 voting doesn't work, so I will just update the first post whenever a new request comes in

**Comment by cytopia** [comment]
@alexd73
FYI:
drupal-console requires at least php 5.5, so unfortunately that won't make it into the php 5.4 container (will go into all others).

**Comment by cytopia** [comment]
@alexd73 is integrated into new release. Update your branch.
