### ISSUE TITLE
Error ?

### ISSUE THREAD

**Issue by wcizmowski** [cytopia/devilbox#560]
#### ISSUE TYPE

 - Question

#### SUMMARY

I have error on start:
 Named volume "devilbox-mongo-3.7:/data/db:rw" is used in service "mongo" but no declaration was found in the volumes section.

**Comment by Flouss** [comment]
Happened to me when I had all the MONGO_SERVER options commented in the .env file.
Same thing also happens for REDIS_SERVER, PGSQL_SERVER.

**Comment by science695** [comment]
My recommendation is not to comment out the env lines for a service you don't need, but instead only bring up the services you need:

> docker-compose up -d bind httpd php mysql

I put that in the rebuild.sh file and just run that

**Comment by cytopia** [comment]
@wcizmowski `devilbox-mongo-3.7` is a non-stable release and therefore not added to the Devilbox. Stick with even numbers. You can read up more on Mongo versioning: https://docs.mongodb.com/manual/release-notes/#mongodb-version-numbers
