### ISSUE TITLE
DATADIR entries missing in env-example

### ISSUE THREAD

**Issue by tobx** [cytopia/devilbox#567]
Why were the following entries removed from the `env-example` file?

- `HOST_PATH_MYSQL_DATADIR`
- `HOST_PATH_PGSQL_DATADIR`
- `HOST_PATH_MONGO_DATADIR`

**Comment by llaville** [comment]
Because the latest version used docker volumes now.
See volumes part of docker-compose.yml file

**Comment by cytopia** [comment]
@tobx

I hope @llaville answer is sufficient and I will close this issue.

**Comment by tobx** [comment]
@llaville 

Ok, thank you.

@cytopia 

Yes, but just to mention it, `$HOST_PATH_MYSQL_DATADIR` is still referenced twice in the section "MySQL root user password".

**Comment by cytopia** [comment]
@tobx thanks for that. I've fixed it for the upcoming PR: https://github.com/cytopia/devilbox/pull/568
