### ISSUE TITLE
Add RabbitMQ

### ISSUE THREAD

**Issue by Vasary** [cytopia/devilbox#57]
Please add RabbitMQ container

**Comment by cytopia** [comment]
@Vasary 

I will need to know a few things in order to decide about how to add it and link it to the rest.

* What is your use-case (can you give some examples)
* Does it require access from the host?
* Does it require access from within the php container?

**Comment by Vasary** [comment]
@cytopia 
1. In my project all of request are deferred via RabbitMQ
2. Yes, it use web ui for monitoring queue
3. Yes, it require access from php container

I think a very good idea opportunity use PSQL or MySQL or both

**Comment by cytopia** [comment]
@Vasary 
Could you give me a more technical example please. Such as: Does it speak with a remote sock on a specific port? Or do you simply need some php module to be loaded?

**Comment by cytopia** [comment]
@Vasary  finally found some time to play around with RabbitMQ.

Should already be working in [Release v0.13](https://github.com/cytopia/devilbox/pull/135). Only thing that's missing is Intranet layout adaptions and Documentation.

**Comment by eortega** [comment]
@cytopia thanks for add rabbitmq, nowadays i'm using a custom devilbox setup for my projects, but i see that soon i could use devilbox out of the box.

**Comment by cytopia** [comment]
@eortega @Vasary RabbitMQ will be available in a few days.

**Comment by cytopia** [comment]
@Vasary @eortega RabbitMQ is finally making it into the Devilbox: https://github.com/cytopia/devilbox/pull/354

**Comment by cytopia** [comment]
https://devilbox.readthedocs.io/en/latest/custom-container/enable-rabbitmq.html#custom-container-enable-rabbitmq

**Comment by eortega** [comment]
Hey @cytopia it's really good to hear that; thanks for your effort in this project !!

I'm gonna try to update devilbox to newest version this weekend.

Regards.
