### ISSUE TITLE
APC Admin GUI 

### ISSUE THREAD

**Issue by llaville** [cytopia/devilbox#574]
#### ISSUE TYPE

 - Feature request

#### SUMMARY

Add an admin GUI for APC (APCu) cache system like PHP Memcache Admin.
Data are refreshed in live time !

#### Goal

Add ability to live monitor data in APC(u) cache.

I propose to include the vendor https://github.com/jithinjose2/APC-Admin

We have to adjust a little to be compatible APC/APCu (because the project was not updated since a long time).

1. Download ZIP from project page at https://github.com/jithinjose2/APC-Admin/archive/master.zip

1. Unzip content in Devilbox folder `.devilbox/www/htdocs/vendor/`

1. Modify the `.devilbox/www/include/Html.php` around line 111 to add entry in Tools Menu
    ```php
		array(
			'name' => 'APC cache GUI',
			'path' => '/vendor/APC-Admin-master/index.php',
			'target' => '_blank'
		),
    ```
1. Use optional config `apc.conf.php` file as APC polyfill (included in `init.php` file)

```php
// apc.conf.php
// APC polyfill.
if (function_exists('apcu_add') && !function_exists('apc_add')) {
	function apc_cache_info() {
		return call_user_func_array('apcu_cache_info', func_get_args());
	}

	function apc_clear_cache() {
		return call_user_func_array('apcu_clear_cache', func_get_args());
	}

	function apc_sma_info() {
		return call_user_func_array('apcu_sma_info', func_get_args());
	}

	function apc_delete() {
		return call_user_func_array('apcu_delete', func_get_args());
	}

	function apc_store() {
		return call_user_func_array('apcu_store', func_get_args());
	}

	class APCIterator extends APCUIterator {}
}
```

**Some Screenshots**

![Home](https://user-images.githubusercontent.com/364342/57180777-7346b000-6e8c-11e9-8910-0cd58a9a694e.png)

![Opcache](https://user-images.githubusercontent.com/364342/57180792-8194cc00-6e8c-11e9-902d-f838aa2b9e93.png)

![User_Cache](https://user-images.githubusercontent.com/364342/57180794-86f21680-6e8c-11e9-8173-9550fd878e5f.png)

**Comment by cytopia** [comment]
@llaville I have got this working as per your instructions and tried this. I dind't find any valuable information in the Gui though. Any hints on why this is desired or what you'd do with that?

**Comment by llaville** [comment]
@cytopia The APC Admin GUI is no more maintained, and after using it in real application context usage, I don't see, me too, any valuable information.

I realized that this feature is a bit obsolete, because PHP echo system used more Redis or Memcache as Cache Backend. 
Symfony projects used also APCu Backend for PHPDoc annotations, but Symfony Profiler is more efficiency that this APC Admin GUI.

I think we could close this report !

**Comment by cytopia** [comment]
Closing in favour of: https://github.com/cytopia/devilbox/issues/654
