### ISSUE TITLE
How to setup custom domains like local.project.com

### ISSUE THREAD

**Issue by elamurugan** [cytopia/devilbox#576]
#### ISSUE TYPE

 - How to setup custom domains like local.project.com

#### SUMMARY
Currently it has option to change only TLD's like project.test or project.local or project.loc

#### Goal
I am trying to set this vhosts to be like local.project.com or project.local.domain

**Comment by cytopia** [comment]
This way round does not work with `TLD_SUFFIX`. You can however fully control the web server configuration and set whatever project name you want. See here: https://devilbox.readthedocs.io/en/latest/vhost-gen/example-add-subdomains.html#step-2-adjust-apache22-yml

**Note:** Going this way will not show them in the Devilbox intranet vhost page.

**Comment by elamurugan** [comment]
@cytopia Thank you for the update/reference links. 
This worked for me, thank you so much for giving this one stop solution for every environment setup.

In case if anyone looking for solution on this =>
Copied the **cfg\vhost-gen\apache24.yml-example-vhost** file to actual project folder under **data\www\[project_name]\.devilbox\apache24.yml** and added only this line 


 <VirtualHost __DEFAULT_VHOST__:__PORT__>
      ServerName __VHOST_NAME__
      Protocols  __HTTP_PROTO__
      **ServerAlias  local.whatevername.fr local.whatevername.de**

      CustomLog  "__ACCESS_LOG__" combined
      ErrorLog   "__ERROR_LOG__"

  __REDIRECT__
  __SSL__
  __VHOST_DOCROOT__
  __VHOST_RPROXY__
  __PHP_FPM__
  __ALIASES__
  __DENIES__
  __SERVER_STATUS__
      # Custom directives
  __CUSTOM__
  </VirtualHost>

**Comment by science695** [comment]
A note of caution, don't hard code the ServerAlias like that if you have multiple project folders, otherwise the hardcoded alias will only work on 1 of them, and apache may randomly pick which one to load based on some sorting order of the generated files.

Much better for multi-subdomains to do something using the __VHOST_NAME placeholder in it for uniqueness.
