### ISSUE TITLE
Blackfire and proxy support with dedicated server

### ISSUE THREAD

**Issue by llaville** [cytopia/devilbox#579]
### ISSUE TYPE

 - Bug Report

### Checklist

* [ ] `.env` file is attached
* [ ] `docker-compose.override.yml` is attached (if it exists)
* [ ] Custom configs from `cfg/` dir are attached (if customized)
* [ ] `docker-compose logs` and `log/` output is added
* [X] I've looked through the docs: https://devilbox.readthedocs.io/en/latest/
* [X] I've looked through existing issues: https://github.com/cytopia/devilbox/issues
* [X] I've read troubleshooting: https://devilbox.readthedocs.io/en/latest/support/troubleshooting.html

### OS / ENVIRONMENT

1. Host operating system and version: Linux Ubuntu 16.04 LTS
3. Docker version: Docker version 18.09.5, build e8ff056
4. Docker Compose version: docker-compose version 1.18.0, build 8dd22a9
5. (Linux) Is SELinux enabled?:
6. What git commit hash are you on?:  6bc99d02b2e3239a3cd185ef531d6d52938256cc

### SUMMARY

Be able to use Blackfire on dedicated server with proxy support !

### STEPS TO REPRODUCE

I've recently try to profile an application (Symfony 3.4 / PHP 7.1) with Firefox Companion 1.18.2 for my current Customer that have a Blackfire Enterprise Edition

The collector is located on a dedicated server (private) rather than http://blackfire.io, and it's reachable via a proxy.

### EXPECTED BEHAVIOUR

Profile requests and see profile generated (graph and more ... )

### ACTUAL BEHAVIOUR

Cannot access to dedicated server (collector) 
Message [Are You Authorized to Profile this Page? Probe Not Found or Invalid signature](https://blackfire.io/docs/up-and-running/troubleshooting#are-you-authorized-to-profile-this-page-probe-not-found-or-invalid-signature) is displayed 

### OTHER INFORMATION

I suggest to upgrade https://github.com/cytopia/devilbox/blob/master/autostart/configure-blackfire-cli.sh-example to be able to support custom collector ( see BF_COLLECTOR ) and http-proxy ( see BF_PROXY )

Here is my version `autostart/configure-blackfire-cli.sh`
```
#!/usr/bin/env bash

set -e
set -u
set -o pipefail


###
### Pre-flight check
###
if ! command -v blackfire >/dev/null 2>&1; then
	echo "No blackfire cli found, skipping configuration."
	exit 0
fi


###
### Blackfire Client (cli) Variables
###
# Blackfire Client ID via env: BLACKFIRE_SERVER_ID
BF_CLIENT_ID=
# Blackfire Client Token via env: BLACKFIRE_SERVER_TOKEN
BF_CLIENT_TOKEN=
# Blackfire client configuration file
BF_CLIENT_INI="/home/devilbox/.blackfire.ini"
# Blackfire Data Collector 
BF_COLLECTOR="https://blackfire.io"
# Blackfire Proxy
BF_PROXY=

###
### Get Client ID and Client Token
###
if BF_CLIENT_ID="$( env | grep -Eo '^BLACKFIRE_CLIENT_ID=.*$' )"; then
	BF_CLIENT_ID="${BF_CLIENT_ID#*=}"
fi

if BF_CLIENT_TOKEN="$( env | grep -Eo '^BLACKFIRE_CLIENT_TOKEN=.*$' )"; then
	BF_CLIENT_TOKEN="${BF_CLIENT_TOKEN#*=}"
fi

if BF_COLLECTOR="$( env | grep -Eo '^BLACKFIRE_COLLECTOR=.*$' )"; then
	BF_COLLECTOR="${BF_COLLECTOR#*=}"
fi

if BF_PROXY="$( env | grep -Eo '^HTTP_PROXY=.*$' )"; then
	BF_PROXY="${BF_PROXY#*=}"
fi

###
### Create Client (cli) Config
###
{
	echo "[blackfire]";
	echo ";";
	echo "; This is a configuration file for Blackfire.";
	echo ";";
	echo "";
	echo ";";
	echo "; setting: ca-cert";
	echo "; desc   : Sets the PEM encoded certificates to use";
	echo "; default:";
	echo "ca-cert=";
	echo "";
	echo ";";
	echo "; setting: client-id";
	echo "; desc   : Sets the Client ID used for API authentication";
	echo "; default:";
	echo "client-id=${BF_CLIENT_ID}";
	echo "";
	echo ";";
	echo "; setting: client-token";
	echo "; desc   : Sets the Client Token used for API authentication";
	echo "; default:";
	echo "client-token=${BF_CLIENT_TOKEN}";
	echo "";
	echo ";";
	echo "; setting: endpoint";
	echo "; desc   : Sets the API endpoint";
	echo "; default: https://blackfire.io";
	echo "endpoint=${BF_COLLECTOR}";
	echo "";
	echo ";";
	echo "; setting: http-proxy";
	echo "; desc   : Sets the HTTP proxy to use";
	echo "; default:";
	echo "http-proxy=${BF_PROXY}";
	echo "";
	echo ";";
	echo "; setting: https-proxy";
	echo "; desc   : Sets the HTTPS proxy to use";
	echo "; default:";
	echo "https-proxy=${BF_PROXY}";
	echo "";
	echo ";";
	echo "; setting: timeout";
	echo "; desc   : Sets the Blackfire API connection timeout";
	echo "; default: 15s";
	echo "timeout=30s";
} > "${BF_CLIENT_INI}"

chown devilbox:devilbox "${BF_CLIENT_INI}"
chmod 0600 "${BF_CLIENT_INI}"
```
It will produce a `/home/devilbox/.blackfire.ini` file 

**The ISSUE is related to contents of `/etc/blackfire/agent` that is not updated as expected**

Following contents are not changed 
```
;
; setting: collector
; desc   : Sets the URL of Blackfire's data collector
; default: https://blackfire.io
collector=https://blackfire.io

;
; setting: http-proxy
; desc   : Sets the HTTP proxy to use
; default: 
http-proxy=

;
; setting: https-proxy
; desc   : Sets the HTTPS proxy to use
; default: 
https-proxy=
```

When I  EDIT the `/etc/blackfire/agent` and change collector (with BLACKFIRE_COLLECTOR env var value) and proxy http/https (with HTTP_PROXY env var value) See `.env` file 

All run FINES

#### Blackfire Agent 

```
./shell.sh
devilbox@php-7.1.28 in /shared/httpd $ blackfire-agent -v
blackfire-agent 1.25.0 linux amd64 gc 2019-04-17T08:24:07+0000

devilbox@php-7.1.28 in /shared/httpd $ php --ri blackfire

blackfire

Blackfire => enabled
Blackfire => 1.24.4~linux-x64-non_zts71
Timing measurement => cgt
Sessions support => enabled
Num of CPU => 4
Profiling heap memory => 0 Kb
Main instance trigger mode => HTTP header triggered
Main instance => disabled

Directive => Local Value => Master Value
blackfire.agent_socket => unix:///var/run/blackfire/agent.sock => unix:///var/run/blackfire/agent.sock
blackfire.agent_timeout => 0.25 => 0.25
blackfire.env_id => no value => no value
blackfire.env_token => no value => no value
blackfire.log_level => 1 => 1
blackfire.log_file => no value => no value
blackfire.server_id => no value => no value
blackfire.server_token => no value => no value


Blackfire developed by Blackfire

```

#### .env part of file 

```
BLACKFIRE_SERVER=latest
BLACKFIRE_COLLECTOR=http://blackfire.vpod1.carrefour.com

BLACKFIRE_CLIENT_ID=<OFFUSCATED>
BLACKFIRE_CLIENT_TOKEN=<OFFUSCATED>

BLACKFIRE_SERVER_ID=<OFFUSCATED>
BLACKFIRE_SERVER_TOKEN=<OFFUSCATED>

HTTP_PROXY=http://10.176.205.3:8080
HTTPS_PROXY=http://10.176.205.3:8080
```

#### Docker Compose Override

```
  blackfire:
    image: blackfire/blackfire:${BLACKFIRE:-latest}
    hostname: blackfire
    environment:
      - BLACKFIRE_SERVER_ID=${BLACKFIRE_SERVER_ID:-id}
      - BLACKFIRE_SERVER_TOKEN=${BLACKFIRE_SERVER_TOKEN:-token}
      - BLACKFIRE_CLIENT_ID=${BLACKFIRE_CLIENT_ID:-id}
      - BLACKFIRE_CLIENT_TOKEN=${BLACKFIRE_CLIENT_TOKEN:-token}
    networks:
      app_net:
        ipv4_address: 172.16.238.200
    depends_on:
      - bind
      - php
      - httpd
```

#### Start command

```
$ docker-compose up -d
```

Hope my report is enough.
I'm at your disposal to help you as always !

**Comment by cytopia** [comment]
> When I EDIT the /etc/blackfire/agent and change collector (with BLACKFIRE_COLLECTOR env var value) and proxy http/https (with HTTP_PROXY env var value) See .env file

Afaik the agent runs within its own Docker container (`blackfire/blackfire`, if started) and doesn't need to be configured within the PHP container or am I missing something here?

**Comment by llaville** [comment]
> Afaik the agent runs within its own Docker container (blackfire/blackfire, if started) and doesn't need to be configured within the PHP container or am I missing something here?

I've investigated yesterday at my office, and I think I've a good feeling (to solve it easily). 
I'll come back to you after a last test on monday (I need to be at my office to be able to access private blackfire dedicated server).

**Comment by llaville** [comment]
I've let down usage of Blackfire at my Office, because nobody seems interrested to use it ! I'm sad to see such professional attitude :( 
So I've decided to close this issue.
