### ISSUE TITLE
Allow symlinked scripts in autostart

### ISSUE THREAD

**Issue by HansCz** [cytopia/devilbox#583]
#### ISSUE TYPE

 - Feature request

#### SUMMARY
Allow scripts in devilbox/autostart to be symlinks to scripts elsewhere

#### Goal
To be able to version control autostart scripts, it is necessary to put a symlink to the script in the autostart directory, instead of the file proper. The file proper can then exist elsewhere and be version controlled.

**Comment by HansCz** [comment]
Note that the path the symlink points to is inside a mounted volume, so I assume it is accessible at the time the autostart scripts run.

**Comment by cytopia** [comment]
@HansCz good catch, I wasn't even aware that this did not work. Fix is on the way: https://github.com/devilbox/docker-php-fpm/pull/117

**Comment by HansCz** [comment]
Excellent! :)
