### ISSUE TITLE
Could you please add the directory "yaml-nuggets" to the ".gitignore" file?

### ISSUE THREAD

**Issue by BobbyBabes** [cytopia/devilbox#584]
#### ISSUE TYPE

 - Feature request

#### SUMMARY

Could you please add the directory ```yaml-nuggets``` to the ```.gitignore``` file?

#### Goal

So that I do not have to move the directory out of the project directory before a ```git pull``` from the Devilbox repo.

I have this [tool to merge yaml nuggets/snippets into one docker-compose.yml file](https://gist.github.com/BobbyBabes/9bd6fcbe1f24b0ebed318c4386803df4).
The directory ```yaml-nuggets``` sits at the top level of a project directory and contains cut up parts of the original ```docker-compose.yml```. I use it mainly to prevent the download of PostgreSQL and MongoDB images. Their nuggets/snippets (services and volumes) are entirely commented out.

**Comment by cytopia** [comment]
@BobbyBabes there is no need to add everybody's desired ignore files to this project. This can already easily be achieved by using your own "global" git ignore, which will then automatically and additionally ignore directories within all git projects: 

https://help.github.com/en/articles/ignoring-files#create-a-global-gitignore

TL:DR
```bash
git config --global core.excludesfile ~/.gitignore_global
echo "/yaml-nuggets/" >> ~/.gitignore_global
```

HTH

**Comment by BobbyBabes** [comment]
I didn't even know that there was a "global" .gitignore. That did it. Thanks.

**Comment by cytopia** [comment]
:-) Glad it works out for you then
