### ISSUE TITLE
PHP 7.3 was not up-to-date

### ISSUE THREAD

**Issue by llaville** [cytopia/devilbox#587]
### ISSUE TYPE

 - Bug Report

### Checklist

* [ ] `.env` file is attached
* [ ] `docker-compose.override.yml` is attached (if it exists)
* [ ] Custom configs from `cfg/` dir are attached (if customized)
* [ ] `docker-compose logs` and `log/` output is added
* [ ] I've looked through the docs: https://devilbox.readthedocs.io/en/latest/
* [ ] I've looked through existing issues: https://github.com/cytopia/devilbox/issues
* [ ] I've read troubleshooting: https://devilbox.readthedocs.io/en/latest/support/troubleshooting.html

### OS / ENVIRONMENT

1. Host operating system and version: **Linux 16.04 LTS**
2. (Windows) Native Docker or Docker Toolbox: 
3. Docker version: **Docker version 18.09.6, build 481bc77**
4. Docker Compose version: **docker-compose version 1.18.0, build 8dd22a9**
5. (Linux) Is SELinux enabled?: **no**
6. What git commit hash are you on?: **fdb6cff**

### SUMMARY

While PHP 7.1.30, 7.2.19 and 7.3.6 were published 5 days ago (may 30th), only 7.1 and 7.2 were correctly updated.

### STEPS TO REPRODUCE

I've tried to update all containers with  `./update-docker.sh`

### EXPECTED BEHAVIOUR

PHP 7.3.6 

### ACTUAL BEHAVIOUR

PHP 7.3.5

### OTHER INFORMATION

```
7.1-work-0.88: Pulling from devilbox/php-fpm
Digest: sha256:963dff9f61920b06f93ccfa28dc943a55f7fc3b4ae505d41d9cdfdd26d0058ca
Status: Image is up to date for devilbox/php-fpm:7.1-work-0.88
7.2-work-0.88: Pulling from devilbox/php-fpm
Digest: sha256:6cd4d1c439205ad0dace286be8c4556126edae25da732e5260d914543fb7e2d2
Status: Image is up to date for devilbox/php-fpm:7.2-work-0.88
7.3-work-0.88: Pulling from devilbox/php-fpm
Digest: sha256:d960dbd2fc5a5bd1404bd8d2fab06f5d2858abba6150ccb0568766505bf02e95
Status: Image is up to date for devilbox/php-fpm:7.3-work-0.88

```

#### Start command

```
$ docker-compose up -d
```

**Comment by cytopia** [comment]
@llaville there was an error with its build which I am currently fixing.
