### ISSUE TITLE
Auto DNS is not working.

### ISSUE THREAD

**Issue by sustained** [cytopia/devilbox#589]
### ISSUE TYPE

 - Bug Report

### Checklist

* [x] `.env` file is attached
* [x] `docker-compose.override.yml` is attached (if it exists - DOESN'T EXIST)
* [x] Custom configs from `cfg/` dir are attached (if customized - NOT CUSTOMISED)
* [ ] `docker-compose logs` and `log/` output is added (will add if requested but logs for PHP-FPM etc. don't seem relevant to DNS...)
* [x] I've looked through the docs: https://devilbox.readthedocs.io/en/latest/
* [x] I've looked through existing issues: https://github.com/cytopia/devilbox/issues
* [x] I've read troubleshooting: https://devilbox.readthedocs.io/en/latest/support/troubleshooting.html

### OS / ENVIRONMENT

1. Host operating system and version: Fedora 29, Kernel 5.x, x86_64
2. (Windows) Native Docker or Docker Toolbox: N/A
3. Docker version: Docker version 18.09.6, build 481bc77
4. Docker Compose version: docker-compose version 1.24.0, build 0aa59064
5. (Linux) Is SELinux enabled?: Yes
6. What git commit hash are you on?: fdb6cffb3b32081a6f994cb01736f87cf15b1b1f

### SUMMARY

Auto DNS isn't working for me, I read some existing issues and went through everything in those and have been through the documentation and such.

![devilbox-auto-dns](https://user-images.githubusercontent.com/5995080/59158033-346bd180-8aac-11e9-8b63-febb3105ef02.png)

Here are the relevant `.env` values:

```
TLD_SUFFIX=local
HOST_PORT_BIND=53
LOCAL_LISTEN_ADDR=
```

My `/etc/resolv.conf`:

```
# Generated by NetworkManager
nameserver 1.1.1.1
nameserver 1.0.0.1
```

Output of `dig testing.local @127.0.0.1`:

```
; <<>> DiG 9.11.5-P4-RedHat-9.11.5-4.P4.fc29 <<>> testing.local @127.0.0.1
;; global options: +cmd
;; Got answer:
;; WARNING: .local is reserved for Multicast DNS
;; You are currently testing what happens when an mDNS query is leaked to DNS
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 16621
;; flags: qr aa rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 2, ADDITIONAL: 3

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
; COOKIE: 1f60bc39e0730bd1ad68f8cb5cfce1d942c5a61ab40c0510 (good)
;; QUESTION SECTION:
;testing.local.			IN	A

;; ANSWER SECTION:
testing.local.		3600	IN	A	127.0.0.1

;; AUTHORITY SECTION:
local.			3600	IN	NS	ns2.local.
local.			3600	IN	NS	ns1.local.

;; ADDITIONAL SECTION:
ns1.local.		3600	IN	A	127.0.0.1
ns2.local.		3600	IN	A	127.0.0.1

;; Query time: 0 msec
;; SERVER: 127.0.0.1#53(127.0.0.1)
;; WHEN: Sun Jun 09 11:39:21 BST 2019
;; MSG SIZE  rcvd: 154
```

### STEPS TO REPRODUCE

I don't know.

### EXPECTED BEHAVIOUR

Auto DNS works.

### ACTUAL BEHAVIOUR

Auto DNS doesn't work.

#### Start command

```
docker-compose stop && docker-compose kill && docker-compose rm -f && docker-compose up
```

#### File and user permissions (Linux & MacOS)

```
uid = 1000
guid = 1000
groups = ... + 974 (docker)
```

#### File permissions of the Devilbox directory
```
drwxrwxr-x.
```

#### File permissions of your projects
```
drwxrwxr-x.
```

**Comment by sustained** [comment]
Also the guide said to make sure that nothing is running on port 53 so it feels relevant to mention that `sudo -ss -tulpn | grep :53` showed both `dnsmasq` and `avahi-daemon` so I have run the following:

```
sudo systemctl stop avahi-daemon
sudo systemctl stop avahi-daemon.socket
sudo systemctl stop dnsmasq
```

But their processes were still there so I `kill`ed them.

**Comment by sustained** [comment]
Also worth noting that it doesn't work either if I add the entry to `etc/hosts` like the UI says to.

**Comment by cytopia** [comment]
Can you check that the bind container is functioning properly via:
```
dig @127.0.0.1 www.google.com
```

**Comment by cytopia** [comment]
> My /etc/resolv.conf:
> ```
> # Generated by NetworkManager
> nameserver 1.1.1.1
> nameserver 1.0.0.1
> ```

This should rather look like this:
```
nameserver 127.0.0.1
```

**Comment by sustained** [comment]
It appears to be working after a reboot, my apologies. :frowning: Thanks for making such an awesome piece of software!

**Comment by cytopia** [comment]
OK, glad to hear. I will close this bug report then.

**Comment by science695** [comment]
@sustained if you continue to have issues, there are a couple tricks you can do because you are on linux.

instead of forwarding ports from bind to localhost, you can just configure your own dns settings to use the internal docker ip of bind. I have added to my resolv.conf header / setup:
nameserver 172.16.238.100

This prevents me from conflicting with my own OS's dnsmasq / resolving processes.

**Comment by skoskie** [comment]
> nameserver 172.16.238.100

Note that the above solution works on MacOS too, as of `12.4 (21F79)`. Thank you @science695!!

However, note that **both** localhost **and** the bind server must be listed and must come before other DNS servers.

<img width="337" alt="2022-05-20 11 15 11 Screenshot of System Preferences ()" src="https://user-images.githubusercontent.com/495511/169579324-958d2ecd-170a-44c2-8654-0d9e130caebb.png">
