### ISSUE TITLE
How do I install and enable Ghostscript module in PHP?

### ISSUE THREAD

**Issue by sachyya** [cytopia/devilbox#594]
I am Devilbox for WordPress local development. With `WP 4.7`, PDF preview image generation is supported but it does not work in Devilbox. Through some research([](https://deliciousbrains.com/pdf-preview-images-wordpress-real-world/)), I found that 
    `ImageMagick`
    `Imagick`
    `Ghostscript`
should be enabled on the server. 

Now I am stuck on how to install and enable `Ghostscript` on Devilobx or say the right way to enable external modules.

**Comment by sachyya** [comment]
So far I have resolved it by installing the `ghostscript` manually by SSHing into the container using `sudo apt-get install ghostscript`.

But is there any better way or 'devilbox way' to install it?

**Comment by science695** [comment]
inside the rebuild script, you can add:
docker-compose exec php 'apt-get update && apt-get install ghostscript'

Then every time you rebuild the containers, it will install ghostcript.

You might be able to do it in a cfg/startup/ script, but that would run every time the container starts, not just when it is created.

**Comment by cytopia** [comment]
@sachyya will be handled in the [php-fpm](https://github.com/devilbox/docker-php-fpm) repository via this PR: https://github.com/devilbox/docker-php-fpm/pull/134
