### ISSUE TITLE
Support for .NET Core Applications

### ISSUE THREAD

**Issue by 24js** [cytopia/devilbox#596]
#### ISSUE TYPE

 - Feature request

#### SUMMARY

Since Microsoft is heavily investing in .Net Core and there is a lot of open source projects with a huge community who pulling their hairs every time they want to set up a reliable environment to test different project and develop, It would be brilliant if Devil himself could support these poor souls and take them under his wings of awesomeness, Even running .Net Core in IIS is such a hassle ( IIS is huge and fries poor laptops ), even Windows users already are using Docker for .Net Core applications

#### Goal

Adding `microsoft-dotnet-core` to DevilBox arsenal, It also can get behind Apache and Nginx

#### Options
Adding separate fully functional `microsoft-dotnet-core` Container with a separate shell
or 
Someway adding support for SDK and Runtime from current PHP container shell ( Since they need NPM and other awesome tools which DevilBox already has )

**Comment by cytopia** [comment]
@24js the Devilbox offers you to easily add your own Docker images. See documentation: https://devilbox.readthedocs.io/en/latest/advanced/add-your-own-docker-image.html#add-your-own-docker-image

Additionally there are also other *flames* available here: https://github.com/devilbox/flames
