### ISSUE TITLE
Automatically ingest log data into ELK stack

### ISSUE THREAD

**Issue by madmatt** [cytopia/devilbox#597]
#### ISSUE TYPE

 - Feature request

#### SUMMARY
I would like an optional configuration option that allows someone to use the ELK stack to store all logs generated by Docker machines, and perhaps include some useful stats / information within Kibana. This should be optional so that it doesn't prevent devs from using the ELK stack for their own needs.

#### Goal
Ideally what I want is a way to easily and quickly ingest, parse, search and report on logs that the Docker machines generate. In particular, I want to see logs generated by my PHP applications, and have them stored for longer than the current Docker uptime (while I can see the `log` directory exists, it'd be nice to leverage the power of ElasticSearch and Kibana for this, given all the building blocks are already there and it's more about plumbing than building something new).

I would be interested in potentially building some part of this, if it's interesting to the Devilbox maintainers.

Thanks for your consideration!

**Comment by llaville** [comment]
@madmatt Hello,

Even if the https://github.com/amir20/dozzle  project is not really what you expect to have, it could help you as a quick alternative.

**Comment by madmatt** [comment]
Thanks neat, thanks @llaville!

**Comment by Tuurlijk** [comment]
For a console based monitory take a look at https://github.com/jesseduffield/lazydocker

**Comment by cytopia** [comment]
I would also be very much interested in an automatism here. @madmatt if you want to take the lead up on this feel free.

**Comment by llaville** [comment]
[Vector](https://github.com/timberio/vector/) could also be the solution searched !

**Comment by llaville** [comment]
@madmatt and @cytopia Hello guys

This feature and the one detailed by #722 seems really close.
As I've a solution up and running, I'd like to take the lead (if you are agree)
