### ISSUE TITLE
Bind for 0.0.0.0:1053: unexpected error Permission denied

### ISSUE THREAD

**Issue by autaut03** [cytopia/devilbox#598]
### ISSUE TYPE

 - Bug Report

### Checklist

* [X] `.env` file is attached
* [X] `docker-compose.override.yml` is attached (if it exists)
* [X] Custom configs from `cfg/` dir are attached (if customized)
* [X] `docker-compose logs` and `log/` output is added
* [X] I've looked through the docs: https://devilbox.readthedocs.io/en/latest/
* [X] I've looked through existing issues: https://github.com/cytopia/devilbox/issues
* [X] I've read troubleshooting: https://devilbox.readthedocs.io/en/latest/support/troubleshooting.html

### OS / ENVIRONMENT

1. Host operating system and version: Windows 10, v1809
2. (Windows) Native Docker or Docker Toolbox: Native Docker
3. Docker version: 2.0.0.3 (latest stable)
4. Docker Compose version: 1.23.2
5. (Linux) Is SELinux enabled?:
6. What git commit hash are you on?: 0543f2da9218661824c64148e07f601f5e99f302

### SUMMARY
I was having problems with Nginx in Devilbox - it was very laggy and restarting didn't help, so I tried restarting my PC. After the restart, I was no longer be able to start Devilbox at all:

```
Starting devilbox_bind_1 ... error

ERROR: for devilbox_bind_1  Cannot start service bind: driver failed programming external connectivity on endpoint devilbox_bind_1 (768e2e727f861e26159552fb6bbbb34bfda7fe963ba8d9199f8382e288facce8): Error starting userland proxy: Bind for 0.0.0.0:1053: unexpected error Permission denied

ERROR: for bind  Cannot start service bind: driver failed programming external connectivity on endpoint devilbox_bind_1 (768e2e727f861e26159552fb6bbbb34bfda7fe963ba8d9199f8382e288facce8): Error starting userland proxy: Bind for 0.0.0.0:1053: unexpected error Permission denied
ERROR: Encountered errors while bringing up the project.
```

I also tried starting other instance of Devilbox from another project - got the same exact result. I understand this might be an issue with Docker for Win or my PC, but as I was unable to find help regarding this

#### Start command

```
$ docker-compose up -d
```

#### .env
https://pastebin.com/PkvfY8x3

#### Logs
There were no logs regarding `bind` container and `docker-compose logs` showed nothing.

**Comment by vikas5914** [comment]
The issue is in Docker for Windows. not in devil box. 

If you are not using Auto DNS, I suggest changing the HOST_PORT_BIND to `6000 `and LOCAL_LISTEN_ADDR to `127.0.0.1:
`

**Comment by autaut03** [comment]
Thanks for the feedback. After reporting this I switched to another PC (and used devilbox there perfectly fine) for a while, and now, after coming back, the problem is gone on my main PC. I changed or did nothing since.

Thanks for your time again.

**Comment by webdevsuperfast** [comment]
> 
> 
> The issue is in Docker for Windows. not in devil box.
> 
> If you are not using Auto DNS, I suggest changing the HOST_PORT_BIND to `6000 `and LOCAL_LISTEN_ADDR to `127.0.0.1: `

This solved my issue on Windows 10.
