### ISSUE TITLE
Use dev zone instead of a loc one.

### ISSUE THREAD

**Issue by own2pwn** [cytopia/devilbox#60]
Hey there! Is there a way to use .dev zone instead of a loc?

- [x] OSX
- [x] `docker version 17.03.1-ce`
- [x] `docker-compose version 1.11.2, build dfed245`

**Comment by cytopia** [comment]
@own2pwn Already fixed in the upcoming release (https://github.com/cytopia/devilbox/pull/58)
You can already give it a try (however HHVM does not work yet) - simply check out the release branch.

**Comment by cytopia** [comment]
@own2pwn It is working as of now.
