### ISSUE TITLE
2 small bug

### ISSUE THREAD

**Issue by ledeneveugene** [cytopia/devilbox#603]
### ISSUE TYPE

 - Bug Report

### SUMMARY

1. In file docker-compose:
# Mount MySQL Data directory
      - devilbox-${MYSQL_SERVER}:/var/lib/mysql:rw${MOUNT_OPTIONS}
don't creating folder for mount database(OS - Linux Manjaro). Need dot at string start.
i change it to
       - ./databases/devilbox-${MYSQL_SERVER}:/var/lib/mysql:rw${MOUNT_OPTIONS}

2. Do not work with empty TLD_SUFFIX=. Open your main page (like localhost).

**Comment by cytopia** [comment]
@ledeneveugene can you describe what the actual bug is?
