### ISSUE TITLE
PHP 7.x was not up-to-date

### ISSUE THREAD

**Issue by llaville** [cytopia/devilbox#605]
### ISSUE TYPE

 - Bug Report

### Checklist

* [ ] `.env` file is attached
* [ ] `docker-compose.override.yml` is attached (if it exists)
* [ ] Custom configs from `cfg/` dir are attached (if customized)
* [ ] `docker-compose logs` and `log/` output is added
* [ ] I've looked through the docs: https://devilbox.readthedocs.io/en/latest/
* [ ] I've looked through existing issues: https://github.com/cytopia/devilbox/issues
* [ ] I've read troubleshooting: https://devilbox.readthedocs.io/en/latest/support/troubleshooting.html

### OS / ENVIRONMENT

1. Host operating system and version: **Linux 16.04 LTS**
2. (Windows) Native Docker or Docker Toolbox: 
3. Docker version: **Docker version 18.09.6, build 481bc77**
4. Docker Compose version: **docker-compose version 1.18.0, build 8dd22a9**
5. (Linux) Is SELinux enabled?: **no**
6. What git commit hash are you on?: **fdb6cff**

### SUMMARY

While PHP 7.2.20 and 7.3.7 were published on July 4th, only 7.3 were correctly updated.

### STEPS TO REPRODUCE

I've tried to update all containers with  `./update-docker.sh`

### EXPECTED BEHAVIOUR

PHP 7.2.20

### ACTUAL BEHAVIOUR

PHP 7.2.19

### OTHER INFORMATION

```
7.2-work-0.89: Pulling from devilbox/php-fpm
Digest: sha256:b8f95a19c94bb9b41a98742b50d4a3191a7f07baf2fbe4bfbea2d265f3e2a45b
Status: Image is up to date for devilbox/php-fpm:7.2-work-0.89

7.3-work-0.89: Pulling from devilbox/php-fpm
Digest: sha256:cdaf632f0e0c193dd16f95615dadcc92c2bbb27945990497ad506ecff139f5ef
Status: Downloaded newer image for devilbox/php-fpm:7.3-work-0.89

```

#### Start command

```
$ docker-compose up -d
```

**Comment by boumanb** [comment]
According to https://devilbox.readthedocs.io/en/latest/maintenance/update-the-devilbox.html#update-docker-images you could try running `update-docker.sh`.

**Comment by llaville** [comment]
i know and i've already did it ? 
And you ? is it working or not ?

**Comment by llaville** [comment]
Travis did not build anything : see https://travis-ci.org/devilbox/docker-php-fpm since a month now !

**Comment by boumanb** [comment]
Looks like the job logs are getting too big. 

`The job exceeded the maximum log length, and has been terminated.`
https://travis-ci.org/devilbox/docker-php-fpm/jobs/566885135#L31583

Right now the build terminates at output line 31583 on the build for 7.2, only 5.2 seems to build properly.

**Comment by boumanb** [comment]
@cytopia maybe we have to redirect the installation (`docker-php-ext-install`) outputs of the PHP extensions to `/dev/null` like you do with some other output in the dockerfiles. According [this comment](https://github.com/docker-library/php/issues/319#issuecomment-355164084) we'll still receive failures and errors when they occur.

**Comment by llaville** [comment]
All PHP images are not up-to-date now ! 
PHP 7.1.31 and PHP 7.2.21 were released on August 1st and available in docker hub since 8 days now.

**Comment by llaville** [comment]
Nothing was applied to solve the situation since a month now, and all PHP versions are affected.
@cytopia did you have problem ? I didn't see you active on this project since a long time now.

**Comment by llaville** [comment]
No reason to give this bug opened, if no solve are applied.
I'm sad to said that @cytopia, but this project was awesome, while it was maintained. 
If you've not free time to continue to support it, or have private reasons I can understand, but please add a note to all users on this way. Silence is always horrible !

**Comment by vikas5914** [comment]
@cytopia Any update on this ?
