### ISSUE TITLE
modsecurity support

### ISSUE THREAD

**Issue by dimkasta** [cytopia/devilbox#606]
#### ISSUE TYPE

 - Feature request

#### SUMMARY

Modsecurity with CRS will be a huge improvement towards Devilbox's suitability for production environments.

#### Goal

There are already some images that support modsecurity with CRS, but they are poorly maintained and/or poorly documented (including the official owasp images).
Modsecurity could be included either in a proxy container that sits in front of everything, or as a module on existing web containers

**Comment by cytopia** [comment]
@dimkasta do you have some example Dockerfiles or other related documentation which explains the howto and the benefits?

**Comment by dimkasta** [comment]
With version 3, modsecurity comes as a dynamic module that has to be compiled with a connector into nginx.

The best bet for a dockerfile is the official owasp images
The implementation makes sense in two parts. One to create the proxy image, and the second to apply the rules to it (this will probably need more hands-on work to be more configurable, since the full CRS rule-set tends to be very restrictive giving false positives)

https://hub.docker.com/r/owasp/modsecurity
https://hub.docker.com/r/owasp/modsecurity-crs

Here's also a nice article with some description of what's going on, and some tests to verify it's actually working properly
https://medium.com/building-goalwise/how-to-implement-modsecurity-waf-with-nginx-15fdd42fa3


The benefits are that you have a fully fledged WAF in front of your application.

**Comment by cytopia** [comment]
@dimkasta what about of having it as a separate Docker container in front of Apache/Nginx. See sketch below (between Varnish [which is optional] and the actual web server, or maybe even in front of HAProxy - not sure which is the best implementation as I've never used it)

![](https://raw.githubusercontent.com/devilbox/artwork/master/submissions_diagrams/cytopia/01/png/architecture-full.png)
