### ISSUE TITLE
Bind error on windows at composer up

### ISSUE THREAD

**Issue by Gonzalo1987** [cytopia/devilbox#608]
### ISSUE TYPE

 - Bug Report

### Checklist

* [x] `.env` file is attached [env.txt](https://github.com/cytopia/devilbox/files/3403132/env.txt)
* [ ] `docker-compose.override.yml` is attached (if it exists)
* [ ] Custom configs from `cfg/` dir are attached (if customized)
* [x] `docker-compose logs` and `log/` output is added [log.txt](https://github.com/cytopia/devilbox/files/3403149/log.txt)
* [x] I've looked through the docs: https://devilbox.readthedocs.io/en/latest/
* [x] I've looked through existing issues: https://github.com/cytopia/devilbox/issues
* [x] I've read troubleshooting: https://devilbox.readthedocs.io/en/latest/support/troubleshooting.html

### OS / ENVIRONMENT

1. Host operating system and version: Microsoft Windows [Versión 10.0.17134.885]
2. (Windows) Native Docker or Docker Toolbox: Toolbox
3. Docker version: Docker version 18.09.2, build 6247962
4. Docker Compose version: docker-compose version 1.23.2, build 1110ad01
5. (Linux) Is SELinux enabled?:
6. What git commit hash are you on?: 0543f2da9218661824c64148e07f601f5e99f302

### SUMMARY
I don´t know why but I can't run devilbox
My prompt show this when I try to docker-compose up:

> ERROR: for devilbox_bind_1  Cannot start service bind: driver failed programming external connectivity on endpoint devilbox_bind_1 (f3b9fe1705c0a8b49acb233e63e61e07c61d5c4b1f8c56ff6253760db13534ab): Error starting userland proxy: mkdir /port/tcp:0.0.0.0:1053:tcp:172.16.238.100:53: input/output error
> 
> ERROR: for bind  Cannot start service bind: driver failed programming external connectivity on endpoint devilbox_bind_1 (f3b9fe1705c0a8b49acb233e63e61e07c61d5c4b1f8c56ff6253760db13534ab): Error starting userland proxy: mkdir /port/tcp:0.0.0.0:1053:tcp:172.16.238.100:53: input/output error
> ERROR: Encountered errors while bringing up the project.

### STEPS TO REPRODUCE
I just clone it from github, I rename the env file and I run the project

### EXPECTED BEHAVIOUR
devilbox runs

### ACTUAL BEHAVIOUR
devilbox throws error

#### Start command

```
$ docker-compose up...
```

#### File and user permissions (Linux & MacOS)

```
$ id
```

```
$ ls -la
```

```
$ ls -la data/www
```

**Comment by vikas5914** [comment]
HI, 

This is a issue with docker and windows fastboot. Try restarting the the docker and then run docker-compose up command.

**Comment by t0nsofkoalas** [comment]
Have same issue

> This is a issue with docker and windows fastboot. Try restarting the the docker and then run docker-compose up command.

@vikas5914 i disable fast boot and it didn't work for me unfortunately
