### ISSUE TITLE
PHP with ZTS and pThreads

### ISSUE THREAD

**Issue by yoshkin** [cytopia/devilbox#610]
#### ISSUE TYPE

 - Feature request

#### SUMMARY

How can i build devilbox/php-fpm-7.2-work but with ZTS and pThreads? Have you some instructions ?

#### Goal

I need to run CLI application over php7.2 with ZTS and pTreads. But i want to use devilbox package.

**Comment by cytopia** [comment]
@yoshkin Devilbox Docker images have no support for ZTS.
