### ISSUE TITLE
Help: Change IP address for devilbox (not localhost)

### ISSUE THREAD

**Issue by cefuroX** [cytopia/devilbox#612]
Hey,
I would like to change the IP address which will be used on the host for accessing devilbox. Per default it is localhost (127.0.0.1). Is there a way to change this? 
If yes: Please explain me how.

Thanks!

**Comment by cefuroX** [comment]
FYI: I already tried to change LOCAL_LISTEN_ADDR but I always get:
`
ERROR: for bind  Cannot start service bind: driver failed programming external connectivity on endpoint devilbox_bind_1 (5e3ffa6755c2d9a13140b9a59d8334ff13d148d72a60c735e8ab87a4b9fdb3af): Error starting userland proxy: listen tcp 192.168.10.10:1053: bind: cannot assign requested address
`
The IP is just an example.

**Comment by science695** [comment]
Depending on which OS you are using, you may be able to access the containers directly with their docker subnet ip address.

The default ip address of the httpd container in devilbox is: 172.16.238.11
Try going to that address in your browser. if that works, you can change your LOCAL_LISTEN_ADDR to that (with a colon at the end)

Related conversations: https://github.com/docker/for-win/issues/221

**Comment by cytopia** [comment]
> FYI: I already tried to change LOCAL_LISTEN_ADDR but I always get:

@cefuroX  
Can you post your `.env` setting for that.
