### ISSUE TITLE
Please add sodium to php-7.2

### ISSUE THREAD

**Issue by TomashKhamlai** [cytopia/devilbox#613]
#### ISSUE TYPE

 - Feature request

#### SUMMARY

Magento2 is not installing.
```
Warning: Use of undefined constant SODIUM_CRYPTO_PWHASH_ALG_ARGON2ID13 - assumed 'SODIUM_CRYPTO_PWHASH_ALG_ARGON2ID13' (this will throw an Error in a future version of PHP) in /shared/httpd/gql-ce/graphql-c  
  e/lib/internal/Magento/Framework/Encryption/Encryptor.php on line 153
```

#### Goal

Something similar to 
RUN echo "deb http://deb.debian.org/debian stretch-backports main" >> /etc/apt/sources.list 

RUN apt-get update && apt-get -t stretch-backports install -y \
  libsodium-dev

RUN pecl install -f libsodium-1.0.17 / RUN docker-php-ext-install sodium

**Comment by RobsonTrimes** [comment]
For now, I think you can use PHP7.1. I'm doing it on local dev and on my production server.

**Comment by naazguu** [comment]
For Magento 2.3.2

Make sure that you’re running the the latest PHP version 7.2.19 which contains a version of libsodium of at least 1.0.13 (we run 1.0.17 right now).

https://support.hypernode.com/changelog/release-6364-magento-2-preinstall-updated-to-2-3-2/

http://blog.grafzahl.io/magento-warning-after-updating-to-2-3-2/

**Comment by joomi** [comment]
How can I manually upgrade the libsodium to 1.0.13?

**Comment by msyhr** [comment]
I was able to get this working. (Using the php 7.2 box)

1. ssh into the box

2. go root (sudo su)

3. run command:

`wget https://download.libsodium.org/libsodium/releases/libsodium-1.0.18.tar.gz \
    && tar xfvz libsodium-1.0.18.tar.gz \
    && cd libsodium-1.0.18 \
    && ./configure \
    && make && make install \
    && pecl install -f libsodium`

4. docker-compose kill / docker-compose up -d (or however you manage your instances)

**Comment by wfuk-stuart** [comment]
1.0.13 or later of libsodium is needed for Magento 2.3.2 onwards so this breaks if using PHP 7.2 and the latest Magento version.

**Comment by TomashKhamlai** [comment]
@stale unstale

**Comment by robsoned** [comment]
@TomashKhamlai DId you try using PHP 7.3?

**Comment by bgorski** [comment]
PHP 7.3 and 7.2 have the same sodium version installed (1.0.11). As @robsoned mentioned using 7.1 can serve as a temporary solution. It's suboptimal, but it works as this version has no sodium installed at all so there are no problems with it (if there's no sodium, SHA256 is used instead of Argon2id)

**Comment by TomashKhamlai** [comment]
Thank you
