### ISSUE TITLE
Mailhog + php fails with: "unknown shorthand flag: 'o' in -oi"

### ISSUE THREAD

**Issue by pnoeric** [cytopia/devilbox#614]
Hi, I've installed Mailhog per the instructions and it's working great (I can see it at localhost:8025 and send messages from the command line). However, the alias for sendmail that should override php and let the mail() function use mailhog is not working.

First, when I go into the shell and test mailhog, this works perfectly:

```
/usr/local/bin/mhsendmail --smtp-addr="mailhog:1025" test@mailhog.local <<EOF
From: App <app@mailhog.local>
To: Test <test@mailhog.local>
Subject: Test message

Some content!
EOF
```

After I execute that, I can see the message at localhost:8025. All good there.

However, my php app fails with:
```
unknown shorthand flag: 'o' in -oi
Usage of /usr/local/bin/mhsendmail:
  -f, --from="nobody@php": SMTP sender
      --smtp-addr="localhost:1025": SMTP server address
Message could not be sent. Mailer Error: Could not execute: /usr/local/bin/mhsendmail --smtp-addr="mailhog:1025"
```
No idea what the '-o' flag is, but it appears to be passed from php to mhsendmail where it fails.

I did see that mhsendmail's [most recent commit](https://github.com/mailhog/mhsendmail/commit/9e70164f299c9e06af61402e636f5bbdf03e7dbb) says: `Added -o option for compatibility`

That was back in 2017. Could it be that an old version of mhsendmail is included with devilbox? I might try to figure out how I can update mhsendmail inside the box... hmmm...

FWIW I confirmed that I have the latest version of devilbox too:

```
# git pull origin master
From https://github.com/cytopia/devilbox
 * branch              master     -> FETCH_HEAD
Already up to date.

# git describe --tags
v1.0.2-6-g0543f2da
```

**Comment by pnoeric** [comment]
Yeah, here's the sendmail flag that php appears to be passing: 
<img width="758" alt="image" src="https://user-images.githubusercontent.com/447652/61890327-83a87d00-af07-11e9-9502-a42e77274fa5.png">

I tried to figure out how to upgrade the mhsendmail in the box but can't quite work that out. Help ;-)

**Comment by Tuurlijk** [comment]
Try installing the mhsendmail binary you want like: https://github.com/Tuurlijk/docker-php-fpm/blob/master/7.2/php/Dockerfile#L36

**Comment by cytopia** [comment]
@pnoeric will be addressed here: https://github.com/devilbox/docker-php-fpm/pull/143

**Comment by cytopia** [comment]
FYI: The new version of `mhsendmail` now supports those flags.

**Comment by pnoeric** [comment]
@cytopia thank you! 👍🏻
