### ISSUE TITLE
access api  from android emulator

### ISSUE THREAD

**Issue by frkmed** [cytopia/devilbox#617]
#### ISSUE TYPE

- How to accces my api(restApi) developped with php, and deployed with  devilbox at this url  myapi.loc .
When i try to acces this adresse from my android emulator the url is not recognized.
and i dont know how to fix this issue. 

please help me i am new to drocker envirennement.

**Comment by mrbig00** [comment]
The easiest way to access your devilbox virtual hosts from other devices is via [ngrok](https://devilbox.readthedocs.io/en/latest/corporate-usage/showcase-over-the-internet.html).

**Comment by frkmed** [comment]
thanks very much i will try this solution

**Comment by frkmed** [comment]
ngrok work perfectly but internet connection must be active.
if there is another solution without internet I will be grateful for you.

**Comment by mrbig00** [comment]
There are a bunch of ways, but honestly the ngrok solution is the easiest. But you can try something similar: https://blog.oddbit.com/post/2014-08-11-four-ways-to-connect-a-docker/

**Comment by frkmed** [comment]
thank you very much, i will try to implement those solutions
