### ISSUE TITLE
PHP 7.x and WebP Support with Imagick

### ISSUE THREAD

**Issue by fkaminski** [cytopia/devilbox#619]
#### ISSUE TYPE

 - Feature request

#### SUMMARY
With actual devilbox Version and PHP 7.x there is WebP support enabled in the gd-modul 
but the WebP Format is not supported within imagick - see phpinfo().

#### Goal
Please enable the WebP support within imagick too.

I am using the new Contao 4.8 CMS which has auto converting feature like .png ->.webp.
But prefers imagick ( if present ) over gd.
So this feature does not work because the imagick modul do not support the Webp Format.

**Comment by robots4life** [comment]
Yes, it would be great to have webp support from imagick as well.

**Comment by fkaminski** [comment]
Please continue to consider ...

**Comment by cytopia** [comment]
@fkaminski upcoming release will ensure to have it in by default.
See regression test here and let me know if this is sufficient:

https://github.com/cytopia/devilbox/blob/release/v1.1.0/.tests/www/modules/htdocs/gd-webp.php
