### ISSUE TITLE
You don't have permission to access / on this server Ubuntu 18.04

### ISSUE THREAD

**Issue by renekreijveld** [cytopia/devilbox#621]
### ISSUE TYPE

 - Bug Report

### Checklist

* [X] `.env` file is attached
* [ ] `docker-compose.override.yml` is attached (if it exists)
* [ ] Custom configs from `cfg/` dir are attached (if customized)
* [X] `docker-compose logs` and `log/` output is added
* [X] I've looked through the docs: https://devilbox.readthedocs.io/en/latest/
* [X] I've looked through existing issues: https://github.com/cytopia/devilbox/issues
* [X] I've read troubleshooting: https://devilbox.readthedocs.io/en/latest/support/troubleshooting.html

### OS / ENVIRONMENT

1. Host operating system and version: Ubuntu Desktop 18.04 LTS
2. (Windows) Native Docker or Docker Toolbox: 
3. Docker version: Docker version 19.03.1, build 74b1e89
4. Docker Compose version: docker-compose version 1.17.1, build unknown
5. (Linux) Is SELinux enabled?: No
6. What git commit hash are you on?:On branch master
Your branch is up to date with 'origin/master'.

### SUMMARY

After doing docker-compose up I get the following in the browser:

Forbidden
You don't have permission to access / on this server.

### STEPS TO REPRODUCE

Installed devilbox
Copied env-example to .env
Set TLD_SUFFIX=test
Set HTTPD_SERVER=apache-2.4 as HTTPD Server
Added MySQL root passord to .env.
Create a folder testwebsite in ./data/www
Added an index.php to ./data/www/testwebsite.
Added testwebsite.test to /etc/hosts
Started devilbox
Went in the browser to http://testwebsite.test

### EXPECTED BEHAVIOUR

The contents of index.php are shown (phpinfo)

### ACTUAL BEHAVIOUR

Error message:
Forbidden
You don't have permission to access / on this server.

### OTHER INFORMATION
I have added testwebsite.test to /etc/hosts:
```
127.0.0.1	localhost
127.0.1.1	RKR-NUC8i7BEH
127.0.0.1	testwebsite.test
```

#### Start command

```
$ docker-compose up httpd php mysql
```

#### File and user permissions (Linux & MacOS)

```
$ id
uid=1000(rkr) gid=1000(rkr) groups=1000(rkr),4(adm),24(cdrom),27(sudo),30(dip),46(plugdev),116(lpadmin),126(sambashare),999(docker)
```

```
$ ls -la
total 240
drwxr-xr-x 16 rkr rkr  4096 aug 20 17:46 .
drwxr-xr-x 21 rkr rkr  4096 aug 20 17:35 ..
drwxr-xr-x  2 rkr rkr  4096 aug 20 17:24 autostart
drwxr-xr-x  3 rkr rkr  4096 aug 20 17:30 backups
drwxr-xr-x  2 rkr rkr  4096 aug 20 17:24 bash
drwxr-xr-x  2 rkr rkr  4096 aug 20 17:30 ca
drwxr-xr-x 57 rkr rkr  4096 aug 20 17:24 cfg
-rw-r--r--  1 rkr rkr  4651 aug 20 17:24 CHANGELOG.md
drwxr-xr-x  2 rkr rkr  4096 aug 20 17:24 compose
-rw-r--r--  1 rkr rkr  2770 aug 20 17:24 CONTRIBUTING.md
drwxr-xr-x  3 rkr rkr  4096 aug 20 17:24 data
drwxr-xr-x  3 rkr rkr  4096 aug 20 17:24 .devilbox
-rw-r--r--  1 rkr rkr   743 aug 20 17:24 docker-compose.override.yml-example
-rw-r--r--  1 rkr rkr 14314 aug 20 17:24 docker-compose.yml
drwxr-xr-x 20 rkr rkr  4096 aug 20 17:24 docs
-rw-r--r--  1 rkr rkr  2445 aug 20 17:24 .editorconfig
-rw-r--r--  1 rkr rkr 16627 aug 20 17:46 .env
-rw-r--r--  1 rkr rkr 16622 aug 20 17:24 env-example
drwxr-xr-x  8 rkr rkr  4096 aug 20 17:24 .git
drwxr-xr-x  3 rkr rkr  4096 aug 20 17:24 .github
-rw-r--r--  1 rkr rkr  3837 aug 20 17:24 .gitignore
-rw-r--r--  1 rkr rkr  1064 aug 20 17:24 LICENSE.md
drwxr-xr-x  4 rkr rkr  4096 aug 20 17:30 log
drwxr-xr-x  8 rkr rkr  4096 aug 20 17:24 mod
-rw-r--r--  1 rkr rkr 63099 aug 20 17:24 README.md
-rw-r--r--  1 rkr rkr    86 aug 20 17:24 shell.bat
-rwxr-xr-x  1 rkr rkr    59 aug 20 17:24 shell.sh
drwxr-xr-x  5 rkr rkr  4096 aug 20 17:24 .tests
-rw-r--r--  1 rkr rkr  9808 aug 20 17:24 .travis.yml
-rwxr-xr-x  1 rkr rkr  2265 aug 20 17:24 update-docker.sh
-rw-r--r--  1 rkr rkr  1043 aug 20 17:24 UPDATING.md
```

```
$ ls -la data/www
total 12
drwxr-xr-x 3 rkr rkr 4096 aug 20 17:48 .
drwxr-xr-x 3 rkr rkr 4096 aug 20 17:24 ..
-rw-r--r-- 1 rkr rkr    0 aug 20 17:24 .keepme
drwxr-xr-x 2 rkr rkr 4096 aug 20 17:32 testwebsite
```
[docker-compose.logs.txt](https://github.com/cytopia/devilbox/files/3521963/docker-compose.logs.txt)
[testwebsite-error.log](https://github.com/cytopia/devilbox/files/3521966/testwebsite-error.log)
[env.txt](https://github.com/cytopia/devilbox/files/3521970/env.txt)

**Comment by cytopia** [comment]
> Added an index.php to ./data/www/testwebsite.

You need to put this into the `htodcs/` directory: https://devilbox.readthedocs.io/en/latest/getting-started/create-your-first-project.html#step-3-create-a-docroot-directory
