### ISSUE TITLE
php artisan storage:link  not working

### ISSUE THREAD

**Issue by kakariko-village** [cytopia/devilbox#623]
#### ISSUE TYPE

 - Question

Hi i have a Laravel project that need to run php artisan storage:link for creating storage link for image. The problem is even the command output is "The [public/storage] directory has been linked.", there is no storage folder inside public and of course no images were loaded.

#### SUMMARY

php artisan storage:link  not working

#### Goal

I can load image with storage link

**Comment by vikas5914** [comment]
Hi, 

I just tried and its working for me. You need to upload your files to `storage/app/public` folder.

88Command Output:**

![Screenshot_2](https://user-images.githubusercontent.com/7912297/63638160-32c0ab80-c6a2-11e9-89fe-1b3813619979.png)

**One file at storage/app/public**

![Screenshot_3](https://user-images.githubusercontent.com/7912297/63638171-4f5ce380-c6a2-11e9-9825-77c03e25399c.png)

**its output**

![Screenshot_4](https://user-images.githubusercontent.com/7912297/63638178-68fe2b00-c6a2-11e9-8100-5f33a0fae3d3.png)

**Comment by kakariko-village** [comment]
Hi @vikas5914 , my `storage/app/public` folder already contains sub folder with images. The command  created a file names `storage` inside `public` folder but still cannot load images existed in  `storage/app/public` .

**Comment by vikas5914** [comment]
@kakariko-village try to create a demo txt file like i did and check if you can open it.

**Comment by kakariko-village** [comment]
I solved it by delete htdocs folder inside my project folder then create it again then run the symlink command to link htdocs with public folder

**Comment by Tuurlijk** [comment]
@cytopia This issue can be closed

**Comment by vikas5914** [comment]
@kakariko-village can you please close this ticket?
