### ISSUE TITLE
Install and enable the php extension in container

### ISSUE THREAD

**Issue by ozkanonur** [cytopia/devilbox#627]
I have a large project inside the container working pretty nice with devilbox. But my project needs php-geos extension enabled. How do I do that? 

I checked the documentation and then env file, in env file it says only 2 modules can get enabled.
<img width="626" alt="Screen Shot 2019-08-31 at 08 37 04" src="https://user-images.githubusercontent.com/39852038/64059732-ad218c00-cbca-11e9-9e54-141bca4a1991.png">

But what if my project needs different extensions than these 2 of them? How do we install and enable the extension in PHP container? Most of my project work with php-geos, so this is a bit important situation to me.

**Comment by Tuurlijk** [comment]
You can build your own image based on the devilbox/docker-php-fpm box: https://github.com/devilbox/docker-php-fpm/blob/master/Dockerfiles/mods/Dockerfile-7.2

Or submit a patch to add the geos extension to the build

**Comment by vikas5914** [comment]
@stale remove

**Comment by cytopia** [comment]
@ozkanonur  can you link to the php module. if it is easily installable, I can add it as a default

**Comment by ozkanonur** [comment]
> @ozkanonur can you link to the php module. if it is easily installable, I can add it as a default

I already configured whole devilbox for my workspace but maybe for other people would be helpful if you do that.
Here is, https://github.com/mjaschen/phpgeo

**Comment by cytopia** [comment]
As far as I see this is a library not a module or?

**Comment by ozkanonur** [comment]
I call all of these things as a Php extension :) But I'm pretty sure that you can add it like you do for modules right?

**Comment by cytopia** [comment]
If it is a library, then you should use `composer` to install it next to your project. You will only have to do it once per project, as you download the files and they will always be mounted, thus survive restarts. Also keep in mind different projects have different version requirements of libraries, so I can't just install a one-fits-all library.

If it is a module, it needs to be compiled with/against php and added to the image.

**Comment by ozkanonur** [comment]
Sorry, I pasted wrong link.. https://github.com/libgeos/php-geos this one is the extension that I talked about. It looks like dont even get maintain since years but your choice if you want to integrate it.

**Comment by cytopia** [comment]
The provided PHP module [php-geos](https://github.com/libgeos/php-geos) seems to be way outdated (last commit 2017) and will most likely not work on the newer PHP versions. I would suggest to use the phpgeo composer library  as it is also well maintained (last update 8 days ago):
```
composer require mjaschen/phpgeo
```
