### ISSUE TITLE
php(7.0) can't connect to mysql (socket not found)

### ISSUE THREAD

**Issue by fe3dback** [cytopia/devilbox#63]
When i try to open my application (after update to 0.9), mysql fall with error:
```
Mysql connect error [localhost]: (2002) No such file or directory (400)
```

in php container, mysql socket not exist in /tmp/mysql.

--
Now i fix this by add 2 volumes in docker-compose.yml (to mysql and php section):
```
volumes:
- mysql_socket_volume:/tmp/mysql
```

and change this path in php.ini:
```
[mysqli]
mysqli.default_socket = /tmp/mysql/mysqld.sock
```

maybe i do something wrong?

-------------------------
Also i have problem with dnsmasq service, this conflict with cytopia/bind. I use dnsmasq for auto routing .loc domains to localhost. Changing cytopia/bind port from 53 to 54 fix this.

p.s. my os, version of docker and .env files can be found here:
#61

**Comment by cytopia** [comment]
@fe3dback


**1. Socket issues**

I have removed all socket mounts (they have problems on windows).

Now everything is consistently port-forwarded to the php container on `127.0.0.1:<service-port>`.
This makes it more consistent to either connect to services from within the php container or from the host computer.

You should change your sql connections to:
```php
<?php
mysql_connect('127.0.0.1', 'user', 'pass');
```
This way, it can be called from the host as well as from the php container.

See https://github.com/cytopia/devilbox/blob/master/doc/Info.md for more explanation.


**2. DNS issues**

You can change this in `.env`:
```
HOST_PORT_BIND=54
```

You could also use the bundled resolver and attach it to your Host computer instead of your current local resolver. The devilbox bundled DNS server will have the `TLD_SUFFIX` domain routed to `127.0.0.1` automatically. So no need to setup your own DNS server for that - already included :-)

**Comment by fe3dback** [comment]
> You could also use the bundled resolver and attach it to your Host computer
how to do this?

when i run devilbox at /vhosts.php all my project has error "No Host DNS record found. Add the following to /etc/hosts: ..."

i have many-many projects, and i do not want each time add new line in hosts file.

dnsmasq and HOST_PORT_BIND=54 resolve this problem, but if you say it "already included".. =)

**Comment by cytopia** [comment]
**How to enable devilbox DNS**

1. You will have to stop and disable your current local resolver.
2. add `nameserver 127.0.01` to `/etc/resolv.conf`

Now, whenever you create a new project folder, DNS automatically exists. Even if you change `TLD_SUFFIX` to something else, it will still work.

**Comment by cytopia** [comment]
@fe3dback Did you get the devilbox DNS resolver to work locally? Or did this issue resolve otherwise?

**Comment by fe3dback** [comment]
I can't setup DB resolver. My steps:

1) Turn off my dnsmasq service, check host.
2) Replace port to default 53 in HOST_PORT_BIND env (before 54)
3) add nameserver 127.0.0.1 in /etc/resolv.conf
4) Restart my network service
5) Restart docker-compose

In devilbox /vhosts.php page, all my projects have label "No Host DNS record found".

So, now i returned to my dnsmasq service.

**Comment by cytopia** [comment]
`.4` restarting network service is not required. Maybe this changed `/etc/resolv.conf` again with a different resolver after you manually edited it?

Once you re-enabled port 53 and started docker-compose again, did the DNS receive errors during startup?

**Comment by cytopia** [comment]
Btw, are you on OSX or on Linux?

**Comment by fe3dback** [comment]
> Maybe this changed /etc/resolv.conf again with a different resolver after you manually edited it?

no, i check this when run docker-compose up

> Once you re-enabled port 53 and started docker-compose again, did the DNS receive errors during startup?

no errors.

> Btw, are you on OSX or on Linux?

Linux:
Linux more 4.4.0-75-generic #96-Ubuntu SMP Thu Apr 20 09:56:33 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

**Comment by cytopia** [comment]
I will close this ticket for the socket mount path. Could you open a separate ticket for the DNS issue if you want to dig further to get it to work.

**Comment by jhabdas** [comment]
[TCP and UDP ports used by Apple software products](https://support.apple.com/en-us/HT202944) states 53 is taken but does not mention 54.

My out of the devilbox experience following `.env` config was:

```
```

**Comment by jhabdas** [comment]
Updated.

**Comment by cytopia** [comment]
Continued here #82
