### ISSUE TITLE
Duplicate rewrite_log directive (can't get any logs)

### ISSUE THREAD

**Issue by pnoeric** [cytopia/devilbox#630]
I'm trying to log my rewrites...

This is the pertinent part of my nginx.yml override file:

```
###
### Basic vHost skeleton
###
vhost: |
  error_log /var/log/nginx-error.log notice;
  rewrite_log on;
  server {
      listen       __PORT____HTTP_PROTO____DEFAULT_VHOST__;
      server_name  __VHOST_NAME__;

      access_log   "__ACCESS_LOG__" combined;
      error_log    "__ERROR_LOG__" warn;

  __REDIRECT__
  __SSL__
  __VHOST_DOCROOT__
  __VHOST_RPROXY__
  __PHP_FPM__
  __ALIASES__
  __DENIES__
  __SERVER_STATUS__
      # Custom directives
  __CUSTOM__
  }
```

When the server starts up, I see: 

```
httpd_1    | 2019/09/11 16:35:02 [emerg] 268#268: "rewrite_log" directive is duplicate in /etc/httpd/vhost.d/mysite.conf:89
httpd_1    | nginx: [emerg] "rewrite_log" directive is duplicate in /etc/httpd/vhost.d/mysite.conf:89
httpd_1    | watcherd: [2019-09-11 16:35:02] [ERR] TRIGGER failed:    nginx -s stop
```
If I remove the rewrite_log directive from my `nginx.yml` file, it works fine, error message goes away.

I have mailhog installed (per the devilbox docs); could it be possible that it adds its own `rewrite_log` directive? (But there's no override for mailhog: `[WARN] override template not found:  /shared/httpd/mhsendmail/.devilbox/nginx.yml`)

And in general.... how can I just see the final, compiled, finished ;-) `nginx.conf` file (produced by `vhost_gen.py`) that nginx is using?! I can't find it anywhere on the box. That would probably help me spot the cause of this problem immediately. :-\

**Comment by science695** [comment]
The duplicate directive is most likely related to the fact that the nginx.yml template gets used to create http and https configs for every virtualhost.

You can see the compiled config files by going to the devilbox intranet page (possibly at localhost), and then going to Virtual Hosts. Each vhost is there with icons to see the template and compiled output.

**Comment by cytopia** [comment]
```diff
###
### Basic vHost skeleton
###
vhost: |
-  error_log /var/log/nginx-error.log notice;
  rewrite_log on;
  server {
      listen       __PORT____HTTP_PROTO____DEFAULT_VHOST__;
      server_name  __VHOST_NAME__;

      access_log   "__ACCESS_LOG__" combined;
      error_log    "__ERROR_LOG__" warn;
```

Remove this entry. You have specified it twice

**Comment by cytopia** [comment]
> And in general.... how can I just see the final, compiled, finished ;-) `nginx.conf` file (produced by `vhost_gen.py`) that nginx is using?! I can't find it anywhere on the box. That would probably help me spot the cause of this problem immediately. :-\

You can see that in the Devilbox intranet: /vhosts.php for each vhost.

> I have mailhog installed (per the devilbox docs); could it be possible that it adds its own rewrite_log directive?

This is a different Docker container which is not aware of anything else running, so It won't be changing anything in the Apache/Nginx configuration.

**Comment by cytopia** [comment]
@pnoeric I will close this issue. See comment above for how to resolve your issue. If that doesn't fix it, please reply here again.
