### ISSUE TITLE
How to specify a fully self-brewed webserver configuration?

### ISSUE THREAD

**Issue by thadudexx** [cytopia/devilbox#632]
#### ISSUE TYPE

 - Documentation

#### SUMMARY
as i cant get the way mentioned in the docs to work, because vhost-gen will always duplicate the content of the file for http and https. Resulting in duplicate vhost definitions.

#### Goal
see title
maybe make vhost-gen conf configurable for each project or
make it possible to define http and https vhost seperatly (like vhost_http: | / vhost_https: |)

**Comment by science695** [comment]
If you would like help on why you can't get your vhost configs to work right, you should provide more information.

However, your request for documentation is not needed. This information is already well documented:
https://devilbox.readthedocs.io/en/latest/vhost-gen/customize-specific-virtual-host.html#how-to-apply-templates-to-a-specific-project

**Comment by thadudexx** [comment]
Did you even read the issue? Did you try it? 
Which information are you missing, everything necessary is provided?
As i mentioned the documenation isn´t missing its just not working, for the reason provided.

**Comment by science695** [comment]
Most configuration options are fine being in 2 virtual hosts (one for http and one for https).

What are you putting in the configs that is breaking with the 2 versions?

**Comment by thadudexx** [comment]
a fully self-brewed webserver config with 2 virtual hosts (http and https), so i end up with 4 virtual hosts and duplicate definitions.
vhost-gen has the config options (plain, ssl, redir), but the config is hardcoded in devilbox, making vhost-gen conf configurable for each project would solve the problem or adding a keyword that doesn´t do any duplication at all.

**Comment by science695** [comment]
The way devilbox uses these templates, you should not put both exact virtualhosts in the template.

You would put the basics for your http vhost in...and then put the SSL custom stuff in the ssl feature section (which will be added to only the ssl version).

If you are familiar enough with docker, you could map the folder where it saves these vhosts and just manually create your vhost (and set it read only): /etc/httpd/vhost.d/ (for apache)

Any further advise would require you to show what config you are using. If you wanted to post / upload what you are working with (or a sanitized version), I could help further.

**Comment by thadudexx** [comment]
Thank you for your help! I know that it is not possible to do with devilbox and vhost-gen now, thats why i asked why documenation says its possible? Hoping there would be a solution, i didnt see. The "vhost: |"-format covers just the easier ways, more complicated mostly wont work that way. But vhost-gen on his own would be able to do it, just the hardcoded config in devilbox is blocking it. I know i could create my own container or rewrite the whole config, but just using another virtualisation software and copying the working webserver config there is at least 10 times faster. Specially because its the easiest job vhost-gen will ever get, do nothing just copy the file. And i really just wanted to try something quick.
