### ISSUE TITLE
How to Set Memory and CPU Limits ?

### ISSUE THREAD

**Issue by mozgbrasil** [cytopia/devilbox#633]
Good morning my friends

Can you help me

How do I configure memory and processor usage restrictions?

**Comment by vikas5914** [comment]
I think you can do this on docker using its setting.

**Comment by mozgbrasil** [comment]
Hello my friend

I tried to change the "docker-compose.yml" file by adding the snippet as

https://docs.docker.com/compose/compose-file/#resources

But unsuccessful, error returned

"Unsupported config option for services.php: 'deploy'"

If you have a model of how to proceed and if you can make available in advance thank you

**Comment by science695** [comment]
@mozgbrasil Devilbox uses docker-compose version 2.1, so follow the link found from the docs you mentioned and use the V2 configuration parameters:
https://docs.docker.com/compose/compose-file/compose-file-v2/#cpu-and-other-resources

**Comment by cytopia** [comment]
@mozgbrasil will close this in favour of: https://github.com/cytopia/devilbox/issues/618 which will give you the required compose settings.
