### ISSUE TITLE
How to use vue ui with Devilbox (using Nginx)?

### ISSUE THREAD

**Issue by mgsmus** [cytopia/devilbox#638]
data/www/vue-ui/.devilbox/nginx.yml:
```
vhost: |
  server {
      listen       __PORT____HTTP_PROTO____DEFAULT_VHOST__;
      server_name  __VHOST_NAME__;

      access_log   "__ACCESS_LOG__" combined;
      error_log    "__ERROR_LOG__" warn;

      # Reverse Proxy definition (Ensure to adjust the port, currently '8000')
      location / {
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_pass http://php:8000;
      }
```

```
devilbox@php-7.3.7 in /shared/httpd $ vue ui
�  Starting GUI...
�  Ready on http://localhost:8000
```

I'm getting this error:

> [error] 351#351: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.16.238.1, server: vue-ui.test, request: "GET / HTTP/1.1", upstream: "http://172.16.238.10:8000/", host: "vue-ui.test"

and the browser gives me 502 Bad Gateway error.

**Comment by mrbig00** [comment]
i think that you should map the 8000 port from your container to your host machine

**Comment by cytopia** [comment]
> devilbox@php-7.3.7 in /shared/httpd $ vue ui
> �  Starting GUI...
> �  Ready on http://localhost:8000

This must listen on all interfaces and not just on `localhost`. The `httpd` container will otherwise be unable to access your application (which runs on the `php` container).

So ensure to bind your vue application to `0.0.0.0`

**Comment by nasrithamer** [comment]
Hi, Good morning,
i have installed vueJs v2 and i make:

ln -s public/ htdocs
copying ./devilbox ngnix.yml to my directory and modify the port 8080 
modify  package.json scripts vue-cli-service serve --host 0.0.0.0 --port 8080
npm run server 
everything is ok like the image 

![image](https://user-images.githubusercontent.com/13709609/127852342-c511dbfc-be9e-4627-80ca-5ec6a7f32062.png)


but i have 502 bad gateway when i visit http://tuto_vuejs.loc/
