### ISSUE TITLE
Disable email-catchAll ?

### ISSUE THREAD

**Issue by RaffyeMemon** [cytopia/devilbox#642]
Hi,

is there a way to disable email-catch all yet  ? also i any updates to have this production ready ?

Thanks for all you doo !

-RM

**Comment by cytopia** [comment]
@RaffyeMemon I will have a look into this. Seems to be something really useful.

**Comment by cytopia** [comment]
@RaffyeMemon will be addressed here: https://github.com/devilbox/docker-php-fpm/pull/143

**Comment by cytopia** [comment]
Set [ENABLE_MAIL](https://github.com/cytopia/devilbox/blob/master/docker-compose.yml#L138) to `1` and postfix will be started without email catch all.

You will still need to configure postfix yourself to your needs via the startup scripts (use `postconf` in a bash script to accomplish what you require)

**Comment by cytopia** [comment]
Now it is configurable via `.env`
