### ISSUE TITLE
 JPEG support is missing from php 7.4

### ISSUE THREAD

**Issue by IonutNeagu** [cytopia/devilbox#644]
### ISSUE TYPE

 - Bug Report

### SUMMARY

I think the jpeg support is missing because in php 7.4 some parameters used for compilation have been changed
[PHP 7.4 UPGRADE NOTES - Migration to pkg-config ](https://github.com/php/php-src/blob/fa123b51ccd173224fb033ddcf148e8a97138127/UPGRADING#L290)

**Comment by cytopia** [comment]
Upgrade is on the way
