### ISSUE TITLE
PHPUnit version selection

### ISSUE THREAD

**Issue by bashebr** [cytopia/devilbox#651]
#### ISSUE TYPE

 - Feature request

#### SUMMARY

- Actually, the devilbox comes preinstalled with PHPUnit, however, it comes only with one version of PHPUnit. So I would like the devilbox to allow me to select multiple versions of phpunit.

#### Goal

Multiple versions of PHPUnit, so that, I would be able to test different versions of certain application.

**Comment by cytopia** [comment]
Adding more versions of PHPUnit would be a never-ending story, as many different developer would require too many different pre-installed versions. This would  make the image size way too big.

I'd rather recommend to install it locally on a per project base via `composer`:
```
composer require --dev phpunit/phpunit ^8.4
```
* [1] https://phpunit.readthedocs.io/en/8.4/installation.html


I will close this feature request. Feel free to start a community discussion around this topic here: https://devilbox.discourse.group/
