### ISSUE TITLE
Default DNS servers should come from host rather than using Google's DNS servers

### ISSUE THREAD

**Issue by inferont** [cytopia/devilbox#656]
#### ISSUE TYPE

 - Feature request

#### SUMMARY
The default DNS servers currently set up will not have any custom resolution that has been set by the developer or network admins. All requests will also be captured by Google. The container DNS setup should respect the configuration of the host machine.

#### Goal
Any domain that would be resolved by the local machine will also be resolved in the containers through the same servers.

**Comment by cytopia** [comment]
This can be accomplished by specifying different upstream DNS server via `BIND_DNS_RESOLVER` variable in your `.env` file: https://devilbox.readthedocs.io/en/latest/configuration-files/env-file.html#bind-dns-resolver

**Comment by inferont** [comment]
@cytopia  Yes, I am aware of this. I have configured it. This feature request was to have the default DNS resolver come from the host rather than set up to be Google. The BIND_DNS_RESOLVER variable could still exist separately.

**Comment by cytopia** [comment]
> This feature request was to have the default DNS resolver come from the host

This would not be possible. You only have `docker-compose` as your moving target to issue any commands. This won't be able to figure out the host settings (not talking about different Windows, OSX and Linux versions). So I guess it won't be possible.

**Comment by inferont** [comment]
@cytopia Yeah, you're right with how devilbox is currently run by most developers. Maybe the https://github.com/devilbox/devilbox-cli project could be used to handle these kind of features.
