### ISSUE TITLE
Extension installation request: YAML

### ISSUE THREAD

**Issue by boumanb** [cytopia/devilbox#664]
#### ISSUE TYPE

 - Feature request

#### SUMMARY

Adding the `ext-yaml` https://pecl.php.net/package/yaml PHP extension to Devilbox by default so that one can use it without having to install it each time a `docker-compose down` has been run. I'm aware of the fact that running `docker-compose stop` instead of `docker-compose down` will result in not losing the installation of a particular extension but this one seems quite viable to be added by default.

I've looked #263 and #107 and it I guess adding it to the image is the best way to accomplish the goal. Unless I've missed something in the documentation I think there isn't any more convenient way to install custom modules. If someone did succeed in doing so, please respond to this issue.

Thanks in advance.

#### Goal

Using the PHP YAML extension without having to reinstall it on every `docker-compose down`.

**Comment by cytopia** [comment]
@boumanb is coming shortly.
