### ISSUE TITLE
Alternative to all these "Install this program" requests

### ISSUE THREAD

**Issue by science695** [cytopia/devilbox#665]
Hello Cytopia,

I've been looking at all these requests people have for new programs, and custom versions, etc...

What if you shipped a version of all the docker files with an alternative docker-compose file so they could use docker-compose's dockerfile building to run their own apt-get installs on top of your base images?

They would have to recompile those images when your base docker images updated, but would otherwise give them the flexibility for versions etc...without burdening more simpler setups with all the dependencies.

**Comment by cytopia** [comment]
@science695 there is actually a leight-weight image available for all php versions. I haven't made it configurable yet, but could do so. You could replace `work` with `prod` and have a very small image to use.

`docker-compose.yml`:
```diff
index c9aa52b2..13d71b94 100644
--- a/docker-compose.yml
+++ b/docker-compose.yml
@@ -95,7 +95,7 @@ services:
   php:
-    image: devilbox/php-fpm:${PHP_SERVER}-work-0.101
+    image: devilbox/php-fpm:${PHP_SERVER}-prod-0.101
     hostname: php
```

Alternatively I could add another flavour named `full` based on `work` which holds all the custom requested tools. With this one still needs to figure out what kind of tools will go into `work` and what other tools will go into `full`

**Comment by boumanb** [comment]
I've just read: https://github.com/devilbox/docker-php-fpm#load-custom-php-modules, I was able to find the following in Devilbox's `docker-compose.yml`: 
```
# Mount devilbox user-defined *.so files in order
# to load custom PHP modules
- ${DEVILBOX_PATH}/mod/php-fpm-${PHP_SERVER}:/usr/lib64/php/custom-modules:ro${MOUNT_OPTIONS}
```
Does this mean that we could do the following? : 
1. Download `.tgz` or `.dll` of the extension i.e. https://pecl.php.net/package/yaml
2. Compile the extension ourselve
3. Copy it to `mod/php-fpm-${PHP_SERVER}` 
4. Enable the extension using a `.ini` in `cfg/php-ini-${PHP_SERVER}`
5. Use the extension within your environment

It's not that user-friendly I guess but it at least works without having @cytopia to modify the images all the time and without burdening more simpler setups.

**Comment by darkalchemy** [comment]
I am very new to docker and devilbox, actually using this less than a week.
Would this be possible?
In addition to full, work and prod, you could add custom. Maybe using this 'custom' could trigger a build and use only what the user needs. Would that be simpler to maintain?

**Comment by science695** [comment]
@darkalchemy The idea is that you would use prod as the base, and then setup your own dockerfile that could add a few layers to it to add whatever custom tools you wanted:
`FROM devilbox/php-fpm:${PHP_SERVER}-prod-0.101
RUN apt-get update && apt-get install my_custom_tools
COPY my_custom-files /....
etc...
`
Whenever you pull a new version of devilbox, docker-compose would need to rebuild them, but otherwise not every rebuild...

**Comment by darkalchemy** [comment]
@science695 thanks, still so much to learn...
