### ISSUE TITLE
Cannot run Dockers after update

### ISSUE THREAD

**Issue by RaffyeMemon** [cytopia/devilbox#666]
I cannot run any of the containers after update:

Following is the error:

docker-compose up -d mysql

WARNING: The HOST_PATH_SSH_DIR variable is not set. Defaulting to a blank string.
mydevdockers_bind_1 is up-to-date
Creating mydevdockers_php_1 ... error

ERROR: for mydevdockers_php_1  Cannot create container for service php: invalid volume specification: '/host_mnt/home/devilbox/.ssh:ro'

ERROR: for php  Cannot create container for service php: invalid volume specification: '/host_mnt/home/devilbox/.ssh:ro'
ERROR: Encountered errors while bringing up the project.

what is gone wrong. ?

**Comment by cytopia** [comment]
The `HOST_PATH_SSH_DIR` variable is not set. ;-)
Please ensure to read the documentation when updating: https://devilbox.readthedocs.io/en/latest/maintenance/update-the-devilbox.html

I've introduced a new variable in `env-example`. Ensure it also exists in `.env`

**Comment by thadudexx** [comment]
Just out of curiousity, how would reading the documentation help, i couldn´t find anything about the new variable, did i overlook that part?

**Comment by llaville** [comment]
@thadudexx see details here https://devilbox.readthedocs.io/en/latest/configuration-files/env-file.html#host-path-ssh-dir

**Comment by thadudexx** [comment]
Thank you very much, didnt see that one.
