### ISSUE TITLE
`phalcon` extension is not working

### ISSUE THREAD

**Issue by ahmetbibi** [cytopia/devilbox#670]
When I try to create a phalcon project in php container, it says `phalcon: command not found`
I checked the available cli extensions beginning with `p` letter, I couldn't see `phalcon` there.

**Comment by cytopia** [comment]
Which PHP version do you use? You can see the available modules list per PHP version here: https://github.com/devilbox/docker-php-fpm#php-modules

Also, did you pull the latest PHP images?

**Comment by ahmetbibi** [comment]
I've just installed Devilbox, today and created a simple project, it is working (so I didn't make any other step except default devilbox installation). I see `devilbox@php-7.3.13` when I enter the php container so the php version 7.3 I guess.  Phalcon must be available like stateted in https://devilbox.readthedocs.io/en/latest/readings/available-tools.html page am I wrong?

**Comment by ahmetbibi** [comment]
I pulled the latest php images as well, but still command line says `phalcon: command not found` 
Switched to php 7.4 but still it's not working.

![screenshot-devilbox](https://user-images.githubusercontent.com/44682850/73655841-2dbf4980-468f-11ea-8d3a-3b7747b68b68.png)
![devilbox-php7 4](https://user-images.githubusercontent.com/44682850/73655842-2dbf4980-468f-11ea-863e-4c9190b4d59d.png)

**Comment by cytopia** [comment]
Good catch! Binaries are shipping with next php-fpm release. PR here: https://github.com/devilbox/docker-php-fpm/pull/155

**Comment by cytopia** [comment]
Will be available later this day.

**Comment by ahmetbibi** [comment]
Ok, thanks.
