### ISSUE TITLE
Open DevilBox home page at start

### ISSUE THREAD

**Issue by xenio** [cytopia/devilbox#678]
#### ISSUE TYPE
 - Feature request

#### SUMMARY
Is there a way to automatically start the DevilBox home page after all the containers are started?

#### Goal
I am on MacOs and I like to have the http://localhost/vhosts.php or just http://localhost launched on the browser after docker-compose up.

**Comment by science695** [comment]
One potential issue is that the dockers start up, and then take several seconds while they generate the vhosts and the certificates. And this scales with how many subdomains you have in your sites folder.

If we added open localhost as a command in the rebuild, it would likely show a service unavailable.

**Comment by xenio** [comment]
Yep, I am getting Service Unavailable if I use a bash script in the autostart folder with:
`/usr/bin/open -a "/Applications/Google Chrome.app" 'http://localhost/vhosts.php'`

With an alias and a sleep command I can make it work, it is ok for me.
`alias devilboxstart='cd /Users/sandro/devilbox && docker-compose up -d httpd php mysql && /bin/sleep 7 && open http://localhost/vhosts.php'`

**Comment by cytopia** [comment]
This would be a better candidate for [devilbox-cli](https://github.com/louisgab/devilbox-cli) which is maintained by @louisgab
