### ISSUE TITLE
unauthorized: authentication required

### ISSUE THREAD

**Issue by RaffyeMemon** [cytopia/devilbox#681]
Hi.. 

need help with docker pull devilbox/php-fpm:7.2-work .. strange part is docker pull devilbox/php-fpm:7.2-prod worked.

not sure why work image is not pulling and prod just worked fine.

Thanks,

-RM

**Comment by boumanb** [comment]
We experienced something alike, after updating docker (Windows). Suddenly some were required to be logged into docker (using a docker hub registered account). 

Can you verify that you're currently logged in using a docker hub account? 
`docker system info | grep -E 'Username'` _or using the GUI on docker desktop (Windows)_

You should be seeing something like this:
`Username: <your_username>` 

If you're not seeing anything than please try logging in and pulling again. You can do this with the docker desktop GUI on Windows. You can also use the CLI on both linux and Windows like this: `docker login`

**Comment by cytopia** [comment]
@RaffyeMemon any update from your side, otherwise I would close this issue as it is not directly related to the Devilbox.

**Comment by RaffyeMemon** [comment]
i uninstalled docker and reinstalled .. after that it worked even without login to docker-hub
