### ISSUE TITLE
Unable to connect to postgree service from terminal 

### ISSUE THREAD

**Issue by MichaelHabib** [cytopia/devilbox#685]
### ISSUE TYPE

 - Bug Report

### Checklist

* [x] `.env` file is attached
* [x] `docker-compose.override.yml` is attached (if it exists)
* [x] Custom configs from `cfg/` dir are attached (if customized)
* [x] `docker-compose logs` and `log/` output is added
* [x] I've looked through the docs: https://devilbox.readthedocs.io/en/latest/
* [x] I've looked through existing issues: https://github.com/cytopia/devilbox/issues
* [x] I've read troubleshooting: https://devilbox.readthedocs.io/en/latest/support/troubleshooting.html

### OS / ENVIRONMENT

1. Host operating system and version: Kubuntu 18
2. (Windows) Native Docker or Docker Toolbox: 
3. Docker version: Client: Docker Engine - Community 19.03.5
4. Docker Compose version: docker-compose version 1.25.4, build 8d51620a
5. (Linux) Is SELinux enabled?: not installed
6. What git commit hash are you on?: 7d6c7a4affcbd47eff888b43e41b4932a3cdc02a

### SUMMARY

Unable to connect to postgre service from command line . Using the default .env without any changes .

### STEPS TO REPRODUCE

- run docker with `docker-compose up pgsql php httpd`
- execute `./shell.sh`
- attempt to connect to postgresql using `psql -U postgre`

### EXPECTED BEHAVIOUR

Being able to connect to postgree service 

### ACTUAL BEHAVIOUR

The following error returned 
"psql: error: could not connect to server: could not connect to server: No such file or directory
	Is the server running locally and accepting
	connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?

"
### OTHER INFORMATION

.env file https://gist.github.com/MichaelHabib/1f1131b5f8908c000b0efa303dc266e0
`docker-compose log` https://gist.github.com/MichaelHabib/8b66593aea2d497d6c2ef68792e08968

#### Start command

```
$ docker-compose up pgsql php httpd

```

#### File and user permissions (Linux & MacOS)

```
$ id
```
uid=1000(user) gid=1000(user) groups=1000(user),4(adm),24(cdrom),27(sudo),30(dip),46(plugdev),113(lpadmin),128(sambashare),999(docker)

```
$ ls -la
```
drwxrwxr-x  8 user user  4096 Mar  9 22:11 ..
drwxrwxr-x  2 user user  4096 Mar  9 09:59 autostart
drwxr-xr-x  3 user user  4096 Mar  9 10:56 backups
drwxrwxr-x  2 user user  4096 Mar  9 09:59 bash
drwxrwxr-x  2 user user  4096 Mar  9 21:09 ca
drwxrwxr-x 57 user user  4096 Mar  9 09:59 cfg
-rw-rw-r--  1 user user  7924 Mar  9 09:59 CHANGELOG.md
drwxrwxr-x  2 user user  4096 Mar  9 09:59 compose
-rw-rw-r--  1 user user  2770 Mar  9 09:59 CONTRIBUTING.md
drwxrwxr-x  3 user user  4096 Mar  9 09:59 data
drwxrwxr-x  3 user user  4096 Mar  9 09:59 .devilbox
-rw-rw-r--  1 user user   747 Mar  9 09:59 docker-compose.override.yml-example
-rw-rw-r--  1 user user 14865 Mar  9 09:59 docker-compose.yml
drwxrwxr-x 20 user user  4096 Mar  9 09:59 docs
-rw-rw-r--  1 user user  2502 Mar  9 09:59 .editorconfig
-rw-rw-r--  1 user user 18695 Mar  9 10:12 .env
-rw-rw-r--  1 user user 18695 Mar  9 09:59 env-example
drwxrwxr-x  8 user user  4096 Mar  9 22:22 .git
drwxrwxr-x  4 user user  4096 Mar  9 09:59 .github
-rw-rw-r--  1 user user  3612 Mar  9 09:59 .gitignore
drwxrwxr-x  4 user user  4096 Mar  9 22:22 .idea
-rw-rw-r--  1 user user  1064 Mar  9 09:59 LICENSE.md
drwxrwxr-x  5 user user  4096 Mar  9 21:09 log
drwxrwxr-x  9 user user  4096 Mar  9 10:56 mod
-rw-rw-r--  1 user user 64530 Mar  9 09:59 README.md
-rw-rw-r--  1 user user    86 Mar  9 09:59 shell.bat
-rwxrwxr-x  1 user user    59 Mar  9 09:59 shell.sh
drwxrwxr-x  5 user user  4096 Mar  9 09:59 .tests
-rw-rw-r--  1 user user 11506 Mar  9 09:59 .travis.yml
-rwxrwxr-x  1 user user  2265 Mar  9 09:59 update-docker.sh
-rw-rw-r--  1 user user  1490 Mar  9 09:59 UPDATING.md

```
$ ls -la data/www
```
drwxr-xr-x 3 user user 4096 Mar  9 22:14 .
drwxrwxr-x 3 user user 4096 Mar  9 09:59 ..
drwxrwxr-x 3 user user 4096 Mar  9 22:11 demo-php-postgre-csv-user-upload
-rw-rw-r-- 1 user user    0 Mar  9 09:59 .keepme

**Comment by science695** [comment]
shell.sh is logging you into the php container of devilbox, and then you are running psql without telling it the path to the psql server.

I'm not real familiar with postgres, but pulling from the manual

```
psql -h <host> -p <port> -u <database>
psql -h <host> -p <port> -U <username> -W <password> <database>
```

I would imagine you could do this after ./shell.sh (assuming you don't need any of the other options):
> psql -h pgsql -U postgre

**Comment by cytopia** [comment]
You can see an example in the documentation: https://devilbox.readthedocs.io/en/latest/maintenance/backup-and-restore-pgsql.html#pg-dump

The host is `-h pgsql` and the user is `-U postgres`

**Comment by cytopia** [comment]
@MichaelHabib can you report back if specifying host solves your issue?

**Comment by MichaelHabib** [comment]
Sorry about the late reply.

Yes, specifying the host seems to solve the issue, I assumed `localhost` would be a default fallback if the host name was not provided .

Thanks for your time.

**Comment by science695** [comment]
> Yes, specifying the host seems to solve the issue, I assumed `localhost` would be a default fallback if the host name was not provided .

@MichaelHabib Just a quick tip on linux systems, they often default to a local socket, not a local ip. So on most systems, it seems like they are defaulting to localhost, but the socket magic is covering it for you.

With dockers, inner container is separated from your computer so it can't just use a socket on your computer.

**Comment by robots4life** [comment]
Install the psql client to connect from the host to the docker container.

:bulb: <a href="https://askubuntu.com/questions/1040765/how-to-install-psql-without-postgres">https://askubuntu.com/questions/1040765/how-to-install-psql-without-postgres</a>

```shell
sudo apt-get install -y postgresql-client
```

:bulb: <a href="https://stackoverflow.com/questions/37694987/connecting-to-postgresql-in-a-docker-container-from-outside">https://stackoverflow.com/questions/37694987/connecting-to-postgresql-in-a-docker-container-from-outside</a>

```shell
psql -h <host> -p <port> -u <database>
psql -h <host> -p <port> -U <username> -W <password> <database>
```

The host is `-h pgsql` and the user is `-U postgres`.

```shell
psql -h 172.16.238.13 -p 5432 -U postgres
```

List all databases while connected to to the PostgreSQL database with the `postgresql-client`.

```shell
\l
```

terminal output :point_right:

```shell
                                 List of databases
   Name    |  Owner   | Encoding |  Collate   |   Ctype    |   Access privileges
-----------+----------+----------+------------+------------+-----------------------
 postgres  | postgres | UTF8     | en_US.utf8 | en_US.utf8 |
 template0 | postgres | UTF8     | en_US.utf8 | en_US.utf8 | =c/postgres          +
           |          |          |            |            | postgres=CTc/postgres
 template1 | postgres | UTF8     | en_US.utf8 | en_US.utf8 | =c/postgres          +
           |          |          |            |            | postgres=CTc/postgres
(3 rows)
```

Prisma PostgreSQL connection string in `.env` file.

```shell
DATABASE_URL="postgresql://postgres@localhost:5432/NAME_OF_YOUR_DATABSE?schema=public"
```
