### ISSUE TITLE
Auto DNS not working

### ISSUE THREAD

**Issue by StanMenten99** [cytopia/devilbox#693]
### ISSUE TYPE
 - Bug Report

### Checklist
* [ / ] `.env` file is attached [env.txt](https://github.com/cytopia/devilbox/files/4444939/env.txt)
* [ / ] `docker-compose.override.yml` is attached (if it exists)
* [ / ] Custom configs from `cfg/` dir are attached (if customized)
* [ / ] `docker-compose logs` and `log/` output is added
* [ x ] I've looked through the docs: https://devilbox.readthedocs.io/en/latest/
* [ x ] I've looked through existing issues: https://github.com/cytopia/devilbox/issues
* [ x ] I've read troubleshooting: https://devilbox.readthedocs.io/en/latest/support/troubleshooting.html

### OS / ENVIRONMENT
1. Host operating system and version: Windows 10 Pro 
2. (Windows) Native Docker or Docker Toolbox: Docker Desktop
3. Docker version: 2.2.0.5
4. Docker Compose version: latest
5. (Linux) Is SELinux enabled?:
6. What git commit hash are you on?:

### SUMMARY
I'm currently using docker in combination with Devilbox with auto DNS enabled.
This works so far.
Now I want to use it on my Windows machine but the auto DNS doesn't work.

### EXPECTED BEHAVIOUR
A working auto DNS.

### ACTUAL BEHAVIOUR
Auto DNS is not working.

#### Start command

```
 cd c:/devilbox
docker-compose up
```

**Comment by vikas5914** [comment]
@StanMenten99 please provide your `.env` file.

**Comment by StanMenten99** [comment]
> @StanMenten99 please provide your `.env` file.


[env.txt](https://github.com/cytopia/devilbox/files/4444935/env.txt)

**Comment by fkaminski** [comment]
I just swichted from Docker Toolbox to Docker-Desktop (Win 10 PRO) 
with the Hyper-V and Docker-Desktop default settings.

Set the HOST_PORT_BIND=53 in the .env 
and 127.0.0.1 as DNS in the network adapter (the generated Hyper-V Virtual Ethernet Adapter):

https://devilbox.readthedocs.io/en/latest/intermediate/setup-auto-dns.html
https://devilbox.readthedocs.io/en/latest/howto/dns/add-custom-dns-server-on-win.html#howto-add-custom-dns-server-on-win


AutoDNS works for me ...

**Comment by StanMenten99** [comment]
> I just swichted from Docker Toolbox to Docker-Desktop (Win 10 PRO)
> with the Hyper-V and Docker-Desktop default settings.
> 
> Set the HOST_PORT_BIND=53 in the .env
> and 127.0.0.1 as DNS in the network adapter (the generated Hyper-V Virtual Ethernet Adapter):
> 
> https://devilbox.readthedocs.io/en/latest/intermediate/setup-auto-dns.html
> https://devilbox.readthedocs.io/en/latest/howto/dns/add-custom-dns-server-on-win.html#howto-add-custom-dns-server-on-win
> 
> AutoDNS works for me ...

Thanks, adding 127.0.0.1 as DNS in my Hyper-V networkadapter did the job.
I was adding it to my main adapter...

**Comment by fkaminski** [comment]
@StanMenten99 
Good News ...

**Comment by cytopia** [comment]
Good to hear :)
