### ISSUE TITLE
Feature request: Add "php-common" package

### ISSUE THREAD

**Issue by Luc45** [cytopia/devilbox#696]
#### ISSUE TYPE

 - Feature request

#### SUMMARY
I would like to use `phpenmod` and `phpdismod`. They are part of `php-common` package. I'd like to suggest adding `php-common` by default.

#### Goal
What I'm trying to achieve is related to Xdebug performance. I will leave it loaded for web requests, but I would like to disable them when running CLI commands. Example: `phpdismod xdebug && phpunit tests && phpenmod xdebug`

Disabling Xdebug makes the tests run up to twice as fast, even if Xdebug is completely turned off. Just by having the extension loaded.

**Comment by Luc45** [comment]
PS: I tried to add it myself before opening this PR, but I simply couldn't. I use Ubuntu on my host machine and I'm used to install all sorts of packages, PPAs and stuff, but I simply couldn't install `php-common` from inside the container. I don't know why.

**Comment by science695** [comment]
I think its because docker containers usually clear all repository caches and indexes. Try:
`apt update && apt install php-common`

**Comment by cytopia** [comment]
`phpenmod` and `phpdismod` are Debian specific script helper to load/unload modules. They will only work if PHP and all of their modules have been installed via `apt` (as it goes into specific locations and does a lot of Debian-based customization).

In case of the Devilbox, it is using the official PHP docker images as base - they are compiled via source, and all of its modules are not installed via `apt` (as this would require PHP itself to be installed via `apt`).

So you cannot install any php-* packages via `apt` (or at least it will not have any benefit or new modules available).

**Comment by Luc45** [comment]
Thanks for the help, @cytopia.

I will look for another way of loading/unloading PHP modules, then, to be able to use Xdebug without slowing down my development environment.

**Comment by cytopia** [comment]
@Luc45 have a look at `/usr/local/bin/docker-php-ext-enable`. This is a shell script provided by the base PHP docker image to enable modules. With a bit of work, you could derive one to disable modules the same way.

**Comment by cytopia** [comment]
@Luc45 (cc @science695 ) you can enable/disable PHP modules via Devilbox itself. Have a look here: https://devilbox.readthedocs.io/en/latest/intermediate/enable-disable-php-modules.html

I will close this issue, as the initial request for `php-common` is a won't do.
