### ISSUE TITLE
Apache 403 Forbidden under Windows 10

### ISSUE THREAD

**Issue by dany-eudes** [cytopia/devilbox#70]
Under Windows, VirtualBox IP address by default is 192.168.99.100. 

So, we'll get a 403 Forbidden because it's not appears in `.devilbox/etc/apache-2.4/01-vhost-default.conf`.
Just include it there as a alias and all stuff will be Ok.
```
<VirtualHost _default_:80>
	ServerName  localhost
	ServerAlias 127.0.0.1
	ServerAlias 172.16.238.*
        ServerAlias 192.168.99.100
	ServerAlias httpd
```
Always nice when ticket resolved itself. ;)
That's it!

Note1: devilbox branch master
Note2: I included also `devilbox.loc` as alias because I put that in `C:\Windows\System32\drivers\etc\hosts` file

**Comment by cytopia** [comment]
@dany-eudes Thanks for the info.

Isn't it also possible to just add:
```
192.168.99.100 httpd
```
in your `C:\Windows\System32\drivers\etc\hosts` file instead of changing the above vhost settings?

**Comment by dany-eudes** [comment]
@cytopia, sure it's possible insert `httpd` alias into `hosts` file. But I prefer `devilbox.loc` because it's a so good name! If I were you I'd put that name in vhost conf file and I'd update the docs to make a direction to Windows guys. BTW, great job! Congrats!

**Comment by cytopia** [comment]
@dany-eudes I keep that in mind.

It will not be before end of summer until i will have my own windows machine. So until then I rely on you guys :-) Keep up ticketing for any problems on windows.

**Comment by cytopia** [comment]
@dany-eudes I will have adjust all 4 webserver docker container in order to simply add an IP address to `.env` as an injectable value

**Comment by cytopia** [comment]
Btw, are you using [Docker Toolbox](https://docs.docker.com/toolbox/overview/) or [Docker for Windows](https://docs.docker.com/docker-for-windows/install/#download-docker-for-windows)

**Comment by cytopia** [comment]
@dany-eudes the whole problematic will be resolved in the upcoming release: https://github.com/cytopia/devilbox/pull/130

The intranet itself is setup to be served from a default virtual host container and should be reachable from any domain (except project domains) pointing to the webserver.

If you want to check it out before the actual release will be merged, follow the instructions described in the above linked pull request.

**Comment by cytopia** [comment]
The above mentioned PR #130 has been merged and should fix this issue.

I have added some information regarding Docker Toolbox: http://devilbox.readthedocs.io/en/documentation/installation/docker-toolbox.html
