### ISSUE TITLE
php-7.4.4 - the requested PHP extension imap is missing from your system.

### ISSUE THREAD

**Issue by milos-stankovic** [cytopia/devilbox#700]
Hello,

How can I solve this missing extension, please!?

![image](https://user-images.githubusercontent.com/14111282/79115938-7da14780-7d87-11ea-822d-cd3dec3f917b.png)

**Comment by julienpastore** [comment]
Hello !

I got the same issue. After checking the documentation, it appears that the php 7.4 image does not contained the imap module.

In this case I assume we have to install it "manually", but I'm not sure how. 

From what I've read, the devilbox allows to use custom php module: https://github.com/vermauv/devilbox/blob/master/docs/Configure.md#13-the-devilbox-mod-directory

But I'm not sure to understand how to apply this example with the imap extension.

If someone more knowledgeable could provide some help, I'll be much obliged.

**Comment by cytopia** [comment]
@milos-stankovic @julienpastore currently baking: https://github.com/devilbox/docker-php-fpm/pull/159

**Comment by cytopia** [comment]
@milos-stankovic @julienpastore I am still having trouble getting MongoDB support for PHP 8.0 If you currently don't care about this, then go ahead and checkout this PR: https://github.com/cytopia/devilbox/pull/711

**Comment by cytopia** [comment]
Merged and available in `v1.7.1`
