### ISSUE TITLE
Mac Mojave DNS issues

### ISSUE THREAD

**Issue by baskettcase** [cytopia/devilbox#701]
### ISSUE TYPE

 - Bug Report

### Checklist

* [X] `.env` file is attached
* [X] `docker-compose.override.yml` is attached (if it exists)
* [X] Custom configs from `cfg/` dir are attached (if customized)
* [X] `docker-compose logs` and `log/` output is added
* [X] I've looked through the docs: https://devilbox.readthedocs.io/en/latest/
* [X] I've looked through existing issues: https://github.com/cytopia/devilbox/issues
* [X] I've read troubleshooting: https://devilbox.readthedocs.io/en/latest/support/troubleshooting.html

[env.txt](https://github.com/cytopia/devilbox/files/4495459/env.txt)
[docker-compose.override.yml.txt](https://github.com/cytopia/devilbox/files/4495464/docker-compose.override.yml.txt)
[docker-compose logs.txt](https://github.com/cytopia/devilbox/files/4495469/docker-compose.logs.txt)

### OS / ENVIRONMENT

1. Host operating system and version: Mac OS X Mojave 10.14.6
2. (Windows) Native Docker or Docker Toolbox: 
3. Docker version: 2.2.0.5
4. Docker Compose version: 1.25.4
5. (Linux) Is SELinux enabled?:
6. What git commit hash are you on?: 8c931cdf5636b08ffecd0c73cb40ec4afd239783

### SUMMARY
DNS does not seem to work, either does AutoDNS. I get the message in the Virtualhosts tab that I need to add the line to the hosts file and it's there. I've used a lot of different tools and they always see the hosts file, but devilbox doesn't seem to see it.

### STEPS TO REPRODUCE
Just follow the instructions on how to install devilbox, then add a virtualhost directory with htdocs in the data/www folder and then load up the virtualhost tab and it shows that I need to add the line to the hosts file.

### EXPECTED BEHAVIOUR
Be able to see the domain in the browser

### ACTUAL BEHAVIOUR
Time out

#### Start command

```
$ docker-compose up -d httpd php mysql
```

#### File and user permissions (Linux & MacOS)

```
$ id
uid=502(murlyn) gid=20(staff)
```

```
$ ls -la
drwxr-xr-x   35 murlyn  staff   1120 Apr 17 15:05 devilbox
```

```
$ ls -la data/www
drwxr-xr-x  3 murlyn  staff    96 Apr 17 12:12 drtungs.com
drwxr-xr-x  3 murlyn  staff    96 Apr 17 13:11 sharmalia.com
```

**Comment by science695** [comment]
Mac no longer supports local DNS servers. Make sure to clear all of the auto dns config from your network settings, and then confirm that the appropriate lines are in /etc/hosts.

**Comment by baskettcase** [comment]
Thank you for your help! Ok I deleted it all, but the only reason I was trying to add AutoDNS was because the hosts file was not working with devilbox, what can I try now? and yes the appropriate lines are in the hosts file.

**Comment by science695** [comment]
What happens if you open terminal and try to ping either of those 2 hosts?
```
ping drtungs.com.loc
ping sharmalia.com.loc
```

**Comment by baskettcase** [comment]
The ping was working (and it wasn't when I first started this thread) and I found that another app was taking over port 80 and 443 even though in the docs it told me how to check if those ports were taken and they were not.. or Im completely blind. I removed those bindings and restarted docker and then devilbox and I am now able to see what I need to see. Thank you for the help!
