### ISSUE TITLE
Generate SSL certificate also for ServerAlias entries

### ISSUE THREAD

**Issue by tzimpel** [cytopia/devilbox#702]
#### ISSUE TYPE

 - Feature request

#### SUMMARY

Right now an SSL vertificate for a VHost is only created for the domain that is auto-generated from the directory name and prefix from `.env`. It would be great if an SSL certificate is also generated for all ServerAlias entries that are made to the custom host configuration in a project (e.g. `.devilbox/apache24.yml`).

Alternatively, there should be a way to also configure for which domains the generated SSL certificate should be valid.

Use case: I develop inside of WordPress multisites that serve content for multiple domains. I need to replicate these domains inside of my dev environment with devilbox.

#### Goal

**User story:**
As a web developer, I want generated SSL certificates also to be valid for ServerAlias entries, so I do not have to manually approve the certificate when accessing a website using the alias name.

**Comment by tzimpel** [comment]
@cytopia where would I have to look to try and provide a patch myself, if that helps with progress?

**Comment by cytopia** [comment]
@tzimpel the SSL certificates are generated independently of the Apache/Nginx config. This is done by having [watcherd](https://github.com/devilbox/watcherd) check for directories, appending the `TLD_SUFFIX` env variable and then have [cert-gen](https://github.com/devilbox/cert-gen) generate those certificates.

So applying this to server aliases will be a whole different story as you would need to parse all existing vhost configurations (for Apache and Nginx), figure out the alias and then generate a certificate.

This would require to setup a completely new logic to the way vhosts are created.

Can you give an example of a vhost name and it's corresponding aliases?

**Comment by tzimpel** [comment]
@cytopia I understand the issue.

I deal with WordPress multisite setups that serve multiple domains. There's no rule or pattern to the aliases used. I use aliases to map the production domains to local ones so I can differentiate between the sites inside of the multisite that are accessed.

One example might be
* Directory: foo-website
* Aliases: foo.test, foo-com.test, foo-net.test, bar.test, baz.test
* Original (production) domains: foo.de, foo.com, foo.net, bar.de, baz.com

Another one might be like
* Directory: foo-website
* Aliases: foo.test, foo.bar.test, baz.foo.test, qux.foo.test
* Original (production) domains: foo.com, foo.bar.com, baz.foo.com, qux.foo.com

I have two possible workarounds:

1. Avoid using https for these setups locally
2. Manually mount the project directory multiple times to the containers using directory names that correspond to the domains

1 might be an option if there is no automated solution, 2 would bloat the containers, is more complex and involves a lot of manual work to set things up. And I don't know if this also has a negative impact on performance.

Can you suggest something else?

**Comment by cytopia** [comment]
> Can you suggest something else?

Another idea could be, if you use something like this:

* Directory: foo-website
* Aliases: de.foo-website, com.foo-website, net.foo-website, bar.foo-website

I could then go ahead and ensure that the certificates are wildcard, meaning any `*.foo-website` is going to be valid and you can simply add aliases

**Comment by wp4nuv** [comment]
I'm also interested in this option as I'm also developing for 3 subdomains sharing the same code.

**Comment by cytopia** [comment]
> I'm also interested in this option as I'm also developing for 3 subdomains sharing the same code.

@wp4nuv can you check my comment above. Currently the generated certificates are wildcards, so you could specifically choose the vhosts aliases as stated above and have valid certs available.

**Comment by timo002** [comment]
I'm running in this kind of issue myself to.

My project is in the directory `assets.domain.com` and my TLD_SUFFIX is `test`, so automatically it creates a certificate for `assets.domain.com.test`. So invalid certificate.

I added `assets.domain.test` to the `DEVILBOX_UI_SSL_CN` in `.env` so it looks like this:
```
DEVILBOX_UI_SSL_CN=localhost,*.localhost,devilbox,*.devilbox,httpd,assets.domain.test
```
But that doesn't work either.

So to sum up my setup:

```
HOST_PATH_HTTPD_DATADIR=/path/to/code
TLD_SUFFIX=test
```

In the dir `/path/to/code` I have multiple folders for different subdirectories, for example `assets.domain.com`, so the full path is `/path/to/code/assets.domain.com`

In that dir I have a `.devilbox` dir with a `apache24.yml` file with the setup of the VHOST. The only thing I changed in that default file is:
```
vhost: |
    <VirtualHost __DEFAULT_VHOST__:__PORT__>
        ServerName assets.domain.test
```

Would be awesome to get the cetificate working with `assets.domain.test`.

**Comment by cytopia** [comment]
> My project is in the directory `assets.domain.com` and my TLD_SUFFIX is `test`, so automatically it creates a certificate for `assets.domain.com.test`. So invalid certificate.

Why is this invalid? The certificate should work for `assets.domain.com.test`, which is your defined domain, no?

**Comment by timo002** [comment]
The domain I use is (in the browser) `assets.domain.test`. And that does not match wit `assets.domain.com.test`

**Comment by vikas5914** [comment]
> The domain I use is (in the browser) `assets.domain.test`. And that does not match with `assets.domain.com.test`

Then you should name your directory `assets.domain`.

**Comment by timo002** [comment]
> Then you should name your directory `assets.domain`.

That is not possible because this get's deployed on a production server this way. Oke, I can do so, but then I would need to modify  my production server where I would like to modify my dev stack. It is not a very big issue, but each time I restart devilbox, I now need to accept the invalid certificate.

**Comment by vikas5914** [comment]
> That is not possible because this get's deployed on a production server this way. Oke, I can do so, but then I would need to modify my production server where I would like to modify my dev stack. It is not a very big issue, but each time I restart the devil box, I now need to accept the invalid certificate.

There are two possible solutions here. 

1. Use only HTTP instead of HTTPS. 

2. Create another directory `assets.domain` and use a symbolic link to map htdocs to `assets.domain.test`  's htdocs folder. 

Note: The proper solution should change the deployed server that does not reply to the project directory name on your local one. I have multiple projects whose directory names are different in local vs prod and I use git and symbolic link to map the folder.

**Comment by timo002** [comment]
@vikas5914 Awesome, I used option 2 and that works fine. Still I think it would be nice if you can make a change / add something to the vhost file (apache24.yml)

**Comment by vikas5914** [comment]
> @vikas5914 Awesome, I used option 2 and that works fine. Still I think it would be nice if you can make a change / add something to the vhost file (apache24.yml)

As mentioned above in the comment, Making an SSL certificate based on the Apache/Nginx Config is a different story. I still believe that your production and Local should not depend on having the same name as the directory.  If you can provide some information maybe we can provide some solution on that.

**Comment by cytopia** [comment]
> That is not possible because this get's deployed on a production server this way. Oke, I can do so, but then I would need to modify my production server where I would like to modify my dev stack.

I see. I would recommend to generally fix your setup. Prod, dev, testing, etc, they should not rely on specific domains. If you get rid of this root problem, then you can name your dev stack whatever. It's probably worth investing some time into this.

**Comment by timo002** [comment]
@vikas5914 The symlink option is working, but now my IDE PHPStorm it also has double references to classes. I marked the symlink folders as exclude but they still show up. That might be on my setup.

My setup:
This is all from legacy where we came from shared hosting and the website was just running in a folder. Through the years we created subdomains and new folders where added. So, a lot is legacy on how we work. Recently we started moving to Symfony and we have one codebase for all (sub) domains. 

The folder structure:
```
\assets.domain.com\public => https://assets.domain.com
\image.domain.com\public => https://image.domain.com
\domain.com\public => https://www.domain.com
\symfony\public => https://backoffice.domain.com/ & https://api.domain.com
```

All these folders exist in the root of the hosting directory and I added the domain that points to the folder behind it.

With moving to Symfony and one codebase, we will move more domain to \symfony\public.
I hope it's clear, I'm open to criticism but whether I do anything with it, that's another story ;)
