### ISSUE TITLE
Xdebug with Ubuntu Docker

### ISSUE THREAD

**Issue by nguyenbo2001** [cytopia/devilbox#704]
Hello,

I wish you to resolve the problem!

I use ubuntu 18.04

Docker version 19.03
Docker compose version 1.17

PHP server version 7.3
![Screenshot from 2020-04-28 17-37-29](https://user-images.githubusercontent.com/14049903/80477943-f81cba80-8976-11ea-9da6-d6d2de878c19.png)

And config vscode and config xdebug in config/php-ini-7.3
![Screenshot from 2020-04-28 17-40-30](https://user-images.githubusercontent.com/14049903/80478243-72e5d580-8977-11ea-99c4-182be497daa8.png)

Information 
![Screenshot from 2020-04-28 17-41-30](https://user-images.githubusercontent.com/14049903/80478298-88f39600-8977-11ea-9f59-3ce3cf757739.png)
![Screenshot from 2020-04-28 17-42-51](https://user-images.githubusercontent.com/14049903/80478433-b8a29e00-8977-11ea-9152-8bb0935d6f30.png)
![Screenshot from 2020-04-28 17-42-30](https://user-images.githubusercontent.com/14049903/80478439-ba6c6180-8977-11ea-8f9b-583af325b573.png)

**Comment by llaville** [comment]
Hello @nguyenbo2001 
Can you tell us what is your problem ?

**Comment by nguyenbo2001** [comment]
Sorry. I setup Vscode to start debug but nothing happen. It not break with your point. Can you give us the solution!

**Comment by llaville** [comment]
To be sure, that its Vscode specific. Have you tried to use xdebug with another IDE platform ?

**Comment by merlijnvl** [comment]
@nguyenbo2001 In the debug launch config example [here](https://devilbox.readthedocs.io/en/latest/intermediate/configure-php-xdebug/linux/vscode.html#configure-php-xdebug-lin-vscode) `${workspaceFolder}` is used for the path mapping not workspace root.

I use `${workspaceFolder}` for my dev setup and it works as expected the only difference is that i use ubuntu 20.4.

**Comment by nguyenbo2001** [comment]
Hello,

I have setup Xdebug again. And it show the error unable to open file (it existed on the local)
![Screenshot from 2020-07-06 14-32-42](https://user-images.githubusercontent.com/14049903/86567616-d6067080-bf95-11ea-895e-a805f6d3411f.png)

**Comment by nguyenbo2001** [comment]
I have resolved the issue. Sorry
