### ISSUE TITLE
crontab in php Container - cron service not running by default

### ISSUE THREAD

**Issue by fkaminski** [cytopia/devilbox#705]
#### ISSUE TYPE

 - Question

#### SUMMARY

Hi, i am trying to test some simple cron jobs and using my local devilbox for testing purpose.
I was wondering why my jobs never be executed at all. It turned out:

When i enter the PHP Container with:
`docker-compose exec --user devilbox php bash -l;`

The cron service is not starting by default - Check with:
`service cron status`
("[FAIL] cron is not running ... failed!")

I have to start the service manually like
```
sudo service cron start
service cron status

```

#### Goal

Is there a way to start the service by default?
Thank you

**Comment by llaville** [comment]
@fkaminski did you tried the Autostart commands feature ( see documentation ) ?

**Comment by fkaminski** [comment]
@llaville 
Thank you will check that:
https://devilbox.readthedocs.io/en/latest/autostart/custom-scripts-globally.html?highlight=autostart

**Comment by fkaminski** [comment]
Thanks, 
works like a charm ...

**Comment by llaville** [comment]
glad to help
