### ISSUE TITLE
No Host DNS record found

### ISSUE THREAD

**Issue by dany-eudes** [cytopia/devilbox#71]
The Virtual Hosts  menu option lists all my projects with a ERR message:
```
No Host DNS record found. Add the following to /etc/hosts:
127.0.0.1 domain.loc
```
Because I'm running under Windows 10, my hosts file uses the default VirtualBox IP Address: 
```
192.168.99.100  domain.loc
```
However the project loads normally without any problems, only the host list of devilbox shows this error and with no apparent side effects.

**Comment by cytopia** [comment]
@dany-eudes Yes this is the problem with windows I have totally overlooked.

As there a quite a few different checks (backend+ajax) could you provide a screenshot also with the Browser inspector open, showing the `_ajax_callback.php` XHR request.

**Comment by mizunoer** [comment]
No Host DNS record found. Add the following to /etc/hosts: 127.0.0.1 onepage.loc
This worked before the update

**Comment by cytopia** [comment]
@mizunoer could you provide some more information: which docker container did you choose, which Windows version, which docker/docker-compose version.

Did you also compare `.env` with `env-example` to make sure it is up to date?

**Comment by cytopia** [comment]
Are you using [Docker Toolbox](https://docs.docker.com/toolbox/overview/) or [Docker for Windows](https://docs.docker.com/docker-for-windows/install/#download-docker-for-windows)

**Comment by cytopia** [comment]
@dany-eudes @mizunoer I made a major rewrite to overcome some limitations. I hope I could also address your problems. Pull request is not merged yet (https://github.com/cytopia/devilbox/pull/130), however could you checkout the branch (**REL-0.12**) and give it a try:

1. just to make sure everything is reset
```
docker-compose down
docker-compose rm -f
```
2. Check out new branch
```
git fetch --all
git checkout REL-0.12
```
3. Compare new `env-example` with your local `.env`
```
vimdiff .env env-example
```
4. Start it up
```
docker-compose up -d
```
Hope it can fix some problems

**Comment by broodje** [comment]
Greetings,
I stumbled upon this topic as I seem to have run into the same issue.
To provide some more information on the topic:
- i'm using Docker for Windows
- no hosts error occurs for both master branch and rel-0.12 branc
- I can see the correct DNS record through the ipconfig /displaydns command

I have attached a screenshot with some information as you've requested in previous replies if it might help :)
![output](https://user-images.githubusercontent.com/4773396/34423251-05a08b88-ec1b-11e7-9e09-84e72c636fad.png)

**Comment by cytopia** [comment]
@broodje looks like `status.json` cannot be loaded (left screen). Can you see the errors of it when u click on it?

**Comment by joberror** [comment]
I'm having that same status,json not loaded problem right now

**Comment by cytopia** [comment]
@joberror @broodje @mizunoer @dany-eudes 

Can you try the upcoming pull request and see if it works for your: https://github.com/cytopia/devilbox/pull/203

**Comment by cytopia** [comment]
## https://github.com/cytopia/devilbox/issues/248

I am already working on this problem. Please find all relevant information in the newly created issue: https://github.com/cytopia/devilbox/issues/248

To reach a broader audience I will close this ticket and link it to the new one (which will be done with multiple related issues as well).
