### ISSUE TITLE
/usr/local/bin/mysqldump-secure: 1937: return: Illegal number: 

### ISSUE THREAD

**Issue by dattapw** [cytopia/devilbox#710]
### ISSUE TYPE

 - Bug Report

### OS / ENVIRONMENT

1. Host operating system and version: MacOS Catalina 10.15.2
2. (Windows) Native Docker or Docker Toolbox: 
3. Docker version: Docker Desktop 2.3.0.2
4. Docker Compose version:  1.25.5
5. (Linux) Is SELinux enabled?:
6. What git commit hash are you on?:

### SUMMARY

Running mysqldump-secure gives error:

> mysqldump-secure -vv
[DEBUG] (CFG): Using config: /etc/mysqldump-secure.conf
[INFO]  (OPT): Logging enabled
[DEBUG] (OPT): Log level: 2
[DEBUG] (OPT): Log file: /var/log/mysqldump-secure.log
[TRACE] (CFG): Using temporary directory: /tmp
[DEBUG] (CFG): Destination dir: /shared/backups/mysql
[DEBUG] (CFG): Using file Prefix: 2020-06-24_10-49__
[INFO]  (OPT): MySQL SSL connection disabled
[TRACE] (CFG): mysqldump custom options: --opt --default-character-set=utf8 --events --triggers --routines --hex-blob --complete-insert --extended-insert --compress
[TRACE] (CFG): mysqldump '--quick':      Applied to DB's >= 200 MB
[TRACE] (CFG): mysqldump '--skip-quick': Applied to DB's  < 200 MB
[TRACE] (CFG): InnoDB-only:  Dumping consistently across tables (using '--single-transaction')
[TRACE] (CFG): InnoDB-none:  Dumping consistently across tables (using '--lock-tables')
[TRACE] (CFG): InnoDB-mixed: Dumping consistently across tables (using '--lock-tables')
[TRACE] (CFG): Ignored DB's: information_schema performance_schema
[TRACE] (CFG): Required DB's: mysql
[INFO]  (OPT): Compression enabled
[DEBUG] (OPT): Compression arguments: gzip -9 -c
[INFO]  (OPT): Encryption disabled
[INFO]  (OPT): Deletion disabled
[INFO]  (OPT): Nagios log disabled
[INFO]  (OPT): Info files enabled
[TRACE] (RUN): MySQL connection test successful.
[DEBUG] (SRV): MySQL server connection: mysql via TCP/IP
[DEBUG] (SRV): MySQL server connection: Not using SSL (plain).
[DEBUG] (SRV): MySQL server rep type:   master
[DEBUG] (SRV): MySQL server version:    MySQL 8.0.19 MySQL Community Server - GPL
[DEBUG] (SRV): MySQL server hostname:   mysql:3306
[TRACE] (RUN): Creating tmp dir:  /tmp/mysqldump-secure.xx6xdKaS4e
[DEBUG] (SQL): Retrieving list of databases...  5
/usr/local/bin/mysqldump-secure: 1937: return: Illegal number: 

#### Start command

```
$ docker-compose up...
```

#### File and user permissions (Linux & MacOS)

```
$ id
```

```
$ ls -la
```

```
$ ls -la data/www
```

**Comment by cytopia** [comment]
@dattapw thanks for reporting this issue. This has already been reported in its own repository here: https://github.com/cytopia/mysqldump-secure/issues/32 So I will close this one.
