### ISSUE TITLE
Makefile for docker-compose

### ISSUE THREAD

**Issue by llaville** [cytopia/devilbox#712]
#### ISSUE TYPE

 - Feature request

#### SUMMARY
A makefile to start, stop, compose your docker-compose stack 

#### Goal
Handle easily all containers without merging `compose/docker-compose.override.yml-*` templates to your own `docker-compose.override.yml`

You may either use standard extra containers found in devilbox `compose/` directory or your own scripts.
But you **MUST** follow naming rule :  prefix script to `docker-compose.override.yml-` if you want to use default devilbox compose scripts.

I think this feature was missing, so I've : 

- in first attempt, [suggested it](https://github.com/louisgab/devilbox-cli/issues/11) to include in https://github.com/louisgab/devilbox-cli project 
- in second attempt, build my [own project](https://github.com/llaville/devilbox-docker-compose-makefile) using a **Makefile** template

I don't really know, if I should open a feature request here or open a thread in forums. @cytopia tell me what do you prefer ?

All feedback are welcome !

**Comment by cytopia** [comment]
> in first attempt, suggested it to include in https://github.com/louisgab/devilbox-cli project

I would rather not include it in this project, as this would require to always keep it up-to-date. Besides it's a stand-alone project by itself. I'd fully agree for documentation though.

> in second attempt, build my own project using a Makefile template

This one I like, big fan of Makefiles myself. Also here I'd suggest to add this to the documentation and keep this as a stand-alone project.

> I don't really know, if I should open a feature request here or open a thread in forums. @cytopia tell me what do you prefer ?

I'd say let's make it a forum post.

**Comment by llaville** [comment]
> I'd say let's make it a forum post.

https://devilbox.discourse.group/t/makefile-to-compose-handle-your-devilbox-stack/397
