### ISSUE TITLE
Request gsfonts mupdf mupdf-tools

### ISSUE THREAD

**Issue by fsimchen** [cytopia/devilbox#713]
#### ISSUE TYPE

 - Feature request

#### SUMMARY

Requesting to add to the image gsfonts, mupdf and mupdf-tools.

#### Goal

Thanks!

**Comment by cytopia** [comment]
@fsimchen will be fixed here: https://github.com/cytopia/devilbox/pull/711

**Comment by cytopia** [comment]
Merged and available in `v1.7.1`
