### ISSUE TITLE
PHP 8.0:  Class MongoDB\Driver\Cursor must implement interface Traversable as part of either Iterator or IteratorAggregate

### ISSUE THREAD

**Issue by cytopia** [cytopia/devilbox#715]
#### ISSUE TYPE

 - Question

#### SUMMARY
When trying to compile [MongoDB](https://github.com/mongodb/mongo-php-driver) for PHP 8.0 it seems to work somehow. However, when then running PHP I get the following startup error:
```
PHP Fatal error:  Class MongoDB\Driver\Cursor must implement interface Traversable as part of either Iterator or IteratorAggregate in Unknown on line 0
```

Does anyone know how to fix this for PHP 8.0?

#### Goal
Re-enable `mongodb` extension for PHP 8.0 without errors.

#### Update

Upstream issue: https://github.com/mongodb/mongo-php-driver/issues/1161

**Comment by vulcangz** [comment]
Refer to this issue, maybe it is caused by adminer??
mongodb/mongo-php-driver#742

**Comment by cytopia** [comment]
@vulcangz thanks for the link. Unfortunately this is not it. It is only present in PHP 8.0 and during startup. For instance if I do a `php -v` on the command the fatal will already be thrown.

**Comment by cytopia** [comment]
Upstream issue is being tracked here: https://github.com/mongodb/mongo-php-driver/issues/1161

**Comment by cytopia** [comment]
https://github.com/cytopia/devilbox/pull/743
