### ISSUE TITLE
libvips

### ISSUE THREAD

**Issue by fsimchen** [cytopia/devilbox#716]
#### ISSUE TYPE

 - Feature request

#### SUMMARY

 - libvips (https://github.com/libvips/libvips)
- php-vips (https://github.com/libvips/php-vips)

#### Goal

A very fast image processing library with low memory needs.

libvips is a demand-driven, horizontally threaded image processing library. Compared to similar libraries, libvips runs quickly and uses little memory.

**Comment by cytopia** [comment]
@fsimchen currently baking here: https://github.com/devilbox/docker-php-fpm/pull/172

**Comment by cytopia** [comment]
https://github.com/cytopia/devilbox/pull/725 merged
