### ISSUE TITLE
How to enable Xdebug on WSL 2 backend

### ISSUE THREAD

**Issue by arkadywtf** [cytopia/devilbox#718]
#### ISSUE TYPE

 - Documentation

#### SUMMARY

As of recently WSL 2 is generally available in Windows 10 so here's how to enable Xdebug using WSL 2 backend.
If not for this [StackOverflow post](https://stackoverflow.com/a/62105184) I probably still would have been pulling hair from my head.

**Step 1**
Set an environment variable for your local WSL 2 IP in your `.bashrc` or `.zshrc` file.

```sh
export IP=$(hostname -I)
```

**Step 2**
Pass the environment variable to `extra_hosts` in `docker-compose.override.yml` file.

```yml
# vim: set ft=yaml:
---
version: "2.3"

services:
  # ------------------------------------------------------------
  # PHP
  # ------------------------------------------------------------
  php:
    extra_hosts:
      docker.for.wsl2.host.internal: ${IP}
```

**Step 3**
Create an `xdebug.ini` file

```ini
; Defaults
xdebug.default_enable=1
xdebug.remote_enable=1
xdebug.remote_port=9000

; The WSL 2 way
xdebug.remote_connect_back=0
xdebug.remote_host=docker.for.wsl2.host.internal

; idekey value is specific to Visual Studio Code
; xdebug.idekey=VSCODE

; Optional: Set to true to always auto-start xdebug
xdebug.remote_autostart=0
```

Using the steps above I managed to enable Xdebug using Docker on WSL 2.

#### Goal
The official documentation is great and helped me a lot with familiarizing with the project, but additional guides for WSL 2 would be a nice addition. Unless there's a better way to achieve what was described here.

**Comment by daxsis** [comment]
Is there a solution for the dynamic allocation of the wsl2 IP on the windows side? Because what you have wrote and the official documentation suppose you have to rebuild your images every time the IP changes, which it does on every restart, and this makes me sad :D

**Comment by massiws** [comment]
After struggling many hours, I found a simple alternative, a little different from what inside documentation.

Contrary to what specified in the [Gather Host IP address](https://devilbox.readthedocs.io/en/latest/intermediate/configure-php-xdebug/windows/vscode.html#gather-host-ip-address) section, _Docker for Windows_ seems to use the **WSL** IP address, not the **Default switch**. Here is an example:

![ip](https://user-images.githubusercontent.com/6533289/99509935-bab96200-2986-11eb-8d03-98784e628937.jpg)

Setting the correct IP address in the `xdebug.ini` file makes the job done:

```
xdebug.default_enable=1
xdebug.remote_enable=1
xdebug.remote_port=9000

; The Windows way
xdebug.remote_connect_back=0
xdebug.remote_host=192.168.32.1
xdebug.idekey=VSCODE
```

Hope this helps,
Max

**Comment by Dan0sz** [comment]
Just to add to this discussion: most (if not all) of the documentation when it comes to Xdebug is based on v2.x. In v3.x basically all of the configuration parameters have been changed or replaced.  I'm pretty sure that's what's keeping me from getting Xdebug to work properly on WSL2. 

I changed all of the parameters in my `xdebug.ini` file, but when I open up `phpinfo()` I still see a bunch of other parameters being set, accompanied by the notice: `This setting has been changed, see the upgrading guide at https://xdebug.org/docs/upgrade_guide#changed-"xdebug.auto_trace"`

Is there any way to force DevilBox to load Xdebug 2.x?

**Comment by janicak** [comment]
I was able to get Xdebug 3.0.1 to work with Devilbox on WSL2 following Steps 1-2 from https://github.com/cytopia/devilbox/issues/718#issue-679805333, but changing `xdebug.ini` to the version 3 settings as suggested at https://xdebug.org/docs/upgrade_guide.

```ini
; Defaults
xdebug.mode=debug
xdebug.start_with_request=yes
xdebug.client_port=9000

; The WSL2 way
xdebug.discover_client_host=0
xdebug.client_host=docker.for.wsl2.host.internal

; idekey value is specific to Visual Studio Code
xdebug.idekey=VSCODE
```

My ```launch.json``` in the VS Code workspace is:

```json
{
  "version": "0.2.0",
  "configurations": [
    {
      "name": "Listen for XDebug",
      "type": "php",
      "request": "launch",
      "port": 9000,
      "pathMappings": {
        "shared/httpd/my_project/htdocs": "${workspaceRoot}"
      }
    },
    {
      "name": "Launch currently open script",
      "type": "php",
      "request": "launch",
      "program": "${file}",
      "cwd": "${fileDirname}",
      "port": 9000
    }
  ]
}
```
The debugger (the VS Code plugin ```felixfbecker.php-debug```) does stop at the break points (as reflected in the variables and call stack panels), but can't open up the local files or highlight the break points, throwing up error notices like:

> "Unable to open 'functions.php': Unable to read file 'vscode-remote://wsl+ubuntu-20.04/shared/httpd/my_project/wordpress.git/wp-content/themes/my-theme/functions.php' (Error: Unable to resolve non-existing file 'vscode-remote://wsl+ubuntu-20.04/shared/httpd/my_project/wordpress.git/wp-content/themes/my-theme/functions.php')."

... which looks like VS Code is attempting to use Devilbox's file path on WSL2. Changing the ```pathMappings['shared/httpd/my_project/htdocs']``` to any other value will cause the VS Code debugger not to pick up on Xdebug, so I'm guessing that's correct.

So the debug experience is mostly functional, but annoying - any ideas as to what's going on here would be greatly appreciated.

**Comment by Dan0sz** [comment]
@janicak Wasn't ${workspaceRoot} deprecated in favor of ${workspaceFolder}? 

Btw. After updating to the latest image of Devilbox (which included XDebug 3 support) I managed to get XDebug working with WSL2 and VS Code by changing the port to something else. Here's my launch.json's configurations node:

```` 
    {
            "name": "XDebug",
            "type": "php",
            "request": "launch",
            "hostname": "0.0.0.0",
            "port": 9999,
            "pathMappings": {
                "/shared/httpd/dev/htdocs": "${workspaceFolder}/htdocs"
            },
            "log": false,
            "xdebugSettings": {
                "max_data": 65535,
                "show_hidden": 1,
                "max_children": 100,
                "max_depth": 5
            }
        },
````

I'm not getting any errors and it's fully functional.

**Comment by IlanVivanco** [comment]
Using @janicak Xdebug's 3 settings worked for me. But as mentioned by @Dan0sz I'm using `${workspaceFolder}` for my **launch.json** file.

Just for reference, I ended up with these:
- _~/.zshrc_
```sh
export IP=$(hostname -I)
```
- _~/devilbox/docker-compose.override.yml_
```yml
version: '2.3'

services:
  php:
    volumes:
      - ${PROJECTS_PATH}/my-plug:/shared/httpd/my-site/htdocs/wp-content/plugins/my-plug
    extra_hosts:
      docker.for.wsl2.host.internal: ${IP}

  httpd:
    volumes:
      - ${PROJECTS_PATH}/my-plug:/shared/httpd/my-site/htdocs/wp-content/plugins/my-plug
```

- _~/devilbox/cfg/php-ini-7.4/xdebug.ini_
```ini
; Defaults
xdebug.mode=debug
xdebug.start_with_request=yes
xdebug.client_port=9000

; The WSL2 way
xdebug.discover_client_host=0
xdebug.client_host=docker.for.wsl2.host.internal

; idekey value is specific to Visual Studio Code
xdebug.idekey=VSCODE

```

- _/home/ilan/code/my-plug/.vscode/launch.json_
```json
{
  "version": "0.2.0",
  "configurations": [
  {
    "name": "Listen for XDebug",
    "type": "php",
    "request": "launch",
    "port": 9000,
    "pathMappings": {
    "/shared/httpd/my-site/htdocs/wp-content/plugins/my-plug": "${workspaceFolder}"
    }
  },
  {
    "name": "Launch currently open script",
    "type": "php",
    "request": "launch",
    "program": "${file}",
    "cwd": "${fileDirname}",
    "port": 9000
  }
  ]
}
```

**Comment by plumrocket** [comment]
Another suggestion is to use [devilbox](https://devilbox.readthedocs.io/en/latest/) which is dockerized LAMP and MEAN stack for local development. You can install it on Ubuntu with docker and WSL2. Here is the [full tutorial](https://plumrocket.com/learn/devilbox-docker-wsl2) with installation instructions for WordPress and video as well - https://www.youtube.com/watch?v=9-vY5nLJC00

**Comment by llaville** [comment]
@plumrocket I'm 👍  with you on WSL2 guide in #604 issue, but not on this one 👎. No link with xdebug => that's a non sense here !
