### ISSUE TITLE
Add xlswriter extension to php image

### ISSUE THREAD

**Issue by taliptako** [cytopia/devilbox#721]
#### ISSUE TYPE

 - Feature request

#### SUMMARY
Would like to have [https://xlswriter-docs.viest.me/en/an-zhuang/pecl](https://xlswriter-docs.viest.me/en/an-zhuang/pecl ) this extension installed in php image it can be manually enabled.

#### Goal
Better extension support

**Comment by taliptako** [comment]
@cytopia if it's okay for you I can add this feature too ?

**Comment by cytopia** [comment]
@taliptako currently baking here: https://github.com/devilbox/docker-php-fpm/pull/172

**Comment by cytopia** [comment]
https://github.com/cytopia/devilbox/pull/725 merged
