### ISSUE TITLE
Browse / Tail logs via web interface?

### ISSUE THREAD

**Issue by frumbert** [cytopia/devilbox#722]
#### ISSUE TYPE

 - Feature request

#### SUMMARY

I'd like a log 'recent events' (particularly errors) section to appear on the devilbox index, or a live tool made available under the Tools menu that can render/tail the various logs in /var/log

#### Goal

I mostly need to be able to quickly check for recent php errors. Currently I have to ssh to the machine running devilbox, then enter the shell, then tail -f /var/log/php/php-fpm.error. A web interface would make that significantly easier.

**Comment by llaville** [comment]
Hello @frumbert. This feature is not new, and some ideas/alt solution, were given in report #597

**Comment by science695** [comment]
Another option is you can turn the logs into a host shared mount so you can access them.

I added this volume to the php container in the docker-compose.overrides.yml:

```
volumes:
- ${DEVILBOX_PATH}/log/php-fpm-${PHP_SERVER}:/var/log/php:rw${MOUNT_OPTIONS}
```

**Comment by llaville** [comment]
+1 to keep this feature on the roadmap

**Comment by llaville** [comment]
@frumbert and @cytopia Hello guys

As I've already said in feature #597 , both feature requests are pretty close.
I've worked on a solution that is up and running. I'll propose it on my repository https://github.com/llaville/flames today !

This solution is based on [vector](https://github.com/timberio/vector/).
