### ISSUE TITLE
no xdebug loaded when PHP 8

### ISSUE THREAD

**Issue by alikon** [cytopia/devilbox#724]
### ISSUE TYPE

 - Bug Report

### Checklist

* [ ] `.env` file is attached
* [ ] `docker-compose.override.yml` is attached (if it exists)
* [ ] Custom configs from `cfg/` dir are attached (if customized)
* [ ] `docker-compose logs` and `log/` output is added
* [x] I've looked through the docs: https://devilbox.readthedocs.io/en/latest/
* [x] I've looked through existing issues: https://github.com/cytopia/devilbox/issues
* [x] I've read troubleshooting: https://devilbox.readthedocs.io/en/latest/support/troubleshooting.html

### OS / ENVIRONMENT

1. Host operating system and version: Windows 10 PRO 10.0.18363
2. (Windows) Native Docker 
3. Docker version:  19,03.12
4. Docker Compose version: 1.26.2
5. (Linux) Is SELinux enabled?: no
6. What git commit hash are you on?: 1.7.1

### STEPS TO REPRODUCE
start with php 8

### EXPECTED BEHAVIOUR
xdebug loaded from php -m

### ACTUAL BEHAVIOUR
no xdebug on php 8  works fine on php 7.4

**Comment by cytopia** [comment]
@alikon currently `xdebug` is not building on the PHP 8 image (https://github.com/devilbox/docker-php-fpm), due to compile errors.
As soon as this is resolved, it will be added.

I will also convert this issue from bug report into a feature request.

**Comment by alikon** [comment]
thank you for the quick response
looking forward to see what happens next....

**Comment by cytopia** [comment]
@alikon will be available shortly: https://github.com/devilbox/docker-php-fpm/pull/171

**Comment by cytopia** [comment]
https://github.com/cytopia/devilbox/pull/725 merged
