### ISSUE TITLE
Phppgadmin - just shows warnings, nothing else

### ISSUE THREAD

**Issue by TheManFromEarth1** [cytopia/devilbox#728]
### ISSUE TYPE

 - Bug Report

### Checklist

* [X]
[env.txt](https://github.com/cytopia/devilbox/files/5251797/env.txt)

* [X] `.env` file is attached: 

* [ ] `docker-compose.override.yml` is attached (if it exists) -- Doesn't exist
* [ ] Custom configs from `cfg/` dir are attached (if customized)

* [X] `docker-compose logs` and `log/` output is added
https://gist.github.com/TheManFromEarth1/6b4e89d8919c22589409b48e2aa95b91

* [X] I've looked through the docs: https://devilbox.readthedocs.io/en/latest/
* [X] I've looked through existing issues: https://github.com/cytopia/devilbox/issues
* [X] I've read troubleshooting: https://devilbox.readthedocs.io/en/latest/support/troubleshooting.html

### OS / ENVIRONMENT

1. Host operating system and version: Kubuntu 20.04, Kernel 5.4.0-47-generic
2. (Windows) Native Docker or Docker Toolbox: 
3. Docker version:             19.03.13
4. Docker Compose version:  docker-compose version 1.26.2
5. (Linux) Is SELinux enabled?: Don't think so, fresh Kubuntu install
6. What git commit hash are you on?: Not sure, I updated devilbox today latest one (Devilbox Release v1.7.2)

### SUMMARY
Postgresql itself is working, because I can access the DB by IP from somewhere else.

PHPpgadmin just shows this: 
https://i.imgur.com/4nRlqnB.png

### STEPS TO REPRODUCE
Navigate to PHPpgadmin

### EXPECTED BEHAVIOUR
I see the PHPpgadmin interface

### ACTUAL BEHAVIOUR
https://i.imgur.com/4nRlqnB.png

#### Start command

```
$ docker-compose up...
docker-compose up php mysql httpd bind mailhog pgsql

#### File and user permissions (Linux & MacOS)
<!-- User and group information -->
```
$ id
```
uid=1000(jet) gid=1000(jet) groups=1000(jet),4(adm),24(cdrom),27(sudo),30(dip),46(plugdev),121(lpadmin),131(lxd),132(sambashare),134(libvirt),998(docker)


<!-- File permissions of the Devilbox directory -->
```
$ ls -la
```total 252
drwxrwxr-x 16 jet jet  4096 Sep 20 15:05 .
drwxrwxr-x 11 jet jet  4096 Sep 10 20:50 ..
drwxrwxr-x  2 jet jet  4096 Jul 25 13:08 autostart
drwxr-xr-x  3 jet jet  4096 Jul 25 14:11 backups
drwxrwxr-x  2 jet jet  4096 Sep 20 15:08 bash
drwxrwxr-x  2 jet jet  4096 Jul 25 14:28 ca
drwxrwxr-x 57 jet jet  4096 Jul 25 13:08 cfg
-rw-rw-r--  1 jet jet  9329 Sep 20 14:37 CHANGELOG.md
drwxrwxr-x  2 jet jet  4096 Sep 20 15:03 compose
-rw-rw-r--  1 jet jet  2770 Jul 25 13:08 CONTRIBUTING.md
drwxrwxr-x  3 jet jet  4096 Jul 25 13:08 data
drwxrwxr-x 11 jet jet  4096 Aug  4 02:04 .devilbox
-rw-rw-r--  1 jet jet   543 Jul 25 14:05 docker-compose.override.yml
-rw-rw-r--  1 jet jet   747 Jul 25 13:08 docker-compose.override.yml-example
-rw-rw-r--  1 jet jet 14999 Sep 20 14:37 docker-compose.yml
drwxrwxr-x 20 jet jet  4096 Sep 20 15:10 docs
-rw-rw-r--  1 jet jet  2502 Jul 25 13:08 .editorconfig
-rw-rw-r--  1 jet jet 18914 Jul 25 14:44 .env
-rw-rw-r--  1 jet jet 18914 Jul 25 13:08 env-example
drwxrwxr-x  9 jet jet  4096 Sep 20 15:54 .git
drwxrwxr-x  4 jet jet  4096 Jul 25 13:08 .github
-rw-rw-r--  1 jet jet  3643 Jul 25 13:08 .gitignore
-rw-rw-r--  1 jet jet  1064 Jul 25 13:08 LICENSE.md
drwxrwxr-x  6 jet jet  4096 Sep 13 16:51 log
drwxrwxr-x 10 jet jet  4096 Jul 25 14:47 mod
-rw-rw-r--  1 jet jet    27 Aug  4 02:11 package-lock.json
-rw-rw-r--  1 jet jet 65488 Sep 20 14:37 README.md
-rw-rw-r--  1 jet jet    86 Jul 25 13:08 shell.bat
-rwxrwxr-x  1 jet jet    59 Jul 25 13:08 shell.sh
drwxrwxr-x  5 jet jet  4096 Jul 25 13:08 .tests
-rw-rw-r--  1 jet jet 11506 Jul 25 13:08 .travis.yml
-rwxrwxr-x  1 jet jet  2265 Jul 25 13:08 update-docker.sh
-rw-rw-r--  1 jet jet  1857 Jul 25 13:08 UPDATING.md

<!-- File permissions of your projects -->
```
$ ls -la data/www
```

total 20
drwxr-xr-x 5 jet jet 4096 Sep 13 17:35 .
drwxrwxr-x 3 jet jet 4096 Jul 25 13:08 ..
drwxr-xr-x 3 jet jet 4096 Sep 13 17:36 data
-rw-rw-r-- 1 jet jet    0 Jul 25 13:08 .keepme
drwxrwxr-x 4 jet jet 4096 Aug  3 23:47 php
drwxrwxr-x 5 jet jet 4096 Aug  9 01:01 wp

**Comment by alikon** [comment]
i can confirm your findings with  php 7.4.10 and Devilbox Release v1.7.2

**Comment by alikon** [comment]
using phppgadmin 7.12.1  it works

**Comment by alikon** [comment]
unfortunately is not working when you try to login

**Comment by alikon** [comment]
for a dirty / temporary fix change
https://github.com/cytopia/devilbox/blob/master/.devilbox/www/htdocs/vendor/phppgadmin-7.12.0/libraries/lib.inc.php#L53-L57
with 
```php
	// Start session (if not auto-started)
	if (!ini_get('session.auto_start')) {
		if (session_id() == '') {
			session_name('PPA_ID');
			session_start();
		}
	}
```

**Comment by TheManFromEarth1** [comment]
Confirmed, thank you very much!

So simple solution, but if you don´t know where to look :)

**Comment by cytopia** [comment]
Thanks for reporting. I am trying to figure out why the integration tests did not catch this.

**Comment by cytopia** [comment]
https://github.com/cytopia/devilbox/pull/743
