### ISSUE TITLE
PHP ini settings

### ISSUE THREAD

**Issue by ilsenem** [cytopia/devilbox#73]
Is there any convenient way to edit `php.ini` settings?

**Comment by cytopia** [comment]
Yes. Inside the devilbox git directory go to `cfg/`. You will find config folders for each PHP version.
Simply put your `*.ini` file into the php version folder.

You can also check `cfg/php-fpm-5.6/` for an example.

Once you have created a config, restart the devilbox and check `http://localhost/info_php.php` if the changes are effective.

Let me know if this works.

**Comment by ilsenem** [comment]
Thanks, all worked well.

P.S. Thanks for the great tool!

**Comment by cytopia** [comment]
Good to hear. Thanks. I will have to update the documentation to also include this section.

**Comment by ilsenem** [comment]
Another one. Problem was with max upload size in first place to let me upload large dump to `MySQL` through `adminer`. `PHP` was the first gate and now `nginx` get in the way. Do i have to change configuration inside `.devilbox/etc/*` folder or there is an easy way?

**Comment by cytopia** [comment]
Please create separate tickets for different bugs:
https://github.com/cytopia/devilbox/issues/75
