### ISSUE TITLE
Postgresql with PostGIS extension

### ISSUE THREAD

**Issue by alikon** [cytopia/devilbox#730]
#### ISSUE TYPE

 - Feature request

#### SUMMARY

Having a postgresql  with PostGIS extension

#### Goal

Postgresql with PostGIS extension

**Comment by cytopia** [comment]
Will give it a try with those images: https://hub.docker.com/r/postgis/postgis

**Comment by yusufonur** [comment]
I want to create postgis extension but getting an error:

Steps:
```
    sudo add-apt-repository ppa:ubuntugis/ppa
    sudo apt install postgis
    sudo apt install postgresql-12-postgis-3
    sudo apt install postgresql-12-postgis-3-scripts
    sudo apt install postgresql-10-pgrouting
    cd devilbox/
    ./shell.sh
    psql -h 127.0.0.1 -p 5432 -U postgres -w
    CREATE EXTENSION postgis;
```
    

`ERROR:  could not open extension control file "/usr/share/postgresql/12/extension/postgis.control": No such file or directory`



I look /usr/share/postgresql/12/extension path and really postgis.control not exists

How can I do it ?

**Comment by Mewgood** [comment]
I am having an issue similar to this, however, the postgis.control file does indeed exist, but I still receive the error:
`ERROR:  could not open extension control file "/usr/share/postgresql/11/extension/postgis.control": No such file or directory`
