### ISSUE TITLE
Consider to upgrade Docker-Bind to latest version (0.17)

### ISSUE THREAD

**Issue by llaville** [cytopia/devilbox#731]
#### ISSUE TYPE

 - Feature request

#### SUMMARY

While working on Auto DNS feature to try to solve issue #604, I've found that : 
- the main `cytopia/bind` image used in `docker-compose.yml` still use an outdated version 0.15  ; see https://github.com/cytopia/devilbox/blob/v1.7.2/docker-compose.yml#L37

I've also noticed that feature that came with version 0.17, has no env variable defined in `env-example` file 
See https://github.com/cytopia/docker-bind#optional-environmental-variables
- `ALLOW_QUERY`
- `ALLOW_RECURSION`

#### Goal

- Raise `cytopia/bind` either to `0.17` or `latest` tag available on docker hub => https://hub.docker.com/r/cytopia/bind/tags

- Defines two new env variables in `env-example` under section 10. Bind Docker Settings

`BIND_ALLOW_QUERY`
`BIND_ALLOW_RECURSION`

And modify the `bind` service in `docker-compose.yml` => https://github.com/cytopia/devilbox/blob/v1.7.2/docker-compose.yml#L36

With version 0.15 I got this output with `docker-compose logs bind` command

```
bind_1   | [INFO] Debug level: 2
bind_1   | [INFO] BIND logging: disabled explicitly
bind_1   | [INFO] Using default DNS TTL time: 3600 sec
bind_1   | [INFO] Using default DNS Refresh time: 1200 sec
bind_1   | [INFO] Using default DNS Retry time: 180 sec
bind_1   | [INFO] Using default DNS Expiry time: 1209600 sec
bind_1   | [INFO] Using default DNS Max Cache time: 10800 sec
bind_1   | [INFO] Adding wildcard DNS: *.local -> 127.0.0.1
bind_1   |
bind_1   | zone local/IN: loaded serial 1601309650
bind_1   | OK
bind_1   | [INFO] Not adding any extra hosts
bind_1   | [INFO] DNSSEC Validation: no
bind_1   | [INFO] Adding custom DNS forwarder: 8.8.8.8,8.8.4.4
bind_1   | [INFO] Starting BIND 9.11.3
```

And with new version 0.17, I got this output 
 
```
bind_1   | [INFO] Debug level: 2
bind_1   | [INFO] BIND logging: disabled explicitly
bind_1   | [INFO] Using default DNS TTL time: 3600 sec
bind_1   | [INFO] Using default DNS Refresh time: 1200 sec
bind_1   | [INFO] Using default DNS Retry time: 180 sec
bind_1   | [INFO] Using default DNS Expiry time: 1209600 sec
bind_1   | [INFO] Using default DNS Max Cache time: 10800 sec
bind_1   | [INFO] Adding wildcard DNS: *.local -> 127.0.0.1
bind_1   |
bind_1   | zone local/IN: loaded serial 1601405542
bind_1   | OK
bind_1   | [INFO] Not adding any extra hosts
bind_1   | [INFO] $ALLOW_QUERY not set.
bind_1   | [INFO] DNS query rules will not be set
bind_1   | [INFO] $ALLOW_RECURSION not set.
bind_1   | [INFO] DNS recursion rules will not be set
bind_1   | [INFO] DNSSEC Validation: no
bind_1   | [INFO] Adding custom DNS forwarder: 8.8.8.8,8.8.4.4
bind_1   | [INFO] Starting BIND 9.11.5
```

**Comment by llaville** [comment]
Friendly ping @cytopia

**Comment by cytopia** [comment]
@llaville how does the new Bind versoin resolve #604?

**Comment by llaville** [comment]
@cytopia It does not solve #604. 
For WSL 2 and AutoDNS I've solved part of problem, but I got CORS issues when I visit vhosts intranet devilbox page. I'll keep continue to search but my answer will be publish on 604 bug report

**Comment by llaville** [comment]
My `docker-compose.overwrite.yml` contains at least 

```
version: '2.3'

services:

  bind:
    image: cytopia/bind:0.17
    environment:
      - ALLOW_QUERY=${BIND_ALLOW_QUERY:-any}
      - ALLOW_RECURSION=${BIND_ALLOW_RECURSION:-localnets,localhost}
```

**Comment by cytopia** [comment]
FYI: Currently working on a separation of the bind container and autodns (so that bind would not be required at all, but only if you want to have auto-dns). It's also related to this PR: https://github.com/cytopia/devilbox/pull/411
Will keep you posted.

**Comment by llaville** [comment]
Thanks a lot !
