### ISSUE TITLE
Intergation of new PHP composer v.2.0

### ISSUE THREAD

**Issue by fkaminski** [cytopia/devilbox#736]
#### ISSUE TYPE

 - Feature request

#### SUMMARY

Please integrate the new PHP Composer version:
see: https://blog.packagist.com/composer-2-0-is-now-available/

**Comment by hielh** [comment]
Hi
By using composer in devilbox i get an error, do you have an idea please or it attached to the version of composer 
![image](https://user-images.githubusercontent.com/909932/97409520-0899f780-18fe-11eb-8247-507ca86ec352.png)

**Comment by Calingcony** [comment]
@hielh Could you try to ping that address? or any other address for that matter?

And are you using composer v2? if not could you please make a separate issue for this problem?

**Comment by uphlewis** [comment]
A quick and easy solution for now (until the base devilbox images get updated) is to update to the latest version of composer in an autostart script.

Create the following [autostart file](https://devilbox.readthedocs.io/en/latest/autostart/custom-scripts-globally.html#where) `/path/to/Devilbox/autostart/update_composer.sh`:

```bash
#! /bin/bash

/usr/local/bin/composer self-update
```

After that, do the usual devilbox container rm -f and restart:

```bash
$ cd /path/to/Devilbox/
$ docker-compose stop && docker-compose rm -f && docker-compose up -d httpd php mysql && ./shell.sh
```

Then verify your composer version:

```bash
composer --version
```

![image](https://user-images.githubusercontent.com/43346009/97558486-18840b00-19d4-11eb-8930-08fd303305ca.png)

If it didnt work you may need to edit the composer update command in update_composer.sh to force version 2.x like so: `/usr/local/bin/composer self-update --2`

**Comment by cytopia** [comment]
https://github.com/cytopia/devilbox/pull/743
