### ISSUE TITLE
.vim and .vimrc

### ISSUE THREAD

**Issue by LubosRemplik** [cytopia/devilbox#737]
### ISSUE TYPE

 - Feature request

#### SUMMARY

Use host .vim and .vimrc same way as .ssh folder is used (HOST_PATH_SSH_DIR).

#### Goal

Since VIM is preinstalled in the php image it would be great if we can use vim configuration from our host. Especially useful for users who use VIM as IDE

**Comment by Tuurlijk** [comment]
You should use a docker-compose.override.yml for that. Inside you can target the machine you need your configs for and mount the directories and files you desire.

**Comment by tiktaz** [comment]
https://devilbox.readthedocs.io/en/latest/configuration-files/bashrc-sh.html#custom-vim-configuration
