### ISSUE TITLE
Need shell output for inotify from Windows users - please paste a few commands?

### ISSUE THREAD

**Issue by cytopia** [cytopia/devilbox#74]
@dany-eudes, @LeG3nDz, @valix85, @doku-san

I am rebuilding the Webservers to make them better work with windows. However, I will need a little help from you guys as I don't have a Windows machine here.

Help me how `inotify` currently behaves on Windows:
(https://github.com/docker/for-win/issues/56 | https://docs.docker.com/docker-for-windows/troubleshoot/#inotify-on-shared-drives-does-not-work)

**First step**
```shell
# Create and assign any temporary directory here (don't know the windows syntax)
# and store it in Variable MY_DIR
MY_DIR="PATH/TO/TMP"

# Run container with tmp dir mount from above
docker run -d --rm --name httpd-test -v ${MY_DIR}:/shared/httpd -t cytopia/apache-2.4

# Install and run inotify
docker exec -it httpd-test gosu root yum install -y inotify-tools
docker exec -it httpd-test gosu root inotifywait /shared/httpd
```
**Second step**
In a different Terminal window (on the docker Host - the windows machine), create a folder inside the `MY_DIR` and paste the output from the above inotifywait command.

If `inotifywait` stops and has output, everything should be alright, otherwise I will have to rethink.

**Comment by instantdelay** [comment]
PS F:\Projects\temphub> docker exec -it httpd-test gosu root inotifywait /shared/httpd
    Setting up watches.
    Watches established.

It didn't output anything or exit when I made the folder unfortunately

    PS F:\Projects\temphub> mkdir testing_folder
    
    
        Directory: F:\Projects\temphub
    
    
    Mode                LastWriteTime         Length Name
    ----                -------------         ------ ----
    d-----        7/17/2017  10:16 PM                testing_folder

**Comment by cytopia** [comment]
@instantdelay Thank you for the information. I hoped it will work :-/. Can you also let me know which Windows version you are running?

**Comment by instantdelay** [comment]
Windows 10 Pro 10.0.15063
