### ISSUE TITLE
Please update PHP 8.0 docker image to RC.3

### ISSUE THREAD

**Issue by dimitrismitsis** [cytopia/devilbox#740]
This is a kind request for refreshing the image of PHP 8.0 to use RC.3, same as the apt manager.

Thank you for this and for your great work!

**Comment by cytopia** [comment]
Will be using the PHP-8.0 branch (it will most likely always be ahead the releases until final 8.0 release): https://github.com/devilbox/docker-php-fpm-8.0/pull/10

**Comment by dimitrismitsis** [comment]
@cytopia thanks a lot! To be honest though, I'm not seeing a difference locally. First I ran `./update-docker.sh` and then I deleted my local containers & images and re-built them but I'm still getting the same build from `8.0.0-dev` from Oct 8.  

By the way, I think around the same time with your changes, the PHP-8.0 branch was merged into master of php-src.  

I would appreciate some info in case I'm doing something wrong so I close this Issue.

**Comment by alikon** [comment]
i've used this approach from https://devilbox.readthedocs.io/en/latest/maintenance/update-the-devilbox.html

to update all images, but only for the versions that are actually set in .env.

`host> docker-compose pull`


and now i have 

![image](https://user-images.githubusercontent.com/181681/98339681-64563600-200c-11eb-88ab-5fb4f724f684.png)

**Comment by cytopia** [comment]
> @cytopia thanks a lot! To be honest though, I'm not seeing a difference locally.

You won't at the moment. So all good on your side.

The changes will have to go through the following repositories in order to bevailable:

* [x] 1. https://github.com/devilbox/docker-php-fpm-8.0 (base image)
* [ ] 2. https://github.com/devilbox/docker-php-fpm (devilbox images)
* [ ] 3. https://github.com/cytopia/devilbox (devilbox)

So I'm currently working on step 2. Unfortunately all images have issues again due to some changes with nodejs.
So it might take 1-2 days more for it to be fixed.

**Comment by cytopia** [comment]
https://github.com/cytopia/devilbox/pull/743

**Comment by alikon** [comment]
Please update PHP 8.0 docker image to RC.4

**Comment by cytopia** [comment]
> Please update PHP 8.0 docker image to RC.4

I've set the CI to auto-update PHP 8.0 nightly to the latest commit in `PHP-8.0` branch. So you just need to docker pull once it has build:

* **PHP 8.0 Pipeline**: https://travis-ci.org/github/devilbox/docker-php-fpm-8.0/branches
* **Devilbox PHP Pipelines**: https://travis-ci.org/github/devilbox/docker-php-fpm/branches

Triggered the first pipeline manually as I forgot to add the nightly build before.
