### ISSUE TITLE
PhpMyAdmin cannot import sql file

### ISSUE THREAD

**Issue by wiedhodho** [cytopia/devilbox#744]
I tried to import sql file into my mariadb database using phpmyadmin 5.0.0 (devilbox: v1.7.2 (2020-09-17))
But always failed, and phpmyadmin give a note: Could not load the progress of the import.

I check on console, the system cannot access 
Request URL: http://localhost/vendor/phpmyadmin-5.0.0/import.php
Request Method: POST
Status Code: 502 Bad Gateway

### ISSUE TYPE

 - Bug Report

**Comment by cytopia** [comment]
@wiedhodho can you update to `v1.8.0` (latest release), which also has a newer phpMyAdmin version.
If you issue continues, please provide reproducible steps for this issue.

**Comment by wiedhodho** [comment]
I have upgrade to the latest release, but the problem is still same

**Comment by Calingcony** [comment]
@wiedhodho 99% of the time this happens is because of a problem with the file you are trying to import. Its either to large, has to many queries or different versions.

Could you try to export and import something really simple? A single table DB with like a couple of entries.

**Comment by wiedhodho** [comment]
my sql file is only 3kb, I dump it using phpmyadmin in another my devilbox.
I tried it using adminer in devilbox and it succeed. But not using phpmyadmin.

**Comment by Sandy-Garrido** [comment]
I'm having this same issue!! Really strange. Checked my php upload sizes and thats fine.

**Comment by jameswadsworth** [comment]
I have had the same issue with phpMyAdmin when importing databases.  I use the php shell to import any databases:

[https://devilbox.readthedocs.io/en/latest/maintenance/backup-and-restore-mysql.html#restore](url)

**Comment by cytopia** [comment]
I've tried to reproduce this, but it always succeeded with phpMyAdmin (~ 1 MB SQL dump).
Could somepne provide a sanitized/anonymized dump which fails including what PHP, HTTPD and MySQL version.

**Comment by wiedhodho** [comment]
Here i attach error image, phpversion, and sql files

I tri using import button and click GO! => Error
But if I try with drag n drog, It succeed. :D

[whatsapp.zip](https://github.com/cytopia/devilbox/files/5541711/whatsapp.zip)

![image](https://user-images.githubusercontent.com/26288665/99160938-bd6a4c00-2727-11eb-91ad-30293b3d5cc8.png)
![image](https://user-images.githubusercontent.com/26288665/99160945-cce99500-2727-11eb-95dd-732ccadc36b5.png)

**Comment by cytopia** [comment]
@wiedhodho @Sandy-Garrido @jameswadsworth I was able to reprocude it.

After some debugging I found out that this is an issue with `uploadprogress`.
You can disable it for now by appending `uploadprogress` to the disabled modules via `.env` file settings:

```bash
PHP_MODULES_DISABLE=oci8,PDO_OCI,pdo_sqlsrv,sqlsrv,rdkafka,swoole,uploadprogress
```

I will have to investigate further.
