### ISSUE TITLE
Support OpenLitespeed 

### ISSUE THREAD

**Issue by codingHippo** [cytopia/devilbox#745]
Hi, one of my hosting providers are not using openlitespeed.  It woud be super to have that as one of the options

#### ISSUE TYPE

 - Feature request

**Comment by cytopia** [comment]
@codingHippo can you update the Feature request with Summary and Goal to make clear what is meant by "support OpenListespeed" and what would be required to have it supported.

**Comment by cytopia** [comment]
Closing as it is not clear what exactly is requested with this feature request.
