### ISSUE TITLE
Add LiteSpeed web server

### ISSUE THREAD

**Issue by codingHippo** [cytopia/devilbox#748]
#### ISSUE TYPE

 - Feature request

#### SUMMARY

I love how I can easily configure and test different environments with DevilBox

Currently it supports Apache and Nginx as the web servers, which probably covers 99% of all configurations.

Lately I have noticed a growing interest in and usage of lite LiteSpeed web server.
It comes in two flavours. 
One is open source: https://openlitespeed.org/
and other one is commercial.

Allegedly it is faster than Apache and Nginx for WordPress
Especially when combined with the matching Litespeed WordPress plug in (cache)
Several (but few) host providers are already using it.

It is supposed to be a drop-in replacement for Apache, using the same configuration files.
They provide a docker image:
https://blog.litespeedtech.com/2020/03/16/litespeed-offers-docker-solutions/
https://hub.docker.com/r/litespeedtech/openlitespeed

#### Goal

I would like this feature so I could easily set up a configuration that uses it for testing and education.
Since I will soon be deploying a couple of sites to a hosting provider that uses it, it would make 
it easy to replicate the "production" environment.

I would also like to develop a better understanding about how WordPress changes using the
dedicated plug-in

**Comment by Sandy-Garrido** [comment]
Thanks @codingHippo for requesting this feature.
Consider this comment an upvote for this as I came here today for this exact reason.

Personally, all of our sites (wordpress) are using OLS and yes, I agree there is a rapid growth in OLS as an option.

**Comment by cytopia** [comment]
> I would like this feature

Still not sure what feature you actually mean though.
Or differently asked: what is currently lacking, that would be added with litespeed?

---

Besides this, I was already looking into litespeed and If I'm not mistaken (or at least I didn't find any information about this) it does not work together with php-fpm, which in case of the Devilbox is the part providing the different PHP versions. Not sure how that could be implemented though.

Regardless, I'd really like to hear about some features that are currently lacking to be able to see that against required effort.

**Comment by codingHippo** [comment]
Hi, 

We already have a great choice between Apache and Ngnix.- 
They by far are the most popular web server being used now for PHP .

This allows users to test configurations and get the best setup to (to some degree)
"replicate production".

Given the claimed advantages of OLS for WordPress including their caching plugin, I think a lot more people will switch to OLS over the next couple of years.

Yes from what I have read OLS uses LSPHP, which allegedly provided better performance than php-fpm
There are some indications that it is possible to set it up with php-fpm but it seems unwise.

If php-fpm is a dependence then it will probably not work

**Comment by cytopia** [comment]
Ist it possible to have LSPHP run on a different machine than litespeed web server?

**Comment by Dan0sz** [comment]
I'm a WordPress plugin developer, and today I ran into an issue, my plugin was having with LiteSpeed Cache; a caching plugin for WordPress. This plugin won't run, unless you have a LiteSpeed webserver. 

I already use DevilBox for all my development tasks. That's why it'd be awesome if LiteSpeed could be included in the package as well!

**Comment by cytopia** [comment]
This is not going to work for the Devilbox.

The Devilbox architecture uses separate containers for web servers and PHP servers (PHP-FPM) in order to achieve selecting different PHP versions. Litespeed does not work with PHP-FPM (https://support.cpanel.net/hc/en-us/articles/1500012848102-Can-I-use-PHP-FPM-with-LiteSpeed-) and thus cannot be integrated into this project
