### ISSUE TITLE
Xdebug cannot be disable In some versions of php

### ISSUE THREAD

**Issue by jonatanaxe** [cytopia/devilbox#749]
### ISSUE TYPE

 - Bug Report

### SUMMARY

Devilbox v1.8.1 (2020-11-12)

xdebug is not disable even by placing in DISABLE_MODULES and PHP_MODULES_DISABLE

it disables in php7.1
Does not disable in PHP 7.2 and 7.3

![image](https://user-images.githubusercontent.com/2486808/99022541-b1bd3080-2541-11eb-9d9f-95094bab6c7c.png)
![image](https://user-images.githubusercontent.com/2486808/99022377-5d19b580-2541-11eb-8ccd-c7daec055a31.png)
![image](https://user-images.githubusercontent.com/2486808/99022412-702c8580-2541-11eb-83b4-b1960a7cbd24.png)

Thank you 😊

**Comment by llaville** [comment]
Confirmed with PHP 7.4 too !

**Comment by cytopia** [comment]
Confirmed

**Comment by llaville** [comment]
Release 0.116 fixed this issue : I've only test it with new PHP 7.4 image

**Comment by jonatanaxe** [comment]
Release 0.116 Tested on PHP 7.1 and 7.2 is working

**Comment by cytopia** [comment]
Fixed here: https://github.com/cytopia/devilbox/pull/750
