### ISSUE TITLE
Add '${HOME}/.composer/vendor/bin' to the $PATH environment variable in .bashrc

### ISSUE THREAD

**Issue by vlad4ernyshov** [cytopia/devilbox#755]
Is it possible to add '${HOME}/.composer/vendor/bin' to the $PATH environment variable in .bashrc by default?

This will make globally available commands set by a requests like this:
`php composer global require friendsofphp/php-cs-fixer`

Now I solve this with a command in autorun:
`su -c 'echo "PATH=${PATH}:${HOME}/.composer/vendor/bin" >> ~/.bashrc' -l devilbox`

[https://getcomposer.org/doc/03-cli.md#global](https://getcomposer.org/doc/03-cli.md#global)

#### ISSUE TYPE

 - Feature request

**Comment by cytopia** [comment]
@vlad4ernyshov good catch. Will add this here: https://github.com/devilbox/docker-php-fpm/pull/181

**Comment by cytopia** [comment]
Fix released here: https://github.com/cytopia/devilbox/pull/757
