### ISSUE TITLE
Add Silverstripe Install Guide

### ISSUE THREAD

**Issue by ozmos** [cytopia/devilbox#756]
#### ISSUE TYPE

 - Feature request

#### SUMMARY
I would like to see a guide for installing Silverstripe CMS in devilbox.

#### Goal

I want a local dev environment on Linux Mint for SilverStripe projects.  The majority of their docs assume you are using Windows or Mac.

**Comment by cytopia** [comment]
I'm happy to review a PR if this is really needed. Otherwise CMS/Frameworks can simply be installed according to their documentation. There is really no difference on the Devilbox (just think of it as a server where you'd install that)

**Comment by ozmos** [comment]
Thanks @cytopia. I've got a better handle on the devilbox environment now so should be fine. Thanks for building and maintaining such a convenient and well documented lamp dev environment.
