### ISSUE TITLE
docker-compose.override.yml-varnish doesn't implement the VARNISH_CONFIG ENV

### ISSUE THREAD

**Issue by msyhr** [cytopia/devilbox#761]
### ISSUE TYPE

 - Bug Report

Varnish will always use /etc/varnish/default.vcl

https://devilbox.readthedocs.io/en/latest/custom-container/enable-varnish.html#stack-env-variables

https://github.com/cytopia/devilbox/blob/master/compose/docker-compose.override.yml-varnish

**Comment by cytopia** [comment]
@msyhr FYI: It's now available in the `v1.9.0` release
