### ISSUE TITLE
Can't update laravel/install past 3.2.0

### ISSUE THREAD

**Issue by Deca** [cytopia/devilbox#762]
I'm unable to install latest laravel version because I can't update laravel/install past 3.2.0 
I've tried to remove and reinstall globally with
```
composer global remove laravel/installer 
composer global require laravel/installer
```
but issuing a --version I still get the 3.2.0

I'm running Devilbox v1.7.1 but supposing laravel/install as a PHP container tool I tried to update only the container I'm actually using with` docker pull devilbox/php-fpm:7.3-work` without luck.

in /home/devilbox/.composer/composer.json I see the latest laravel/install version that should be available (4.1) but at this point I don't know where is the issue

**Comment by vikas5914** [comment]
The laravel/installer is installed while the Docker image is being built. I think you need to update the Devilbox and as well as the update the docker image version for the PHP. 

check this: 
![image](https://user-images.githubusercontent.com/7912297/101532919-340f0800-39bb-11eb-8001-ea64f7c696e7.png)


Also meantime you can use `composer create-project laravel/laravel example-app` command to create laravel project with the latest version.
