### ISSUE TITLE
Magento Only Support Composer Version 1

### ISSUE THREAD

**Issue by ksaltik** [cytopia/devilbox#767]
#### ISSUE TYPE

 - Question
Magento Only Support Composer Version 1. How can I use composer 1 instead composer 2

#### SUMMARY

Magento Only Support Composer Version 1. How can I use composer 1 instead composer 2

#### Goal

So I can install magento

**Comment by llaville** [comment]
Default version is Composer V2 but you can still used Composer V1 by invoking command `/usr/local/bin/composer-1`
