### ISSUE TITLE
Magento 2.4.x only supports Elastic Search 7.6.x and above

### ISSUE THREAD

**Issue by ksaltik** [cytopia/devilbox#768]
#### ISSUE TYPE

 - Question
Magento 2.4.x only supports Elastic Search 7.6.x and above

#### SUMMARY

Magento 2.4.x only supports Elastic Search 7.6.x and above how can I add the version to devilbox

#### Goal

I try to install magento 2.4.x on devilbox

**Comment by cytopia** [comment]
You can set the ElasticSearch version as described here in the documentation: https://devilbox.readthedocs.io/en/latest/custom-container/enable-elk-stack.html#id1
