### ISSUE TITLE
Xdebug v3 info panel

### ISSUE THREAD

**Issue by llaville** [cytopia/devilbox#770]
#### ISSUE TYPE

 - Feature request

#### SUMMARY

Show diagnostic information analogous to PHP's phpinfo() function

#### Goal

Add a new entry in `info` devilbox menu to display the diagnostic panel available in v3 (see https://xdebug.org/docs/profiler#xdebug_info)

Here is a preview 

![localhost_info_xdebug_php](https://user-images.githubusercontent.com/364342/102611043-80321900-412e-11eb-8bad-318736324161.png)

**Comment by alikon** [comment]
see #771

**Comment by llaville** [comment]
I'd though to an menu integration like https://github.com/cytopia/devilbox/blob/master/.devilbox/www/htdocs/info_php.php
BTW thanks for your contrib @alikon

**Comment by alikon** [comment]
ah ok  give me 5 min

**Comment by alikon** [comment]
moved under Info Menu

**Comment by llaville** [comment]
I'll give you my feedback on your PR.
I also want @cytopia point of view, because he his the leader of project.
