### ISSUE TITLE
Split intranet from main project

### ISSUE THREAD

**Issue by llaville** [cytopia/devilbox#772]
#### ISSUE TYPE

 - Feature request

#### SUMMARY

Split '.devilbox' folder into a separate project.

#### Goal

Make it possible to replace default devilbox intranet by a new custom copy.

CI checks has no sense with intranet. Running almost 200 checks for nothing.

I've already begun to work on my own copy of a customizable intranet few month ago.

Easy to replace, because we have just to mount a volume.
https://github.com/cytopia/devilbox/blob/master/docker-compose.yml#L174

@cytopia What do you think about this idea ?

**Comment by cytopia** [comment]
There has already been put a lot of work into moving towards this direction.

* **Step 1** involves separating Frontend and Backend calls. The separated frontend has already been implemented by @hurrtz here: https://github.com/devilbox/web-ui/tree/develop
* **Step 2** would involve me creating the corresponding API's (within the Devilbox project)
* **Step 3** would then be to think about how to move forward with keeping it in this repository or splitting it up.

For **Step 3** I still have to think a bit more as I want to ensure that everything works out of the box without a new user having to do too many installation steps. One option would be to ship a default interface, but still be able to replace it with custom ones.

Another pro for your suggestoin would be, that the interface can be developed independently of this project.

**Comment by llaville** [comment]
> **Step 1**

Until now I didn't noticed that there is a WebUI planning (under development). I'll have a look on it !

> **Step 2**

If I can help, count on me !

**Comment by cytopia** [comment]
> Until now I didn't noticed that there is a WebUI planning (under development). I'll have a look on it !

It is hidden in the `develop` branch ;-)
