### ISSUE TITLE
CI - Docs linkcheck2 failure

### ISSUE THREAD

**Issue by llaville** [cytopia/devilbox#773]
### ISSUE TYPE

 - Bug Report

### SUMMARY

Github Actions - CI - Docs linkcheck2 failed because linuxbrew has migrated. See https://github.com/Linuxbrew/brew
Use Homebrew instead !

If you want to fix issue such as ```[FAIL] https://linuxbrew.sh curl: (6) Could not resolve host: linuxbrew.sh``` line 299 in https://github.com/cytopia/devilbox/runs/1577795684?check_suite_focus=true#logs

**Comment by llaville** [comment]
Perharps time to migrate tools in devilbox too !
See https://github.com/cytopia/devilbox/blame/master/README.md#L633-L636

**Comment by llaville** [comment]
@cytopia are you agree to migrate to homebrew for release #777.
This will fix also this issue and all CI checks will then be successful ?

**Comment by BoGnY** [comment]
:+1:

**Comment by llaville** [comment]
Commit https://github.com/llaville/docker-php-fpm/commit/ce618d91827e3c08c1ea1bd43e18c6bf995be67e provides migration
