### ISSUE TITLE
DNS setup in Windows using Docker and WSL 2

### ISSUE THREAD

**Issue by wp4nuv** [cytopia/devilbox#774]
#### ISSUE TYPE

 - Documentation

#### SUMMARY
Documentation steps to make DNS updates in Windows doesn't take into consideration whether you are using WSL 2. Steps are different if using that Docker solution. 

#### Goal
Update documentation to state the following:
When using Docker with WSL2 support, the DNS entries that are required in Windows must be placed in the Hyper-V virtual adapter related to the WSL 2 instance. Otherwise automatic DNS detection will not work.

**Comment by andrecalistro** [comment]
@wp4nuv could you show how to configure the hyper-v?

**Comment by wp4nuv** [comment]
The procedure is the same as stated in the Devilbox dns for Windows, except that instead of using the machine network controller you make the changes in the ```vEthernet (WSL)``` one.

**Comment by nhanledev** [comment]
I had to put the ip of the WSL2 instance using `ip a | grep eth0` to the Preferred DNS Server field to make it work. `127.0.0.1` does not work on my side.
