### ISSUE TITLE
XDebug error

### ISSUE THREAD

**Issue by ilsenem** [cytopia/devilbox#78]
When trying to setup remote debugging i receive this error in `xdebug.log`:

```
Log opened at 2017-06-07 07:57:26
I: Connecting to configured address/port: 192.168.0.215:9000.
W: Creating socket for '192.168.0.215:9000', poll success, but error: Operation now in progress (29).
E: Could not connect to client. :-(
Log closed at 2017-06-07 07:57:26
```

Is there any relation with Devilbox itself?

For now, i use PHPStorm and internal IDE validation is working fine, but no remote debugging is happening.

**Comment by cytopia** [comment]
I will try to reproduce this. Can you let me know a bit more about your setup:

* Windows, Linux or OSX
* In Case of Windows: Are you using [Docker Toolbox](https://docs.docker.com/toolbox/overview/) or [Docker for Windows](https://docs.docker.com/docker-for-windows/install/#download-docker-for-windows)
* Docker and Docker-compose versions
* XDEBUG setup in `.env`

**Comment by ilsenem** [comment]
* Ubuntu 16.04
* Docker 17.03.1-ce
* Docker-compose 1.13.0

`.env`
```ini
PHP_SERVER=php-fpm-7.1

#############

PHP_XDEBUG_ENABLE=1
PHP_XDEBUG_REMOTE_PORT=9000
PHP_XDEBUG_REMOTE_HOST=192.168.0.215
```

PHPStorm configured through Docker `php` executable, with server mapped properly on container folders.

**Comment by ilsenem** [comment]
That was entirely my mistake. Have not read the comment above `PHP_XDEBUG_REMOTE_HOST` parameter. I forget to change IP to my host address, so `xdebug` was unable to connect. Sorry.

**Comment by cytopia** [comment]
Good to hear. I will have to add this to the FAQ section.

**Comment by lbngoc** [comment]
How can I setup VS Code with Xdebug?
I think Xdebug was started but VS Code cannot "listen" it.
Here is my xdebug.log
```
Log opened at 2017-11-16 17:07:24
I: Connecting to configured address/port: 192.168.0.104:9000.
E: Time-out connecting to client. :-(
Log closed at 2017-11-16 17:07:24
```
PHP Debug for VS Code: https://marketplace.visualstudio.com/items?itemName=felixfbecker.php-debug

Thanks a lot!

**Comment by cytopia** [comment]
@lbngoc Unfortunately I have never used VS Code, so I will not be able to help you on the client side.

On the devilbox side however, you should simply apply those settings:
```
PHP_XDEBUG_ENABLE=1
PHP_XDEBUG_REMOTE_PORT=9000
PHP_XDEBUG_REMOTE_HOST=192.168.0.215
```
Change `192.168.0.215` to whatever IP address you local computer (where VC Code runs on) is using.

**Comment by lbngoc** [comment]
@cytopia 
Can we expose port 9000 to localhost of local computer?
I see that my local IP changed every I power on my laptop.
@ilsenem 
Could you please share your debug config with PHPStorm ?

**Comment by ilsenem** [comment]
@lbngoc There is no config, really. I just replace default IP provided in **devilbox** configuration with my machine IP and all worked. The only thing i changed is path mappings, but **PhpStorm** will ask for it on first debug session.

**Comment by lbngoc** [comment]
@ilsenem Thanks you. I also think my issue maybe come from the path mapping, I will find another way.

**Comment by Cipa** [comment]
@lbngoc did you find a solution. I have the same issue
Log opened at 2017-12-14 06:21:58
I: Connecting to configured address/port: 192.168.0.215:9000.
E: Time-out connecting to client. :-(
Log closed at 2017-12-14 06:21:58

PHP_XDEBUG_REMOTE_HOST=192.168.0.215

If it needs to be different what would the ip be, the ip on the local network 10.0.1.XX?

Thank you

**Comment by mwmllr** [comment]
I see a similar problem. I used 

`ip route get 8.8.8.8 | awk '{print $NF; exit}'`

and put this in `.env` at `PHP_XDEBUG_REMOTE_HOST`

The xdebug log says

> I: Connecting to configured address/port: 192.168.1.170:10000.
W: Creating socket for '192.168.1.170:10000', poll success, but error: Operation now in progress (29).
E: Could not connect to client. :-(

(p.s. I changed 

`PHP_XDEBUG_REMOTE_PORT=10000`

as well as in my IDE)

and according to PHPStorm 'Validate Debugger Configuation on Web Server' all the config settings are good to go.

**Comment by mwmllr** [comment]
Ok I got this working thanks to some posts, like [1](https://stackoverflow.com/a/41446385), [2](https://stackoverflow.com/a/44284500), and [3](https://github.com/laradock/laradock/issues/460#issuecomment-279271592).

set 

`PHP_XDEBUG_REMOTE_CONNECT_BACK = 0`

I could then connect with xdebug but there were problems with my path mappings. PHPStorm makes it simple to apply path mappings to the devilbox htdocs folder and debugging works like normal.

**Comment by cytopia** [comment]
Generalized Xdebug documentation now available: https://devilbox.readthedocs.io/en/latest/intermediate/configure-php-xdebug.html
