### ISSUE TITLE
Add Shopware CLI tools please

### ISSUE THREAD

**Issue by anatol06** [cytopia/devilbox#786]
#### ISSUE TYPE

 - Feature request

#### SUMMARY

Generating plugins with the CLI tools for Shopware would help me a lot

#### Goal

I Would like to have the possibility of using CLI Tools for generating plugins etc. in Shopware
Please get the information [here](https://developers.shopware.com/blog/2015/09/01/generating-plugins-with-the-cli-tools/)

**Comment by jonatanaxe** [comment]
Does it work like the n98-magerun? I install from autostart
https://github.com/jonatanaxe/DevEnvDevilbox/blob/main/devilbox/autostart/autostart.sh
