### ISSUE TITLE
Mysql socket set up to use in Php

### ISSUE THREAD

**Issue by eortega** [cytopia/devilbox#79]
Hi;

I'm having a trouble with mysql/php; mysql socket is created inside mysql container in this path _/tmp/mysql/mysqld.sock_ but this is out of the scope of the php container. How is possible to share mysql socket between both mysql and php containers ?

In the php container mysql socket is expected in _/var/lib/mysql/mysql.sock_

I think that I'm missing some configuration or maybe a environment variable when I execute docker-compose up.

Thanks in advance.

**Comment by eortega** [comment]
I found a workaround using volumes, now php could use socket generated by mysql but I had to modify docker-compose.yml.

**Comment by cytopia** [comment]
@eortega I have removed socket mounts and configuration via docker volumes as it did not work properly on windows. The recommended way for database connections is to use `127.0.0.1`. This will be available on the Docker host as well as inside the PHP container (syncronized).
