### ISSUE TITLE
Adding ext-mailparse php extension 

### ISSUE THREAD

**Issue by 24js** [cytopia/devilbox#793]
#### ISSUE TYPE

 - Feature request

#### SUMMARY

Adding **ext-mailparse** to list of extensions for PHP container

#### Goal

`ext-mailparse` is a really useful extension, if you want to use for example `php-mime-mail-parser` it requires `ext-mailparse`, and it's inside so many projects you can check the stats just from [packagist.org](https://packagist.org/packages/php-mime-mail-parser/php-mime-mail-parser) it has 1 478 955 installs

**Comment by llaville** [comment]
Adding new extension is related to PHP container. That's means its for https://github.com/devilbox/docker-php-fpm project !

Easy to include. I'm currently integrate it in my fork https://github.com/llaville/docker-php-fpm/tree/software_enabled_refactoring
Will be soon available.

- Version 2.1.6 (latest of branch 2) is for PHP versions 5.2 to 5.6
- Version 3.x is for PHP versions 7.x to 8.0

**Comment by llaville** [comment]
FYI: the https://github.com/mlocati/docker-php-extension-installer project already support this extension.
See my new report https://github.com/devilbox/docker-php-fpm/issues/215

On the other side, I don't understand point of view of community that ask for new extension and didn't send their feedback when helper offer to contribute

**Comment by 24js** [comment]
I had a problem updating to the latest version since I had so many custom extensions
Finally managed to update <3

**Comment by llaville** [comment]
☺️
