### ISSUE TITLE
Cannot start service bind

### ISSUE THREAD

**Issue by krebbi** [cytopia/devilbox#795]
### ISSUE TYPE

 - Bug Report

### Checklist

* [ x] `.env` file is attached
* [ x] `./check-config.sh` output is added below
* [ ] `docker-compose logs` output is added below
* [ ] `docker-compose.override.yml` is attached (if exists)
* [ ] Custom configs from `cfg/` dir are attached (if exist)
* [ ] I've looked through the docs: https://devilbox.readthedocs.io/en/latest/
* [ ] I've looked through existing issues: https://github.com/cytopia/devilbox/issues
* [ ] I've read troubleshooting: https://devilbox.readthedocs.io/en/latest/support/troubleshooting.html

### OS / ENVIRONMENT

1. Host operating system and version: macOS 11.3
2. (Windows only) Native Docker or Docker Toolbox:
3. Docker version: 3.2.1 Engine 20.10.5
4. Docker Compose version: 1.28.5
5. (Linux) Is SELinux enabled?:
6. What git commit hash are you on?: cdfb55ec2d061bb20bb6aad1792034d995a855a2

### SUMMARY
It's not starting. 

➜  devilbox git:(master) docker-compose up
Starting devilbox_bind_1 ... 
Starting devilbox_bind_1 ... error

ERROR: for devilbox_bind_1  Cannot start service bind: driver failed programming external connectivity on endpoint devilbox_bind_1 (7ec965227100c4a4a33b50ba66f0c8337f1e7f7db37fc82754ae9e75c261a27d): Error starting userland proxy: listen tcp4 0.0.0.0:53: bind: address already in use

ERROR: for bind  Cannot start service bind: driver failed programming external connectivity on endpoint devilbox_bind_1 (7ec965227100c4a4a33b50ba66f0c8337f1e7f7db37fc82754ae9e75c261a27d): Error starting userland proxy: listen tcp4 0.0.0.0:53: bind: address already in use
ERROR: Encountered errors while bringing up the project.

### STEPS TO REPRODUCE
Updated Docker. 

### EXPECTED BEHAVIOUR
Devilbox running

### ACTUAL BEHAVIOUR
Devilbox not running

#### Start command

```
$ docker-compose up...
```

#### Outputs

```bash
$ ./check-config.sh

# ==============================================================================
# Checking git
# ==============================================================================
[SUCC]  git is clean

# ==============================================================================
# Checking .env file
# ==============================================================================
[SUCC]  .env file exists
[SUCC]  .env file is readable
[SUCC]  All variables are present in .env file
[SUCC]  No variables is duplicated in .env file

# ==============================================================================
# Checking .env file values
# ==============================================================================
[SUCC]  All .env file variables have correct values

# ==============================================================================
# Checking required Devilbox core directories exist
# ==============================================================================
[SUCC]  All PHP cfg/ sub directories are present
[SUCC]  All PHP log/ sub directories are present
[SUCC]  All PHP mod/ sub directories are present
[SUCC]  All HTTPD cfg/ sub directories are present
[SUCC]  All HTTPD log/ sub directories are present

# ==============================================================================
# Checking devilbox core directory permissions
# ==============================================================================
[SUCC]  All devilbox directories have correct permissions
[SUCC]  All devilbox directories have correct uid
[SUCC]  All devilbox directories have correct gid

# ==============================================================================
# Checking devilbox core file permissions
# ==============================================================================
[SUCC]  All devilbox files have correct permissions
[SUCC]  All devilbox files have correct uid
[SUCC]  All devilbox files have correct gid

# ==============================================================================
# Checking projects permissions
# ==============================================================================
[SUCC]  All project dirs have correct permissions
[SUCC]  All project dirs have correct uid
[SUCC]  All project dirs have correct gid

# ==============================================================================
# Checking projects settings
# ==============================================================================
[SUCC]  All projects have valid DNS records
[SUCC]  All projects have valid HTTPD_DOCROOT_DIR

# ==============================================================================
# Checking customizations
# ==============================================================================
[NOTE]  [vhost-gen]  Custom Nginx vhost-gen config present in: data/www/lobby/
[NOTE]  [vhost-gen]  Custom Apache 2.4 vhost-gen config present in: data/www/spreader/
[NOTE]  [php.ini]    Custom config present in cfg/php-ini-7.4/
[NOTE]  [mysql]      Custom config present in cfg/mariadb-10.4/

# ==============================================================================
# SUMMARY
# ==============================================================================
[SUCC]  Found no errors
[NOTE]  4 custom configurations applied. If you encounter issues, reset them first.
```

```bash
$ docker-compose logs

Attaching to devilbox_bind_1
```

**Comment by wp4nuv** [comment]
If I may ask, why was this closed? Was there a solution found? I'm presenting the same issue with WSL 2 Ubuntu 20.04.

**Comment by krebbi** [comment]
I had in .env
HOST_PORT_BIND=53
for the past year or so and out of a sudden the error mentioned above occurred.

So I changed it to
HOST_PORT_BIND=1053
and now it works again.

**Comment by wp4nuv** [comment]
I tried that before, but if the documentation to get it to work is to use port 53, why is it crapping out now? I've been using Devilbox for a while, its not like its not worked before. Even with WSL2 Devilbox DNS works fine once you adjust the WSL ethernet to use 127.0.0.1 for dns

**Comment by wp4nuv** [comment]
Just checked after changing .env to have dns run on port 1053. Making that change makes the stack run, but Auto DNS is shot, including using dns names inside the stack.
