### ISSUE TITLE
Cannot start service bind

### ISSUE THREAD

**Issue by fkaminski** [cytopia/devilbox#796]
Windows 10 Pro und Docker Desktop (via Hyper-V - Not WSL2)
Bekomme nach dem autom. Docker Update auf die Version(en):

docker desktop: 3.2.1 (61626)
engine: 20.10.5
compose: 1.28.5

die Meldung:
```
ERROR: for devilbox_bind_1  Cannot start service bind: driver failed programming external connectivity on endpoint devilbox_bind_1 (1313b666c3f5f6f555d17d93ca82b3f723d3a476daf36975988fdbc7311b284b): Error starting userland proxy: listen tcp4 0.0.0.0:53: bind: address already in use

ERROR: for bind  Cannot start service bind: driver failed programming external connectivity on endpoint devilbox_bind_1 (1313b666c3f5f6f555d17d93ca82b3f723d3a476daf36975988fdbc7311b284b): Error starting userland proxy: listen tcp4 0.0.0.0:53: bind: address already in use
Encountered errors while bringing up the project.
```

Wenn ich in der .env die Angabe HOST_PORT_BIND wieder auf 1053 setze geht es. Mit Port 53 nicht.
Der Port 53 ist ansonsten nicht belegt.

Habe dann docker desktop und Hyper-V features unter Windows deinstalliert und dann wieder neu installiert.
Dann geht es - auch Mit den HOST_PORT_BIND=53 Einstellungen

Kurz danach macht docker desktop ein autom. Update auf obige Version ...
Und schon erhalte ich wieder den Fehler ???

**Comment by wp4nuv** [comment]
While I'm not fluent in German, I understand enough to think what's happening to you is happening to me as well although with WSL2 (Ubuntu 20.04). I receive the same message when starting the stack. There are no services on the WSL2 instance using port 53. I've reinstalled both Ubuntu and Docker with the same result. 
``` Starting devilbox_bind_1 ...
Starting devilbox_bind_1 ... error

ERROR: for devilbox_bind_1  Cannot start service bind: driver failed programming external connectivity on endpoint devilbox_bind_1 (d4c3a1727c2085b146a3f6cd093e77fca7ca1763705da7ea9668e45b9a22e414): Error starting userland proxy: listen tcp4 0.0.0.0:53: bind: address already in use

ERROR: for bind  Cannot start service bind: driver failed programming external connectivity on endpoint devilbox_bind_1 (d4c3a1727c2085b146a3f6cd093e77fca7ca1763705da7ea9668e45b9a22e414): Error starting userland proxy: listen tcp4 0.0.0.0:53: bind: address already in use
ERROR: Encountered errors while bringing up the project.
```
There are no other docker-compose logs as the process fails from even running the other containers.

Docker version 20.10.5, build 55c4c88
docker-compose version 1.28.5, build c4eb3a1f

**Comment by fkaminski** [comment]
@wp4nuv Please excuse: english is not my native language - so I will try anyway:

Tried again:
Reinstall Windows 10 Hyper-V and then "docker desktop" (without WSL2):

Status then:

docker desktop: 3.1.0 (51484)
Engine: 20.10.2
Compose: 1.27.4

The devilbox is running: Also with port 53 (HOST_PORT_BIND=53).

Then docker do the auto. update again:

docker desktop: 3.2.1 (61626)
Engine: 20.10.5
Compose: 1.28.5

And I get above error message ...?

So as long as I suppress the docker updates (on Windows) it works.
I don't know now what the problem is: 
Windows / Hyper-V o. WSL2 / docker - docker-compose version / devilbox ...

If someone knows more info about this -
Thanks

**Comment by wp4nuv** [comment]
@fkaminski, I don't know really how, but for me German is like English written differently.. I understand most of it, even while reading... Anyway, to update my earlier post, here's the output of my config-check script:
```
./check-config.sh

# ==============================================================================
# Checking git
# ==============================================================================
[SUCC]  git is clean

# ==============================================================================
# Checking .env file
# ==============================================================================
[SUCC]  .env file exists
[SUCC]  .env file is readable
[SUCC]  All variables are present in .env file
[SUCC]  No variables is duplicated in .env file

# ==============================================================================
# Checking .env file values
# ==============================================================================
[SUCC]  All .env file variables have correct values

# ==============================================================================
# Checking required Devilbox core directories exist
# ==============================================================================
[SUCC]  All PHP cfg/ sub directories are present
[SUCC]  All PHP log/ sub directories are present
[SUCC]  All PHP mod/ sub directories are present
[SUCC]  All HTTPD cfg/ sub directories are present
[SUCC]  All HTTPD log/ sub directories are present

# ==============================================================================
# Checking devilbox core directory permissions
# ==============================================================================
[SUCC]  All devilbox directories have correct permissions
[SUCC]  All devilbox directories have correct uid
[SUCC]  All devilbox directories have correct gid

# ==============================================================================
# Checking devilbox core file permissions
# ==============================================================================
[SUCC]  All devilbox files have correct permissions
[SUCC]  All devilbox files have correct uid
[SUCC]  All devilbox files have correct gid

# ==============================================================================
# Checking projects permissions
# ==============================================================================
[SUCC]  All project dirs have correct permissions
[SUCC]  All project dirs have correct uid
[SUCC]  All project dirs have correct gid

# ==============================================================================
# Checking projects settings
# ==============================================================================
[SUCC]  All projects have valid DNS records
[SUCC]  All projects have valid HTTPD_DOCROOT_DIR

# ==============================================================================
# Checking customizations
# ==============================================================================
[INFO]  No custom configurations applied

# ==============================================================================
# SUMMARY
# ==============================================================================
[SUCC]  Found no errors
[INFO]  No custom configurations applied
[INFO]  Ensure to run 'docker-compose stop; docker-compose rm -f' on .env changes or custom configs
```
This is a brand new devilbox clone with a fresh ```.env``` file and no other updates. Funny that one of the checks says all projects have valid DNS records, but I haven't added any yet.

**Comment by wp4nuv** [comment]
I just thought of something. Just the other day there was a Docker update.. I wonder if that's what's causing the issue. I'm going to reinstall an earlier version, just to see if anything changes. Mind you that I already reset the current Docker installation to default values and cleared all images, just to be sure

**Comment by wp4nuv** [comment]
Ok, so the earlier version of Docker didn't solve anything. bind still fails to start. :(

**Comment by fkaminski** [comment]
Strange,
as described above it works fine with an older "docker desktop" version. 
But i do have to go the hard way (on Windows): 

- Deinstall docker-dektop / deinstall windows hyper-v feature 
- Install windows hyper-v feature / install docker-desktop

Just cleaning up the containers/images (docker system prune etc.) was not enough ...

**Comment by fkaminski** [comment]
Have now tested this on a computer with Windows 10 Home and WSL2.

With docker-desktop version 3.1.0 everything works as before
( Auto DNS via port 53 ).

Hint:
One must add in this environment then additionally 127.0.0.1 in the network Ethernet adapter ( vEthernet(WSL) ).

Apart from that: 
As long as I do not allow docker update then it just continues to work ... ???

**Comment by wp4nuv** [comment]
Thanks,  I'll check it out. If it indeed works, I'll try to make a bug ticket for Docker Desktop

**Comment by wp4nuv** [comment]
Just found the above issue in Docker for Windows GitHub issues. Seems like there is a real problem with 3.2.1 and DNS.  (Among other complaints is the automatic auto update that has no option to be disabled, which sucks because if you have to downgrade for issues like this, its impossible to keep the old version as-is while work continues on a fix). Anyway, there seems to be ongoing work to handle this problem.

**Comment by wp4nuv** [comment]
For those interested, while we wait for an official Docker patch, there is a release available that deals with port 53 not available.
https://github.com/docker/for-win/issues/10601#issuecomment-797983785

**Comment by fkaminski** [comment]
With the new docker update (3.2.2) everything works now again.
So maybe this issue could be closed ...
