### ISSUE TITLE
URL stay on Missing entry in hosts file

### ISSUE THREAD

**Issue by LeG3nDz** [cytopia/devilbox#8]
Hi Cytopia :)

I would like test your very nice devilbox, but when i edit my hosts file, URL stay with `Missing entry in /etc/hosts`. My hosts file :

```
127.0.0.1	localhost
127.0.1.1	ubuntu
::1             localhost

# The following lines are desirable for IPv6 capable hosts
#::1     ip6-localhost ip6-loopback
#fe00::0 ip6-localnet
#ff00::0 ip6-mcastprefix
#ff02::1 ip6-allnodes
#ff02::2 ip6-allrouters

127.0.0.1 www.project.lan.loc
```
But, if i go on www.project.lan.loc, vhost work fine. It's juste the URL status.

Do you have any idea ? Yet I have followed the instructions :)

Thank you !

**Comment by cytopia** [comment]
Hi @LeG3nDz can u post the exact error message from the intranet.
It should actually provide you the exact string that you need to put into `/etc/hosts`.

Also please attach your `.env` as well as an `ls -l` on your www directory, so I can see the names of the folders.

By your above entry, your foldername should be `www.project.lan`

**Comment by LeG3nDz** [comment]
Thank for your response.

I did not necessarily error, juste the URL status (on vhost page) have `Missing entry in /etc/hosts`.

My .env :

```
###
###  ---------------------------------------------------
###  D E V I L B O X   R U N - T I M E   S E T T I N G S
###  ---------------------------------------------------
###
###  All the following settings are applied during
###  $ docker-compose up
###
###  No need to rebuild any dockers!
###


###
### Show all executed commands in each
### docker image during docker-compose up?
###
### 1: Yes
### 0: No
DEBUG_COMPOSE_ENTRYPOINT=0



################################################################################
###
### 1. Choose Images (Version)
###
################################################################################

###
### You can choose any combination of httpd, mysql or php.
### Each of them are fully compatible between one another.
###


###
### 1.1 Choose HTTP Server Image
###

#HTTPD_SERVER=apache-2.2
HTTPD_SERVER=apache-2.4
#HTTPD_SERVER=nginx-stable
#HTTPD_SERVER=nginx-mainline



###
### 1.2 Choose MySQL Server Image
###

#MYSQL_SERVER=mysql-5.5
MYSQL_SERVER=mysql-5.6
#MYSQL_SERVER=mysql-5.7
#MYSQL_SERVER=mariadb-5.5



###
### 1.3 Choose PHP Server Image
###

#PHP_SERVER=php-fpm-5.4
#PHP_SERVER=php-fpm-5.5
PHP_SERVER=php-fpm-5.6
#PHP_SERVER=php-fpm-7.0
#PHP_SERVER=php-fpm-7.1



###
### 1.4 Timezone for all dockers and service config files
###

TIMEZONE=Europe/Berlin






################################################################################
###
### 2. Host Settings (Your computer)
###
################################################################################


##
## Local filesystem path to www projects.
##
##
HOST_PATH_TO_WWW_DOCROOTS=~/data/www

##
## Local filesystem path to mysql datadir.
##
## This can be an existing mysql data directory or empty.
## If it already is a mysql data directory with content,
## it will be mounted into the docker and used.
##
## If this directory is empty, a new mysql database will be
## created.
##
HOST_PATH_TO_MYSQL_DATADIR=~/data/mysql56




################################################################################
###
### 3. HTTP Docker Settings
###
################################################################################

# - no options here




################################################################################
###
### 4. MySQL Docker Settings
###
################################################################################

##
## MySQL root user password
##
## If $HOST_PATH_TO_MYSQL_DATADIR already contains an existing
## mysql datadir, enter the password for the existing mysql database
##
## If $HOST_PATH_TO_MYSQL_DATADIR is empty, choose a new password that
## will be applied
##
MYSQL_ROOT_PASSWORD=


###
### Custom MySQL Runtime Settings
###

MYSQL_GENERAL_LOG=1



################################################################################
###
### 5. PHP-FPM Docker Settings
###
################################################################################


###
### Xdebug
###

# Enable/Disable Xdebug
PHP_XDEBUG_ENABLE=1

# Your local port (your computer host [not the docker])
# where your ide/editor is listening for xdebug connections.
PHP_XDEBUG_REMOTE_PORT=9000

# Your local IP address (your computer host [not the docker])
# where your ide/editor is listening for xdebug connections.
PHP_XDEBUG_REMOTE_HOST=172.20.10.2
```

I've restart my Ubuntu, and if i run `docker-composer up`, I do not have any project to detect in www/ folder.

Result command `ls -l` in **~/data/www**

```
drwxr-xr-x 3 root root 4096 oct.  26 01:26 ./
drwxr-xr-x 4 root root 4096 oct.  26 01:22 ../
drwxr-xr-x 5 root root 4096 oct.  26 01:27 www.project.lan/
```

Thank again,

**Comment by cytopia** [comment]
Could you please attach a screenshot of the vhosts status page.

Also inside the devilbox folder, please check `./log/php-fpm-5.6/` and `./log/apache-2.4` for errors.

**Comment by cytopia** [comment]
Btw

> Result command `ls -l` in **~/data/www**
> ```
> drwxr-xr-x 3 root root 4096 oct.  26 01:26 ./
> drwxr-xr-x 4 root root 4096 oct.  26 01:22 ../
> drwxr-xr-x 5 root root 4096 oct.  26 01:27 www.project.lan/
> ```

Is that correct, that it belongs to root in your `~` directory?

**Comment by LeG3nDz** [comment]
Yep, the config is good.

After restart my Ubuntu and run docker-composer up, i do not see my project :(

![devilbox](https://cloud.githubusercontent.com/assets/4712791/19724102/c438edea-9b7e-11e6-8188-dbe8a166735d.jpg)

**Comment by cytopia** [comment]
Are you running the devilbox in VMWare and edited `/etc/hosts` on your host computer?

**Comment by LeG3nDz** [comment]
I'm run Ubuntu with VMWare on Windows, and i edit Ubuntu hosts file.

**Comment by cytopia** [comment]
Are you browsing from your ubuntu VM or from windows?

**Comment by LeG3nDz** [comment]
All action in on my Ubuntu started on VMWare.

**Comment by cytopia** [comment]
Ubuntu seems to use `127.0.1.1` instead of `127.0.0.1`.
What does `ifconfig` on ubuntu show?

**Comment by cytopia** [comment]
Btw, regardless of this error, Is it actually possible to reach this site via the browser?

**Comment by cytopia** [comment]
Should work now.

I had to disable the `/etc/hosts` check for now.
It somehow works under OSX, but not on Linux.

I still have to figure out why and how to re-implement this properly.

If it works for you, please let me know, so this can get closed.

**Comment by LeG3nDz** [comment]
Hi @cytopia 

I confirm it work :)
Just, maybe add a message indicating that it must update hosts file ?

Thank you again for your support. Very nice devilbox :)

**Comment by cytopia** [comment]
Cool. Yes I will figure something out to make it as nice as before under Linux.

**Comment by cytopia** [comment]
Linking the progress here:

#9 [Access docker hosts `/etc/hosts` from inside the PHP-docker (works on OSX, not on Linux)](9)
