### ISSUE TITLE
GraphicsMagick and Gmagick extension

### ISSUE THREAD

**Issue by robots4life** [cytopia/devilbox#800]
Gmagick extension is not listed here.
https://github.com/devilbox/docker-php-fpm#user-content-php-modules

#### ISSUE TYPE

 - Feature request

#### SUMMARY

Compared to ImageMagick, GraphicsMagick works faster, uses less system resources and is more stable.
https://www.php.net/manual/en/book.gmagick.php

#### Goal

Be able to work with high resolution images faster while using less system resources and have higher stability.

Thank you for considering this feature request.

**Comment by llaville** [comment]
I'm surprised to see no stable release since the first one in 2009 (see https://pecl.php.net/package/gmagick)

**Comment by robots4life** [comment]
Oh my.. :roll_eyes:
