### ISSUE TITLE
Mount only subfolder of projet 

### ISSUE THREAD

**Issue by o2bj** [cytopia/devilbox#803]
I'm using devilbox on windows "docker for windows", but the issue is that working with magneto2 on docker (windows) is extremely slow. 
I dealt with it (in my previous docker setup) by mounting only  the "/ app" subdolder of magento, not the entire folder with the magento installation.
But I'm not sure how do it on devilbox. 

Can someone provide instruction, how to after magento installation  
disable mount  
`data\www`
and mount only 
`data\www\my_project\htdocs\subfolder_to_mount `

**Comment by cytopia** [comment]
You can override the mount via `docker-compose-override.yml`. See docs here: https://devilbox.readthedocs.io/en/latest/configuration-files/docker-compose-override-yml.html

I'm not sure if this will work at all, if only part of your code is available inside the container.
Nevertheless, hope this helps.
