### ISSUE TITLE
Installation Error on CentOS 7.2

### ISSUE THREAD

**Issue by Budapresst** [cytopia/devilbox#810]
### ISSUE TYPE

 - Bug Report

### Checklist

* [x] `.env` file is attached
* [x] `./check-config.sh` output is added below
* [x] `docker-compose logs` output is added below
* [x] `docker-compose.override.yml` is attached (if exists)
* [x] Custom configs from `cfg/` dir are attached (if exist)
* [x] I've looked through the docs: https://devilbox.readthedocs.io/en/latest/
* [x] I've looked through existing issues: https://github.com/cytopia/devilbox/issues
* [x] I've read troubleshooting: https://devilbox.readthedocs.io/en/latest/support/troubleshooting.html

[dotENV.txt](https://github.com/cytopia/devilbox/files/6499049/dotENV.txt)

### OS / ENVIRONMENT

1. Host operating system and version:  linux-centos-7.2-x86_64
2. (Windows only) Native Docker or Docker Toolbox:
3. Docker version: 20.10.6, build 370c289
4. Docker Compose version: 1.29.2
5. (Linux) Is SELinux enabled?: No
6. What git commit hash are you on?: 59738601b2f940610ca89134690fbba7f26ad5ed

### SUMMARY

After issue the `docker-compose up` command, the php-fpm files start downloading, pulling, and extracting... One of the files/hashes produces an error as it completes extraction and prevents the devilbox from loading:

514ee8724937: Pull complete
c982c820d971: Extracting [==================================================>]  150.5MB/150.5MB
e82639f2ad1a: Download complete
432338ecfff9: Download complete
f75f7ab31e83: Download complete
1d2df7a99913: Download complete
d648c89805c3: Download complete
4ebb484d6da7: Download complete
a4d4f798ce1a: Download complete
2042dec7c3c2: Download complete
d4aa01db8fda: Download complete
a20fe4353516: Download complete
ERROR: failed to register layer: ApplyLayer exit status 1 stdout:  stderr: unlinkat /opt/nvm/.cache/bin/node-v14.15.3-linux-x64: invalid argument

I have tried using a different version of PHP-FPM, but it's not related to that. I don't see anything wrong with the unlinkat command except that the resource it is trying to remove does not exist, but then again it's nvm which I know nothing about.

### STEPS TO REPRODUCE

Install the same Devilbox on the same version of CentOS.  

#### Start command

```
docker-compose up httpd php mysql redis

[dotENV.txt](https://github.com/cytopia/devilbox/files/6499049/dotENV.txt)
```

#### Outputs

```bash
$ ./check-config.sh

# ==============================================================================
# Checking git
# ==============================================================================
[SUCC]  git is clean

# ==============================================================================
# Checking .env file
# ==============================================================================
[SUCC]  .env file exists
[SUCC]  .env file is readable
[SUCC]  All variables are present in .env file
[SUCC]  No variables is duplicated in .env file

# ==============================================================================
# Checking .env file values
# ==============================================================================
[SUCC]  All .env file variables have correct values

# ==============================================================================
# Checking required Devilbox core directories exist
# ==============================================================================
[SUCC]  All PHP cfg/ sub directories are present
[SUCC]  All PHP log/ sub directories are present
[SUCC]  All PHP mod/ sub directories are present
[SUCC]  All HTTPD cfg/ sub directories are present
[SUCC]  All HTTPD log/ sub directories are present

# ==============================================================================
# Checking devilbox core directory permissions
# ==============================================================================
[SUCC]  All devilbox directories have correct permissions
[SUCC]  All devilbox directories have correct uid
[SUCC]  All devilbox directories have correct gid

# ==============================================================================
# Checking devilbox core file permissions
# ==============================================================================
[SUCC]  All devilbox files have correct permissions
[SUCC]  All devilbox files have correct uid
[SUCC]  All devilbox files have correct gid

# ==============================================================================
# Checking projects permissions
# ==============================================================================
[SUCC]  All project dirs have correct permissions
[SUCC]  All project dirs have correct uid
[SUCC]  All project dirs have correct gid

# ==============================================================================
# Checking projects settings
# ==============================================================================
[SUCC]  All projects have valid DNS records
[SUCC]  All projects have valid HTTPD_DOCROOT_DIR

# ==============================================================================
# Checking customizations
# ==============================================================================
[INFO]  No custom configurations applied

# ==============================================================================
# SUMMARY
# ==============================================================================
[SUCC]  Found no errors
[INFO]  No custom configurations applied
[INFO]  Ensure to run 'docker-compose stop; docker-compose rm -f' on .env changes or custom configs
```

```bash
$ docker-compose logs

Attaching to
```

**Comment by cytopia** [comment]
There seems to be an issue with pulling the images, which is still before the Devilbox starts.
Can you do a:
```
docker-compose pull
```
and see if you can successfully pull all docker images.

**Comment by Budapresst** [comment]
Thank you for the help!  Everything pulls except the PHP which seems to have the same problem in the same place:

[root@devbox devilbox]# docker-compose pull
Pulling bind  ... done
Pulling php   ... extracting (100.0%)
Pulling httpd ... done
Pulling mysql ... done
Pulling pgsql ... done
Pulling redis ... done
Pulling memcd ... done
Pulling mongo ... done

ERROR: for php  failed to register layer: ApplyLayer exit status 1 stdout:  stderr: unlinkat /opt/nvm/.cache/bin/node-v14.15.3-linux-x64: invalid 
ERROR: failed to register layer: ApplyLayer exit status 1 stdout:  stderr: unlinkat /opt/nvm/.cache/bin/node-v14.15.3-linux-x64: invalid argument

**Comment by cytopia** [comment]
Can you try the branch from this PR: https://github.com/cytopia/devilbox/pull/777

It's gonna be merged very soon, only requires some minor adjustments.

**Comment by Budapresst** [comment]
sorry for the noob question, but what's my command for that?  I tried "git clone https://github.com/cytopia/devilbox -b pull/777" but obviously that's wrong... :)

**Comment by cytopia** [comment]
```
git clone https://github.com/cytopia/devilbox
cd devilbox
git checkout release/v1.9.1
docker-compose stop
docker-compose rm
docker-compose pull
docker-compose up
```

**Comment by Budapresst** [comment]
A new but similar error appeared... Any ideas...  It seems to be something about this VPS and Docker... Everything is loading fine on my bare metal server with CentOS7.2

[root@devbox home]# git clone https://github.com/cytopia/devilbox
Cloning into 'devilbox'...
remote: Enumerating objects: 26159, done.
remote: Counting objects: 100% (128/128), done.
remote: Compressing objects: 100% (94/94), done.
remote: Total 26159 (delta 50), reused 80 (delta 33), pack-reused 26031
Receiving objects: 100% (26159/26159), 43.85 MiB | 10.30 MiB/s, done.
Resolving deltas: 100% (12810/12810), done.
[root@devbox home]# cd devilbox
[root@devbox devilbox]# git checkout release/v1.9.1
Branch release/v1.9.1 set up to track remote branch release/v1.9.1 from origin.
Switched to a new branch 'release/v1.9.1'
[root@devbox devilbox]# cp env-example .env
[root@devbox devilbox]# docker-compose stop
[root@devbox devilbox]# docker-compose rm
No stopped containers
[root@devbox devilbox]# docker-compose pull
Pulling bind  ... done
Pulling php   ... extracting (100.0%)
Pulling httpd ... extracting (100.0%)
Pulling mysql ... done
Pulling pgsql ... done
Pulling redis ... done
Pulling memcd ... done
Pulling mongo ... done

ERROR: for httpd  failed to register layer: ApplyLayer exit status 1 stdout:  stderr: unlinkat //docker-entrypoint.d: invalid argument

ERROR: for php  failed to register layer: ApplyLayer exit status 1 stdout:  stderr: unlinkat /opt/nvm/.cache/bin/node-v14.17.0-linux-x64: invalid argument
ERROR: failed to register layer: ApplyLayer exit status 1 stdout:  stderr: unlinkat /opt/nvm/.cache/bin/node-v14.17.0-linux-x64: invalid argument

**Comment by cytopia** [comment]
The whole thing just ran fine in CI multiple times. So I'd also assume that there's an issue with your local docker setup/installation.

**Comment by Budapresst** [comment]
Okay... Thank you for your help.  I will approach it as a Docker issue and keep working on it.  Have a great day!

**Comment by Budapresst** [comment]
Fixed!  I reinstalled CentOS and the problem "disappeared".  Thank you @cytopia for the incredible product and great support!  :)
