### ISSUE TITLE
Release 1.9.1 still referenced linuxbrew tool

### ISSUE THREAD

**Issue by llaville** [cytopia/devilbox#811]
#### ISSUE TYPE

 - Documentation

#### SUMMARY

Even if documentation https://devilbox.readthedocs.io/en/latest/readings/available-tools.html did not display `linuxbrew` tool anymore, it still appears in https://github.com/cytopia/devilbox/blame/v1.9.1/README.md page

#### Goal

Remove the line from README page

BTW, I'd rather like to have a migration from linuxbrew to homebrew rather than removed it (something like https://github.com/llaville/docker-php-fpm/commit/ce618d91827e3c08c1ea1bd43e18c6bf995be67e)

**Comment by cytopia** [comment]
@llaville thanks for pointing out. This is the part I missed.

I was actually only removing it due to struggle of maintenance and also image size (as well as I didn't really manage to implement the newly moved project). If you still find `brew` useful, I will accept the PR and move it back into PHP-FPM.

**Comment by llaville** [comment]
@cytopia PR is available at https://github.com/devilbox/docker-php-fpm/pull/206

**Comment by llaville** [comment]
@cytopia As docker-php-fpm 0.126 is already available ( thanks ),  dont forget to update the README page of the Devilbox project !

**Comment by cytopia** [comment]
I will, together with the new version for `0.126` (Currently still `0.125` https://github.com/cytopia/devilbox/blob/master/docker-compose.yml#L98)

**Comment by cytopia** [comment]
Adressed in https://github.com/cytopia/devilbox/pull/814
