### ISSUE TITLE
Add swoole to php 8

### ISSUE THREAD

**Issue by fibis** [cytopia/devilbox#815]
#### ISSUE TYPE

 - Feature request

#### SUMMARY

The PHP 8 image doesn't include swoole as PHP extension. I would like to use swoole with PHP 8.

#### Goal

Goal is to add the swoole extension to the PHP 8 images.

**Comment by fibis** [comment]
Resolved here: https://github.com/devilbox/docker-php-fpm/pull/211

**Comment by fibis** [comment]
Was resolved here: https://github.com/devilbox/docker-php-fpm/pull/212

**Comment by cytopia** [comment]
@fibis keep in mind that I still need to PR the update image version here :-)
So currently we're still running with the old version. Will however do it today.

**Comment by fibis** [comment]
@fibis is there also some magic stuff for that or is it only changing this line: https://github.com/cytopia/devilbox/blob/master/docker-compose.yml#L98 to 128?

**Comment by cytopia** [comment]
> @fibis is there also some magic stuff for that or is it only changing this line: https://github.com/cytopia/devilbox/blob/master/docker-compose.yml#L98 to 128?

That's all that needs to be done. Might give it another hour or so until the images are built and pushed
