### ISSUE TITLE
Plugin Tinker not work

### ISSUE THREAD

**Issue by morsergen** [cytopia/devilbox#816]
Good day!
How can I use the Tinker plugin in Laravel with Devilbox?

![image](https://user-images.githubusercontent.com/45065258/122612809-71e89980-d08c-11eb-9640-c7af57f62875.png)

![image](https://user-images.githubusercontent.com/45065258/122612720-49609f80-d08c-11eb-91f0-0c7f6eeee1c2.png)

![image](https://user-images.githubusercontent.com/45065258/122612490-e111be00-d08b-11eb-93df-48de33b5ce47.png)

**Comment by cytopia** [comment]
Good day as well @morsergen,
`DB_HOST` should be `mysql` not `127.0.0.1`

**Comment by morsergen** [comment]
/etc/hosts - 127.0.0.1 mysql

![image](https://user-images.githubusercontent.com/45065258/122651864-43c69080-d144-11eb-87f6-c09e2240d4ca.png)

![image](https://user-images.githubusercontent.com/45065258/122651875-5214ac80-d144-11eb-90aa-89b9a8e6304b.png)

**Comment by cytopia** [comment]
Good day  @morsergen,

If I'm inside the PHP container, it does find the `mysql` host without having to specify it in `/etc/hosts`:


`resolving hostname` (inside container)
```
devilbox@php-8.1.0-dev in /shared/httpd $ ping mysql
PING mysql (172.16.238.12) 56(84) bytes of data.
64 bytes from devilbox2_mysql_1.devilbox2_app_net (172.16.238.12): icmp_seq=1 ttl=64 time=0.262 ms
```
`/etc/hosts` (inside container)
```
devilbox@php-8.1.0-dev in /shared/httpd $ cat /etc/hosts
127.0.0.1       localhost
::1     localhost ip6-localhost ip6-loopback
fe00::0 ip6-localnet
ff00::0 ip6-mcastprefix
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters
172.16.238.1    docker.for.lin.host.internal
172.16.238.1    docker.for.lin.localhost
172.16.238.10   php
```

If you think this is a bug, I would suggest to re-create the ticket with the bug report template and fill out all steps especially the "how to reproduce" description (which should also include your Tinker setup and the trigger that caused the error message), otherwise there is no real way to support you on this, except for guessing.

**Comment by morsergen** [comment]
Good day @cytopia 
Thanks for answers.

I did not quite understand...
I do not add anything to the hosts file inside the container.
Here are my screenshots:
![image](https://user-images.githubusercontent.com/45065258/122678788-e9cfd480-d1f0-11eb-8611-9c2b2420ef66.png)
![image](https://user-images.githubusercontent.com/45065258/122678814-fc4a0e00-d1f0-11eb-8f4b-ce57df236927.png)

Inside the container in the terminal, the tinker works without problems.
![image](https://user-images.githubusercontent.com/45065258/122678988-aa55b800-d1f1-11eb-89ae-08af765ae6d5.png)

Outside the container, PHPStrom cannot connect to the database. It was outside that I was trying to add / etc / hosts - 127.0.0.1 mysql
But it doesn't work with this record and without it.

What am I doing wrong? And as far as I can see, the tinker has no settings.
Thank you

**Comment by cytopia** [comment]
I can connect to the Devilbox DB from my host system just fine:
```
host> mysql -uroot --host=127.0.0.1

Welcome to the MariaDB monitor.  Commands end with ; or \g.
Your MariaDB connection id is 4
Server version: 10.5.8-MariaDB-1:10.5.8+maria~focal-log mariadb.org binary distribution
```

If the above works for you (from your host) it is a tinker issue.
If the above does not work for you (you have a permission issue with the root user of the database)

**Comment by morsergen** [comment]
the connection works from the container, there is no connection outside the container
I don't understand how to use tinker in PHPStorm
please, help

![image](https://user-images.githubusercontent.com/45065258/122683677-6a9aca80-d209-11eb-9211-ace35f9ccc67.png)

![image](https://user-images.githubusercontent.com/45065258/122683683-7c7c6d80-d209-11eb-9f22-df3ad9811082.png)

**Comment by cytopia** [comment]
Follow the instructions from your second screenshot to test the DB from your host

**Comment by morsergen** [comment]
Good day @cytopia
Thanks for answers.

I install mysql to my host
![image](https://user-images.githubusercontent.com/45065258/122724003-37455380-d27c-11eb-8e4b-42358109fee8.png)
![image](https://user-images.githubusercontent.com/45065258/122724204-61971100-d27c-11eb-82e5-fcb8d3c266b4.png)
![image](https://user-images.githubusercontent.com/45065258/122724284-7378b400-d27c-11eb-8df7-9332784febe5.png)

but when I put the settings DB_HOST in .env:

127.0.0.1
![image](https://user-images.githubusercontent.com/45065258/122724514-ac188d80-d27c-11eb-8798-bc6fa52a3dc2.png)

172.16.238.12
![image](https://user-images.githubusercontent.com/45065258/122724934-1f220400-d27d-11eb-994d-94fb5fc6b5ea.png)

mysql
![image](https://user-images.githubusercontent.com/45065258/122724978-306b1080-d27d-11eb-8e0d-a96a2fba562a.png)

**Comment by cytopia** [comment]
@morsergen So MySQL connectivity from Devilbox side of things works fine on your machine.
Now all that's left is to play around with Tinker and get it setup correctly. I'd suggest to ask in their Forum for further help.

**Comment by morsergen** [comment]
OK thanks
