### ISSUE TITLE
Can I somehow change the version of Xdebug with the 3 on the 2?

### ISSUE THREAD

**Issue by evgeny-2019** [cytopia/devilbox#818]
My IDE does not support the third version of Xdebug. Can I change Xdebug in DevilBox to the second version? How to do it?

**Comment by llaville** [comment]
Question was [already asked](https://github.com/cytopia/devilbox/issues/769#issuecomment-752124436) and @cytopia already gave an [answer](https://github.com/cytopia/devilbox/issues/769#issuecomment-752136558)

That means if you downgrade your version from 0.127 in your [docker-compose.yml](https://github.com/cytopia/devilbox/blob/v1.9.2/docker-compose.yml#L98) to 0.118 you'll probably also lose some other benefits (changes). See [versions compare](https://github.com/devilbox/docker-php-fpm/compare/0.118...0.128)

**Comment by cytopia** [comment]
@evgeny-2019 see answer from @llaville : https://github.com/cytopia/devilbox/issues/818#issuecomment-932680051
