### ISSUE TITLE
Please add runkit7 to the enable-able php modules

### ISSUE THREAD

**Issue by ultrablue** [cytopia/devilbox#819]
#### ISSUE TYPE

 - Feature request

#### SUMMARY
Please add runkit7 to the enable-able php modules.
https://www.php.net/manual/en/book.runkit7.php

#### Goal
Currently, I have to install it by hand every time I restart the php container. It would be great if it could be automatic.

Thank you!

**Comment by llaville** [comment]
Did you noticed that there is not yet a stable release since the begining of its development.
Personnaly I'm not agree to have it included in any php-fpm docker images of the devilbox.

**Comment by llaville** [comment]
Alternative will be to include uopz extension (https://www.php.net/manual/en/book.uopz.php) that already have stable releases.
Or just check the project https://github.com/badoo/soft-mocks if it match your needs @ultrablue 

Personnaly I don't think it's a PHP development best practice to allow to modify functions on fly but I admit it just be allowed to write unit tests and mock some of internal PHP functions like `time()`

**Comment by cytopia** [comment]
@ultrablue If you install `runkit7` yourself on the PHP image, it will persist as long as you only "stop" the docker container.

See difference between `docker-compose stop` and `docker-compose down`

**Comment by ultrablue** [comment]
Hi, @llaville  and @cytopia:

Thanks for the response. @llaville good points. However, I'm stuck with runkit7 from a legacy application.

@cytopia thanks for the tip. I have been using down. :/

**Comment by ultrablue** [comment]
If I wanted to modify Devilbox myself, how would I go about doing that?

Thanks again! Devilbox is the best.

**Comment by llaville** [comment]
Hello @ultrablue

I'm working on a new refactoring (again) of cytopia project https://github.com/devilbox/docker-php-fpm.

My first approach was to fixed some issues before cytopia finally fixed it in official version by my fork still available at https://github.com/llaville/docker-php-fpm/tree/software_enabled_refactoring
and added new extensions. https://github.com/devilbox/docker-php-fpm/issues/199

But I must admit that even if it's now easy for me (after a learning stage) to modify docker-php-pfm images, it could be not so easy for a beginner !

My new work is to simplify building of docker-php-fpm mods image that define and include PHP modules.
This work used the open source project https://github.com/mlocati/docker-php-extension-installer that have lof of PHP extensions supported https://github.com/mlocati/docker-php-extension-installer#supported-php-extensions

It's almost ready and I should present it later this week.

**Comment by ultrablue** [comment]
Hi, @llaville: 

Oh, cool, thanks.

I appreciate your efforts on this. If there's anything I can do to be of assistance, let me know.

Thanks!

**Comment by llaville** [comment]
@ultrablue review my new report https://github.com/devilbox/docker-php-fpm/issues/215 and give me your feedbacks are welcome

**Comment by llaville** [comment]
Instead of runkit7, @ultrablue consider to use https://pecl.php.net/package/uopz extension that come with a PHP 8 compatible release (7.0.0) since yesterday

**Comment by cytopia** [comment]
I have tried `uopz`, however some php and pecl commands were failing after it had been installed:
```
Build process completed successfully
Installing '/usr/local/lib/php/extensions/no-debug-non-zts-20200930/uopz.so'
install ok: channel://pecl.php.net/uopz-7.1.1
configuration option "php_ini" is not set to php.ini location
You should add "extension=uopz.so" to php.ini
+ docker-php-ext-enable uopz
+ true
Removing intermediate container 89b28eadd0a8
 ---> 1d03aabd59d6
Step 56/65 : RUN set -eux       && pecl install uploadprogress  && docker-php-ext-enable uploadprogress         && true
 ---> Running in bbbabcae7c74
+ pecl install uploadprogress
Segmentation fault (core dumped)
```

The only version I was able to install it without issues was PHP 8.1

**Comment by llaville** [comment]
@cytopia I've let down support for `uopz` extension, because I noticed like you that, side effects with others extensions. 
I do not recommend to add it.
