### ISSUE TITLE
Laravel missing when using PHP8

### ISSUE THREAD

**Issue by lokinz** [cytopia/devilbox#823]
Setting PHP level to 8.0 in the .env file pulls in `devilbox/php-fpm:8.0-work-0.127`

When I shell into the PHP container and try to run `laravel` I get the `bash: laravel: command not found` error.
This works fine on the 7.4 container. 

Other tools (like symfony) work fine.

**Comment by llaville** [comment]
@lokinz It works as expected with current definition https://github.com/devilbox/docker-php-fpm/blob/master/build/ansible/group_vars/all/work.yml#L556-L558 Laravel, Lumen installer are disabled on PHP 8.x

**Comment by Jarco** [comment]
I have the same issue with Drush. I can see it is disabled in 8.0 and 8.1 but I cannot find any documentation on how to enable it. ( I am not well versed in docker ). The documentation seems to assume it is just there.
Is there a way to enable these tools again? I imagine I am not the only person who stumbles upon this issue during a Google search.

**Comment by cytopia** [comment]
Added
