### ISSUE TITLE
Store database outside of container

### ISSUE THREAD

**Issue by folkevil** [cytopia/devilbox#824]
#### ISSUE TYPE

 - Feature request

#### SUMMARY

Sometimes Docker crashes and images/containers are deleted, so the database is also lost (mariadb, postgres), the local database backup is sometimes not done. So I propose to add a feature that allows data to be saved in an external folder.

#### Goal

No more lost databases.

**Comment by cytopia** [comment]
Persistent data is already stored outside of the container: https://github.com/cytopia/devilbox/blob/master/docker-compose.yml#L348

You'll loose data only, if you delete those docker volumes
