### ISSUE TITLE
Set custom date & time in docker php container via datefudge

### ISSUE THREAD

**Issue by guycalledseven** [cytopia/devilbox#827]
#### ISSUE TYPE

 - Feature request

#### SUMMARY
Sometimes in programming, one has a need to program stuff that will be executed in future. In order to test such software, usually computer's date & time had to be set in BIOS.

#### Goal
Now with Docker and containers changing BIOS time and restarting Docker is too complicated and there is much easier way by using [datefudge](http://manpages.ubuntu.com/manpages/trusty/man1/datefudge.1.html) utility.

#### Easy Solution

Add `datefudge` to php container image.

#### Full Solution

In order to test different time in php currently you have to:

1. create custom supervisord config and place it under `devilbox/supervisor/` on local file system:

```
[program:php-fpm]
command = /usr/bin/datefudge --static "Wed 06 Aug 2021 04:15:51 PM CEST" /usr/local/sbin/php-fpm
autostart               = true
autorestart             = true
stdout_logfile          = /dev/stdout
stdout_logfile_maxbytes = 0
stdout_events_enabled   = true
stderr_logfile          = /dev/stderr
stderr_logfile_maxbytes = 0
stderr_events_enabled   = true
```

2. remove php container, start php container so our custom conf ends up in `/etc/supervisor/custom.d` in php container.

3. when container is started, bash inside php container and install `datefudge`:

```
sudo apt update && sudo apt install datefudge
```

4. stop php container and start it (do not delete it, so you do not loose custom supervisord conf which adds datefudge while starting php-fpm).

Now php is fixed to see always Wed 06 Aug 2021 04:15:51 PM CEST 🥇 

#### Best Solution
Best solution would be to use `datefudge -f sometime.txt` so `sometime.txt` could be user editable file mounted from local filesystem. Eg. when container is created - if file exists - datefudge can be added to supervisord. Even maybe on dockerfile level

```
FROM devilbox/php-fpm:7.2-work-0.122
CMD ["datefudge" "-f" "/home/default/date.txt"]
```

edit: typos

**Comment by cytopia** [comment]
@guycalledseven thanks for the write-up. The feature will not be added explicitly to the docker images, as this would add up on complexity and I rather decrease the complexitiy. Also you've shown how easily this can already be accomplished with provided customization options :+1: 

I'm therefore closing this issue. The "Full Solution" should rather be something for the documentation
