### ISSUE TITLE
Allow another port for HOST_PORT_BIND

### ISSUE THREAD

**Issue by Ernestopheles** [cytopia/devilbox#831]
#### ISSUE TYPE

 - Allow another port for HOST_PORT_BIND

#### SUMMARY
Under Ubuntu 20 DNS service is by systemd_resolved, which will use port 53. No Chance to change this. So if I want AUTO DNS, the only way is to have a different port for it 

#### Goal
 AUTO DNS not working means manually editing /etc/hosts for each new project

**Comment by fkaminski** [comment]
Maybe:
https://github.com/cytopia/devilbox/issues/695
or
https://github.com/cytopia/devilbox/issues/225

**Comment by Ernestopheles** [comment]
I do not think both mentioned issues will provide a stable solution

**Comment by fkaminski** [comment]
Did you tried
https://github.com/cytopia/devilbox/issues/695#issuecomment-652330381 ?

**Comment by Ernestopheles** [comment]
No, as I do not want to change my systems internet connection configuration. I rather think we should find an alternative way to gain AUTO DNS, f.i. by allowing a different port (if possible)

**Comment by cytopia** [comment]
> by allowing a different port

@Ernestopheles 
You can already set any port you want in the `.env` file:

![Screenshot 2022-02-04 19-57-48  selection](https://user-images.githubusercontent.com/12533999/152587148-4a13603d-97ac-423c-be60-d6c912452dc5.png)

**Comment by Ernestopheles** [comment]
With devilbox 3 this PR is obsolete now. Thanks @cytopia
