### ISSUE TITLE
make it possible to specify the required nodeJs version

### ISSUE THREAD

**Issue by dgoosens** [cytopia/devilbox#833]
#### ISSUE TYPE

 - Feature request

#### SUMMARY

Add a param (.env, docker-compose.yml) to specify the NodeJs version that is required for the project.

#### Goal

Devilbox uses NVM to install node...  
Right now, it installs the latest version by default.  
This may not always be possible when, for instance, the production environment is running a specific version.

It would be nice if it were possible to add a param to the devilbox configuration to set the required NodeJs version that is to be installed...  
Default should probably be "latest"

**Comment by Lenitr** [comment]
This would be great, not just to match production environments (we have some control over that) but also to match other people/colleagues using devilbox since their node versions are also automatic (based on the time of install)

**Comment by cytopia** [comment]
@dgoosens @Lenitr automatically changing the node version during startup (by installing from the internet)  is not a good idea to enable by default. This would then result in always requiring an active internet connection for starting Devilbox and people should still be able to use it offline.

You already have all the tools to change it yourself to any desired version:
```shell
# Jump into the Devilbox
host> ./shell.sh

# Now as devilbox user simply type:
devilbox> nvm install 10
devilbox> nvm use 10
```

**Comment by timo002** [comment]
> You already have all the tools to change it yourself to any desired version:
> 
> ```shell
> # Jump into the Devilbox
> host> ./shell.sh
> 
> # Now as devilbox user simply type:
> devilbox> nvm install 10
> devilbox> nvm use 10
> ```
When doing so, after a `docker-compose down` and `docker-compose up -d`, node is back to the default installed version (17.x currently). How to make this persistant.

**Comment by Lenitr** [comment]
> > You already have all the tools to change it yourself to any desired version:
> > ```shell
> > # Jump into the Devilbox
> > host> ./shell.sh
> > 
> > # Now as devilbox user simply type:
> > devilbox> nvm install 10
> > devilbox> nvm use 10
> > ```
> 
> When doing so, after a `docker-compose down` and `docker-compose up -d`, node is back to the default installed version (17.x currently). How to make this persistant.

This is exactly the issue i had when changing the node version manually as well. I guess the way to do it would be to add the nvm install and nvm use commands to the startup script (perhaps not the most elegant solution but it should work)
