### ISSUE TITLE
Add support for Meilisearch

### ISSUE THREAD

**Issue by folkevil** [cytopia/devilbox#847]
#### ISSUE TYPE

 - Feature request

#### SUMMARY
Add support for Meilisearch on default setting

**Comment by cytopia** [comment]
@folkevil can you add some details on what the requirements/settings would be to support it "on default settings"

**Comment by minhchu** [comment]
Hi @cytopia I think the default installation of meilisearch is enough.

Or is there any guidance for adding meilisearch to devilbox so I can open a PR

**Comment by cytopia** [comment]
> Or is there any guidance for adding meilisearch to devilbox so I can open a PR

Nothing in written form as of yet, but generally you will need to address three parts:

* You can add the compose overwrite file here: https://github.com/cytopia/devilbox/tree/master/compose
* Append the contents to the "all" file as well: https://github.com/cytopia/devilbox/blob/master/compose/docker-compose.override.yml-all
* Add the appropriate documentation here: https://github.com/cytopia/devilbox/tree/master/docs/custom-container

**Comment by cytopia** [comment]
Was merged in: https://github.com/cytopia/devilbox/pull/910
