### ISSUE TITLE
Update PHP 8.0 container to latest version

### ISSUE THREAD

**Issue by ericp-mrel** [cytopia/devilbox#853]
Any chance we can get an updated image for PHP 8.0?

It is currently stuck at 8.0.7, and the latest is [8.0.13](https://www.php.net/ChangeLog-8.php#8.0.13). It also looks like the image that gets pulled down was last built 5 months ago.

```
devilbox/php-fpm                   8.0-work-0.127     549abc72a14c   5 months ago    2.94GB
```

**Comment by llaville** [comment]
Id you want a compatible version 8.0 with latest release available, consider to have a look on my project : https://github.com/llaville/docker-php-toolbox.
A new docker image with PHP 8.1 will also be available in next hours.

**Comment by llaville** [comment]
After 4 months to work on this project, I'm proud to announce a final version https://github.com/llaville/docker-php-toolbox/releases/tag/1.0.0, Devilbox architecture compatible, for all users who want an alternative to Docker images outdated.

**Comment by alikon** [comment]
What does it mean that this project will never receive updates on docker php images ?

**Comment by llaville** [comment]
@alikon I can't speak in place of @cytopia. I just would like announce that an alternative that work pretty fine with the devilbox is available. You have choice to build your own image (with extensions and tools) without to wait
