### ISSUE TITLE
Add sqlite3 to php container

### ISSUE THREAD

**Issue by onasipim** [cytopia/devilbox#856]

**Comment by cytopia** [comment]
`pdo_sqlite` and `sqlite3` are available, see here: https://github.com/cytopia/devilbox#available-php-modules

**Comment by onasipim** [comment]
I meant the cmd line tool for the shell, not the php lib. You have all major sql engines covered, so sqlite would be nice addition

**Comment by llaville** [comment]
I suggest https://sqlitebrowser.org/ that I used myself since a long time now and appreciate a lot

**Comment by cytopia** [comment]
Added
