### ISSUE TITLE
Couldn't create the ssl-cache mutex

### ISSUE THREAD

**Issue by acoalex** [cytopia/devilbox#862]
### ISSUE TYPE

 - Bug Report

### Checklist

* [x] `.env` file is attached
* [x] `./check-config.sh` output is added below
* [x] `docker-compose logs` output is added below
* [x] `docker-compose.override.yml` is attached (if exists)
* [x] Custom configs from `cfg/` dir are attached (if exist)
* [x] I've looked through the docs: https://devilbox.readthedocs.io/en/latest/
* [x] I've looked through existing issues: https://github.com/cytopia/devilbox/issues
* [x] I've read troubleshooting: https://devilbox.readthedocs.io/en/latest/support/troubleshooting.html

### OS / ENVIRONMENT

1. Host operating system and version: Macos 12.2
2. (Macos 12.2 only) Docker Desktop for M1:
3. Docker version: 4.4.2
4. Docker Compose version: 2.2.3
5. (Linux) Is SELinux enabled?: 
6. What git commit hash are you on?: 9272bfec922589ba7783a2bd8c81befd12ce55f4

### SUMMARY

After pulling last changes from repository httpd service doesnt start and display this error message:
devilbox-httpd-1  | [Mon Jan 31 15:43:10.749810 2022] [core:emerg] [pid 2222:tid 274907404160] (95)Operation not supported: AH00023: Couldn't create the ssl-cache mutex
devilbox-httpd-1  | AH00016: Configuration Failed 

Minutes before i was developing normally but after upgrading devilbox repository that error appears

### STEPS TO REPRODUCE
 1- Pull last repository commits
2- docker-compose up httpd mysql php

### EXPECTED BEHAVIOUR
Can access to web site

### ACTUAL BEHAVIOUR
httpd service is down

**Comment by acoalex** [comment]
Switching to v1.9.2 tag work perfectly.
Thanks

**Comment by cytopia** [comment]
> * [x]  `.env` file is attached
> * [x]  `./check-config.sh` output is added below
> * [x]  `docker-compose logs` output is added below

These checkboxes should actually only be ticked, if their criteria is fulfilled. Let me know if this is unclear and how I can better formulate this to make it more clear.

When checking google for `AH00023: Couldn't create the ssl-cache mutex` it tells me that "_semaphores are running short on count / space"_. Not sure If this is a host issue, or an issue on the Apache container:
* https://serverfault.com/questions/991946/no-space-left-on-device-ah00023-couldnt-create-the-mpm-accept-mutex-when-re
* https://webake.ro/2018/04/26/fix-ssl-cache-mutex-issue-centos/

**Comment by acoalex** [comment]
Thanks @cytopia , sorry for that checks, my fault.
I think that should be a problem with apache container, on host i have enought space:

overlay         61255492  32678616  25435552  57% /
tmpfs              65536         0     65536   0% /dev
shm                65536         0     65536   0% /dev/shm
grpcfuse       971350180 179114772 792235408  19% /ca
/dev/vda1       61255492  32678616  25435552  57% /var/mail
tmpfs            4063132         0   4063132   0% /sys/firmware

Only switching to tag 1.9.2 all works perfect, i will try to checkout again to master and change httpd image to 0.36 to determine if that is the problem.
Thanks again for your effort

**Comment by acoalex** [comment]
> Here is another one which might indicate an issue with M1: [webdevops/Dockerfile#433](https://github.com/webdevops/Dockerfile/issues/433)

I try with a 2019 Macbook pro with intel processor and works correctly, so its clearly M1 processor fail.
Thanks

**Comment by cytopia** [comment]
@acoalex can you give the upcoming release a try. Had an explicit fix for the ssl-cache mutex on Apache: https://github.com/cytopia/devilbox/pull/865

**Comment by acoalex** [comment]
@cytopia Yes, give me a while and i will try again.
Thanks a lot.

**Comment by acoalex** [comment]
@cytopia Hi!! I have make a pull request to repository and launch again docker but the same errors appears:

devilbox-httpd-1  | [Tue Feb 15 12:48:20.479133 2022] [core:emerg] [pid 5685:tid 274907404160] (95)Operation not supported: AH00023: Couldn't create the ssl-cache mutex
devilbox-httpd-1  | AH00016: Configuration Failed

Thanks

**Comment by cytopia** [comment]
> I have make a pull request to repository and launch again docker...

Not sure what this means. Did you checkout branch `release/v1.10.4` ?

**Comment by cytopia** [comment]
It is not merged yet, as the PR is stull open. You need to try it by checking out the above specified branch

**Comment by acoalex** [comment]
@cytopia Its Works!!! Thanks a lot.

**Comment by henriquemattos** [comment]
@cytopia given your commit, it's not clear what you did to fix Mutex SSL. Is there a specific configuration/setting you modified either in a Dockerfile or [httpd|apache|*].conf that you could share?

I'm not using your software, but I'm having similar problem on M1 and setting `Mutex posixsem` stops the error from the log but I keep loosing requests - and given the frequency and timing, I believe it's related to SSL.

Thanks in advance,
Henrique
