### ISSUE TITLE
Update Homepage with Complete Support Versions List

### ISSUE THREAD

**Issue by mah484** [cytopia/devilbox#873]
This is just a suggestion to update what I believe is the [official marketing website](http://devilbox.org/) with newer supported versions.  For example PHP is only listed up to 7.3 at the moment.

**Comment by jonatanaxe** [comment]
fixed http://devilbox.org/

**Comment by cytopia** [comment]
Thanks for the PR @jonatanaxe https://github.com/devilbox/devilbox.org/pull/13

@mah484 Closing
