### ISSUE TITLE
Available Tools : Add Vercel, Netlify and GitHub CLI to Devilbox

### ISSUE THREAD

**Issue by robots4life** [cytopia/devilbox#876]
Would it be possible to have the Vercel, Netlify and GitHub CLI as available tools in the Devilbox ?
https://vercel.com/docs/cli
https://cli.netlify.com/
https://cli.github.com/

**Comment by robots4life** [comment]
https://devilbox.readthedocs.io/en/latest/autostart/custom-scripts-globally.html#custom-scripts-globally

In `/devilbox/autostart` I have created a file `clis.sh` with following content.

```shell
#! /usr/bin/env bash

# run this script
# chmod +x clis.sh
# ./clis.sh

npm i -g vercel

npm install netlify-cli -g
```

**Remember to `chmod +x clis.sh` inside `/devilbox/autostart` so the script can be executed.**
This will install Vercel and Netlify CLI globally in Devilbox and persist the installation as long as the `clis.sh` fils is kept inside `/devilbox/autostart`.

Per docs, i.e. 
```shell
# Install grunt as devilbox user
# su -c "npm install grunt" -l devilbox
```
asks for a password that I don't know and that is not the host password.

**But the CLIs are installed as the `devilbox` user since in `devcontainer.json` I have the line `"remoteUser": "devilbox",`.**

https://github.com/cli/cli/blob/trunk/docs/install_linux.md

The GitHub CLI has a different approach to install and since `git` is pretty much the only tool I have on the host I am happy installing the GitHub CLI on the host as well.

Now this is one way of doing it, if this is the Devilbox preferred way to do this then @cytopia kindly go ahead and close this issue, thank you. Otherwise I am curious to see if these tools will be added directly to the Devilbox.

**Comment by cytopia** [comment]
> ```shell
> # Install grunt as devilbox user
> # su -c "npm install grunt" -l devilbox
> ```

Use `sudo` instead of `su`. Sudo will not ask for a password

**Comment by cytopia** [comment]
@robots4life not sure if this has worked out for you or not. There is however a new way available since the `v2.2.0` release.

You can now create your own custom set of PHP-FPM flavours via this repository: https://github.com/devilbox/docker-php-fpm-community/

This would allow you to add whatever tools you need and even have it integrated via CI, so it will also build nightly.
These images can then be integrated into the Devilbox as such: https://devilbox.readthedocs.io/en/latest/custom-container/enable-php-community.html

**Comment by robots4life** [comment]
@cytopia Having a simple bash script in the `/devilbox/autostart` folder has worked out for me, thank you.

However I am also taking due note of the new custom PHP-FPM community flavors option and will try to use this use case to create an image that has Vercel and Netlify included as a starter. In this issue I will post the steps taken and likewise also happy to contribute with possibly further documentation or an example use case to Devilbox.

Fully with you wanting to keep the official images rather small.

**Comment by cytopia** [comment]
> @cytopia Having a simple bash script in the `/devilbox/autostart` folder has worked out for me, thank you.

Perfect! I will close this issue then :-)
