### ISSUE TITLE
How could we use default plugin on elasticsearch dockerimage

### ISSUE THREAD

**Issue by hielh** [cytopia/devilbox#882]
#### ISSUE TYPE

 - Question

#### SUMMARY

My need is to install somes plugins in elasticsearch image by default, 

RUN elasticsearch-plugin install analysis-icu
RUN elasticsearch-plugin install analysis-phonetic

How can I use devilbox to use by default thoses plugin.

**Comment by hielh** [comment]
@cytopia any help please

**Comment by jonatanaxe** [comment]
@hielh  A way I found to install and use a sh and change the

docker-compose.override.yml

/sh/docker-entrypoint-es.sh

```
#!/bin/sh
# setting up prerequisites

bin/elasticsearch-plugin install analysis-phonetic
bin/elasticsearch-plugin install analysis-icu

exec /usr/local/bin/docker-entrypoint.sh elasticsearch
```

docker-compose.override.yml
```
volumes:
      - devilbox-elastic:/usr/share/elasticsearch/data;
      - ./sh/docker-entrypoint-es.sh:/usr/share/elasticsearch/docker-entrypoint-es.sh
    entrypoint: /usr/share/elasticsearch/docker-entrypoint-es.sh
```

**Comment by cytopia** [comment]
@hielh closing this issue as it's been resolved. @jonatanaxe thanks for helping out here!
