### ISSUE TITLE
pdo_sqlsrv version update[Feature]: 

### ISSUE THREAD

**Issue by acoalex** [cytopia/devilbox#899]
### What is your idea or feature suggestion?

For Mac M1 users the provided version of pdo_sqlsrv 5.9 is not compatible with the M1 processor.
Using that driver throws an Unknown processor architecture Fatal error:
https://github.com/microsoft/msphpsql/issues/1223

I think in the new 5.10 version was solved.

### Benefits

Can use pdo_sqlsrv driver on Devilbox php container

### Where can we find information about this?

https://github.com/microsoft/msphpsql/issues/1223
https://github.com/microsoft/msphpsql/tree/v5.10.0

**Comment by cytopia** [comment]
PHP 7.4 and later will have updated versions available as soon as this one goes live: https://github.com/devilbox/docker-php-fpm/pull/249

**Comment by acoalex** [comment]
Great!!
Thanks @cytopia
