### ISSUE TITLE
[Feature]: phalcon 5 RC4 in php-8.x

### ISSUE THREAD

**Issue by casparjones** [cytopia/devilbox#913]
### What is your idea or feature suggestion?

Would it be possible to include in the php8 images phalcon in RC version? Since I would like to migrate my projects to PHP 8.

https://blog.phalcon.io/post/phalcon-v5-0-0rc4-released

**Comment by casparjones** [comment]
In the meantime version Phalcon 5.1.1 has been released.
Are there any plans to include this in the standard images of devilbox?

**Comment by cytopia** [comment]
@casparjones coming here: https://github.com/devilbox/docker-php-fpm/pull/249
