### ISSUE TITLE
[Feature]: Is it possible to add nvm to available tools in PHP container (https://devilbox.readthedocs.io/en/latest/readings/available-tools.html#available-tools)?

### ISSUE THREAD

**Issue by rozkqu** [cytopia/devilbox#914]
### What is your idea or feature suggestion?

E.g. i can write simple script to set up node version during PHP container initial startup (and put it in autostart/ dir).

### Benefits

Better automation possibilities for developers.

**Comment by cytopia** [comment]
The `nvm` binary is already available
