### ISSUE TITLE
[Howto]: Communicate between 2 projects from php container

### ISSUE THREAD

**Issue by TheoD02** [cytopia/devilbox#915]
### Have you already checked elsewhere?

- [X] I have read the [Devilbox documentation](https://devilbox.readthedocs.io/en/latest/)
- [X] I have checked the [Devilbox Troubleshooting Guide](https://devilbox.readthedocs.io/en/latest/)
- [X] I have checked the [Devilbox FAQ](https://devilbox.readthedocs.io/en/latest/support/faq.html)
- [X] I have checked the [Devilbox Howto](https://devilbox.readthedocs.io/en/latest/support/howto.html)
- [X] I have checked the [Devilbox Forum](https://devilbox.discourse.group/)
- [X] I have checked [existing issues](https://github.com/cytopia/devilbox/issues)
- [X] I have googled already with no luck
- [ ] I have not done any of the above

### What are you struggling with?

Hello,

My problem is related to the connection of 2 projects that must communicate with each other.

2 projects are reachable from host, but not from container

### What is your goal?

I would like to make 2 projects communicate with each other,

So I have my project folder which contains my project A & B.

My project A needs to call the api of project B to get information.

I use the guzzle client in project A so I call the api with the following url as I would in postman for example "b.loc/api/endpoint" this works fine on the postman side, but how do I do it in the container?

Currently, it returns me the "localhost" dashboard page of devilbox

**Comment by cytopia** [comment]
This should work by default. Is `bind` running? Also, can you do a curl at both of your API's from within the PHP container.

**Comment by cytopia** [comment]
> Calling my API from PHP ⇒ return devilbox dashboard

Can you share the code snippet that is calling the API

**Comment by cytopia** [comment]
@TheoD02 
This works perfectly fine from inside the container. I assume that this has been resolved as the requested information has not been provided.
