### ISSUE TITLE
[Howto]: How can i run multiple projects with different configuration?

### ISSUE THREAD

**Issue by wcaaan** [cytopia/devilbox#918]
### Have you already checked elsewhere?

- [X] I have read the [Devilbox documentation](https://devilbox.readthedocs.io/en/latest/)
- [X] I have checked the [Devilbox Troubleshooting Guide](https://devilbox.readthedocs.io/en/latest/)
- [X] I have checked the [Devilbox FAQ](https://devilbox.readthedocs.io/en/latest/support/faq.html)
- [X] I have checked the [Devilbox Howto](https://devilbox.readthedocs.io/en/latest/support/howto.html)
- [X] I have checked the [Devilbox Forum](https://devilbox.discourse.group/)
- [X] I have checked [existing issues](https://github.com/cytopia/devilbox/issues)
- [X] I have googled already with no luck
- [ ] I have not done any of the above

### What are you struggling with?

How can i run multiple projects with different configuration. if all the project are under ./data/www they will be under same php, mysql and other services. how do i seperate the .env file for each project.

for example:

project 1
php 5.6
mysql 5.5
apache 2.2

project 2:
php 7.4
mysql 5.7
apache 2.4

project 3:
php 8.1
mariadb 10.7
apache 2.4

### What have you tried already?

I have tried to setup multiple devilboxes, but it won't work, becuase i have to take down the first one in order run the second one.

### What is your goal?

I don't want to setup devilbox for each project (which does not work anyway). I want to keep all projects in one directory and apply different .env settings on each project or group of projects.

**Comment by cytopia** [comment]
@wcaaan this is currently not possible. See this open issue here: https://github.com/cytopia/devilbox/issues/146

**Comment by cytopia** [comment]
@wcaaan you can at least now run different PHP versions per project #942
