### ISSUE TITLE
[Howto]: How to create SSH keys in /home/devlibox/.ssh since it is mounted as read-only?

### ISSUE THREAD

**Issue by sachyya** [cytopia/devilbox#933]
### Have you already checked elsewhere?

- [X] I have read the [Devilbox documentation](https://devilbox.readthedocs.io/en/latest/)
- [X] I have checked the [Devilbox Troubleshooting Guide](https://devilbox.readthedocs.io/en/latest/)
- [X] I have checked the [Devilbox FAQ](https://devilbox.readthedocs.io/en/latest/support/faq.html)
- [X] I have checked the [Devilbox Howto](https://devilbox.readthedocs.io/en/latest/support/howto.html)
- [X] I have checked the [Devilbox Forum](https://devilbox.discourse.group/)
- [X] I have checked [existing issues](https://github.com/cytopia/devilbox/issues)
- [ ] I have googled already with no luck
- [X] I have not done any of the above

### What are you struggling with?

I am trying to create new SSH keys to use on Github but ssh-keygen command says that the .ssh folder is read only. Should I create another folder for the keys or change path for keys in .env file?  Any help would appreciated.

### What have you tried already?

I have tried remounting as read-write but it does not seem to be logical since in the comment it says it's for safety.

### What is your goal?

Creating the ssh keys in the /home/devilbox/.ssh

**Comment by sachyya** [comment]
I found the solution but please let me know if it's the right one. I added the devilbox user to sudo group and it worked. Is that the right way to go?

**Comment by cytopia** [comment]
@sachyya you added the devilbox user to the sudo group and kept the `.ssh` dir mounted read-only? That should still not work

**Comment by cytopia** [comment]
I would suggest to generate your ssh key outside (on your host system). It is anyways mounted and can then be used inside. Having it mounted read-only is only a precaution that you do not accidentally overwrite your ssh keys inside the container
