### ISSUE TITLE
[Feature]: Add taskfile

### ISSUE THREAD

**Issue by TheoD02** [cytopia/devilbox#934]
### What is your idea or feature suggestion?

Hi everyone! :)

I use https://taskfile.dev/ in my projects as a replacement for make, would it be possible to integrate it ?

A big thank you for the work!

### Where can we find information about this?

https://taskfile.dev/

**Comment by cytopia** [comment]
@TheoD02 it is on the way

**Comment by cytopia** [comment]
@TheoD02 Available here: https://github.com/cytopia/devilbox/releases/tag/v2.4.0
