### ISSUE TITLE
[Howto]: Install wkhtmltopdf on Apple M1

### ISSUE THREAD

**Issue by chieroz** [cytopia/devilbox#936]
### Have you already checked elsewhere?

- [X] I have read the [Devilbox documentation](https://devilbox.readthedocs.io/en/latest/)
- [X] I have checked the [Devilbox Troubleshooting Guide](https://devilbox.readthedocs.io/en/latest/)
- [X] I have checked the [Devilbox FAQ](https://devilbox.readthedocs.io/en/latest/support/faq.html)
- [X] I have checked the [Devilbox Howto](https://devilbox.readthedocs.io/en/latest/support/howto.html)
- [X] I have checked the [Devilbox Forum](https://devilbox.discourse.group/)
- [X] I have checked [existing issues](https://github.com/cytopia/devilbox/issues)
- [X] I have googled already with no luck
- [ ] I have not done any of the above

### What are you struggling with?

I cannot find a way to install wkhtmltopdf on my MacBook Pro with M1 chip. Everything was fine on my old Intel machine.

### What have you tried already?

I tried this:

```
wget https://github.com/wkhtmltopdf/packaging/releases/download/0.12.6.1-2/wkhtmltox_0.12.6.1-2.bullseye_arm64.deb
sudo dpkg -i wkhtmltox_0.12.6.1-2.bullseye_arm64.deb
```

but I got this error:

```
dpkg: dependency problems prevent configuration of wkhtmltox:
 wkhtmltox depends on xfonts-75dpi; however:
  Package xfonts-75dpi is not installed.
 wkhtmltox depends on xfonts-base; however:
  Package xfonts-base is not installed.

dpkg: error processing package wkhtmltox (--install):
 dependency problems - leaving unconfigured
Errors were encountered while processing:
 wkhtmltox
```

I tried with different packages but with no success.

Thank you for you help.

### What is your goal?

I want to use wkhtmltopdf with Snappy

**Comment by chieroz** [comment]
Update: apparently in the new arm64 php images wkhtmltopdf is missing.
I temporarily turned back to the amd64 image and I opened an issue.

**Comment by cytopia** [comment]
@chieroz it is on the way.

**Comment by cytopia** [comment]
@chieroz Available here: https://github.com/cytopia/devilbox/releases/tag/v2.4.0
