### ISSUE TITLE
PHP container exits on certain `NEW_GID` setting in `.env`

### ISSUE THREAD

**Issue by ims-one** [cytopia/devilbox#96]
Hi,

i installed devilbox on arch linux and i become the following error:

`nginx: [emerg] host not found in upstream "php" in /etc/nginx-mainline/01-vhost-default.conf:59`

docker --version
Docker version 17.05.0-ce, build 89658bed64

docker-compose --version
docker-compose version 1.14.0, build unknown

The localhost show just a 502 Bad Gateway.

Can you help?

**Comment by ims-one** [comment]
Ok, i give it up now after 2 days.
PHP container dont start on Arch.
Devilbox dont run on Arch.

Thanks

**Comment by ims-one** [comment]
`docker ps
CONTAINER ID        IMAGE                           COMMAND                  CREATED             STATUS                          PORTS                                            NAMES
03cd8f950acc        cytopia/mariadb-10.3:latest     "/docker-entrypoin..."   5 minutes ago       Up 5 minutes                    127.0.0.1:3306->3306/tcp                         devilbox_mysql_1
ac9af6b7d429        mongo:3.4                       "docker-entrypoint..."   5 minutes ago       Up 5 minutes                    127.0.0.1:27017->27017/tcp                       devilbox_mongo_1
257aedc5899c        postgres:9.6                    "docker-entrypoint..."   5 minutes ago       Up 5 minutes                    127.0.0.1:5432->5432/tcp                         devilbox_pgsql_1
1a391818d1fd        redis:3.2                       "docker-entrypoint..."   5 minutes ago       Up 5 minutes                    127.0.0.1:6379->6379/tcp                         devilbox_redis_1
bdc34008afe5        memcached:latest                "docker-entrypoint..."   5 minutes ago       Up 5 minutes                    127.0.0.1:11211->11211/tcp                       devilbox_memcd_1
cac4e94c1976        cytopia/nginx-mainline:latest   "/docker-entrypoin..."   5 minutes ago       Up 5 minutes                    127.0.0.1:85->80/tcp                             devilbox_httpd_1
efc14ca5ddc9        cytopia/php-fpm-7.0:latest      "/docker-entrypoin..."   5 minutes ago       Restarting (4) 42 seconds ago                                                    devilbox_php_1
d9eef188a8d9        cytopia/bind:latest             "/docker-entrypoin..."   5 minutes ago       Up 5 minutes                    127.0.0.1:1053->53/tcp, 127.0.0.1:1053->53/udp   devilbox_bind_1
`

php is restarting all the time.

**Comment by ims-one** [comment]
change back from 
`
NEW_UID=1000
NEW_GID=100
`
to
`
NEW_UID=1000
NEW_GID=1000
`

and all is up and running :o)

**Comment by cytopia** [comment]
@ims-one sorry for the late reply. Its good that everything works.

Was there any readon for having `NEW_GID` set to `100`? If that is still desired I will probably have to look into this issue.

**Comment by ims-one** [comment]
yes. if i type **id** in my console:

`uid=1000(xxx) gid=100(users) Gruppen=100(users),10(wheel),996(docker)`

**Comment by cytopia** [comment]
Ok I'll keep the ticket open and try to reproduce the error

**Comment by cytopia** [comment]
The PHP container does not properly start up when `gid` is set to `100`. This is the case as there is already a group present in the container occupying this id. The corresponding group is called `users`.

I will have to modify all php container and get rid of that group.

**Comment by cytopia** [comment]
First fix for PHP 7.0 is on its way:

https://github.com/cytopia/docker-php-fpm-7.0/pull/22

**Comment by cytopia** [comment]
I have fixed all php/hhvm docker container. You can use `update-docker.sh` to pull new images.

**Comment by tracyfloyd** [comment]
Works great now. Thanks!
