### ISSUE TITLE
Devilbox UI footer overlaps embedded tools

### ISSUE THREAD

**Issue by ilsenem** [cytopia/devilbox#97]
- Devilbox: 0.11
- OS: Ubuntu 16.04
- docker: 17.06.0-ce
- docker-compose1.13.0

**Adminer** (and maybe other embedded tools) overlapped by footer. Unable to see table list or controls for pagination and additional command on bottom.

![Screenshot](https://dl.dropboxusercontent.com/1/view/ghd10q7xj2y2vii/Apps/Shutter/Selection_003.png)

**Comment by cytopia** [comment]
@ilsenem as this is a browser issue, could you please provide your browser name and version.

**Comment by ilsenem** [comment]
Chrome and FF latest versions - 100%. IE and Safari - unable to test.

This issue appears only on **Adminer** as far as i can see.

**Comment by cytopia** [comment]
@ilsenem could you check out branch `DVL-012` and see if it is working as expected.

**Comment by ilsenem** [comment]
![Nope](https://dl.dropboxusercontent.com/1/view/fip4t776rw1reph/Apps/Shutter/Selection_004.png)

Nope, still there. =(

Maybe there is a good solution to just open **Adminer** in new tab outside of **Devilbox** UI like you do with **phpMyAdmin**?

**Comment by cytopia** [comment]
Sorry, ticket got auto-closed by merging the PR.
The above merged PR introduced some minor enhancements, but does not yet fully resolve the issue.
I will probably go with your solution to separate Adminer from the devilbox intranet.
