### ISSUE TITLE
[Bug]: Laravel with Vite

### ISSUE THREAD

**Issue by masiorama** [cytopia/devilbox#972]
### Have you already looked into this bug?

- [X] I have checked the [Troubleshooting Guide](https://devilbox.readthedocs.io/en/latest/support/troubleshooting.html)
- [X] I have checked [Release notes](https://github.com/cytopia/devilbox/releases) for potential migration steps
- [X] I have checked [existing issues](https://github.com/cytopia/devilbox/issues) for similar bugs
- [X] I have googled this bug already with no luck
- [ ] I have not done any of the above

### (Optional) Error message

404 for all assets built with vite with 

### What went wrong?

Hello @cytopia, hope you are doing fine.
Since Laravel 9 the new default assets package builder is vitejs (in place of laravel mix).
As far as I know now devilbox is not able to make vite works as it should.

I tried on a fresh laravel 10 installation but I cannot make it work with `npm run dev`.
I have to stress that instead `npm run build`, which actually build the assets in public folder does work, so the only problem is on the vite dev script.

Once I run it, vite builds a localhost url with this a specific port: `http://localhost:5173/` which cannot be reached by devilbox.
I can reach the domain.loc registered on the file hosts, but the result is the welcome page but with all assets 404
![viteerrors](https://user-images.githubusercontent.com/731916/224261615-2d2bff9a-f6f5-47ef-9aea-48930fbbf0bd.jpg)

I tried with many different vite configurations but no luck.

Has anyone been able to make this work?

laravel vite docs: https://laravel.com/docs/10.x/vite
vite docs: https://vitejs.dev/config/

### Expected behaviour

It should be possibile to `npm run dev` the project without errors.
`npm run build` instead works as it should.

### How can we reproduce the bug?

1. Enter PHP 8.1 container (I run Devilbox on WSL 2)
2. Install new laravel 10 project  `laravel new laravel-project`
3. add the laravel-project.loc to hosts and to laravel .env APP_URL
4. install package dependencies: `npm install`
5. apply inside the header tag of the `resources\views\welcome.blade.php` file this vite directive: `@vite(['resources/css/app.css', 'resources/js/app.js'])` and comment out tailwindcss style tag
6. customize app.css with something like `body {    background-color: red;    }`
7. in the shell run `npm run dev`
8. visit the laravel-project.loc: all assets 404
9. in the shell run `npm run build`
10. visit the laravel-project.loc: all assets works (red background with huge laravel icon)

### Host Operating System

Linux

### Host Platform (amd64, arm64, other)

amd64

### (Linux only) Is SELinux enabled?

I don't know

### Docker version

Docker version 23.0.1, build a5ee5b1

### Docker Compose version

docker-compose version 1.29.2, build 5becea4c

### Devilbox version

Devilbox v2.4.0 (2022-12-18) and 3.0.0-beta-0.3

### Have you removed stopped containers before starting?

Yes

### Have you pulled latest Docker images before starting?

No

### Devilbox start command

docker-compose up mysql

### Config: .env file

```shell
Not related.
```

### Config: ./check-config.sh

```shell
Not related.
```

### Log: docker-compose logs

```shell
Not related.
```

**Comment by masiorama** [comment]
@robots4life I read on #797 you had luck with svelte. Do you have any suggestions? Thanks!

**Comment by robots4life** [comment]
@masiorama 

I have ` Devilbox v3.0.0-beta-0.3 (2023-01-02) `, assuming that is the latest version. You can see he version number by just going to `https://localhost/`, it is shown there in the top left corner of the page. Perhaps try to update Devilbox to the latest version first.

Then at the root of the project, inside the `.devilbox` folder I have the `backend.cfg` file with `conf:rproxy:ws:php:3000` or `conf:rproxy:http:php:3000`. This works with Svelte, yes. However Svelte and Kit run on Vite, so I assume using something else that is based on Vite should/could work as well.

Given https://laravel.com/docs/10.x/vite#configuring-vite and  https://laravel.com/docs/10.x/vite#working-with-a-secure-development-server I would assume perhaps something of this sort could work with Laravel in the Vite config, though I have not tested this.

```js
...
    server: {
        host: '0.0.0.0',
        port: 3000,
        strictPort: true,
        hmr: {
            clientPort: 443
        }
    },
...
```

I would first try to update to the latest version of Devilbox and use the `backend.cfg` file inside the `.devilbox` folder and see what happens. IF this does not work then try adjusting the Vite config with above example. Hope you will manage. :crossed_fingers: 

I don't use Laravel but might find time to play around with it and see if I can get it running with Devilbox, this is going to take some time though. Comes to mind, have you checked the Vite Discord, if they have any, perhaps someone there can help you. Devilbox also has a Discord, perhaps someone there knows more.

**Comment by masiorama** [comment]
Hello @robots4life thanks for you answer, I will check what you suggested and report my discoverings here.

**Comment by robots4life** [comment]
@masiorama yes, please do, curious about this, thank you. :smiley:

**Comment by masiorama** [comment]
@robots4life 
I upgraded to devilbox 3.0.0-beta-0.3 without issues.
I don't get the backend.cfg part and its role in the configuration, but I tried alternatively the 2 file contents you suggested (with no luck).
I played a bit with the vite configuration (your suggestion and other combinations from the config), but still no luck so far.

**Comment by masiorama** [comment]
@cytopia do you have any suggestions in here? I'm kinda stuck at this point, unable to upgrade to vite which is the default from laravel 9. Thanks in advance.

**Comment by MirkoFarina** [comment]
@cytopia  I'm in the same situation of @masiorama

**Comment by C4pt4inM** [comment]
I want to add a comment about a work around 
`npm run dev` would run vite which will eventually throw error which OP mentioned. but what I tried  is to run `npm run build` which then builds the assets in public folder. this is not a feasible way for devs because hmr helps alot.

**Comment by vikas5914** [comment]
@C4pt4inM, you can do that. However, you need to use Devilbox V3, 

1) Create a new host with following proxy settings: 

![image](https://github.com/cytopia/devilbox/assets/7912297/d609427a-841b-4834-a0a8-48d8f5447497)

2) Use the following config for the Vite server. Note: Update to `laravel-mix-hot.wip` with the host created in the above step. 

![image](https://github.com/cytopia/devilbox/assets/7912297/0353308d-51bb-46eb-8e66-59cddea2c499)

**Comment by C4pt4inM** [comment]
> 

@vikas5914  I already saw that but I dont have any `.devilbox` folder anywhere. can you please guide where the folder is and what `laravel-mix-hot.wip` is?

**Comment by vikas5914** [comment]
@C4pt4inM To make the Vite HMR work, run it on a different URL. For example, lets your project run on `example. local (local is Devilbox TLD_SUFFIX). You need to run the HMR on some other URL like `hmr. local` . I use `wip` as Devilbox, so the `laravel-mix-hot.wip` it just a different nginx vhost. 

You need to be on that Devilbox V3 beta, and create a new folder in your `www` folder called `hmr`. Inside that `hmr` folder, create a folder `.devilbox `.  Now cd into that  `.devilbox` folder and create a file called `backend.cfg` and copy the content that I gave in the original comment. 

Now use that `host` in the vite config, and you are good to go.

**Comment by C4pt4inM** [comment]
@vikas5914  thanks a lot. Although I had to make some changes as  I am not using HTTPS . here I am listing easy steps extracted from your comment  for anyone having less experience like me , to make Vite work. 
1. Create a folder in `<devilbox root folder>/www/<any_folder_name>` 
2. Create `.devilbox` folder in your `<any_folder_name>` folder. 
3. Create `backend.cfg` in `.devilbox`  and add `conf:rproxy:ws:php:8080`  in it.
4. edit `vite.config.js` file in your Laravel project and modify `defineConfig` function using following code 
```js
export default defineConfig({
    server: {
        https: false,
        host: '0.0.0.0',
        port: '8080',
        hmr: {
            host: 'hmr.test', //your <any_folder_name> host
            clientPort: '8080',
            protocol: 'ws',
            https: false,
        }
    },
   plugins: [ ....
});
```
finally  run `npm run dev` and it should work.

**Comment by masiorama** [comment]
Unfortunately I am not able to successfully replicate your configuration, guys.
I need to work with https, but I tried also to make it work with http as @C4pt4inM example was a nice and condensed list, but I get only:

GET http://hmr.loc:8080/resources/css/app.css net::ERR_CONNECTION_REFUSED
GET http://hmr.loc:8080/@vite/client net::ERR_CONNECTION_REFUSED
GET http://hmr.loc:8080/resources/js/app.js net::ERR_CONNECTION_REFUSED

**Comment by vikas5914** [comment]
@C4pt4inM  @masiorama `clientPort` must be `443 (HTTPS)` or `80 (HTTP)`.  Otherwise, you will get an error like the above.

**Comment by C4pt4inM** [comment]
> @C4pt4inM @masiorama `clientPort` must be `443 (HTTPS)` or `80 (HTTP)`. Otherwise, you will get an error like the above.

Yes this error did appear to me, I am using Fedora 37 so I have not installed SSL for devilbox.
@masiorama  I forgot one part, and that is to add `hmr.test` in `/etc/hosts`  similarly you would add any other project. I am using Laravel 10 . here are screenshots

-> host file content https://i.imgur.com/ZN3lZ5p.png
-> result of that https://i.imgur.com/1BnloCT.png
-> my www folder content https://imgur.com/a/ijLHJjt
and just for confirmation. I just setup installation of same project locally in my laptop having same devilbox version (v3.0.0-beta-0.3) . 

@vikas5914  must be right about ports but God knows how my solution is working for me I don't know I just played it a little bit and it worked.  the only things I know is that `wss` is for secure and `ws` is for unsecure.

**Comment by vikas5914** [comment]
@C4pt4inM Are you running the Vite command inside the docker or outside the docker?

**Comment by C4pt4inM** [comment]
> @C4pt4inM Are you running the Vite command inside the docker or outside the docker?

I am running it outside. I tried running in `./shell.sh` but the server I had no URLs to open . also my Laravel was not detecting any vite server running.

**Comment by vikas5914** [comment]
@C4pt4inM, that's why. The code I provided works when running the vite inside the docker.

**Comment by masiorama** [comment]
Hello guys, thanks for all the clarifications.

I do feel more comfortable to work inside devilbox shell (aka inside docker), so I tried everything inside of it.
I know I had to add my hmr.loc inside my windows hosts file, as I do for every project inside devilbox.
I didn't know the difference between _ws_ and _wss_, so I'm trying right know.

I will start from scratch with a new laravel 10 project and report it in my next comment so you can track step by step and probabily find out what I'm doing wrong.

I'll keep you posted.

Update: actually, the error was indeed the wrong protocol; the right one is _wss_.
Everything started to work once I changed it. Thanks to you both!
