### ISSUE TITLE
[Howto]: Add new coding standard to phpcs

### ISSUE THREAD

**Issue by BWBama85** [cytopia/devilbox#986]
### Have you already checked elsewhere?

- [X] I have read the [Devilbox documentation](https://devilbox.readthedocs.io/en/latest/)
- [X] I have checked the [Devilbox Troubleshooting Guide](https://devilbox.readthedocs.io/en/latest/)
- [X] I have checked the [Devilbox FAQ](https://devilbox.readthedocs.io/en/latest/support/faq.html)
- [X] I have checked the [Devilbox Howto](https://devilbox.readthedocs.io/en/latest/support/howto.html)
- [X] I have checked the [Devilbox Forum](https://devilbox.discourse.group/)
- [X] I have checked [existing issues](https://github.com/cytopia/devilbox/issues)
- [X] I have googled already with no luck
- [ ] I have not done any of the above

### What are you struggling with?

I would like to add a new coding standard for phpcs in the php container I am using. I run multiple php versions, if that matters.

### What have you tried already?

I have tried searching and have poked around the container but can not see where or how standards should be installed. 

phpcs -vv shows me this:

```
devilbox@php-8.1.14 in /shared/httpd/xenforo/htdocs/src/addons/TheWilsonNet/SeedAttachments $ phpcs -vv
Processing ruleset /shared/httpd/xenforo/htdocs/src/addons/TheWilsonNet/SeedAttachments/phpcs.xml
        => set config value testVersion: 7.4
        Processing rule "Generic.PHP.Syntax"
                => phar:///usr/local/bin/phpcs/src/Standards/Generic/Sniffs/PHP/SyntaxSniff.php
        Processing rule "PHPCompatibility"
                => PHPCompatibility
ERROR: Referenced sniff "PHPCompatibility" does not exist

Run "phpcs --help" for usage information
```

As you can see, I have a phpcs.xml that is trying to use PHPCompatibility but it is not installed as a coding standard in the container. 

### What is your goal?

Add new coding standards to phpcs in a php container.

**Comment by userwiths** [comment]
Hello, was messing with my local config to check around this issue. 
You can try this, run `composer global require phpcompatibility/php-compatibility`.
 
After that take the current `installed_paths` value. Run `phpcs --config-show` take the value of `installed_paths`, it should be a path (or a few paths separated with a comma `,`).
And finally add the path to the PHPCompatibility to the other path.
You can check if its added correctly with `phpcs -i` should mention that `PHPCompatibility` is installed.

After that you should be ok to add your own codding standard

For example:
I run `php --config-show`
And receive
```
installed_paths: ~/a/b/c,~/d/e/f
```
Then I'd run
```
phpcs --config-set installed_paths ~/a/b/c,~/d/e/f,~/.composer/vendor/phpcompatibility/php-compatibility/PHPCompatibility
```

Hope this helps ~
