### ISSUE TITLE
Multiple PHP versions running simultaneously

### ISSUE THREAD

**Issue by msrajawat298** [cytopia/devilbox#991]
### What is your idea or feature suggestion?

We need to create a Docker image or YAML file that allows running multiple PHP versions simultaneously on the server. By default, all applications should run using the chosen or latest PHP version.

Additionally, we should be able to specify a specific PHP version for a particular project by modifying the .htaccess file. It's important to note that server restarts should not be required; the changes should automatically take effect when the user runs docker-compose up.

**Please note that the user does not need to restart the server; it should automatically work once the user runs 'docker-compose up**

### Benefits

User can we run multiple env. php project at same time no need to upgrade or downgrade php version every time.

### Where can we find information about this?

https://youtu.be/HQlhytfwfj8
https://youtu.be/Xzs4VLc3iE0
https://youtu.be/CQVbpU7IANc

### Are you willing to provide a PR to address this?

None

**Comment by vikas5914** [comment]
@msrajawat298 You can achieve this by using v3 beta: https://github.com/cytopia/devilbox/pull/943

Also suggest you join Devilbox discord server so we can help you if any problem comes.

**Comment by msrajawat298** [comment]
ok thanks let me try this.
